---
title: "Parte 2"
format:
  html:
    toc: true
    toc-depth: 5
    number-sections: false
    theme: cosmo
    css: styles.css
---

# **CAPÍTULO II**

## La religión

La verdad científica se fundamenta en sus propias definiciones,
conceptos y terminologías, tales como hipótesis, experimentación,
teorías, leyes, metodologías, evidencias, predicciones, observaciones,
conocimiento e una infinidad de términos que aplican en sus innumerables
campos de acción. Todos ellos definidos en aquello que tiene un alto
grado de objetividad y es demostrable desde el conocimiento humano y su
relación con el universo; pero también con una buena dosis de misterios
aún no resueltos.

El origen del universo y de la vida, la muerte, el sentido del "ser"
como misterio humano, tiene una respuesta en la verdad científica, todo
termina para un ser vivo cuando se cumplen ciertas condiciones
estipuladas en su metodología. La consciencia en la experiencia
subjetiva del individuo desde la verdad individual, sigue en la búsqueda
de su propia identidad como alternativa al sentido de la existencia y de
otros misterios cuyas respuestas son parciales o negaciones cuando
dependen solo de la verdad científica.

Siendo todo misterio una incógnita universal, la búsqueda de la verdad
absoluta implica la búsqueda de un punto de unión en un cimiento único,
de diferente aproximación entre las verdades científica, filosófica y
teológica, ya que las verdades parciales confluyen a la única verdad, de
diversas maneras en un intrincado viaje de entendimiento, en la verdad
individual de cada ser humano con la que se identifica en el trayecto de
su vida en el si mismo[^1]. Es una búsqueda , que además ha sido
permanente a través de la historia del ser humano desde las numerosas
religiones; hoy se calcula que existen diez mil religiones en el mundo.
Siendo la principales, el Cristianismo, el Islamismo, el Hinduismo y el
budismo; aproximadamente un 16% de la población del mundo no tiene
afiliación religiosa[^2]. Esta gran diversidad es una expresión de la
gran riqueza cultural de las naciones y al mismo tiempo la búsqueda
implacable de un marco de principios y valores humanos que, aunque se
han formado en un camino largo y fructífero en muchos casos, no se han
podido encontrar partiendo de aquel cimiento único, que sirva de guía o
timón a la humanidad.

El significado de la religión puede ser ampliamente debatible
dependiendo de las fuentes desde donde se pretende entender; los
variados argumentos pueden encontrarse en incontables documentos a
través de los siglos. Tanto Cicerón (Arpino, 106 -- 43
a.c.,Formies)[^3], historiador romano, como Lactancio (Africa
septentrional, 250-325, Galia )[^4] , escritor Cristiano nacido en el
norte de Africa , se encuentran entre los primeros en exponer
definiciones epistemológicas. Cicerón asumió una definición a partir del
deber : "Quienes se interesan en todas las cosas relacionadas con el
culto, las retoman atentamente y como las releen, son llamados
«religiosos»" definición que se deriva de la re lectura con una dosis de
escrúpulo en cuanto a los cumplimientos de los deberes en el culto a los
Dioses. Lactancio le dio un carácter de vinculación : "Obligados por un
vínculo de piedad a Dios" estamos "religados"; del latín religare. En
esta definición se resalta la relación de dependencia.[^5] Durante los
siglos siguientes, se encuentran diferentes aproximaciones al
significado de la religión dependiendo del contexto histórico o lugar
donde se defina, siendo su definición un debate inconcluso.
Recientemente se incluyen enfoques diferentes, especialmente a partir de
las ciencias humanas como la sociología y la antropología cultural;
también en el sentido que se le puede dar a la palabra religión desde el
contenido de cada creencia. En un sentido general y monoteísta William
James (Nueva York, 1842 -- 1910, Chocorua)[^6] afirma: "consiste en la
creencia de que existe un orden invisible y nuestro Dios supremo
permanece en un armonioso ajuste de nosotros mismos a ello". En sentido
politeísta la define Wittgeinstein (Viena,1889-1951,Cambridge)[^7]:
"Porqué llamamos a algo religión ?, bien, quizás porque tiene una
relación directa con muchas cosas que hace mucho son llamadas religión;
y esto puede afirmarse para dar una relación indirecta a otras cosas que
llamamos con el mismo nombre".Muchas culturas carecen o rechazan la
distinción entre lo natural y lo sobrenatural. Creen que las personas o
poderes incorpóreos no existen en una realidad de otro mundo, pero tal
vez en el tope de cierta montaña, en las profundidades del bosque, o en
"todas partes". Para evitar esta vista de dos realidades separadas,
algunos teóricos han reemplazado la palabra sobrenatural, con otros
términos como "super humano". Hick (Scarborough,1922-
2012,Birgminham,)[^8] usa el término trascendente: "La realidad aceptada
que trasciende todo lo que no sea el si mismo pero no es trascendido por
nada más que el si mismo". Desde una aproximación funcional y
sustantiva, se sostiene que aún formas ateístas del capitalismo,el
nacionalismo y el marxismo funcionan como religiones. La literatura de
estas instituciones seculares como religiones funcionales es masiva, "El
volumen de literatura soportando el punto de vista de que el Marxismo es
una religión es tan abundante que no se puede descartar fácilmente".[^9]

Cada religión se construye y define desde la experiencia humana
reflejada en la verdad individual de sus fieles seguidores y en su
comunidad , desde la creencia y desde la fe, que no aplican por igual en
todos los casos. Desde la trascendencia se construyen los conceptos de
Dios, alma y espiritualidad que también tienen sus propios y diversos
matices. Las religiones parten también de experiencias inmanentes[^10],
esencialmente concebidas al interior del ser como ente individual; es la
experiencia subjetiva del ser humano y el pensamiento de la lógica de
Dios, que marcan las diferentes formas de entender un camino en la
edificación del conocimiento y aceptación de las religiones,algunas
concebidas desde una posición racional.

## Historia de las religiones

El ser humano descendiente del Homo Erectus, en los archivos de la
historia data de hace unos 2 millones de años, proveniente del sur de
África[^11], el cual evolucionó en una ramificación del género "Homo"
que dio origen al ser humano -- el "Homo Sapiens" moderno; los demás
géneros homo, han desaparecido siendo el más conocido el Homo
Neardental[^12]. Es una hipótesis, todavía bajo investigación que en
España en un lugar llamado la "sima de los huesos de Atapuerca", hace
400 mil años pudo originarse el primer rito[^13] funerario por el Homo
Neardental[^14]; datos mas recientes confirman un rito funeral[^15]
Neardental de hace 50 mil años en Francia en La Capelle Aux-Sanints. Los
descubrimientos arqueológicos de "la dama roja de Pavilon" revelan el
primer humano encontrado[^16] y enterrado hace unos 30 mil años AC,
junto con conchas, anillos y varillas de marfil teñidos de rojo con la
misma sustancia que los huesos, indicando esto una manera de despedir a
los muertos. En aquel periodo prehistórico llamado el paleolítico[^17] ,
el ser humano sobrevivía a la última glaciación y era principalmente
nómada y cazador, realizando grandes migraciones desde el sur del África
hacia el Asia, Europa y América. Pareciera que tanto el Homo Sapiens
como el Homo Neardental fueron las especies con algún grado de
expectativa frente a la muerte como un misterio del "más allá",
admitiendo lo sobrenatural y por sentido común, la posibilidad de la
continuación de la vida después de la muerte; ya entonces, en algún
momento, se perfila un sentido espiritual como parte del ser humano, es
la semilla del ser "religioso" una gran diferencia ante otras especies
de seres vivos. Muy posiblemente en aquellos escenarios prehistóricos
comenzó el ser humano a cuestionarse y a asombrarse ante la posibilidad
de la muerte y a asumir significados arraigados en diferentes contextos
tribales. La pregunta sobre el sentido de la existencia y la vida
después de la muerte de aquel espíritu trascendente, propio del ser
humano y se fue consolidando y hacia el 10 mil AC, ya se encontraban las
primeras huellas de grupos sociales tribales con ritos de mayor
complejidad; aparecieron en cada cultura el equivalente del chamán o el
chieftan, el jefe tribal o quien tenía una posición jerárquica
importante por su capacidad de contacto con aquella visión trascendental
o del mas allá de la muerte del ser humano. Eran culturas mas avanzadas
que tuvieron que ajustarse a drásticos cambios climáticos, desarrollaron
el arte a partir de las pinturas rupestres, como manifestación de su
experiencia subjetiva; pero el empleo de la agricultura y la
domesticación animal, marcaron un hito importante para la humanidad,
puesto que a partir de esta práctica se desarrollaron las primeras
comunidades sobre las cuales aparece posteriormente la cuna de la
civilización. Podría considerarse este periodo que inició hace unos 10
mil años AC, llamado el neolítico[^18] hasta el 4 mil AC, tal vez el
periodo más revolucionario de la historia humana, pues, además de ser la
época del inicio de las principales religiones, es el inicio del
crecimiento de la población humana; la dominación entre las clases
sociales y culturas, las guerras, el dominio técnico de la naturaleza y
por consiguiente aparecen muchos aspectos de convivencia social que
posteriormente se convertirán en parte de los problemas que aquejan
todavía a la civilización contemporánea. El afán de la dominación "del
otro", de la "otra tribu", o del "otro grupo social", es el evento o la
acción de desestabilización de la comunidad que el ser humano ha
ejercido con mayor frecuencia, entre diferentes grupos de interés,
inicialmente tribales, desde el neolítico hasta la civilización del
mundo contemporáneo. En el neolítico, el mundo ya tiene un nivel de
desarrollo y transferencia precaria de ideas a través de las migraciones
y el incipiente intercambio comercial, en las grandes regiones con
características locales en el Medio Oriente, Europa, Asia, América y
África. Se reconoce a Jericó[^19] (Cisjordania) como una de las aldeas
más antiguas del mundo, incluye en sus inicios una torre, posiblemente
para defensa, almacenamiento de semillas o actividades rituales. Pero es
en Gobekli Tepe[^20] en Turquía el lugar habitado por una sociedad
nómada -sedentaria , donde aparece el santuario o templo más antiguo del
mundo y se distingue ya una conciencia de lo sagrado; su complejo
megalítico es seis mil años mas antiguo que los de Stonehenge[^21] en
Inglaterra, data de entre el nueve mil al siete mil AC. Los monolitos
eran piedras de 5.5 mts de altura y hasta 40 toneladas cada uno, siendo
un yacimiento de 90 mil metros cuadrados que todavía está en proceso de
excavación. Los pilares de los monolitos en forma circular tenían
apariencia humana estilizada, construido por grupos de cazadores -
recolectores de 200 kms a la redonda para celebrar rituales asociados a
las fuerzas animales que representan los pilares del complejo. Similares
patrones se siguieron en todo el neolítico en cada una de sus regiones,
por ejemplo en Asia se habla del hombre de Pekin[^22], una sub especie
del Homo Erectus; o de una cultura cuyas ramas se desprenden de los
grupos tribales[^23] Peilikan y Cishan, que finalmente evolucionaron con
diferentes tipos de arte y cerámica encontrada en tumbas de aquellos
miembros privilegiados de su comunidad[^24]. El período neolítico, marca
también, un hito importante en el nacimiento de los cultos y mitos
buscando un sentido a la vida en las actividades primordiales como
producción agrícola y la guerra, las manifestaciones naturales y otros
sucesos de carácter sobrenatural para la comunidad tribal como es el
sentido trascendente de la vida después de la muerte través de ritos
funerales de diferentes matices y diversidad de tumbas adornadas con
tipos de artefactos ya sea de arte rudimentaria o más avanzada, o
elementos que de alguna manera se relacionaban con quien fallecía. Eran
los cultos[^25] que se evidenciarían en las civilizaciones primitivas
buscando respuestas sobrenaturales en los animales, la naturaleza ,
figuras antropomorfas, totems y santuarios de diferente composición. En
algún momento del neolítico, también aparece la semilla de la mayoría de
las religiones que dominan el mundo moderno; puesto que la escritura no
existía, la tradición oral , costumbres y ritos se fueron consolidando
según las regiones y culturas. Muchos de estos cultos adoraban a
diversos Dioses e incluso tenían costumbres arraigadas en el sacrificio
humano; era una forma de religión primitiva. En el transcurso del
neolítico y hasta el siglo primero AC, otros dos eventos que marcarán la
humanidad van emergiendo entre migraciones, guerras, invasiones e
intercambios comerciales cada vez de mayor frecuencia: la invención de
la escritura en siglo el 3.5 AC y el uso de los metales[^26] y su
tecnología entre los siglos 4.5 AC y 1 AC. Durante el neolítico aparecen
la primeras civilizaciones[^27], siendo Mesopotamia la de mayor
reconocimiento, emergió en el medio oriente entre los ríos Tigris y
Eufrates. La cultura sumeria es parte inicial de esta civilización en
cuanto a la creación de las ciudades -- estado y la aparición de la
escritura cuneiforme. En dicho entorno , la ciudad de Ur, fue una de las
primeras ciudades sumerias cuyas ruinas datan del siglo 5 AC y existen
todavía en el actual Irak. Es aquí donde confluye el origen histórico de
tres religiones que marcan la historia de la humanidad en occidente: el
Judaísmo, el Cristianismo e Islamismo. Todas confluyen en un Padre o
Patriarca llamado Abraham. Vale la pena resaltar que su origen histórico
nace de la evidencia en las escrituras iniciales entre el siglo 3 y 5 AC
; sin embargo, de acuerdo a sus seguidores la tradición oral es mucho
más antigua, el Libro del génesis, común para el Judaísmo y el
Cristianismo pudo tener su origen en la tradición en el siglo 9 AC[^28].
Tienen en común estas tres religiones también, que son religiones
monoteístas, puesto que creen en un solo Dios; algo inusual durante el
neolítico y la edad de los metales. El Judaísmo[^29] surge entonces en
medio de una civilización naciente, donde florecieron con
características culturales y dinámicas religiosas diferentes y numerosos
imperios de la edad antigua[^30]; eran el cimiento de una nueva
estructura social dominante. Para el Judaísmo Dios[^31] creó el mundo e
hizo una alianza con Abraham, del linaje de Noe, para entregarle la
tierra prometida al pueblo de Israel y la diseminación de sus
descendientes por las naciones del mundo de la estirpe de su hijo Isaac,
a quien tuvo con Sara. La enseñanza y principio más importante del
Judaísmo es que hay un solo Dios, incorpóreo y eterno, que quiere que
todos los hombres hagan lo que es justo y misericordioso. Todas las
personas son creadas a imagen de Dios y merecen ser tratadas con
dignidad y respeto. El texto Judío más importante es la Biblia Hebrea,
que cual consistió inicialmente de los cinco libros de la Tora,
posteriormente se complementó con la Mishná y el Talmud. En la Biblia
Hebrea, la ley de Moises está por encima de cualquier autoridad.
Tradicionalmente, el pueblo Judío vive a la espera de la llegada de una
era mesiánica en la que la paz universal será establecida en la tierra
de acuerdo a la visión de los profetas de Israel[^32]. La historia del
pueblo de Israel está estrechamente ligada a su religión; una historia
de increíble superación que ha estado marcada por destierros y
ocupaciones de territorios ancestrales y conflictos bélicos aún hasta
nuestros días, su historia fue marcada en una edad media exacerbada por
conflictos religiosos como las cruzadas y movimientos anti-semitas que
llegaron a su cúspide con el holocausto durante la segunda guerra
mundial. Jerusalén por ser reconocida la cuna desde las tres religiones
que manifiestan un mismo Patriarca, ha mantenido ocupaciones centenarias
por parte de diferentes imperios, como el imperio Romano, Bizantino,
Musulmán, Otomano y Británico entre otros, hasta su reunificación en
1967.[^33] Actualmente el Judaísmo mantiene varias denominaciones y sub
grupos que varían según su interpretación religiosa, entre los
principales se encuentran los reformistas, los conservadores, los
ortodoxos y reconstruccionistas. Muchos Judíos se denominan a si mismos
simplemente como Judíos, sin denominación alguna[^34]. Durante la
ocupación del imperio Romano nace el Cristianismo con Jesús quien para
los Cristianos es Dios hecho hombre y quien nace por obra del Espíritu
Santo de la Virgen María teniendo como Padre putativo a San José. Jesús
es reconocido por el pueblo Judío como uno más de tantos profetas de
aquella convulsionada época y quien aseguran, fue divinizado por sus
seguidores. Jesús es descendiente del rey David quien a su vez es
descendiente de Abraham de acuerdo a la Biblia Cristiana, compuesta por
el antiguo y el nuevo testamento. El Cristianismo encuentra entonces en
Jesús el hijo de Dios Padre, la continuación de las enseñanzas de los
profetas Judíos en el antiguo testamento, reconociendo al mismo Dios
Padre, creador del universo referido por los Judíos; fue Jesús el
Mesías, quien vino a traer la salvación en la vida eterna a la humanidad
gracias a su mensaje de amor divino, su misericordia y su muerte
consentida por Él mismo en la Cruz. Jesús como Judío renovó la ley de
Moises, por ello , su muerte fue causada por quienes le rechazaron en el
pueblo Judío y autorizada por Poncio Pilato, prefecto de Judea en la
época de la dominación Romana. La razón teológica sobre la que se
sostiene el Cristianismo como continuación del anuncio de los profetas
del Antiguo testamento y la ley de Moises, es la encarnación de
Jesucristo, hijo de Dios como hombre y su resurrección, venciendo la
muerte y prometiendo así un reino de amor eterno a quienes por voluntad
propia le sigan y a la perdición de las almas a quienes le
rechacen[^35]. Sus primeros seguidores fueron los doce apóstoles a
quienes Jesús se apareció resucitado; de ahí que sus seguidores se
multiplicaron y se diseminaron por el mundo, especialmente en occidente,
hasta el presente. La historia de la Cristiandad está colmada también de
persecuciones sanguinarias a sus seguidores, pero también de una larga
transición conflictiva manifestada en guerras y persecuciones religiosas
a los herejes o no creyentes, con mayor fuerza durante la edad media,
época en la cual prevalecía una marcada influencia monárquica
inicialmente de los imperios Romano y Bizantino y posteriormente en los
nacientes estados imperiales de Europa occidental. El Cristianismo tiene
también diferentes ramas y subdivisiones de acuerdo a la interpretación
religiosa de sus fieles, siendo los grupos principales representados por
las iglesias ortodoxas, las iglesias Evangélicas o protestantes, y la
iglesia Católica; siendo esta última el foco del presente
documento[^36]. La iglesia Católica reconoce al Papa como sucesor de
Pedro, quien según los fieles Católicos fue el primer Papa. Algunos
siglos después, hacia el año 570 DC , nace el profeta Mahoma (La Meca
575 D.C.-- 676 D.C., Medina )[^37], descendiente de Abraham, quien
recibió revelaciones de Dios a través del ángel San Gabriel para
corregir el error humano con las escrituras y doctrinas del Judaísmo y
del Cristianismo y todas las demás religiones en el que se había
incurrido. Esta corrección se hace a través del Corán , el libro cuya
revelación está escrita en lengua árabe. Según el Islam , la alianza de
Dios con Abraham para extender su estirpe con el mundo fue a través de
su hijo Ismael[^38], hijo de Agar su sierva egipcia; no de Isaac como lo
asegura la religión Judía y Cristiana. El pueblo Musulmán es el que
sigue al Islam, considera como profeta anterior a Mahoma a Jesús, quien
para ellos no fue crucificado. Para el Islam, existe un solo Dios. Él es
justo y razonable, y quiere que alcancemos el Paraíso. Dios es el
creador de todas las cosas. Sin embargo, Dios[^39] nos ha colocado en
esta vida como una prueba, para evidenciar lo malo de lo bueno. Y
estaríamos perdidos si nos abandonara a nuestra suerte[^40]. Los
Musulmanes también creen en un paraíso eterno al cual tendrán acceso las
almas que siguen a su Dios y se perderán las que no lo hagan. Jerusalén
[^41], La Meca y Medina son las tres ciudades sagradas del Islam; por
ello Jerusalén ha sido fuente de invasiones y guerras por parte de los
pueblos Musulmanes y posteriormente del imperio Otomano. El Islamismo
está ampliamente extendido en el Oriente Medio, Norte de Africa , Asia
Occidental y en numerosos Países de lengua árabe. Al igual que en el
Judaísmo y el Cristianismo aparecen diferentes ramas del Islamismo, con
sus respectivas sub divisiones, siendo las más importantes el Sunismo,
el Chiismo, el Jariyismo, el Sufismo entre otros. En algún momento del
neolítico, mientras en occidente, las religiones monoteístas se
desarrollaban, hacia el oriente florecía otra civilización sobre el
valle del rio Indo y evolucionaba otro tipo de religión que conservaba
una tradición cultural de varios Dioses como manifestación de una gran
divinidad. No hay un Dios único, sino que todo es Dios; naturaleza,
universo, consciencia u alguna otra esencia material primigenia y Dios
están al mismo nivel , son las religiones llamadas panteístas[^42], de
entre las cuales el Hinduismo es una herencia de aquella época, una
religión Henoteísta[^43], en la que se reconocen varios Dioses, pero uno
es digno de adoración. El Hinduismo mantiene sus raíces en la India
actual y posteriormente en regiones aledañas como Pakistan, Afganistan,
Nepal, Europa occidental y Estados Unidos. El periodo védico[^44] entre
el 1500 y el 500 AC, en el norte de la India pertenecía a una zona de
constantes invasiones con gran influencia cultural y religiosa desde
todos los flancos, por el occidente desde la antigua Grecia[^45]; siendo
la cultura griega gran influenciadora en el origen y desarrollo de la
filosofía, el Panteísmo e incluso la ciencias como se las conoce hoy en
día. Por el norte la influencia cultural proviene de los pueblos
Arios[^46] y posteriormente el imperio Persa[^47] y desde el oriente por
el comercio generado por la ruta de la seda desde la incipiente
China[^48]. Posteriormente en los primeros siglos de la era Cristiana,
también tuvo fuerte influencia por los pueblos Árabes y el imperio
Británico. La historia de la India[^49] procede, con una gran diferencia
frente a las religiones monoteístas, por la gran apertura a diferentes
religiones y la adaptación a las mismas alimentada por la gran variedad,
mezcla e influencia cultural. La religión Veda compone el conocimiento
en sánscrito en cuatro libros, el Rig-veda, el Samaveda, el Yajurveda y
el Atharvaveda compuestos en himnos por diversos autores[^50],
considerados por sus seguidores como los más antiguos del mundo dada la
tradición oral que los precede; estos son la base del Hinduismo[^51]
junto con otras escrituras que juegan un papel de suma importancia
[^52]. El Hinduismo está basado en una estructura social de castas, en
las que la posición de cada individuo depende del mérito acumulado en
vidas pasadas o karma, es decir sus seguidores creen en la
reencarnación. Existe una creencia en varios Dioses, que se manifiestan
a través de un Dios, una sola divinidad absoluta infinita y manifiesta
de diferentes formas trascendentales, es Brahman)[^53], que es la causa
de la creación del universo, su disolución y transformación en constante
ciclos repetitivos. El objetivo último es la liberación del ciclo de
reencarnación, Moksha, a través de diferentes caminos del Yoga[^54] para
la unión con un Dios de paz y amor. En el Hinduismo, la vida es sagrada,
debe ser amada y reverenciada, se debe enarbolar la pureza, la verdad y
la no violencia[^55] ; para sus seguidores ninguna religión es la única
vía para la salvación, pero todos los caminos genuinos son la luz de
Dios y deben ser tolerados y entendidos. Sus principales Dioses, [^56]
son Shiva (Dios destructor ), Vishnú (Dios preservador), y Brahmá (Dios
creador, diferente a Brahman). En el Hinduismo, el Dharma es el concepto
de religión que para sus seguidores no tiene una traducción al estilo
occidental, su significado varía entre la ley natural, la enseñanza, la
virtud y en el fondo un deber supremo que todo individuo debe ejecutar
para realizarse interiormente. Incluso la naturaleza tiene su Dharma. Es
la ley divina, que prevalece en cada nivel de la existencia desde el
orden cósmico hasta las leyes religiosas y morales que unen al ser
humano en armonía con dicho orden[^57]. Continuando con el camino de la
historia de la religión, en el 563 -- al 483 AC , en la India antigua,
existió Siddhartha Gautama o Buda, quien nació de una familia
aristocrática, según dice la leyenda, un adivino predijo que renunciaría
a su vida terrenal; por ello su Padre un rey, le mantuvo rodeado de
bienes materiales y placeres. Pero , en su juventud , al salir de su
encierro tuvo la oportunidad de observar las diversas formas de
sufrimiento del ser humano y también observó a un monje asceta. El
contraste entre su vida y lo que observó le llevó a pensar que todo el
placer de este mundo era pasajero y solo cubría temporalmente el
sufrimiento humano. Gautama abandonó a su esposa e hijo para seguir
diferentes maestros e intentar el ascetismo y la renunciación en el
bosque , hasta el extremo de la inanición por falta de alimento.
Finalmente se dio cuenta que esto solo traía más sufrimiento. Se sentó a
la sombra de un árbol a comer y a meditar. En la mañana siguiente ,
llegó a la iluminación o el Nirvana , a través del cual encontró las
respuestas a las causas verdaderas del sufrimiento, la forma de evitarlo
y como alcanzar la salvación. Entonces el Buda, dedicó el resto de su
vida para dar a conocer su legado en la India[^58]. Así nació el
budismo, enarbolando inicialmente las cuatro nobles verdades; la verdad
acerca del sufrimiento, la verdad sobre la causa del sufrimiento, la
verdad sobre el fin del sufrimiento y la verdad sobre el camino que
lleva a la terminación del sufrimiento. Es en la tercera verdad en la
que se alcanza la iluminación o el Nirvana. El budismo también cree en
la reencarnación de acuerdo al Karma en la vida individual, en ciclos de
muerte y nacimiento , que de acuerdo a sus acciones en la vida anterior
le corresponde el plano en la nueva vida.[^59] En la tercera noble
verdad se termina el ciclo de muerte y nacimiento y en la la cuarta
noble verdad se enseña la cesación del sufrimiento a partir del óctuple
sendero, es decir recto entendimiento, recto pensamiento, recto
lenguaje, recta acción, recta vida, recto esfuerzo, recta atención y
recta concentración[^60]. El budismo también tiene diferentes
clasificaciones , siendo las tres principales el Thervada, el Mahayana y
el Tibetano; a pesar de su origen en la India, terminó expandiéndose y
concentrándose por en el Oriente Asiático , en países como China,
Tailandia, Japón, Corea , Cambodia, Tibet, Nepal , con seguidores en
diferentes regiones del mundo. El budismo no tiene una autoridad
central, pero reconoce al Dalai Lama como el Monje que lidera el budismo
Tibetano. A pesar de que sus libros de sabiduría están en constante
evolución, sus principales textos son el Vinaya Pitaka, el Sutta Pitaka
y el Abhidhama Pitaka , que constituyen el canon Pail de los tres
canastos[^61]. A menudo es considerada una religión no teísta, no existe
un Dios creador ( diferente a ateísta), o en ocasiones es considerada
más una filosofía o marco de pensamiento. En Asia oriental,
especialmente en la China se combinó posteriormente el budismo con otras
religiones de alto contenido filosófico, como el Confusionismo y el
Taoísmo[^62]. Tanto en Oriente como en Occidente, la filosofía a jugado
un papel en el pensamiento frente a la posibilidad de un Dios,
dependiendo de la cultura o el marco histórico al que se haga
referencia. El filósofo Baruch Spinoza (Amsterdam, 1632 -- 1677, La
Haya)[^63] identifica el todo o el infinito como una realidad
equivalente a la "sustancia" que conforma la naturaleza; el ser humano
es finito, todos los entes son determinados porque ningún ser finito
subsiste por si mismo. Es un punto de vista completamente "inmanente",
se elimina la posibilidad de la trascendencia o de un Dios creador. Dios
se expresa exclusivamente mediante las leyes de la naturaleza. El
individuo posee pasiones ; el apetito o deseo es del ente "ser humano",
de ahí nace la alegría como idea del aumento de la perfección y la
tristeza como causa de la disminución de la perfección. De la
combinación de ambos se derivan los restantes afectos como el amor y el
odio. Algunos identifican a Spinoza como representante del Panteísmo, en
el cual Dios y la naturaleza o el universo son equivalentes; otros lo
clasifican como Deísta , es decir la existencia de la deidad suprema a
través de la razón y la experiencia personal o la ya descrita
experiencia subjetiva.

## La paradoja del progreso contemporáneo

La búsqueda de la humanidad de un cimiento único como marco y origen de
principios y valores, que la guíen en su aspiración a un desarrollo en
armonía para la construcción de una civilización post modernista o
contemporánea, está latente ya en la sociedad humana desde el neolítico,
periodo de gestación de los grandes retos de convivencia que aquejan al
mundo actual, hasta la era de la invención de una tecnología científica
inverosímil en la prehistoria; simultáneamente se han desarrollado
variados planteamientos filosóficos en el ámbito del alcance del
conocimiento y entendimiento del "ser" humano; y aún hoy en día siguen
naciendo nuevas religiones, bajo el estudio de la teología ; sin
embargo, continúa la búsqueda de una verdad absoluta, esencia de aquel
cimiento único. El ser humano se enfrenta entonces con su historia y su
propia encrucijada, las religiones y filosofías de manera general, que
han predominado en la historia humana, defienden su propia verdad de una
manera u otra, influyendo en la justicia, la convivencia, el amor, la
rectitud entre otros y dan un sentido a la existencia en armonía,
algunas con mayor énfasis en convivencia con la naturaleza, otras más
arraigadas en marcos de pensamiento filosóficos individualistas o
racionalistas; pero la mayoría prometen ser la guía para alcanzar tal
visión de una humanidad capaz de una coexistencia permanente en
reciprocidad con los principios y valores que de ellas se desprenden.
Sin caer en cuadros pesimistas, el complejo tramado de espacios
filosóficos y religiosos desarrollados por el ser humano en el contexto
histórico y cultural de cada región, es el que ha conducido a la
humanidad hasta hoy. La historia de las religiones han marcado desde el
neolítico , entre varias características, un elemento en común , que se
manifiesta desde sus diferentes formas de expresión en la evolución de
la civilización, este es la capacidad y deseo de "dominación" que se ha
ejercido entre las diferentes culturas y que finalmente se ha conjugado
en la era post medieval. Así se ha llegado al progreso contemporáneo,
que comenzó a enfilar baterías en la edad media y se ha consolidado
durante los últimos dos siglos, este planteamiento sigue un esquema de
razonamiento determinista y objetivo dominando ahora, no por monarquías,
reyes o creencias religiosas, pero si por un sistema global de naciones
-- estado, sistema de coexistencia fundamentado en la eficiencia
industrial y tecnológica, con nuevos principios y valores que descansan
en la creación del bienestar, en función de la riqueza económica, la
capacidad de dominación entre múltiples grupos de interés y de la
consideración que de ella se deriva en el anhelo de felicidad, del
individuo y de la comunidad.

En la sociedad moderna y contemporánea , el pensamiento racional y la
verdad científica se alimentan de la experiencia subjetiva pero, cada
vez , con mayor insistencia se construyen modelos de principios y
valores que dependen unicamente del pensamiento racional y científico,
con objetivos deterministas y funcionales como guía del progreso, pero
si dirección precisa. Se vive entonces en una paradoja , una gran
contradicción cuando el elemento de la verdad subjetiva que en muchas
instancias sociales se rechaza, forma parte del sistema de convivencia
en la construcción de principios y valores; el componente subjetivo no
se comprende, pero es parte imprescindible de la construcción de la
verdad que se busca. Un ejemplo en el cual el elemento subjetivo influye
en la vida diaria de millones de individuos en la era contemporánea es
el "tiempo", el cual se puede entender como un recurso humano limitado,
partícipe de la eficiencia, el cuál, a su vez es un imaginario
conceptual[^64] que no tiene ninguna característica física, no ha sido
capturado, ni fotografiado; pero siendo una experiencia subjetiva,
adquiere gran importancia en la funcionalidad de la sociedad y en la
verdad científica desde su definición y medición espacio-temporal. En un
sentido subjetivo diferente, pero de gran importancia desde el
neolítico, el sentido de lo trascendental tiene cada vez menos
incidencia en nuestra vida diaria , puesto que no es de carácter
funcional como lo es el control del tiempo; bajo la propuesta filosófica
del pensamiento contemporáneo, se excluye como parte del progreso el
sentido de lo trascendental, el cuál implica en cada ser humano su
aspecto espiritual. En la aspiración del progreso Dios no forma ya parte
de este pensamiento; y en muchos casos, no existe. En la gran mayoría de
sus marcos de pensamiento, es la ciencia y el pensamiento racional el
bastión para entender al ser humano y a la sociedad como un todo; queda
entonces la filosofía atrapada en la misma paradoja del progreso
contemporáneo. El relativismo de la antigua Grecia propuesto por
Protágoras (Grecia, 485 AC -- 411 AC)[^65] en el cual, "el hombre es la
medida de todas las cosas", parece haber revivido adornado de otras
características mas sofisticadas; el existencialismo promueve la idea de
un ser humano que vive en una angustia permanente por su necesidad de
tomar decisiones que afectan su vida constantemente; el positivismo solo
admite el conocimiento científico para el entendimiento del ser humano y
su entorno social; el marxismo promueve la lucha de clases como
explicación del comportamiento social y como el medio de promover el
bienestar individual; la fenomenología acepta la trascendencia solo
desde la percepción de los sentidos; otras formas de pensamiento como el
naturalismo, estructuralismo y muchas corrientes más que, además, por su
diversidad confirman ser un manifiesto ampliamente subjetivo en el marco
filosófico que confluyen en el presente siglo; en su mayoría se centran
en el individuo, en el si mismo y en la sociedad como explicación última
de la verdad en la que se deben construir los principios y valores del
progreso de la humanidad.

En el mundo del progreso moderno y contemporáneo, se tiende a determinar
como bien lo predijeron aquellos científicos en Solvay a la religión
como un conjunto de doctrinas que carecen de valor y tienden a
desaparecer. Pero este fenómeno se está dando en un sentido figurado:
las estadísticas muestran a una población mundial religiosa proyectada
hasta el 2050, con una variación cercana al 13% para los no creyentes (
sin religión )[^66]. Las relaciones entre los multifacéticos y diversos
grupos de interés de mayor poder e influencia , en un mundo global e
hiper conectado , han abandonado la doctrina religiosa como punto de
sostén para mantener el muy complejo entretejido de relaciones sociales
de la humanidad en su definición del progreso; el secularismo[^67]
religioso, que separa tajantemente la dinámica religiosa de la sociedad
en la construcción de sus principios y valores, es un resultado de la
historia[^68] de la humanidad, que ha influido en un creciente bienestar
global; pero que ha abierto durante los dos últimos siglos una nueva
ventana de progreso en el que la fe y la razón no conviven, al separar
el anhelo religioso del individuo expresado en la búsqueda de la verdad,
de la gran maraña de las relaciones sociales, sus interacciones y
definiciones de bienestar y progreso. Esto sucede hasta un punto extremo
en el que lo único que es cierto en una relación social enfocada al
progreso, es lo demostrable y lo que se considera como pensamiento
objetivo. El ser humano entonces se encuentra sujeto a una aguda tensión
opuesta, que viene de siglos de historia de una vivencia en la que, lo
que era verdad, era de carácter espiritual o divino, a otro extremo ,
donde lo único cierto es el argumento racional y científico. Incluso el
contacto con la naturaleza, que perduró durante siglos en los esquemas
de desarrollo cultural y social brindando al ser humano esa relación con
su ecosistema que le permitía entenderlo y cuidarlo, está en proceso de
extinción gracias a una nueva forma de "dominio" o exterminio de miles
de especies, que compromete hoy en el progreso económico. Permanece
entonces en la humanidad un desasosiego profundo, desde la prehistoria,
pero ahora con un camuflaje diferente, en un ecosistema social
científico y de progreso técnico, en un tejido social que no logra
demostrar su capacidad de generar la coexistencia armoniosa y amable de
la humanidad y que no logra superar los desafíos en los que la
civilización se ha sumergido desde que comenzó a enterrar a sus muertos,
en el periodo neolítico. El nuevo escenario, que se ha venido edificando
desde la edad media y se consolida a partir del siglo XVIII, es una
fuente de principios y valores relativos a los numerosos grupos de
interés, con gran poder e influencia social, expresados en una tendencia
de sus propias verdades deterministas, pero ajenos y alejados a la
realidad espiritual y religiosa del individuo que los conforma en una
gran mayoría poblacional; la humanidad queda a merced de una verdad
completamente relativa, sumergiéndose así en un relativismo moral.
Jeremy Rifkin (Denver, 1943, actualmente)[^69] lo expresa de la
siguiente manera: "Si las historias de todos son igualmente válidas , ¿
sobre que base podemos establecer entonces la distinción entre lo que
constituye la forma moralmente adecuada de comportarse y estar en el
mundo y lo que no ? : El riesgo del relativismo moral." (finales del
siglo IXX ).[^70] La gran contradicción de un progreso que promulga el
determinismo racional y científico, centrado solo en el ser humano y la
sociedad, produce entonces una miríada de verdades individuales tan
complejas de cotejar en el plano de la experiencia subjetiva en el
individuo y la comunidad, que produce un cambio poco entendido y aún
menos asimilado en la construcción de principios y valores sociales,
como conductores del progreso moderno.

Encontrar una "dinámica social e individual", creadora de un escenario
donde la demandante espiritualidad del individuo humano tenga voz y sea
reconocida en el progreso contemporáneo, sin caer en un fanatismo
espiritual , pero reconociendo los errores históricos y la realidad del
pensamiento racional y científico es la tarea a la que se enfrenta la
humanidad, si desea alinearse a través de un cimiento único, con sus
raíces en una verdad absoluta que sirva de base para la construcción de
principios y valores que la conduzcan a un destino de coexistencia y
armonía en el largo plazo.

Para identificar una respuesta racional, como parte de un contexto
histórico, es necesario que todo grupo de interés tenga la capacidad de
superar el punto de vista único del carácter de la religión en general
como una esfera de conocimiento "inválida", puesto que el conocimiento
del si mismo, en lo trascendental y espiritual, es aún mas perplejo y
desconcertante que el conocimiento del universo y sus leyes. Quienes no
perciben en la teología como una guía válida para la construcción de
principios y valores, tienden a considerar a todas las religiones en una
misma bolsa, ya que en diferente medida son percibidas en el contexto
del mito, el fanatismo, la superstición o el dogmatismo autoritario. Sin
embargo, cada religión tiene marcadas diferencias, en la interpretación
de su verdad[^71], y debido a que, son poco entendidas desde su
interior, han sido acusadas de ser partícipes y promotoras de guerras y
conflictos históricos, propios del momento y la evolución de la
humanidad. Es la actitud del ser humano de dominio y poder, esta
herencia histórica, especialmente en el mundo occidental del medievo, es
tan polémica como la misma definición de la fe; Pero finalmente, quienes
han edificado las religiones desde su experiencia subjetiva y su fe,
equivalen a la población humana a través de los siglos, miriadas de
individuos, quienes las han entendido y las entienden desde el si mismo,
en su verdad individual, son quienes han construido los principios y
valores sobre los que se ha cimentado la civilización como se conoce,
con sus consideraciones positivas y negativas, con los errores y
aciertos a los que aún la humanidad puede hacer referencia para su
proceso de aprendizaje y desarrollo.

Encontrar dicho cimiento único interpretado desde una dinámica social
constructiva, es tan complejo como la diversidad de caminos que en su
búsqueda han sido creados por la humanidad; y siendo la teología uno de
ellos, a continuación describiré la respuesta de la religión Cristiana,
desde un enfoque racional, sin pretender que esta sea su esencia, pero
enfatizando que la fe Cristiana tiene una lógica y entendimiento, que
aunque al igual que la ciencia participa del misterio, pero un misterio
espiritual que no se basa en una simple superstición, ni tampoco en un
afán desordenado de encontrar alguna explicación superficial; en cuyo
caso, el misterio no se resuelve pero se percibe en los límites de la
naturaleza humana.

En el enfoque de la religión Cristiana , aquellos misterios racionales y
objetivos que se han logrado descifrar y entender desde la verdad
científica, no contradicen su mensaje, mas bien lo complementa. Son
caminos diferentes que señalan a un mismo objetivo en la búsqueda de la
verdad. La verdad científica refuerza en este caso, el camino de la
religión Cristiana. Sin embargo, no sucede al contrario, puesto que
ninguna experiencia religiosa, por ser de un carácter subjetivo que no
se comprende, o por sostener el elemento espiritual, no añade valor en
el camino de la búsqueda de la verdad desde la metodología científica.

## La polémica Cristiana sobre el origen del universo

Ya desde la época de Platón (Atenas, 427 -- 347 A.C)[^72] , durante la
ilustración (Siglo XVIII) y actualmente se ha continuado con una
argumentación entre teólogos y racionalistas sobre la creación. El
origen del universo desde la verdad científica sigue siendo un misterio
, aunque en la actualidad todo apunta a un nacimiento del universo a
partir del big bang. Sobre la creación, la Biblia Cristiana en su libro
del Génesis se define el origen del universo como creación de Dios
[^73]. Dicho mensaje implica en su lectura inicial un pequeño terremoto
de discernimiento obligado en la consciencia de cada ser humano. En
primer lugar, establece un estado de inicio del universo y un origen que
podría interpretarse acorde a los indicios de la ciencia actual. En
segundo lugar, se expresa un mensaje directo de la creación por un Dios;
esto implica un ser de naturaleza absolutamente superior al ser humano ;
y en tercer lugar el mismo acto apoteósico, misterioso y sobrenatural de
la creación. Los dos últimos aspectos , son cuestionamientos mayores en
la construcción de una propia verdad individual en la identidad de cada
ser humano y de su comunidad porque se obliga a aceptar o rechazar la
posibilidad de un Dios superior y creador; lo que hace pensar al
individuo como una criatura que podría ser "dominada" por un ser
superior; o en su defecto, se impone a la consciencia a la búsqueda de
una explicación a dicha situación. El sentido de un Dios creador no
podrá resolverse desde la razón; pero si desde dicho rincón del
pensamiento del ser humano se advierten ciertas posturas que invitan a
la reflexión; mencionaré los extremos opuestos de dichas posturas como
ilustración de un debate que continúa hasta nuestros días, pero que no
constituye cimiento alguno para el soporte de la fe Cristiana. Albert
Einstein conservó una profunda reverencia por la armonía y la belleza de
lo que el denominaba la mente de Dios tal como se expresaba en la
creación del universo y sus leyes; sin embargo mantuvo toda su vida un
recelo hacia dicha autoridad y tuvo un alejamiento radical de su fe
Judía desde muy joven. El contacto con filósofos y las lecturas
científicas de la época lo llevaron a esa posición donde intentaba
conciliar la ciencia y su inclinación religiosa como el mismo lo
señalaba " La inclinación religiosa radica en la vaga conciencia que
reside en los humanos de que toda la naturaleza, incluyendo en ella a
los propios humanos, no constituye en absoluto un juego accidental, sino
una obra legítima, de que hay una causa fundamental en toda la
existencia"[^74]. Este reconocimiento de una causa fundamental, en otros
autores, una causa fundacional o una causa primera, que se reflejaba en
las leyes del universo como reflejo de la mente de Dios, tiene una
interpretación más aventurada desde la razón en la existencia de Dios a
través de aproximación a lo que se denomina el "diseño inteligente".
Muchas de las variables identificadas por la ciencia y que son
indispensables para la existencia del universo, son tan precisas en sus
valores que pequeñas variaciones en ellos, no permitirían la
subsistencia del universo. Una de ellas, la constante cosmológica
introducida por el mismo Einstein, aquella que hace contrapeso a la
fuerza de gravedad y de un valor infinitesimal, no podría tener un valor
diferente, puesto que si es mayor el universo se contraería y
desaparecería y si es mayor, el universo se dispersaría dejando un gran
vacío[^75]. El diseño inteligente contradice aquella posición en la cual
dicha constante obtuvo su valor por "azar", la absoluta perfección de
las leyes del universo no podrían surgir sin una mente de inteligencia
superior que las haya diseñado, así como un poema de Charles Dickens, no
se formaría, al azar, al caer las letras del alfabeto, cuando se han
lanzado al aire. Uno de los defensores del razonamiento del diseño
inteligente, Stephen C Meyer[^76] ( Washington, 1958 - actualmente) , se
apoya en los siguientes postulados de perfil Aristotélico : i. Todo lo
que comienza a existir debe tener una causa ii.El universo comenzó a
existir iii. El Universo debe tener una causa separada de él mismo. iv
Esa causa trascendental es Dios. Los críticos de esta posición aducen
falta de hipótesis medibles y de evidencia científica y advierten lo que
consideran la falacia del "Dios de los vacíos", en la que las
explicaciones que no pueden satisfacerse desde la razón se atribuyen a
Dios[^77]. El debate se centra más en ambientes educativos y culturales
y en algunas ramas de la Cristiandad y de otras religiones. Quienes ven
en la razón y la verdad científica cómo la única explicación al origen
del universo hacen un planteamiento que excluye a Dios en la acción de
la creación desde diversas hipótesis y teorías, siendo una de las
posiciones más recientemente expuestas por un gran científico cuyos
aportes en el estudio de los agujeros negros y en su excepcional
capacidad de dar a conocer la física cuántica al grueso de la población
mundial han sido grandiosos. Stephen Hawkin (Oxford, 1942 --
1918,Cambridge)[^78] en su último libro "El gran diseño" afirma que
debido a que existe una ley como la ley de la gravedad, el universo se
puede crear de la nada por si mismo[^79]. Sus detractores parten de la
base de su desconocimiento profundo de la teología en general o de a
filosofía; también en contradicciones de su postulado, entre ellos
Cristianos Evangélicos como John Lenox (Armagh , 1943 --
Actualmente)[^80] quien responde al postulado de Hawkins como una
contradicción explícita puesto que la gravedad es "algo" que tuvo que
ser creado, la gravedad es una ley que finalmente deja en la
incertidumbre la cuestión de cual sería la naturaleza de las leyes y por
último el cuestionamiento de causalidad del universo creándose a si
mismo, no tiene sentido[^81]. Dicho debate persiste desde los primeros
siglos del pensamiento filosófico y no ha se ha encontrado una respuesta
unánime y aceptada sin alguna refutación. En el caso de Hawkins y Lenox,
la interpretación de la "nada", tiene un significado diferente para la
ciencia que para la metafísica. El origen del universo desde una óptica
racional en el Cristianismo puede tener diferentes matices, dependiendo
de las ramas del Cristianismo desde donde se enfoque su definición;
siempre bajo un Dios creador. En la actualidad, la iglesia Católica , no
se opone al desarrollo científico, tampoco se aprueban o desaprueban
teorías científicas puesto que no es su campo de acción. Se aceptan las
teorías científicas aprobadas por especialistas y expertos científicos
aportando también al desarrollo de las ciencias, como la teoría del Big
Bang postulada inicialmente por el sacerdote Católico de origen Belga,
Georges Lemaitre; o aportando a la teoría de la evolución de Darwin con
Gregor Mendel (Heinzendorf, 1822 -- 1884, Brno)[^82] quien fue un
sacerdote Católico considerado el Padre de la genética moderna. La
primera asociación científica del mundo fue promovida por la iglesia
Católica; la Pontificia Academia de las Ciencias fue creada en 1,603,
cuenta con más de cuatrocientos años de antigüedad[^83], ha tenido
miembros relevantes de la talla de Galileo Galilei (Pisa, 1564 -- 1642
,Arcetri)[^84] . A pesar de los aportes a la ciencia, el origen del
universo en términos científicos desde el texto Bíblico, es una
discusión sin sentido desde la óptica de la fe Católica, ya que a pesar
de que la Biblia tiene en su mensaje un sentido lógico con su raíz en la
fe; su esencia, no es una respuesta cosmológica de la creación, sino
salvífica, todo lo creado debe caminar hacia aquel ser Divino, superior
a cualquier definición cosmológica, hacia un Dios sobrenatural. El
mensaje parte de la aceptación o rechazo de Jesús en su revelación
trinitaria a partir de un lenguaje cargado de simbolismos y formas
literarias que adquieren sentido en la verdad individual y en el marco
histórico cultural en el que se desenvuelve; el mensaje de Jesús se
destila en un fondo de comunicación Espiritual, más allá de lo
cosmológico, que adquiere fuerza y entendimiento en quien desea de
verdad conocerle, no de manera superficial y protocolaria, ni
pretendiendo una justificación plenamente racional. Solo bajo la
aceptación del misterio, también siempre presente en la ciencia y la
razón, se puede llegar a Él. El ser humano es eminentemente superior a
todas las demás especies vivas, en términos intelectuales y en cuanto al
dominio de la naturaleza, pero la ciencia no admite una definición de
superioridad en términos sobrenaturales en el misterio común del origen
del universo. El sentido racional de las premisas a favor y en contra de
la creación de Dios es muy difuso, porque solo tienen significado en un
plano filosófico; para la verdad científica no tiene sentido dicha
posición y para el pensamiento Cristiano existen razones adicionales a
la fe, que dan cabida a dicha posibilidad. ¿Puede la creación misma
negarse como evidencia de la existencia de un ser superior, un Dios?. El
mismo principio de la metodología científica no permite rechazar una
hipótesis, sin previa demostración; sin embargo la ciencia descarta
incluso la posibilidad de la pregunta anterior y lo hace por falta de
evidencias materiales, siendo estas evidencias las únicas aceptadas por
la inteligencia del cerebro humano aún conociéndose muy poco a si mismo
y conociendo parcialmente tan solo el cinco % del universo que le rodea.
La religión Cristiana parte de una compleja e incomprendida realidad en
la interpretación del ser humano, la cual incluye una esencia espiritual
que existe y deja su huella en una verdad individual que admite una
revelación de Dios; y es extensiva desde la experiencia subjetiva a
través de la fe a la comunidad. De nuevo, es de anotar, que la verdad en
la religión Cristiana y por ende en el mensaje Bíblico no está
edificado, ni interesado en la demostración racional de la verdad
científica, o en la descripción cosmológica, o evolutiva de la
naturaleza ni del universo, como si sucede en otras religiones; y que a
pesar de que acoge y aprueba la verdad científica, por cuanto apunta
hacia la misma verdad absoluta, como en el evento de un origen del
universo, no se sustenta en ella. La ciencia interpreta la Biblia
únicamente en el contexto de forma; pero no de fondo dado su mensaje
espiritual, el cual tampoco es del todo entendido en el ser humano desde
la razón, puesto que admite el misterio y la debilidad humana. Esto se
advierte en otra aseveración, que desde el primer párrafo de la Biblia,
se convierte en una de sus revelaciones en la creación "...el espíritu
de Dios aleteaba sobre las aguas...", puesto que la Espiritualidad de
Dios como ser creador, se constituye en uno de los pilares fundamentales
en la visión teológica de la religión Cristiana a partir de la fe.
Debido a que la civilización moderna, de hace unos siglos para acá, está
empeñada en entender la fe en la verdad individual únicamente desde la
razón y la ciencia, entender la presencia del "Espíritu", en el mundo
del progreso contemporáneo, lleva a continuas frustraciones y callejones
sin salida. Leonard Susskind (New York, 1940 - actualmente)[^85] uno de
los científicos actuales de gran reconocimiento en su medio, quien está
entre los creadores de la nueva teoría de cuerdas para la explicación
del origen del universo, no rechaza la posibilidad de que una
inteligencia superior esté involucrada en la creación del universo de
una manera u otra; pero admite que si es verdad, ¿ como se podría
describir?, ¿cuales serían la reglas que le harían estar ahí? ,
finalmente es más la curiosidad que causa esa posibilidad y son más las
preguntas sin respuesta, que para Susskind no tiene sentido ni siquiera
plantear una hipótesis[^86].

## El Espíritu Humano y el cimiento único Cristiano

Siendo el alma una definición filosófica y teológica milenaria, del
latín ánima, se refiere en una de sus definiciones a aquello que está
animado, que se mueve, que tiene vida. Pensadores y culturas a través
del tiempo han construido diversas y complejas concepciones alrededor de
su significado, una definición que finalmente está arraigada en el
momento histórico cambiante de la civilización es su definición como una
entidad separada del cuerpo [^87] , pero que finalmente es un misterio y
cuya existencia sigue en el terreno de la teología y de la filosofía. El
ser humano posee un alma expresada desde la Cristiandad como una "unidad
espiritual con su cuerpo" , definida con una naturaleza de salvación; es
decir, puede perderse[^88] o no, según la voluntad de Dios; tiene
entonces un sentido o esencia espiritual[^89], a través del cual se
relaciona el alma con Dios. [^90] Es el espíritu en su libertad, el que
permite al individuo, a través de su fe, obtener la gracia de Dios por
medio del Espíritu Santo, el mismo "Espíritu que aleteaba" sobre la
superficie de las aguas. La espiritualidad en el ser humano, como
expresión de la experiencia subjetiva en la verdad individual, en el si
mismo, puede extrapolarse como una vivencia interpretada desde la
religión Cristiana también como expresión de toda una comunidad.
Entonces, aquel cimiento único, como propuesta del Cristianismo, fuente
de principios y valores que el individuo busca por una inercia
espiritual al abrir su corazón, es la *gracia de Dios*, puesto que es
ahí donde confluye toda verdad individual de manera voluntaria y
natural; es ahí donde la experiencia subjetiva adquiere un significado
imposible de explicar con plena exactitud, pero de carácter vivencial y
unificador a través de la fe en Dios, "único ser supremo" fuente y
destino de toda verdad, por tanto, camino a la verdad absoluta; y por
ende camino de toda la comunidad y la sociedad que le acepta.

La espiritualidad manifestada a través de la gracia de Díos tiene una
connotación primordial en la religión Cristiana desde el punto de vista
teológico, pero también tiene una explicación racional, en su componente
objetivo, la cual implica una lógica de pensamiento, que tiene sentido ,
una vivencia desde la verdad individual. Haciendo un poco de gimnasia
conceptual , se puede explicar que la espiritualidad desde la religión
mantiene entonces una huella de su existencia en cada ser humano. Tal
como en la verdad científica sabemos que la gravedad existe dadas las
tesis y leyes de la física que así lo demuestran , aunque no conocemos
su esencia ni su relación con las otras fuerzas de la naturaleza, de la
misma manera desde la verdad individual es factible acercarse a los
rastros de la espiritualidad humana y su reflejo en cada persona, de tal
manera que aunque su esencia es desconocida, dichas huellas señalan su
existencia. Aquella huella espiritual humana, puede fundirse y
expresarse en la libertad, la voluntad y en la conciencia del bien y del
mal. La naturaleza racional del libre albedrío de la que goza todo ser
humano como capacidad de tomar la decisión de pensamiento o de acción
que considere de manera autónoma, es explicada por Santo Tomas de Aquino
(Rocassecca, 1,224 -- 1,274 , Abadía de Fossanova ) [^91], así:

"En el hombre hay libre albedrío. De no ser así, inútiles serían los
consejos, las exhortaciones, los preceptos, las prohibiciones, los
premios y los castigos. Para demostrarlo, hay que tener presente que hay
seres que obran sin juicio previo alguno. Ejemplo: Una piedra que cae de
arriba; todos los seres carentes de razón. Otros obran con un juicio
previo, pero no libre. Ejemplo: Los animales; la oveja que ve venir al
lobo juzga que debe huir de él, pero lo hace con un juicio natural y no
libre, ya que no juzga analíticamente, sino con instinto natural. Así
son los juicios de todos los animales. En cambio, el hombre obra con
juicio, puesto que, por su facultad cognoscitiva, juzga sobre lo que
debe evitar o buscar. Como quiera que este juicio no proviene del
instinto natural ante un caso concreto, sino de un análisis racional, se
concluye que obra por un juicio libre, pudiendo decidirse por distintas
cosas. Cuando se trata de algo contingente, la razón puede tomar
direcciones contrarias. Esto es comprobable en los silogismos
dialécticos y en las argumentaciones retóricas. Ahora bien, las acciones
particulares son contingentes, y, por lo tanto, el juicio de la razón
sobre ellas puede seguir diversas direcciones, sin estar determinado a
una sola. Por lo tanto, es necesario que el hombre tenga libre albedrío,
por lo mismo que es racional."[^92]

Como complemento a un libre albedrío en el ser humano, en aquella huella
que señala hacia la existencia del espíritu humano, a diferencia de las
otras especies , se encuentra la conciencia del bien y del mal a manera
de un juicio moral.

De manera similar a lo que podría ser el dominio de la voluntad del
individuo, si la conciencia del "bien y el mal " pudiese descifrarse y
entenderse desde la verdad científica, encontrando el gen, la neurona,
el efector[^93], o cualquier otro elemento biológico, material o
energético, responsable del mal, podría entonces la humanidad encontrar
la erradicación de la maldad en la humanidad, el invento más
revolucionario sería algo similar a la vacuna contra el mal. Sería tal
vez el avance tecnológico más polémico de la humanidadcientificismo La
responsabilidad de la decisión sobre la modificación a la voluntad
individual recaería sobre unos pocos grupos de interés dominantes y
sería el fin del libre albedrío. Es a través de su propia voluntad que
el individuo decide; y aquella dirección en el actuar, es un reflejo o
manifestación de la naturaleza espiritual del individuo que permanece
inmutable en su corazón, en las profundidades del alma de todo ser
humano. La voluntad de elección entre el bien y el mal, se concibe
también desde la conciencia, donde se esclarecen los aspectos morales
que edifican los principios y valores humanos; la conciencia de lo que
es lícito o ilícito, es una señal de la espiritualidad del ser humano
como individuo, que puede ser manipulada o transgredida por otro ser,
pero en primera instancia se manifiesta en el espíritu de cada ser
humano. El Cardenal San John Henry Newman [^94] lo considera de esta
manera:

"El ser supremo tiene un cierto carácter, el cual expresado en términos
humanos, lo llamamos ético. Él tiene los atributos de justicia, verdad,
sabiduría, benevolencia y misericordia como características eternas en
su naturaleza, la verdadera ley de su ser, idéntica en su ser; en
seguida, cuando fue creador, implantó esta ley , la cual es Él mismo, en
la inteligencia de todas sus criaturas racionales. La ley divina,
entonces, es la ley de la verdad ética, el estándar de lo correcto y lo
incorrecto, una soberana, irreversible y absoluta autoridad en la
presencia de hombres y ángeles. - La ley Eterna - , lo dice San Agustín
(Tagaste, 354 -- Hipona, 430 DC)[^95], Es la razón divina o voluntad de
Dios, dirigiendo la obediencia, prohibiendo el disturbio del orden
natural de las cosas". -La Ley Natural-, dice Santo Tomás, - es la
impresión de la luz divina en nosotros, una participación de la ley
eterna en la criatura racional-. Esta ley, como intuitivamente es
entendida en las mentes del ser individual, es llamada -- conciencia-. Y
a pesar de que sufre una refracción al pasar por el medio intelectual de
cada uno, no es tan afectada como para perder su carácter de ser la ley
divina, pero aun tiene, en si, la prerrogativa del llamado a la
obediencia".[^96]

La gracia de Dios, como expresión y regalo del Espíritu de Dios, se
constituye en la manera como Dios permite que el ser humano en su
dimensión espiritual esté inmerso y participando en la naturaleza divina
y eterna, en la ley divina; entonces, la gracia, es aquel cimiento único
que se vislumbra desde la fe del individuo en una permanente búsqueda,
quien debe atender dicha ley divina de la conciencia del bien y del mal,
de manera natural. La conciencia del bien y del mal está presente en
todo ser humano, sin que necesariamente sea Cristiano, como parte de su
verdad individual que se manifiesta desde su experiencia subjetiva; y la
gracia es el camino unificador y voluntario a través de la fe hacia la
verdad absoluta, a través de la divina revelación, presente en la
historia de la humanidad.

No se ha podido comprobar científicamente el origen del estado "moral"
de la conciencia humana, ni tampoco algunas posibles formas incipientes
de la moral, presente en otras especies. En este sentido, desde la
verdad científica se observa una naturaleza, por momentos,
extremadamente cruel vista desde la moral humana, pero también con
fuertes expresiones de empatía. La explicación a este comportamiento
moral se presenta en una interpretación de la teoría de la evolución de
las especies, muchos siglos después de las anotaciones realizadas por
Santo Tomás de Aquino. La teoría de Darwin, presenta las leyes de la
selección natural como una teoría carente del sustento matemático de las
leyes físicas de la ciencia en su componente sobre la evolución
biológica, pero se desarrolla como observaciones que reflejan leyes
biológicas que actúan en las especies con el fin último de mantener una
adaptación al medio ambiente que garantice la supervivencia de la
especie. Dicha posición considera también que la crueldad o el amor, en
el ser humano, tienen su explicación en la misma teoría de la evolución
y algunos de sus representantes deducen que tiene su origen en la
ciencia de la genética, aún no comprendida al nivel de la conciencia. La
teoría de Darwin es de gran aporte para las ciencias biológicas, en el
mismo contexto señalado por Darwin, pero la interpretación filosófica
desde el modernismo, implica que la conciencia es un resultado de la
evolución, por ende el sentido de la vida del ser humano se reduce a su
deseo de sobrevivir; no podría entonces superar aquella intensa
esperanza de ir al encuentro de la verdad y la trascendencia. En este
sentido, entonces, en muchos casos el Darwinismo filosófico interpreta
cualquier explicación de carácter religioso y espiritual, como un
imposible y mas bien se encasilla en una justificación propia del campo
de la superstición o del fundamentalismo religioso, entendida toda
religión como una misma realidad, establecida en una posición contraria
al evolucionismo, sin profundizar, ni conocer en las diferencias
teológicas ni filosóficas que les caracteriza;[^97] son esos casos, otra
manera de negar la espiritualidad del ser humano. Como ilustración ,
cada ves más científicos aceptan la posibilidad del comportamiento moral
en los animales, el cual todavía bajo debate podría ser algún día
aceptado por la comunidad científica[^98]. Sin embargo, el criterio de
"juicio moral" difiere entre la ciencia y la Cristiandad, debido a que
los principios que los forjan en un caso y en el otro no son
comparables. Desde la ciencia se pueden demostrar niveles de conciencia
e inteligencia en diferentes especies que adquieren su propio
significado en el ecosistema al que pertenecen, lo mismo que poseen
libertad limitada al nivel al que corresponde su instinto natural. El
evidente "sentir" de la planta mimosa púdica sensible al tacto[^99], no
significa que "siente" como un ser humano, pues no tiene sistema
nervioso. El "juicio moral" de un animal diferente al ser humano no es
el mismo "juicio moral" con el que obra un ser humano, no solo por la
gran distancia en cuanto al raciocinio intelectual, o el libre albedrío,
sino porque el ser humano posee un principio espiritual trascendental.
Cuando desde el estudio científico de la evolución de las especies se
analizan estos aspectos y se comparan al ser humano, corren el riesgo de
tocar el campo filosófico o teológico y en ese instante el evolucionismo
entra en un error[^100] alertado desde la Cristiandad, puesto que de
nuevo, se niega la posibilidad de la espiritualidad manifestada por el
ser humano. Todo ello sin percatarse de que por causalidad, al
preguntarse por la causa primera de la evolución se llega al mismo
debate sobre el origen del universo y a las mismas inquietudes sobre "el
ser", que ninguna otra especie es capaz de manifestar. De nuevo se asoma
el misterio que al final une a las ciencias y al Cristianismo en busca
de una verdad absoluta, cada perspectiva desde su propia justificación.
Se presenta el caso también de muchos seguidores del Darwinismo, los
mismos detractores de un posible escenario de un Dios omnipotente, que
adicionalmente tienden a confundir el antropocentrismo[^101] , el
pensamiento del ser humano como centro de todo, admitiendo la conciencia
del hombre como elemento diferenciador: el ser humano, es la única
especie que puede encontrar placer y disfrutar, mientras actúa con
maldad y de manera voluntaria, racional y premeditada sobre cualquier
criatura, incluso otro ser humano. Aunque esta afirmación , no forma
parte de la verdad científica, si forma parte de la verdad individual;
en la cual cada individuo puede tomar disposición hacia un acto de
maldad o de bondad, según su libre albedrío. La teoría del evolucionismo
de Darwin es aceptada por la iglesia Católica dándole el sentido de una
interpretación de la obra de la creación de Dios[^102]. Desde la
Cristiandad, todo ser vivo en la naturaleza y la naturaleza misma son
buenos y no tienen alguna maldad, puesto que todo lo que Dios creó lo
creo "bueno"[^103], pero el ser humano por tener libertad puede decidir
su actuar de forma consciente con juicio de maldad en la manera más
perversa e inimaginable contra si mismo, contra otras personas y contra
la misma naturaleza. El libre albedrío se manifiesta desde la
espiritualidad del ser humano en aquello que se convierte en emoción o
sentimiento inmediato, algo que "se siente" y se origina en la
conciencia al experimentar en el si mismo la aprobación o el rechazo a
una acción previa. Todo ser humano en su vivencia personal ha sentido
una reacción de reconocimiento de "culpabilidad" ó "aprobación" en el si
mismo; pero aquello que "se siente" es algo que va mas allá de lo
puramente racional. Este sentir es un reflejo del individuo como un todo
en su propia identidad, así también se refleja la espiritualidad del
individuo quien por su propia voluntad ejecutó el acto inspirado en su
verdad individual. Este aspecto, fuente de la moral en el ser humano, es
aquel que influye en la elaboración de los principios y valores también
en su comunidad. Se hace, entonces, evidente algo fundamental y es que
la espiritualidad del ser humano, inexplicable desde la ciencia, tiene
sentido en la experiencia subjetiva de la verdad individual. Ahora bien;
se han tocado algunas señales o huellas, sobre la existencia del
espíritu humano, las cuales pueden explorarse desde el legado de la
Cristiandad con mucha más profundidad.

## El Espíritu Santo

Uno de los misterios más explorados y sobre los que se ha escrito tanto
en la religión Cristiana, es el misterio de la Santísima Trinidad.
Cuenta la historia que San Agustín, el gran teólogo y Santo Católico
intentaba descifrar este misterio de la doctrina Cristiana, en el cual
existe un solo Dios , un solo ser en tres personas diferentes: El Padre,
el Hijo y El Espíritu Santo. El Hijo procede del Padre y el Espíritu
Santo procede del Padre y del Hijo. Todos son personas divinas[^104].
Estaba San Agustín pensando en la playa , y de repente vio un niño
frente a un hoyo en la arena intentando verter el agua del mar en el
hoyo. Le pregunta San Agustín, "¿Qué haces ?" y el niño responde
"intento verter toda el agua del mar en este hoyo", ante lo que San
Agustin responde "eso es imposible"!. El niño luego le dice, es más
fácil que yo pueda verter toda el agua del mar en este hoyo, a que tu
comprendas el misterio de la Santísima Trinidad. En la iglesia Cristiano
Católica se habla del "soplo" del Espíritu Santo como una manera de
expresar la influencia del Espíritu Santo en el ser humano, es el
portador de la gracia de Dios en cada individuo, formando así parte de
su verdad individual. Entender la esencia del Espíritu Santo de manera
racional es tal vez imposible, ya que solo puede ser parte de la
realidad en la existencia de cada individuo como experiencia subjetiva;
pero actúa como guía y bastión de una verdad absoluta que por si mismo,
el individuo no puede comprender; cuando se le invoca, se adquiere su
gracia sobrenatural y en la vivencia personal se despierta la fe. Aún
cuando no se pueda entender plenamente el significado[^105] del Espíritu
Santo, atender a su llamado conlleva a un largo camino de conversión.
Debido a que Dios creó al ser humano a su imagen y semejanza, el
espíritu humano está relacionado al Espíritu Santo a través del
sacramento del bautismo. Pero esto, que suena como un cuento de hadas
para el pensamiento racional, en la realidad de la verdad individual de
quienes tienen fe, es un asentimiento real. El "Espíritu Santo", en la
religión Cristiana y siendo parte de la trinidad, es la manifestación
del amor divino, amor del padre y del hijo presente a través del
cimiento único de la gracia en cada ser humano, permaneciendo en Él la
esencia de la ley divina; Él es quien guía el caminar hacia la verdad
absoluta, hacia la sabiduría de un amor sobrenatural que no cabe en la
capacidad de entendimiento humano, es mucho más que la expresión de una
emoción, un sentimiento o alguna energía cósmica. El Espíritu Santo como
parte del Dios hecho trinidad es un misterio de fe; un misterio
rechazado al no encontrar al menos una evidencia desde el conocimiento
del universo y del ser humano; "En el cosmos material no hay bien
espiritual , ni la más pequeña cantidad de bien espiritual"[^106].
Paradójicamente, la señal de su existencia no está tan lejos, ni es tan
compleja, pues se puede encontrar al interior de cada persona; en el si
mismo como parte de la verdad individual, en un lugar recóndito y
reservado por Dios; se busca mediante la gracia en el silencio del alma,
en el corazón del ser humano, en la meditación mediante un diálogo
directo con Jesús a través de las sagradas escrituras. En su sabiduría
Jesús nos dejó la forma más fácil de llegar a Él: la búsqueda del
Espíritu Santo en el ser humano y su presencia, se encuentra en la
oración humilde en "silencio". Es el regalo más preciado, más fácil de
obtener y el más incomprendido y de muchas formas, al no ser de carácter
funcional, es ignorado y en muchas ocasiones rechazado por el progreso
contemporáneo; es el regalo de la gracia de Dios, el cimiento único que
apoya y guía al ser humano en la oración en el silencio del alma.

### El silencio

Es más fácil entender una verdad que percibimos con los sentidos. Pero
intentar resolver inquietudes de tipo espiritual desde la lógica de la
actividad puramente intelectual lleva a la desilusión. Por ello un
lenguaje más cercano al corazón es más adecuado, la espiritualidad puede
ser mucho mejor expresada desde un lenguaje casi poético, directamente
por las fuentes expertas de este laberinto del si mismo en el ser
humano. Numerosas vidas de filósofos, profesionales en diversas ramas
del conocimiento y teólogos de diversas religiones, se han dedicado a la
exploración de la espiritualidad humana desde la existencia de la
civilización; en este caso acudo literalmente a párrafos representativos
de dos escritores maravillosos que exaltan desde sus propias vivencias
una idea literaria extraordinaria de lo que puede ser el encuentro del
alma con el Espíritu en el silencio; Entre los muchos caminos, en las
obras "La fuerza del silencio" de el Cardenal Robert Sarah (República de
Guinea, 1945, actualmente)[^107] y de "La sabiduría de los Padres del
desierto" del Monje Anselm Grun(Baja Franconia, 1945 -
actualmente)[^108] , se describe cómo el ser humano a través del
silencio puede encontrarse en el si mismo con el Espíritu de Dios. Este
es un lugar desconocido por la verdad científica, e impreso en una
experiencia subjetiva y cobijado bajo la verdad individual de los
autores que desean expresar el silencio como personas partícipes de sus
propias debilidades y fortalezas humanas, mas allá de las profundidades
de la consciencia humana, en su espíritu humano. El silencio es una de
las maneras de llegar a la verdad absoluta con el beneplácito de la
gracia de Dios, es el medio para buscar al Espíritu Santo, portador del
amor divino; es a través de un lenguaje natural y despreciado por la
civilización del progreso , lenguaje accesible desde la fe, lenguaje
espiritual llamado "silencio", lenguaje a veces mas incomprensible que
las mismas matemáticas, teniendo en cuenta el ruido al que está
habituada la sociedad del presente. Estos son algunos apartes de las
obras de Sarah y Grun.

¿Donde está el Espíritu Santo ?

-   ¿Cómo se desarrolla la naturaleza ? En el silencio más absoluto. Un
    árbol crece en silencio y los manantiales de agua brotan del
    silencio de la tierra. El sol que se alza sobre la tierra,
    deslumbrante y grandioso, nos da calor en el silencio. Lo
    extraordinario siempre es silencioso (...). El niño crece en
    silencio en el vientre de su madre. Cuando un recién nacido duerme
    en la cuna, a sus Padres les gusta mimarlo con la mirada, sin decir
    nada para no despertarlo: es un espectáculo que solo se puede
    contemplar en silencio, maravillados ante el misterio del hombre en
    su pureza original[^109].

-   Nosotros escuchamos las palabras del sacerdote: Yo te bautizo\...,
    vemos correr el agua por la cabeza del niño; pero de esa inmersión
    en la vida íntima de la Trinidad, de la gracia y de la creación que
    requiere nada menos que la acción personal y omnipotente de Dios, no
    hemos visto nada. Dios ha pronunciado su verbo en el alma en
    silencio. En esa misma oscuridad silenciosa suelen acontecer los
    sucesivos desarrollos de la gracia[^110].

-   \"Cuando a los sabios se les agita la sabiduría, conviene escuchar a
    los niños\" escribe George Bernanos en Diálogo de Carmelitas[^111].

-   ¿Porqué los hombres no pueden escuchar la voz de Dios cuando habla a
    través de la creación ? ¿De hecho nos creemos los únicos capaces de
    escucharle y de hablarle ?. En Partir antes de alba Julien Green
    escribe: \"Dios habla con suma dulzura a los niños y lo que tiene
    que decirles suele decirlo sin palabras. La creación le proporciona
    el vocabulario que necesita: las hojas, las nubes, el agua que
    corre, un punto de luz. Es el lenguaje secreto que no se aprende en
    los libros y que los niños conocen bien(\...) Los niños son como un
    pueblo numeroso que han recibido un secreto incomunicable que se va
    olvidando poco a poco porque las naciones supuestamente civilizadas
    se han adueñado de su destino (\...)[^112]

-   En el corazón del hombre existe un silencio innato, pues Dios habita
    en lo más íntimo de cada persona[^113].

-   El autor de la famosa frase "Noverim me, Noverim te"[^114] (Solil
    2,1), afirma a lo largo de toda su obra que el conocimiento propio y
    el conocimiento de Dios están íntimamente unidos. Ir en busca de
    Dios no consiste en salir de si mismo para hallar un objeto en el
    mundo exterior, sino en separarse de ese mundo y replegarse en uno
    mismo "No quieras derramarte fuera; entra dentro de ti mismo, porque
    en el hombre interior reside la verdad".[^115]

-   El silencio es un paraíso, pero el hombre no lo vé de forma
    inmediata. Está lleno de contradicciones. Ante Dios hemos de ser
    como niños. Y sin embargo, empleamos multitud de medios para hacer
    difícil, oscura y hasta inexistente nuestra relación con Él. El
    hombre ha perdido la sencillez de la infancia. Por eso le cuesta
    tanto el silencio. Y lo rechaza hasta tal punto que quiere
    convertirse en Dios. En el silencio, el hombre no puede ser una
    falsa divinidad, sino limitarse a permanecer en un luminoso cara a
    cara con Dios.[^116]

-   ¿Quieres conocer a Dios ? Aprende antes a conocerte a ti mismo. Sin
    este conocimiento, estamos siempre en peligro de que nuestra idea de
    Dios, sea una pura proyección de nosotros mismos.[^117]

Existe un silencio impreso al interior de cada ser humano en su verdad
individual, silencio que se manifiesta en los niños y en la naturaleza,
lugares donde habita Dios; y es este silencio el que permite navegar
interiormente para encontrar a Dios a través del Espíritu Santo. Esta
acción en la que Dios permite la unión de su Espíritu con el del ser
humano, es un misterio de fe que sucede desde el bautismo; pero, lo
dejamos desvanecer con el pasar del tiempo por atender únicamente el
ruido del progreso.

La enseñanza de los Monjes...

-   Los monjes tomaron la sabiduría y la experiencia que ascetas de
    todas las religiones y de los círculos filosóficos habían acumulado
    ya anteriormente. Solo así pudieron permanecer en continua soledad y
    vigilancia y en constante búsqueda de Dios, para alcanzar de ese
    modo un gran conocimiento del ser humano y un verdadero rastro de
    Dios[^118].

-   La ascesis es un medio que nos ayuda a quitar de nuestra vida lo que
    la sobrecarga, es decir, lo que pone trabas a nuestra vida
    espiritual y constituye un obstáculo para la oración. Si, es
    precisamente en la oración donde Dios nos comunica su vida y
    manifiesta su presencia en nuestra alma regándola con el caudal de
    su amor trinitario.[^119]

-   Los monjes han desarrollado métodos de lucha para conseguir ese amor
    , esa claridad y limpieza interior y estar abiertos a Dios. Dos son
    las imágenes que encontramos en sus escritos y que corresponden a la
    imagen que Dios se ha hecho de nosotros: somos atletas de Cristo,
    somos soldados de Cristo rey.[^120]

-   La sumisión del cuerpo al Espíritu se consigue mediante la ascesis
    en el alimento. El monje renuncia a la carne y come lo menos
    posible.(\...) La ascesis se exige también en el sueño. Los monjes
    dormían lo menos posible.(...) De todos modos, los monjes nos ponen
    en vela contra la ascesis exagerada, que , sin prestar atención a
    las propias limitaciones, quisiera someter por la fuerza al propio
    cuerpo.[^121]

-   Del abad Poimén conservamos esta frase: Toda exageración es el
    demonio[^122].

-   En este permanecer en la celda hay que tener en cuenta siempre dos
    aspectos: el conocimiento de uno mismo y el envolverse totalmente a
    Dios.[^123]

-   No olvidemos nunca las palabras de San Bruno, dulces y enérgicas, en
    su carta a Raoul le Verd: \"Aquí, por el esfuerzo del combate,
    concede Dios a sus atletas la esperada recompensa: la paz que el
    mundo ignora y el gozo en el Espíritu Santo\".[^124]

-   Blaise Pascal afirmó que la causa de las miserias humanas radica en
    que ya nadie permanece en su habitación consigo mismo. No aguantarse
    sin saltar de una cosa a otra resulta hoy ya habitual. El hombre
    puede así distraerse muy bien. No necesita más que ver todos los
    programas de la televisión. Sin embargo, ¿ que es lo que sucede en
    el alma ? Nada puede madurar, nada puede crecer. No arraiga ninguna
    verdad.[^125]

-   El método "anterrhético", trata de conocer los propios pensamientos
    y de buscar en la sagrada escritura palabras de sanación que puedan
    curarnos de ellos. Este método de contraponer una frase de la
    sagrada escritura a los malos pensamientos y sentimientos los ha
    tomado también el método americano de pensar positivo. Pero allí,
    aparece con frecuencia como si nosotros pudiéramos manipular
    nuestros sentimientos, como si bastara pensar en positivo para que
    todo se pusiera en orden.[^126]

-   La espiritualidad de los monjes ha hecho una cultura de la vida.
    Ella nos invita hoy a impregnar nuestra vida de espiritualidad, a
    fomentar una cultura de vida espiritual que aparezca también
    exteriormente.[^127]

Jesús se retira cuarenta días y sus noches al desierto; este capítulo de
su vida es seguido inicialmente por los ermitaños en los siglos II al IV
de nuestra era con el fin de encontrarse espiritualmente con el Padre.
Luego los monjes capitalizaron estos aprendizajes y vivieron en
comunidad, trazando nuevas maneras y métodos de oración para el mismo
fin; en el camino todos han tenido que vencer al mal, en sus diferentes
manifestaciones. Veinte siglos después existen los monasterios y las
comunidades de monjas religiosas, quienes desde una presencia humilde,
silenciosa y desapercibida, oran constantemente por la humanidad en
compañía del Espíritu Santo. El grueso de la comunidad Cristiana, tiene
por descubrir mucho en las enseñanzas que Jesús nos envía a través de
estos Monjes.

Sobre la oración \...

-   Muerta en el silencio de la escucha, la palabra vuelve a florecer
    bajo el sol del Espíritu Santo que la despierta a la vida. Asimilada
    y fecundada en la oración, aparece como un ser nuevo cargado de
    copiosos frutos: si el grano de trigo no muere queda infecundo. La
    muerte de la semilla es la vida de la planta. Y la planta, el único
    ser de la naturaleza que es a la vez silencioso y animado, se
    presenta ante nosotros como la imagen más perfecta de lo que ocurre
    en los momentos que siguen a la escucha silenciosa.[^128]

-   La oración consiste en conseguir callar, escuchar a Dios y saber oír
    los gemidos infalibles del Espíritu Santo que habita en nosotros y
    grita en silencio.[^129]

-   La oración tiene que ser un modo de resistencia para ahuyentar las
    dificultades. Permite revestirse de la armadura de Dios. El hombre
    se vuelve humildemente hacia Él para que intervenga a su
    favor.[^130]

-   Para aprender a guardar silencio y alimentarlo de la presencia de
    Dios hemos de practicar la Lectio Divina, ese rato de escucha
    silenciosa, de contemplación y de profundo recogimiento a la luz del
    Espíritu. La Lectio Divina es un torrente abundante que lleva
    consigo todas las riquezas acumuladas por los lectores piadosos de
    la palabra de Dios en el transcurso de la historia de la iglesia. La
    Lectio Divina no es nunca ni únicamente una lectura personal. Se
    alimenta de la interpretación de quienes nos han precedido. El
    monje, el sacerdote y el diácono están habituados a ellas gracias al
    oficio divino que les permite escuchar, además del Texto Sagrado,
    los comentarios de los padres de la iglesia. A veces estos
    comentarios difieren mucho entre sí. A la mentalidad contemporánea
    le parecen austeros, desconcertantes y extraños. Pero, si
    perseveramos en la Lectio Divina y en la escucha silenciosa de lo
    que el Espíritu dice a las iglesias, nuestro esfuerzo se verá
    recompensado con tesoros y riquezas increíbles.[^131]

-   San Juan María Vianney, hombre de silencio , gran pastor de almas,
    plenamente entregado a la Palabra de Dios y al Misterio de la
    Reconciliación (\...) Nos deja la definición más sublime de la
    oración\...(\...) \" La oración no es otra cosa que la unión con
    Dios. Todo aquel que tiene el corazón puro y unido a Dios
    experimenta en si mismo como una suavidad y dulzura que embriaga, se
    siente como rodeado de una luz admirable. En esta íntima unión, Dios
    y el alma son como dos trozos de cera fundidos en uno solo, que ya
    nadie puede separar. Es algo muy hermoso está unión de Dios con su
    pobre criatura; es una felicidad que supera nuestra
    comprensión.[^132]

-   El silencio contemplativo es un silencio de adoración y escucha del
    hombre que se presenta ante Dios. Presentarse en silencio ante Dios
    es orar. La oración nos exige conseguir hacer el silencio para oír y
    escuchar a Dios.[^133]

-   Me parece lógico que el hombre que no ora nunca sea incapaz de
    comprender la palabra silenciosa de Dios. Cuando estamos enamorados,
    sin embargo, percibimos hasta el más mínimo gesto del ser amado. Lo
    mismo ocurre con la oración. Si tenemos la costumbre de orar con
    frecuencia, podremos captar el significado de los silencios de Dios.
    Hay señales que solo los novios son capaces de comprender. También
    el hombre de oración es el único que capta las señales silenciosas
    de afecto que recibe de Dios.[^134]

-   Antes de acusar a los demás, conviene mirarse a uno mismo. Tenemos
    una infinita capacidad de arrojar la piedra a la cara del vecino.
    Haríamos mejor en asumir nuestras propias faltas. En la oración y el
    silencio nuestro corazón reluce mucho menos que en el frenesí ciego
    y autista de la rebelión.[^135]

-   En la oración contempla el hombre su propia luz, si, se hace
    consciente de su propia naturaleza, que es toda luz, participación
    de la luz de Dios.En ese lugar de Dios, en el lugar de la paz, en el
    interior del alma, está todo tranquilo. Allí habita solo Dios. Allí
    todo es santo. Allí se encierran en el amor de Dios todas las llagas
    que nos ha abierto la vida. Allí desaparecen todos los pensamientos
    contra las personas que nos han herido. Allí nuestras pasiones no
    tienen ya entrada. Allí tampoco pueden alcanzarnos los hombres con
    sus expectativas , con sus ideas con sus juicios. Allí estaremos
    unidos con Dios. Allí nos sumergimos en su luz, en su par , en su
    amor. Este es el objetivo del camino espiritual.[^136]

El silencio y la oración son cómplices para encontrar en el si mismo al
Espíritu Santo. La Lectio Divina es uno de los tantos caminos que la
iglesia enseña para encontrar aquella paz sumergida en el amor, en el
interior del alma donde está todo tranquilo. Dios escucha la oración y
responde a cada ser humano, a su manera, a su tiempo, sacando un bien
mayor de todo mal y para enriquecer en sabiduría la verdad individual.

El misterio

-   Para nosotros el misterio es una realidad muy positiva. Somos como
    los niños que contemplan el mar por primera vez. Fascinados por lo
    que ven, no dejan de adivinar que lo que está más allá escapa con
    mucho a sus ojos, e incluso a su imaginación. Pueden decir que han
    visto el mar, que lo conocen y, al mismo tiempo, que les queda todo
    por descubrir de él. Cuando se trata del mar sin orillas, el
    infinito de Dios, el misterio ofrece una apertura sin fin hacia
    Aquel a quien nunca acabaremos de descubrir. Las palabras se quedan
    cortas a la hora de describir una realidad tan fascinante.[^137]

-   Cuanto más estudiamos un misterio, más comprendemos que no
    comprendemos, lo cual acrecienta nuestra admiración.[^138]

-   Con el tiempo terminamos conociendo el lenguaje de Dios, un lenguaje
    distinto para cada persona. Yo conozco muy bien el lenguaje que
    emplea conmigo, esa manera tan especial de mezclar lo humano y lo
    divino, y puedo afirmar que es maravillosamente adecuado. Mas de
    palabras , se trata de un amor que se despierta y que se viene de
    fuera, porque su origen no está en mi. La intimidad divina\...no
    siempre se nos da, y el desierto puede parecer árido. Cuando se
    manifiesta, su melodía resuena con mucha más intensidad que el
    bienestar del simple silencio junto a Dios.[^139]

-   Es una suerte que se nos escapen tantas cosas: nos queda un infinito
    por descubrir. Las realidades más conocidas están llenas de
    misterio. Cuanto más avanza la ciencia, por ejemplo, menos entiende
    la materia. Solo quien no ha reflexionado sobre el tiempo cree saber
    lo que es. ¿ Quien puede pensar que somos capaces de averiguar el
    sentido del actuar de Dios en este mundo ?.[^140]

-   Cuando se trata de Dios, el misterio está por todas partes. El
    propio hombre es misterio, porque ha sido hecho a imagen de Dios. La
    creación es misterio, porque Dios lo es todo y fuera de Él no puede
    existir nada. El primer versículo de la Biblia nos permite afirmar
    que Dios ha creado el mundo, pero no podemos explicarlo.[^141]

El misterio es una forma de silencio en la que eventualmente se intenta
entender a Dios de manera infructuosa y equivocada; Dios ha permitido al
ser humano encontrarse con Él desde la admiración del misterio, desde su
aceptación y contemplación; así como se contempla la creación y la
naturaleza como un regalo de Dios, así se puede contemplar a Dios a
través del silencio , en el infinito de lo divino, de lo inexplicable.

Sobre Cristo...

-   En este mundo el único silencio que hay que buscar es el que
    pertenece a Dios. Porque solo el silencio de Dios se alza con la
    victoria. El pesado silencio de la muerte de Cristo no duró mucho y
    engendró vida.[^142]

-   Con su encarnación Cristo asume los límites humanos. Ante el
    silencio de Dios nos enfrentamos al amor absoluto. Y ese gran
    silencio explica también la libertad concedida al hombre. El único
    poder de Dios es amar en silencio. Es incapaz de cualquier fuerza
    opresiva. Porque Dios es amor y el amor no puede obligar, forzar ni
    presionar para que se le devuelva el amor.[^143]

-   Todos hemos experimentado alguna vez una sensación espantosa de
    abandono, y lo que más miedo nos da de la muerte es precisamente
    esto, al igual que los niños tenemos miedo a estar solos en la
    oscuridad y solo la presencia de una persona que nos ama nos puede
    tranquilizar\...(\...)..El ser humano vive por el hecho de que es
    amado y puede amar; y , si el amor ha penetrado incluso en el
    espacio de la muerte, entonces hasta allí ha llegado la vida.[^144]

-   La ausencia del Espíritu Santo en la iglesia crea todas las
    divisiones. Allí donde está la iglesia, está el Espíritu Santo. Allí
    donde está el Espíritu Santo, está la iglesia. El Espíritu Santo es
    el vínculo de comunión entre el Padre y el Hijo. Es el aliento de
    vida que no somos capaces de atrapar. Es invisible pero está
    plenamente presente.[^145]

-   Es importante dejar que el Espíritu Santo penetre hasta las regiones
    más profundas del alma. En ese espacio secreto habita y actúa Dios;
    obra para llevar a cabo nuestra unión con Él. Mientas el hombre no
    alcance a reconocer el gran silencio de Dios en lo más hondo de su
    corazón, mientras no alcance a comprender ese misterioso espacio de
    lo eterno en su carne, no podrá acceder a una auténtica
    transformación espiritual y humana. Este es el verdadero sonido del
    silencio: no podemos escuchar al verbo si previamente no hemos sido
    transformados por el silencio de Dios.[^146]

-   ¿ Porque vamos a alzarnos en contra la muerte ? El rechazo a la
    muerte es un callejón sin salida. Porque por encima de la ausencia y
    la sepultura, la muerte es un nuevo nacimiento. Ante ella somos como
    los recién nacidos: no sabemos hablar, pero la vida se desarrolla y
    crece de manera invisible.[^147]

El poder del misterio de la trinidad se manifiesta en el amor infinito y
silencioso de Jesús, quien enviado por Dios Padre y acompañado por el
Espíritu Santo, vence a la muerte desvaneciendo en su sufrimiento las
culpas terrenales de aquellos arrepentidos, quienes así podrán también
vencer a la muerte y nacer así al verdadero paraíso de muchas moradas,
donde podrá disfrutar del amor y la felicidad eterna.

El camino de la humildad..

-   Si lo comprendes, no es Dios , escribe San Agustín.[^148]

-   El camino hacia el cielo consiste en volver a encontrar nuestra
    interioridad silenciosa en la que Dios habita y nos espera
    escrutando el horizonte.[^149]

-   Para Poimén, el camino espiritual comienza por las pasiones. A estas
    es a las que hay que prestar atención primero y con ellas hay que
    lidiar. Solo entonces, entenderá uno algo de Dios. Si, el trato con
    las pasiones es, para él, el camino que lleva a Dios.[^150]

-   San Benito, La paradoja está, en que subimos a Dios cuando bajamos a
    nuestra propia realidad. Así entiende él las palabras de Jesús: \"El
    que se humilla será ensalzado\" Lc 14; 11;18,14)[^151]

-   La humildad es para el hombre el valor de reconocer la verdad,
    reconocer su condición de tierra y su condición de hombre\....es la
    prueba de una vida según el espíritu de Dios\...sin humildad está
    siempre el peligro de manipular a Dios\...es la condición para dejar
    a Dios ser Dios, para descubrir el rastro de un Dios totalmente
    diferente.[^152]

-   Cuánto más se acerca uno a Dios, tanto más humilde se es, pues uno
    experimenta que , como hombre está muy lejos de la santidad de Dios.
    La humildad es la respuesta a la experiencia de Dios.[^153]

-   El amor silencioso solo puede crecer en la humildad.(\...)El Padre
    en quien creemos es infinitamente humilde, silencioso, carente de
    todo afán de prestigio.[^154]

-   Dios nos forma a través de nuestros fallos, de nuestras defecciones.
    Así es cómo Él nos conduce por el camino de la humildad, que es el
    único que lleva a Dios.[^155]

-   Sin una humildad radical expresada en gestos de adoración y en los
    ritos sagrados no hay amistad posible con Dios. El silencio
    manifiesta esa relación de un modo evidente. Para convertirse en
    silencio de comunión el verdadero silencio Cristiano se hace antes
    silencio sagrado.[^156]

El camino de la humildad inicia desde el dominio de las pasiones
terrenas, que tan solo con la guía del Espíritu Santo, podremos escalar
al encuentro con Dios. La humildad también surge del silencio como
ingrediente indispensable para caminar hacia la verdad absoluta y para
recibir el abrazo glorioso de Dios.

El bien y el mal\...

-   Tenemos que estar expuestos a las tentaciones que lleva consigo la
    vida. Y no se dará ningún momento en el que podamos descansar sobre
    nuestros laureles.[^157]

-   Los monjes en cambio hablan de las tentaciones de los pensamientos,
    de las pasiones y de los demonios. Tales tentaciones son algo
    sustancial en nosotros y nos hacen más vigilantes y
    cuidadosos.[^158]

-   En nuestro interior aparece una lucha entre el bien y el mal, entre
    la luz y las tinieblas, entre el amor y el odio.[^159]

-   Los horrores de los hombres y las obras del Diablo son un misterio
    que la humanidad nunca podrá entender del todo. El mal físico o
    moral siempre es injusto e infame. Envilese y destruye al hombre.
    Empaña la imagen de Dios impresa en el hombre.[^160]

-   Dios no quiere el mal. Dios no quiere la guerra. Dios no quiere ni
    la muerte ni el sufrimiento. Dios no quiere la injusticia. Y sin
    embargo, permite todos estos males de la tierra. ¿ Porqué este
    misterio ? El Padre desea que asumamos la totalidad de nuestra vida
    en la tierra. Y el mal forma parte de la condición humana. Ha
    querido que su propio hijo sufra la experiencia del mal más abyecto
    para la redención y salvación del mundo.[^161]

-   El silencio divino es una revelación misteriosa. Dios no es
    insensible al mal.A primera vista, se podría pensar que Dios permite
    que el mal destruya a los hombres. Pero aunque Dios guarde silencio,
    no sufre menos que nosotros ese mal que desgarra y desfigura a la
    tierra. Si procuramos estar junto a Él en el silencio,
    comprenderemos su presencia y su amor.[^162]

    La tentación nos obliga a la lucha. Sin lucha no hay victoria. Pero
    la victoria no es nunca algo que merecemos. En las luchas podemos
    aprender que Cristo actúa en nosotros, que, llegado el momento, nos
    libra de la constante lucha y nos concede una paz profunda.[^163]

-   He vivido un doloroso asesinato de manos de la calumnia, la
    difamación y la humillación pública, y he aprendido que, cuando una
    persona decide destruirte, no le hacen falta palabras, ni saña, ni
    hipocresía: la mentira tiene un inmenso poder a la hora de armar
    falsos argumentos, pruebas y falsas verdades. Cuando ese
    comportamiento procede de hombres de iglesia y, en especial, de
    obispos ambiciosos y falsos, el dolor es aún más profundo. Pero los
    hombres miran las apariencias y Dios mira el corazón. Tengamos en
    cuenta únicamente su mirada y conservemos la calma y el silencio,
    pidiendo la gracia de no permitir que nos invadan el rencor, el odio
    y los sentimientos mezquinos. Mantengámonos firmes en el amor a Dios
    y a su iglesia, firmes en la humildad.[^164]

El hogar del ser humano es el cielo; pero el ser humano se desterró al
dejarse tentar por el mal y caer en el pecado. Dios en su misericordia,
ha permitido que regrese aún cuando el ser humano le sigue rechazando y
ofendiendo. Pero, porque Dios le ama, le ha dado una oportunidad y es
vencer por su propia voluntad esa maldad que le hizo caer y que sigue al
asecho en el destierro. Dios no quiere el sufrimiento, pero lo permite
en cualquiera de sus formas sacando siempre un bien mayor, inclusive en
su Hijo, porque lo estableció en su omnipotencia como condición para la
fiesta de regreso del ser humano a su hogar santo y natal. En su camino,
el Seńor se compadece y le sostiene como un Padre que lleva de su mano a
su hijo al caminar. Tampoco Dios ha dejado en la oscuridad de su propia
voluntad al ser humano en esta lucha, pues le ha dado una manera de
defensa infalible, le ha ofrecido aquella luz, que moldea el alma, un
misterioso lugar donde habita Dios mismo. Aquella luz , es el amor
divino, que se encuentra en las profundidades del silencio en el si
mismo, que llega a través de la gracia en quien la pide, como cimiento
del Espíritu Santo.

La sociedad moderna

-   El juzgar a otros es siempre síntoma de que uno no se ha encontrado
    con uno mismo. De aquí que haya gente piadosa que se escandaliza de
    los demás, que nunca se ha encontrado con su propia realidad. Su
    religiosidad no les ha confrontado consigo mismos ni con sus
    pecados.[^165]

-   El juzgar a los otros vuelve ciegos para las propias faltas. Guardar
    silencio en vista de los demás hace posible más claro el
    conocimiento de uno mismo. Y dejamos de proyectar sobre otros
    nuestras propias faltas.[^166]

-   Los hombres en los juicios de hoy, no son considerados pecadores.
    Son catalogados como sanos, enfermos, malos, buenos, fuertes
    débiles, ricos, pobres, sabios, ignorantes; pero la palabra pecado
    no se encuentra jamás. Y no retorna porque, distanciado el intelecto
    humano de la sabiduría divina , se ha perdido el concepto de
    pecado.[^167]

-   Nosotros no somos responsables de los pensamientos que nos vienen.
    Pero sí de cómo nos comportamos con ellos.[^168]

-   La gran diferencia entre Dios y el hombre reside en el tema de la
    posesión. Si el ser humano no posee bienes materiales , se siente
    como si no tuviera nada, perdido y débil. La mayor parte de nuestros
    problemas proceden de cierta transgresión de la pobreza. El hombre
    se deja atrapar de sus más bajos instintos posesivos. Quiere
    acumular bienes materiales para saciarse y disfrutar de ellos. Pero
    esos bienes superfluos tapan nuestros ojos, cierran nuestros
    corazones y minan nuestra energía espiritual. Aún así hay muchos
    hombres ricos que viven una excepcional vida espiritual junto a Dios
    y una generosidad inmensa con los pobres.[^169]

-   Dios no desprecia a los poderosos porque él es poderoso. Jb,
    36,5.[^170]

-   Sin Dios es fácil constatar los rotundos fracasos de los debates
    humanos y las soluciones políticas frente al mal.[^171]

-   Hoy son demasiado pocos los Cristianos dispuestos a entrarse en si
    mismos para mirarse y dejarse mirar por Dios.[^172]

-   Hoy en día, se habla también del miedo de los jóvenes a
    comprometerse, pues no quieren hacerlo para siempre ni en el
    matrimonio ni en el orden sagrado.[^173]

-   La ausencia de Dios constituye la raíz de una forma de rebelión
    ruidosa. Esta rebelión es una ilusión que consiste en creer que
    podemos prescindir de Él para vivir mejor en este mundo. A partir de
    ahí , el silencio de Dios se convierte en un aliado casi objetivo,
    la prueba tangible de una humanidad sin creador. Al defender su
    autonomía respecto de lo divino, el hombre moderno acaba no
    soportando siquiera el silencio de Dios.[^174]

-   Estamos ansiosos de dar una respuesta a tantas dificultades,
    sufrimientos y desastres como se debaten sobre la humanidad.
    Olvidamos que el origen de nuestros males es la ilusión de ser algo
    más que polvo. El hombre que se endiosa no quiere saber que es
    mortal.[^175]

-   A fuerza de querer dominarlo todo, de situar todo bajo el signo de
    la rebelión, el hombre corre el riesgo de no poner nada en manos de
    Dios. Se encuentra solo frente a sus límites y su impotencia. No
    obstante , el hombre sin Dios está perdido. Sin la fe vivida en un
    silencio confiado, se aparta de su Dios y redentor.[^176]

-   El peligro actual reside en el activismo desenfrenado del mundo
    moderno. Estamos constantemente llamados a combatir, a hacer
    campaña, a derribar al adversario, a destruirlo. De hecho , se
    invita al hombre a añadir más mal al mal, cuando habría que dejar
    crecer la cizaña y el trigo. El silencio nos dará paciencia para
    aguardar el momento en que las malas hierbas mueran
    solas..(\...)..Existe un tiempo de pelear y un tiempo de callar. Si
    domináramos de verdad la pedagogía del silencio que procede de Dios,
    tendríamos algo de la paciencia del Cielo.[^177]

-   También hoy da esto: un endemonamiento de la posesión y una
    ideologización de la pobreza, que no nos ayuda. La pobreza se
    confunde a veces con la falta de cultura. Cuando la pobreza es solo
    negación de la vida, no nos hace libres. La pobreza genuina trata el
    deseo de poseer de una manera humana. Tiene el instinto, pero lo
    relativiza porque conoce la riqueza profunda. Solo por este valor
    interior podemos dejar la posesión exterior, ser libres del ansia de
    acumular.[^178]

-   La sociedad moderna ya no puede prescindir de la dictadura del
    ruido, que nos adormece sumergiéndonos en la ilusión de una falsa
    democracia mientras nos arranca la libertad con la violencia sutil
    del demonio, Padre de la mentira: \"Si vosotros permanecéis en mi
    palabra, sois en verdad discípulos míos, conoceréis la verdad, y la
    verdad os hará libres\" Jn 8, 31-32.[^179]

-   Y ese ser poco razonable que lleva el nombre de \"hombre\" se pasa
    la noche inventando nuevos medios para aumentar el ruido, para
    propagar más rápidamente el alboroto y la estupidez. Si, estamos a
    punto de lograr la inversión total: ahora que los medios de
    comunicación casi han alcanzado la cumbre de rapidez y una amplitud
    sin límites, nos hallamos al mismo tiempo en el punto más bajo de la
    significación de las comunicaciones. Tan grande es la prisa actual
    para gritar todo sobre todos, tan grande la extensión de la
    habladuría. Oh, por favor: silencio.(...) del filósofo Soren
    Kierkegaard(Copenhague, 1813 - id., 1855) en su Libro "Para un
    examen de si mismo recomendado a este tiempo".[^180]

-   La sociedad mediática va de rebelión sentimental en rebelión moral,
    como un sísifo desesperado que escala sin descanso la montaña.
    Reivindica su rebelión, su odio hacia lo que auto define como
    injusto y no igualitario, orgullosa de sus buenos sentimientos que,
    sin embargo, son lo más fatuo que existe. Cínica y deshonesta, se
    refugia rastrera mente en sus aversiones.[^181]

-   El mundo moderno transforma al que escucha en un ser inferior. Con
    fatídica arrogancia, la modernidad enaltece al hombre embriagado de
    imágenes y eslóganes estridentes, matando al hombre interior.[^182]

-   El hombre moderno es capaz de todo tipo de ruidos, de guerras y de
    falsas declaraciones solemnes en medio de un caos infernal porque ha
    excluido a Dios de su vida, de sus combates y de su gigantesca
    ambición de transformar al mundo en su propio beneficio
    egoísta.[^183]

-   Estás multitudes ruidosas e insistentes se adhieren a nuestra alma.
    Puede ser que decidamos rezar y nos demos cuenta que nos resulta
    imposible concentrarnos en nuestra vida interior. Hay mil casos que
    nos alteran y nos distraen. El jaleo interior hace imposible el
    silencio. Hasta la pasión más pequeña que agitaba nuestro corazón
    antes de una oración puede aniquilar ese momento de oración. El
    ruido triunfa y el silencio se escapa.[^184]

-   Nuestro mundo ha dejado de escuchar a Dios, porque no deja de hablar
    a un ritmo y a una velocidad letales para no decir nada. La
    civilización moderna no sabe estar callada. Vive en permanente
    monólogo. La sociedad pos moderna rechaza el pasado y considera el
    presente un vil objeto de consumo: contempla el futuro entre los
    rayos de un progreso casi obsesivo. Su sueño, convertido en triste
    realidad, ha sido encerrar el silencio en un calabozo húmedo y
    oscuro. A partir de entonces se instaura una dictadura de la
    palabra, una dictadura del énfasis verbal. En ese escenario sombrío
    solo queda una llaga purulenta de palabras mecánicas , sin relieve,
    sin verdad y sin cimiento. Muchas veces la verdad no es más que una
    creación mediática engañosa y consolidada por imágenes y testimonios
    inventados.[^185]

-   Cuando se ha encontrado de verdad a Dios, es imposible comprometer
    el evangelio y los preceptos de la revelación divina con las
    posturas políticas e ideológicas de un mundo que se revela contra
    las leyes de Dios y de la naturaleza.[^186]

-   La iglesia continua evangelizando pese a unos poderes y tantos
    medios financieros y técnicos cada vez más invasivos que se
    esfuerzan encarnizadamente por acabar con la religión, la moral, la
    familia, el matrimonio y los valores humanos, espirituales y éticos
    fundamentales. La iglesia vive hoy fuerzas internas y externas sin
    parangón. Es como si un terremoto quisiera destruir sus cimientos
    doctrinales y su enseñanza moral multisecular.[^187]

La dilución de principios y valores mencionada en la conferencia de
solvay, es sustentada nuevamente; una humanidad en la que el ser humano
se aleja rápidamente de la fe espiritual y la reemplaza por la fe en el
intelecto y la razón, reemplazando de paso los principios y valores que
ahora dependen del ideal de progreso, disfrazado en el bienestar
material y en el estímulo al orgullo del interés colectivo y al
liderazgo de la soberbia. Debido a esto, la gracia del Espíritu Santo no
cabe en el estridente ruido al interior del si mismo, cada vez el camino
del silencio en el alma del ser humano, es un camino más espinoso. La
sociedad contemporánea se deja tentar, separando la fe de la razón en el
ámbito público y social; elevando a la persona a la categoría de todo
poderoso, alejándose desde su verdad individual y relativa en el si
mismo que se antepone a la gracia de Dios y atacando cada vez con más
fuerza la única verdad absoluta justificada en el amor divino.

El amor divino

-   Lo que hacemos lo hacemos para amar. Por eso lo que da la medida en
    todo es el amor. Este es el objetivo de nuestro obrar. Los
    instrumentos son secundarios.[^188]

-   El amor no se expresa con palabras: se encarna y se convierte en un
    único y mismo Ser con aquel que ama de verdad. Es tanta su fuerza
    que nos arrastra para que nos entreguemos hasta la muerte, hasta el
    don humilde y silencioso y puro de nuestra vida. Si queremos
    prolongar la obra de Cristo en este mundo, tenemos que amar el
    silencio, la soledad y la oración.[^189]

-   El amor que no dice nada y no exige nada conduce al amor supremo, el
    amor silencioso de Dios. El silencio del amor es el silencio
    perfecto ante Dios que reúne toda la bondad, toda la belleza y toda
    la perfección.[^190]

-   Con su silencio Dios quiere permitir que trascendemos el mero amor
    humano para comprender el amor divino.[^191]

-   ¿ Hay alguien hoy en día que se atreva a decir que amaba su enemigo
    y obra en su interés y por su bien ?. Aún conservamos el espíritu y
    la conducta de los hombres del antigüo testamento.[^192]

-   Está experiencia de una vida interior y de un amor vivido en
    intimidad con Dios ha seguido siendo imprescindible en cualquier
    época para encontrar la felicidad.[^193]

-   Porque la omnipotencia de Dios es la omnipotencia del amor, y la
    omnipotencia del amor es la muerte. El infinito de Dios no es un
    infinito en el espacio, un océano sin fondo o sin orillas: es un
    amor que no tiene límites. La creación es un acto de amor infinito.
    El sufrimiento del hombre se convierte misteriosamente en
    sufrimiento de Dios. En la naturaleza divina, el sufrimiento no es
    sinónimo de imperfección.(...) Este problema me trae a la memoria la
    carta de una madre de familia conmovida por la idea de la
    vulnerabilidad de Dios: «cuando mis hijos eran pequeños quien
    pensaba por ellos y decidía por ellos era yo. Todo resultaba fácil:
    lo único que estaba en juego era mi libertad.Pero, en un momento
    dado, cuando me di cuenta de que mi papel consistía en ir
    acostumbrándolos a elegir, sentí -nada más asumirlo -que me invadía
    la inquietud. Al dejar que mis hijos tomaran decisiones y , por lo
    tanto, corrieran riesgos, al mismo tiempo yo también corría el
    riesgo de ver aparecer otras libertades distintas a la mía. Si con
    demasiada frecuencia he seguido eligiendo en su lugar, he de
    confesar que ha sido para ahorrarles el sufrimiento derivado de una
    elección que más tarde podrían lamentar; pero también, y en la misma
    medida-no en mayor medida-, para no arriesgarme a vivir en
    desacuerdo entre su elección y lo que a mi me gustaría verles hacer.
    Faltaba amor por mi parte, porque actuando así lo que querría por
    encima de todo era protegerme contra un posible sufrimiento: el que
    he experimentando cada vez que mis hijos han emprendido un camino
    distinto al que yo consideraba mejor para ellos. Así he conseguido
    entrever cómo es posible que Dios "Padre" sufra. Nosotros somos sus
    hijos . Quiere que seamos libres de construirnos a nosotros mismos y
    el infinito de su amor le impide toda coacción. Amor perfecto sin
    traza de cálculo , pero que implica la aceptación de un sufrimiento
    inherente a esa libertad total que quiere para nosotros.»[^194]

-   ¿ Cómo puede golpear el mal a Dios ? Imagínese a una madre cuyo hijo
    está enfermo. Sufre por su hijo por su amor e identificación. Una
    madre perfectamente sana puede vivir la agonía de su hijo más
    dolorosamente aún que él debido a esa identificación del amor con el
    ser amado. Su amor es capaz de ello. Alguien puede pensar que el
    amor de Dios es menos maternal que el amor de una madre, cuando todo
    el amor de todas las madres, incluido el de la Santísima Virgen , no
    es más que una gota en el océano de la ternura maternal de Dios. Por
    eso ningún hombre recibe un golpe sin que Dios lo reciba también en
    él, antes que él y por él.[^195]

-   En \"otro modo de ver al hombre\", Maurice Zundel parece profundizar
    en la idea de Plotino:\" Toda nuestra existencia está incluida en
    esta alternativa: o estoy en mi o estoy en Dios. No hay término
    medio. Cuando dejo de estar conmigo, es que Dios está realmente
    presente en mi. Cuando me pierdo de vista es que le miro a Él, y
    entonces el bien, en todos sus ámbitos consiste justamente en
    perderme en Él. El programa es sencillo, pero su concreción es
    difícil, porque no podemos decretar un encuentro ni fijar la hora en
    que ha de brotar el amor.[^196]

-   El hombre tiene que presentarse en silencio ante Dios y decirle:
    Dios mío, ya que me has concedido el conocimiento y el deseo de
    perfección, guíame siempre hacia el absoluto del amor. Haz que
    crezca en el amor, porque tú eres el artesano sabio que no deja
    ninguna obra inacabada, siempre que el barro de la criatura no ponga
    ningún obstáculo, ningún rechazo. Me entrego sin palabras a Tí,
    Señor. Quiero ser dócil y maleable como el barro en tus manos de
    hábil y benévolo alfarero.[^197]

-   El Eclesiastés contiene unos versículos espléndidos \"Todo tiene su
    momento y hay tiempo para cada cosa bajo el cielo: tiempo de nacer y
    tiempo de morir, tiempo de plantar y tiempo de arrancar lo plantado,
    tiempo de matar y tiempo de curar, tiempo de derruir y tiempo de
    construir, tiempo de llorar y tiempo de reír, tiempo de llevar luto
    y tiempo de bailar, tiempo de tirar piedras y tiempo de recoger
    piedras, tiempo de abrazar y tiempo de dejarse de abrazos, tiempo de
    buscar y tiempo de perderse, tiempo de guardar y tiempo de desechar,
    tiempo de rasgar y tiempo de cocer, tiempo de callar y tiempo de
    hablar, tiempo de amar y tiempo de odiar, tiempo de guerra y tiempo
    de paz\" (Ro, 3, 1-8). El silencio del amor nace de quién ha sabido
    atravesar todas estas etapas para experimentar solamente el silencio
    de Dios.[^198]

-   El lenguaje del sufrimiento y el silencio es distinto del lenguaje
    del mundo. Ante el dolor vemos dibujarse dos caminos diametralmente
    opuestos: la noble vía del silencio y el surco pedregoso de la
    rebelión, es decir, el camino del amor de Dios y el del amor a uno
    mismo.[^199]

El amor divino, es el amor puro y diáfano que lo penetra todo. Su origen
y destino son Dios. Es un amor absoluto unicamente posible en la medida
de la union con Dios en el silencio del Espíritu Santo. De manera
misteriosa el amor divino también se vive en el sufrimiento, en el cual
se comparte con Dios. Pero, en el máximo estado de sufrimiento, el amor
venció al dolor y a la muerte y trajo la paz y la felicidad en un estado
de salvación del alma. Así lo decidió Dios en su omnipotencia, para
dejar que la humanidad supere su pecado con plena libertad. Al ser
humano no le cabe en su mente, que su lucha en el destierro no la puede
ganar con su amor propio y limitado, tampoco con su intelecto. Ni si
quiera así ha logrado la paz; por ello el mundo se queda a medio camino,
enredado en el ruido del progreso ideológico y el enaltecimiento de su
ego. Sin embargo, cuando su humildad se lo permite y sigue el silencio
de Dios en su alma, el ser humano puede contemplar y experimentar en su
verdad individual, el amor infinito que Dios le comparte a través de su
gracia.

El Espíritu Santo que permite caminar hacia la verdad absoluta se vale
entonces de la gracia de Dios, que se manifiesta a través del amor
divino y se escucha en el silencio del alma de manera individual y se
comparte en comunidad. Pero, para escuchar dicho silencio, se requieren
los audífonos espirituales de la fe y la esperanza.\
\
La fe y la Esperanza

-   Las gracias divinas se derraman sobre el hombre a través de la
    sagrada escritura escuchada y meditada en silencio. Es en la fe y no
    recorriendo países lejanos ni cruzando mares y continentes, donde
    podremos encontrar y contemplar a Dios. En realidad llegaremos a
    Dios escudriñando durante horas y horas las Sagradas Escrituras
    después de haber resistido los embates del príncipe de este
    mundo.[^200]

-   Muchas veces los sufrimientos físicos son indispensables para
    provocar una rectificación espiritual y moral. El hombre probado que
    se confía a la bondad divina muestra una fe inmensa en Dios.[^201]

-   Es urgente que el mundo moderno recupere una mirada de la fe; si no,
    la humanidad se precipita a su perdición. La iglesia no puede
    acuartelarse en una visión meramente social. La caridad tiene un
    sentido Espiritual. La caridad guarda una estrecha relación con el
    silencio de Dios.[^202]

-   El silencio, esfuerzo del hombre, va de la mano de la esperanza,
    virtud teologal. En realidad el poder divino de la virtud teologal
    eleva y orienta el alcance humano y ascético del silencio. Aparece
    entonces una segunda virtud moral: la fortaleza. Su misión consiste
    en apartar cualquier obstáculo que impide a la voluntad obedecer a
    la razón. La fortaleza es activa y ofensiva. Hay que empeñarse en
    cultivar esa virtud que frena cuánto puede evitar que el hombre viva
    en dependencia de Dios. El silencio y la esperanza son dos
    condiciones que permiten a la fortaleza hallar su alimento.[^203]

-   ¿ Porque no se habla nunca de lo que es nuestra esperanza ? Más aún
    , si cuando nos observamos de cerca, comprendemos que esta esperanza
    está inscrita en el corazón de cualquier hombre : la esperanza de un
    amor sin límites no acabará jamás.[^204]

-   Aunque los criminales sean capaces de la destrucción más feroz, no
    pueden forzar la entrada del silencio, del corazón y de la
    conciencia del hombre. Los latidos de un corazón silencioso, la
    esperanza, la fe y la confianza en Dios siguen siendo
    inquebrantables. Fuera el mundo se desmorona en ruinas , pero dentro
    de nuestra alma Dios vela en el mayor silencio. La guerra, la
    barbarie y su cortejo de horrores nunca vencerán a Dios, presente en
    nosotros.[^205]

-   El examen de conciencia silencioso, en el corazón del dolor, permite
    al hombre contemplar que ha hecho con su vida y que le queda por
    hacer. La enfermedad es una esperanza sublime en el gran silencio de
    Dios.[^206]

La fe y la Esperanza son mucho más que una emoción, un sentimiento, un
mito o una superstición; nacen y se sustentan de la palabra de Dios
presente en las escrituras y en el verbo encarnado, Jesucristo; son el
resultado de vivir el silencio de la oración en la verdad individual y
actúan de manera recíproca en la construcción de una confianza perpetua
en Dios. Quien las ha cultivado, las manifiesta en los momentos más
críticos de dolor y destrucción. Dios refleja su poder, su gracia y su
fortaleza , a través de la fe y reivindica el amor y la paz en una
esperanza sin límites.

## Fe y razón

La relación entre la fe y la razón abarca un amplio y complejo espectro
de pensamiento, abordado por siglos desde los diferentes esquemas
filosóficos y religiosos, una de sus interpretaciones es relevante desde
la teología, la cual estudia la lógica de la revelación de Dios y su
interpretación de la fe en las diferentes religiones; para el caso que
nos interesa, haré referencia en el presente documento a la teología
Cristiana como punto de apoyo, teniendo en cuenta que el encuentro con
la fe desde el punto de vista teológico en la religión Cristiana tiene
un alcance y una pertinencia de mayor envergadura a la pretensión de
este documento.[^207] La intención es entender como la fe Cristiana
tiene un sentido alineado en el intelecto, la lógica y la razón; mas no
que estas sean su esencia. La fe Cristiana no es una fe ciega ni
irracional, se puede desagregar su sentido en un ejercicio de la razón y
el entendimiento. Siendo así, la fe se convierte en un misterio
espiritual de la doctrina Cristiana, que finalmente refleja en la
esperanza los principios y valores plenamente correspondidos por el amor
incondicional de Jesucristo.

A diferencia de todas las criaturas de la tierra, el ser humano tiene
consciencia espiritual; la búsqueda de la trascendencia en el ser humano
es una manifestación única de su especie y su respuesta, para algunos
está inmersa solo en su capacidad y habilidad mental, como función del
cerebro. Como complemento, existe otra perspectiva desde la fe, la cual
contiene elementos propios de la razón que se manifiestan de alguna
manera armoniosa en la integridad del si mismo y su experiencia
subjetiva, la fe es algo innato en la verdad individual del ser
humano.Una fe ciega incapaz de entenderse o validarse en el momento
histórico del individuo o la comunidad, puede caer en un peligroso
fanatismo religioso. De la misma manera al intentar separar la fe de la
razón, se rompe su armonía y la distorsión resultante puede caer en el
fanatismo de la razón, de la ciencia y del intelecto humano. La fe se
expresa a través de pequeñas expectativas de la vida cotidiana; o a
través de proyectos de gran complejidad. En la Cristiandad es un camino,
un don[^208] que Dios brinda a los seres humanos para poder conocerle y
a través del cual nos confirma su gracia y su mensaje de amor. De esta
manera es también una expresión de la espiritualidad humana. Una humilde
viejecita , quien pudiera vivir en la esquina del barrio, podría tener
más fe que el Papa; y no necesitaría de un estricto análisis racional
para vivirla en su diario caminar, por ello es además misterio. En el
ámbito de la verdad científica, un "don", de esta naturaleza no es algo
factible y solo desde la razón, la naturaleza de la fe se la tiende a
estigmatizar por la sociedad contemporánea en la categoría del mito, la
creencia arbitraria, o la superstición; teniendo en cuenta que la
creencia , es la base del mito como estado mental humano y diferente a
la fe, en que esta , es entrega y es esperanza que surge de la gracia.
Se tiende a categorizar la fe también en la simple expresión superficial
de la emoción y el sentimiento, incluso, es entendida desde
aproximaciones filosóficas, como la respuesta creativa justificada en la
necesidad humana de sobreponerse a los miedos y misterios que la ciencia
y la razón no han logrado superar. Aún cuando el individuo no se percata
de ello, la fe juega un papel fundamental en la vida de los seres
humanos como materia prima de la esperanza. Todo proyecto humano, por
pequeño o grandioso que sea , cae en el terreno de la fe y la esperanza;
se podría decir que es la esperanza la que mantiene a la humanidad en su
búsqueda de "progreso", según sea su definición creada desde los
principios y valores desplegados por los diversos grupos de interés
desde los liderazgos humanos. Para el entendimiento de la fe Cristiana
desde la razón, el Cardenal San Jhon Henry Newman (Londres, 1801- 1899,
Birmingham)[^209], dejó un postulado de pensamiento excepcional [^210].
Es a partir de su legado, que se escriben las siguientes líneas, en un
intento para darla a conocer por demás, intrigante, que sienta algunas
bases para quien desea explorar el don de la fe, en su equilibrio
armonioso con la razón y el entendimiento.

El origen de la fe puede ser humano en toda su dimensión. Haciendo una
breve referencia a uno de los proyectos que mas incidencia ha tenido
sobre el desarrollo del mundo actual, es la teoría de la relatividad;
trabajo de un científico sobre quien su capacidad intelectual es
destacada permanentemente, pero pocas veces se atribuye el mérito que
corresponde a su fe humana, en la verdad del si mismo, causa racional
del buen desenlace de tan ardua labor de índole intelectual.

Albert Einstein (Ulm,1879 -- 1955, Princetown )[^211] quien es descrito
por el biógrafo y escritor Walter Isaacson (New Orleans, 1952-
actualmente)[^212] como una persona de pensamiento independiente quien
se dejaba arrastrar por una imaginación que rompía los límites del saber
convencional, era una oveja negra, un rebelde reverente y se guiaba por
su fe -- llevada con ligereza y con cierto guiño de un Dios que no juega
a los dados dejando que las cosas acontecieran por casualidad. Es de
anotar que Einstein, de formación Judía , activista por la paz, no era
religioso, pero si creía en un Dios, dada la perfección de las leyes de
la física y en lo que hoy algunos proponentes de la existencia de Dios
conocen como el diseño inteligente. Einstein creía en un Dios a su
manera [^213]. El planteamiento, desarrollo y lanzamiento de la teoría
de la relatividad general fue para Einstein un complejo entretejido de
eventos que comenzó en 1911 , tiempo durante el cual tuvo que
enfrentarse a no pocas adversidades; no solo a sus propios errores que
le acarreaban lagunas mentales al no encontrar solución a sus
postulados; la carrera contra el tiempo le afectaba ya que el matemático
David Hilbert (Königsberg 1862 - 1943, Gotinga)[^214] trabajaba a toda
marcha en las mismas ecuaciones; su crisis matrimonial tocó fondo en
1914 y en agosto del mismo año estalló la primera guerra mundial y por
ser Judío sintió las amenazas propias del momento. Adicionalmente, su
trabajo teórico debería ser comprobado a través de la física
experimental, una actividad que pretendía medir la desviación
milimétrica de la luz que pasa cerca al sol, y esto lo haría su amigo el
astrónomo Erwin Freundlich (Wiesbaden-Biebrich, 1885 --
1964,Wiesbaden)[^215]. Desafortunadamente su amigo fue capturado en
Rusia, en plena guerra intentando documentar las pruebas de la teoría.
Su fe en el proyecto prevaleció intacta a pesar de tantos obstáculos.
Fue finalmente en Noviembre de 1915, cuando Einstein logró anunciar
triunfante la teoría de la relatividad general. Y no fue sino hasta Mayo
29 de 1929 durante un eclipse total que se comprobó la teoría con
equipos de astrónomos en la isla de Príncipe (África) y en la población
de Sobral (Brasil). Como anota Isaacson en su libro, parte del genio de
Einstein residía en su tenacidad. Podía aferrarse a una serie de ideas
incluso ante su aparente contradicción, tal como el mismo había escrito
en 1905 en su artículo sobre la relatividad. También tenía una profunda
fe en su intuición sobre el mundo físico; su fe como parte de su
experiencia subjetiva fue su motor en la esperanza de la correcta
interpretación de las leyes del universo, su imaginación y capacidades
intelectuales le complementaron para el desarrollo de la ciencia en la
búsqueda de la verdad para una mejor comprensión del universo: Einstein
tuvo desde niño dificultad con el lenguaje, característica que le
permitió el desarrollo de sus ideas en imágenes como cabalgar sobre un
rayo de luz. "rara vez pienso en palabras para nada -- le diría a un
psicólogo -. Me viene una idea , y puede que trate de expresarla en
palabras después". [^216]En el proyecto de Einstein desde la perspectiva
de La fe, se puede manifestar como un ejercicio de la razón, una
actividad intelectual en la que se "cree" inicialmente en "algo" de
manera consciente o inconsciente, una actividad ética en su origen en
cuanto a que es mejor "creer", en ese "algo" que madura hacia una sólida
fe humana, porque es lo correcto en la búsqueda de la verdad científica,
antes de entender el porqué de aquella creencia inicial que se alimenta
de su "imaginación", como parte de su experiencia subjetiva. Si
Einstein, no hubiera tenido fe en su proyecto , en su ideas e
imaginación y en su razonamiento completamente aventurado, difícilmente
habría logrado su propósito; su fe se complementa con aquellas
suposiciones o experiencias subjetivas y no empíricas; su mérito radica
en que se basa, no necesariamente en el conocimiento de una evidencia
experimental sensorial o mental aceptada bajo la metodología científica
, si no en ciertos antecedentes que se forman en el campo de la
confianza, sustentados inicialmente en su fe apalancada por su férrea y
terca voluntad. Se funden la fe, la voluntad y la libertad como opción
para no abandonar su proyecto ante la persecución nazi. Tuvo que luchar
contra la corriente de los eventos que se sucedieron en su vida, contra
la incredulidad por la negación de la ciencia Newtoniana del medievo
intelectual, ante los nuevos supuestos planteados como la negación del
eter[^217]; todo ello con la fuerza de su fe , siendo esta la impulsora
en la antesala intelectual que da forma a las hipótesis que finalmente ,
ante la demostración experimental , derivaron en nuevas teorías que
cambiaron la ciencia para siempre. En este sentido, la fe, partiendo de
un ejercicio de la razón, no es un conocimiento como tal. Otra
característica de la fe que se resalta en el proyecto de Einstein, es
que precede a la demostración, a la evidencia que desde un ejercicio
racional se construye a través del experimento contenido en la
metodología científica y que concluye en una teoría aceptada o
rechazada. En su proyecto, muchas veces Einstein evitaría caer en
derrotas tempranas nadando en la interpretación de la ciencia del
momento. Tuvo que mantener gran fortaleza frente a su propia duda para
llegar al descubrimiento que por momentos sentía que se le escapaba.
Einstein mantuvo siempre un "asentimiento nocional"[^218] a las
proposiciones, que como hipótesis iniciales forjaron una pensamiento
inferencial, que llevó a una conclusión. Hay que detenerse aquí, pues
Newman nos concede una elegante manera que puede aproximar lo que es un
asentimiento en la ciencia y su correspondiente asimilación que nos
puede acercar a lo que se entiende desde la fe. Un asentimiento nocional
es una afirmación incondicional, tiene diferentes grados, algunos son
débiles y superficiales, como la moda del día, o más fuertes, aquellos
que son una aceptación firme y consciente de una proposición como
verdadera, como la investigación, las verdades matemáticas o los juicios
legales; un asentimiento nocional se refiere a la aprehensión de objetos
abstractos y ejercicios mentales. Las ideas, la filosofía, la teología y
en las ciencias se presenta a través de sus premisas y conclusiones. El
asentimiento nocional es la aceptación incondicional de una proposición
y la inferencia es la aceptación condicionada a la aceptación de las
premisas, a manera de conclusión. Entonces la fe, como forma de
asentimiento es aceptada en su misterio, tanto por el científico como
por el santo y místico. El primero tiene una fe casi ciega en las
matemáticas como lenguaje universal que le permitirá interpretar como
funciona cada rincón del universo, sabe que están presentes en el
pensamiento y no surgen del experimento en la partícula atómica, sabe
que han estado antes de la civilización humana y estarán ahí para ser
descubiertas aún cuando desaparezca la civilización humana; mientras el
místico, además sabe por su fe que representan un destello de la
inteligencia de Dios , el profesor y matemático supremo.

Otro aspecto a tener en cuenta en la teoría científica desarrollada por
Einstein, es que se desarrolló en la técnica que hoy se disfruta en la
humanidad con sus consecuencias negativas y positivas, es en la acción
final donde culmina la obra inicial del gran científico. Richard Feynman
(New York, 1918 -- 1988, Los Ángeles )[^219], reconocido científico del
siglo pasado, define la ciencia de la física teórica así: "Primero se
adquiere una idea intuitiva de como funciona algo; luego se encuentran
las ecuaciones que cuantitativamente expresan la idea. De las ecuaciones
, se hacen cálculos y se predice algo nuevo, un número o una nueva
relación. Luego, alguien hace un experimento para verificar la
predicción. Si la predicción es correcta , entonces se tiene una teoría;
si la teoría cubre suficientes casos , se convierte en un
principio"[^220]. En dicha definición, aquella idea intuitiva tiene una
verdad escondida en su raíz, es una creencia o fe que complementa a la
intuición; y la aplicación, en la vida real de aquella teoría o
principio, se constituye finalmente en una acción moral "lícita" o
"ilícita". En el caso del proceso de la ciencia, la definición de lo
"correcto" o "incorrecto" corresponde a la metodología propia de la
ciencia, en la evaluación de la verdad racional, pero no en el contexto
moral ni espiritual. Ese era el peligro que se advertía en la reunión de
Solvay. Es así, como la aplicación de la teoría científica, queda
truncada al final en función de una premisa completamente racional, sin
dirección moral llevada desde la teoría a la acción, en su ejecución. En
tal consideración, el componente de naturaleza moral del individuo que
se manifiesta desde la conciencia queda mutilado, ante un acuerdo del
carácter funcional de lo que se considera progreso o bienestar. "Lo que
funciona y se demuestra para todos, está bien": esta es la gran tragedia
con la que discrepan y argumentan constantemente los múltiples y
complejos grupos de interés de la sociedad contemporánea bajo líneas
filosóficas unificadas solo en la razón. Esta es la circunstancia que
debe asumir la sociedad contemporánea en decisiones aisladas en el
contexto racional. Se ha perdido el valor de la fe en la abandonada
discusión moral, la cual queda aislada y por ende, la sociedad está
desconectada en la secuencia fe-acción y en un limbo asumido por los
diversos grupos de interés que interpretan la ley humana como el mandato
supremo, pero aislado de cualquier relación con la fe,
independientemente de la religión o filosofía que le soporta; el
discurso de la fe se considera obsoleto o anticuado. La advertencia del
reloj de doomsday, es otro ejemplo de lo que puede suceder cuando se ha
truncado la relación fe-acción como resultado de la teoría de la
relatividad. Einstein fue un pacifista consumado , considerado
erróneamente el padre de la bomba atómica; la reacción en cadena del
uranio derivada de su teoría de la relatividad para la construcción de
una bomba atómica fue algo que no se le había ocurrido, su amigo Leó
Szilárd[^221] (Budapest, 1898 - 1964 ,La Joya) le alertó sobre dicha
posibilidad. Finalmente, Einstein aceptó firmar una carta al presidente
Franklin D Roosevelt, alertándole sobre una posible catástrofe
inconcebible que ya la Alemania Nazi estaba desarrollando tal
conocimiento. Einstein, no participó en la construcción de la bomba, y
se arrepintió, luego de los hechos en Nagasaki e Hiroshima, de haber
firmado tal carta. En algún momento, el estado moral "incorrecto" del
alma de algunos seres humanos, contemplaron tal posibilidad, que llevó
no solo al desafío en el uso de la bomba atómica, si no a la carrera
armamentista nuclear persistente hasta nuestros días. Cuando el
componente moral en cualquier proyecto de índole humana comienza a ser
descartado, el papel del ser humano queda reducido a una actitud
exclusivamente mental: la conveniencia funcional de amenazar, crear y
ganar una guerra; la necesidad de dominar al otro sigue vigente desde el
neolítico.

Similitudes en la lógica de la fe que se desarrolló en el proyecto de
Einstein, sucede en la fe Cristiana , pero frente al "proyecto de vida"
del ser humano como individuo, en el camino de su fe y su acción final.
Dicha semejanza radica en la coherencia entre la imaginación, el
pensamiento, lo que se postula y se comunica en el sentido de la fe
desde las profundidades del corazón y la forma como se actúa. La acción
es el punto culminante del proyecto científico en el que se decide como
se aplica la teoría científica; es en la acción , en la cual se define
su beneficio y la dirección "correcta" para su aplicación en el
bienestar de la sociedad. En la vida del Cristiano en la fe y en la
acción está involucrado el significado trascendente del "ser", que por
fe advierte un objetivo contundente en su anhelo de estar con un Dios de
amor en la eternidad, anhelo que se convierte en acción permanente desde
el presente; es además el proyecto del sentido de la vida misma del
individuo; es la búsqueda de la espiritualidad del ser humano desde la
gracia de Dios, es admitir la búsqueda de una verdad absoluta, una
verdad que supera la capacidad de la mente humana, de la ciencia y de la
razón, pero que está presente en el motor de la fe, como don
sobrenatural. A diferencia del proyecto científico que comprende aquella
verdad en la ley de la naturaleza, la verdad que busca el ser humano,
inicia su camino en el trayecto de su vida; se reciben los hechos del
testimonio de la naturaleza primero, luego de la revelación y de las
conclusiones a que esta nos lleva mediante el ejercicio de la
abstracción y la inferencia. Se mantiene en la esperanza del amor y se
confirma en el encuentro con Dios; es decir en una verdad espiritual que
se manifiesta en cada persona de una manera diferente, desde su
experiencia subjetiva, pero en una misma dirección sustentada en la fe y
en el cimiento único de la gracia, cuya esencia es el amor divino que
trasciende al ser humano, en el amor del Espíritu Santo; amor del Padre
y del Hijo. Regresando a la afirmación desde el asentimiento, nos enseña
Newman, en el proyecto de vida de todo ser humano además de
asentimientos nocionales, hay asentimientos reales y combinaciones de
ellos. El asentimiento nocional, es más abstracto. Un asentimiento real
se da en la aprehensión de un objeto, una cosa y de manera más evidente
en el conocimiento de una persona; en este caso los sentidos dan más
peso a un asentimiento real que a uno nocional en el grado de la
afirmación. En el asentimiento real la mente está dirigida hacia las
cosas representadas por las impresiones que ha dejado en la imaginación.
Estas imágenes, si se les concede el asentimiento, tienen tanto en el
individuo como en la sociedad una influencia que no pueden tener las
simples nociones. Pero también surge el asentimiento real por medio de
las experiencias particulares y personales, las mismas que llamamos en
los primeros capítulos "experiencia subjetiva"; son experiencias
impresas en nosotros que permiten obtener una aprehensión de lo que son
estas cosas cuando no estamos haciendo experiencia de ellas; una
aprehensión de vistas y sonidos, colores, formas, lugares y personas,
actos y estados mentales paralelos a los de nuestra experiencia actual,
de forma que, cuando nos encontramos con proposiciones concretas que los
expresan, nuestra aprehensión de las mismas no puede llamarse abstracta
o nocional. La noticia de un incendio en una ciudad lejana y
desconocida, corresponde a un asentimiento real cuando se asimila a
algún incendio que la persona ha experimentado en su ciudad natal, esto
de manera independiente del conocimiento de la ciudad lejana o del
significado de la palabra incendio[^222]. Pero, en cuestiones religiosas
se presenta también el asentimiento de diversas maneras. Un dogma de fe
es una proposición que puede representar una noción o una cosa; creer un
dogma es dar el asentimiento de la mente a esta proposición como
representante de la una o de la otra. Dar un asentimiento real a esta
proposición es un acto de religión; forma parte de la experiencia del
individuo. Dar un asentimiento nocional es un acto teológico. Tal
proposición es comprendida, absorbida y asimilada por la imaginación
religiosa y es mantenida como verdadera por el entendimiento teológico;
he aquí una forma de armonía entre la fe y la razón. Afirma Newman, "
Puesto que el entendimiento y la imaginación son comunes a todos los
hombres, cualquier hombre religioso es en cierta medida un teólogo y no
hay teología que pueda empezar o desarrollarse si no es por la
iniciativa y la presencia continua de la religión"[^223]. Así, la
imaginación, la misma que forma parte de la ciencia y el asentimiento en
sus diversas formas, son un punto de unión para la expresión de la fe
humana o como un don de gracia en el camino del misterio del amor; como
parte del proyecto científico o del proyecto de vida, incluso la vida
eterna como esperanza en una acción final, en cuyo caso el sentido
espiritual escapa del alcance de la metodología científica.

El Abad San Antonio (Heracleópolis Magna, 251 -- 356, Egipto)[^224] ya
lo decía desde comienzos de la era Cristiana a aquellos filósofos,
representantes de la ciencia de la época, que lo cuestionaban en el
sentido de la fe cuando les preguntaba: ¿ Que viene primero el acto de
fe o la demostración verbal ?. Le respondieron: el acto de fe. Bien
respondido y les dijo, "la fe surge de la disposición del alma y la
dialéctica viene de la habilidad de los que la idean"[^225]. Los que
tienen una fe activa, no necesitan un argumento de palabras que a menudo
no pueden ni siquiera expresar, de lo que por la fe se percibe. En un
proceso de discernimiento de la razón; la fe y la razón están en
sincronía, la fe precede a la demostración y a la demostración se llega
desde un lenguaje común, ya sea un lenguaje matemático, o un lenguaje en
el que todos están de acuerdo, un lenguaje de una naturaleza diferente
al de la fe, en el cual lo que todos sienten es lo que todos comprenden.
También en el lenguaje espiritual, lo que comienza en un intrincado
ensamblaje de consideraciones y prejuicios, es lo que conlleva a un
correcto juicio y acción, de tal manera que se reduce ese "algo
desconocido" a una premisa de fácil interpretación.

La lógica de la fe en la vida espiritual, es una secuencia natural que
se desarrolla de manera consciente o inconsciente, que al separarla de
la razón queda el resultado de la acción en un estado de difícil
interpretación moral. El actuar de manera "lícita" o "ilícita" es una
posición moral que depende de un estado del alma, del espíritu humano o
del corazón, impresos en la voluntad y libertad del si mismo. Es en este
punto crucial en donde en el post modernismo se escabullen los
principios y los valores en pro de un resultado puramente científico y
racional de lo que se considere por progreso y bienestar. A pesar de los
inteligentes argumentos filosóficos e ideologías alejadas de la fe, la
historia ha demostrado una y otra vez que la humanidad no ha sido capaz
de encausar su propia libertad hacia un bien común alejado del profundo
deseo del dominio del otro. En el post modernismo aún prevalecen las
etiquetas en el ser humano para el hombre, la mujer, la condición
sexual, la raza, la religión, el origen, el nivel de educación y muchas
otras categorías. La fe Cristiana se dirige al "ser" humano, en una
relación individual con Dios en el cual no hay cabida a las categorías
humanas. Fue así como por primera vez, ante la incredulidad del contexto
medieval de una condición dominante establecida por siglos, que desde la
fe-acción se desmontó la justificación de la esclavitud. Jesús, siendo
Dios, padeció en la cruz como los esclavos de la época. Desde la
fe-acción Cristiana, el proyecto de vida y de búsqueda de una verdad
absoluta culmina en la dirección "correcta" mediante el asentimiento
real a la misma fe de la que se origina, de la experiencia religiosa en
el camino hacia una libertad inmersa en un Dios de amor perfecto,
evitando así caer en el limbo de la relatividad de la verdad individual
del si mismo y su interpretación de la libertad.

En las actividades cotidianas del individuo también se manifiesta la
naturaleza de la secuencia fe-acción. Se adquiere conocimiento o se
experimentan eventos en la vida diaria que tienen una evidencia moral;
se conocen cosas del pasado, o aspectos invisibles a través del
razonamiento, mediante sus consecuencias de los hechos en el presente.
Con gran probabilidad, quien lee estos párrafos no ha verificado
científicamente su fecha de nacimiento; pero la conoce por fe. En este
sentido, las suposiciones dejan de ser algo superficial y se pueden
convertir en evidencias tan fuertes para quien las vive, que en
ocasiones se les puede dar mas valor que al conocimiento demostrado. En
esos casos, se puede llegar a inferir que "esto va más allá de la
razón". Y así, la fe se puede constituir en un principio que sobrepasa
la razón, que sobrepasa los argumentos; el acto de fe se fortalece o se
debilita hasta perderse, dependiendo de las señales, evidencias y
experiencias que lo soportan en relación al individuo.

La fe espiritual es tan válida en la verdad individual, como tan válida
era la creencia de Einstein en su proyecto científico, antes de ser
aceptado. La señal en el ejercicio de la razón que parte del amor divino
de Dios como huella espiritual en el si mismo, puede ser más poderosa
que la fe que Einstein tuvo en si mismo. Los cimientos de la fe
Cristiana no provienen del razonamiento observable o comprobado, sino
del terreno de la confianza, cuyas raíces están en el corazón y en el
espíritu humano, de tal manera que puede encontrar el sentido de su
existencia en su relación con Dios, en su verdad espiritual e individual
y en última instancia formará parte desde su voluntad. La fe procede de
un ejercicio mental evaluado desde el corazón mediante una presunción y
con un origen en un antecedente vivo: la señal sobre lo lícito y lo
ilícito, alimentada en la conciencia y el libre albedrío. La fe
espiritual actúa como el motor de la esperanza; a partir de un misterio
intangible sustentado en la revelación de Dios, cuya huella, es la
muerte y resurrección de Jesús que, como ejercicio objetivo se refleja
en la mente y por ello se puede expresar en emociones o sentimientos,
sin que dicho misterio esté reducido solo a ellos. Los fieles Cristianos
tienen fe en Jesucristo, sus antecedentes, su vida y su mensaje, los
cuales por voluntad propia se pueden leer en el corazón del si
mismo.Tener fe espiritual implica la fortaleza de asumir un riesgo de
algo que no es un conocimiento demostrado y que nace en un escenario de
naturaleza diferente, pero complementario al de la evidencia
experimental; Einstein imaginaba un ascensor en caída libre con una
persona en su interior en aparente estado de ingravidez; a temprana edad
se preguntaba que pasaría si pudiera cabalgar sobre un rayo de luz; con
su imaginación y la dirección de estas ideas, algo descabelladas para
muchos, dio forma a su teoría. La fe de un Cristiano tiene un sentido
que se origina en lo más profundo del corazón y del alma, aceptando el
mensaje y aquellas señales que invitan a compartir el amor divino con
Dios en un estado de salvación eterna del alma. Es una idea descabellada
para muchos, pero no para quienes han experimentado el amor de Dios. La
fe implica un acto de voluntad. La razón en la búsqueda de la verdad
científica es un acto de confianza afianzado por el método científico.
Cuando el proyecto pasa a ser la búsqueda de la verdad absoluta, del
sentido de la vida terrenal y eterna, o de la felicidad en el ser
humano, la fe en la religión Cristiana es el camino que responde a
través de un ejercicio espiritual que se manifiesta en el acto
religioso, desarrollado paso a paso, cargado de vivencias desde la
experiencia subjetiva, desde la convicción de una inquietud
trascendental, y una imaginación exclusivamente humana. Lo importante de
la fe, en la religión Cristiana, no es la secuencia del ejercicio
racional en el cual se fundamenta y sobre el cual puede haber
diferencias de interpretación; si no en su naturaleza, en su raíz sujeta
a la razón del corazón, como un timón perteneciente al alma y al estado
espiritual del individuo. La fe Cristiana implica un examen de tipo
moral independientemente del proceso mental y de su conclusión.

Jhon Henry Newman escribió hace doscientos años, algo que persiste hoy
respecto a la fe Cristiana; "La fe es vista como algo opuesto a la
razón"; es lo que la sociedad moderna ha interiorizado en su definición
de progreso, gracias en parte a la evidencia del bienestar, evidencia
que genera un halo de superioridad en la humanidad. Desde la
espiritualidad, no tener o negar la fe es la tendencia válida en el
pensamiento racional y entre muchos fieles Cristianos, modificarla o
adaptarla a su verdad individual aparece como alternativa compensada por
la razón. Acomodar la fe promulgada y enseñada por Jesús desde el propio
razonamiento, es una posición bastante común. Lo paradójico de esta
posición, de acuerdo a Newman es que los antecedentes y suposiciones a
los que hacen referencia quienes rechazan, modifican , o acomodan a su
interés la fe Cristiana, son los mismos a los que acuden quienes
mantienen su fe, solo que son de naturaleza contraria o diferente.
Newman lo resume afirmando que la improbabilidad del antecedente es una
refutación suficiente de la evidencia. La muerte y resurrección de
Jesucristo es una improbabilidad para muchos, y por ello lo definen como
una negación absoluta; no se deja ni siquiera a la imaginación del
escenario posible, puesto que se atribuye a la superstición. Pero no es
así para aquellos quienes le vieron resucitado y para quienes les
creyeron a aquellos, tanto así que su fe ha llevado durante siglos a
miles incluso a dar su vida por Jesús. Esto es así por su confianza y
por el antecedente: el legado de Jesús en la fe y la esperanza y la
evidencia de sus señales presentes a través de los siglos en el
individuo Cristiano y su comunidad. En este punto existe entonces el
gran problema ¿ cómo justificar la fe Cristiana? ¿ Que garantiza que la
fe Cristiana no sea un mito, una superstición o una fe equivocada?.

El pensamiento racional responde a esta pregunta, según Newman, de
manera incorrecta; quienes justifican una respuesta de corte racional
desde la sociedad moderna , encuentran la solución en la educación
científica de las masas, pretendiendo así que cualquier persona,
mientras tenga un alto nivel educativo científico o técnico, podrá
discernir internamente si su fe es justificada, si es un mito o una
superstición. Sin embargo, existen personas con la mas alta capacidad y
formación cognitiva, que fundamentan aspectos importantes de su vida en
actos de superstición. La virtud de la hipótesis es diferente al mito o
la superstición sin virtud. Y no solo eso, también, dichas personas son
susceptibles a acciones incorrectas incluso, siendo ajenas a la
enseñanza de la teología Cristiana.

Consecuentemente , ante la fe se puede reaccionar con una exigencia de
tipo empírico y probatorio o con una posición de aceptación, aprobación
o asentimiento . Aquella predisposición es un estado de la voluntad de
cada individuo. De acuerdo a Newman, es comúnmente aceptado el decir que
la fe es "un examen del estado del corazón del individuo". En este
sentido, se refiere mas bien al estado general de su mente en términos
de sus convicciones, sentimientos, gustos y deseos como fuente en la
voluntad. Por tal razón, cuando se presenta un hecho previamente a la
evidencia, cada persona asume su propio punto de vista como una
manifestación de la verdad individual.

Entonces, si el problema de la justificación de la naturaleza de la fe
Cristiana, no se resuelve de esta manera ¿ cómo se resuelve ?. Cómo se
justifica la naturaleza de la fe en la religión Cristiana frente a otras
religiones de manera independiente a su origen, ya sea que provenga de
Mahoma, Buda, de un pensamiento filosófico, del si mismo, o de donde
provenga ?.

En el caso de la religión Cristiana, la justificación está en el estado
"correcto" del corazón, del alma o del espíritu humano calificado y
alimentado desde el amor ; no el amor del ser humano sino el amor de
Dios, el mismo que soporta la fe Cristiana, el amor de una revelación
Divina , hecho realidad en cada ser humano y enseñado por Jesús hasta
nuestros días. Es un amor que proviene de un ser concreto y
sobrenatural[^226] , que se ha dado a conocer a la humanidad; y es un
amor que se puede experimentar en el ejercicio de la razón, sin que sea
esta su esencia. Es el amor divino el que sustenta aquel cimiento único
de la gracia y la verdad en Jesucristo, quien es fuente diáfana de
principios y valores; de tal manera que, haciéndose humano Él es persona
con identidad y reconocimiento, pero es divinidad al mismo tiempo; y con
su presencia abre la posibilidad de la búsqueda de una verdad absoluta
en el amor, con un mensaje que trasciende hacia la vida eterna, marcando
así un camino a seguir. En este sentido, el individuo que vive la fe
Cristiana, entiende que el estado correcto del corazón es un misterio
espiritual enseñado y proporcionado por la revelación divina de un Dios
Trinitario, un ser superior real y presente, que reside en el interior
del alma de cada individuo y es escuchado a través del silencio en la
consciencia del individuo, desde la oración y su meditación con
humildad; y que solo desde la fe , es misterio asimilado por quien desea
escucharle , es un estado que se fortalece en la acción, especialmente
en la caridad; y que es inspiración de las decisiones diarias del ser
humano y por ende se fortalece en la esencia de la vida misma. Esta
verdad absoluta, no niega las verdades de otras religiones, como bien lo
explica el Papa Benedicto XVI(Marktl,1927 -- 2022, Ciudad del
Vaticano)[^227]: "Una cosa es que nosotros digamos que Cristo es el hijo
de Dios y que en Él se expresa la plena presencia de la verdad sobre
Dios. Otra cosa es que en otras religiones haya también verdades de la
índole más múltiple, que esas verdades posean como fragmentos, luces
provenientes de la gran luz, que en cierto sentido representan también
un movimiento interior hacia Él. Decir que en Cristo está presente Dios
y que, con ello, se nos aparece y nos habla el Dios verdadero, no
excluye que en otras religiones hayan también verdades, pero justamente
verdades que , por así decirlo, señalan hacia la verdad. En este
sentido, el dialogo, en el que ese señalamiento tiene que hacerse
visible es una consecuencia interior de la situación de la
humanidad.[^228]" A pesar de la separación de la fe y la razón en el
post modernismo , las condiciones para el diálogo entre religiones está
más presente ahora que en el medievo.

Y de ahí en adelante queda el libre albedrío, de quien decide su
búsqueda por voluntad propia. La voluntad de conocer a Jesús,
profundizar en su mensaje o no hacerlo, llenar el camino de la fe
Cristiana a la que con persistencia Jesús clama a todo ser humano; el
argumento para aceptarlo o rechazarlo habita en la percepción de los
antecedentes o suposiciones construidas en la verdad individual de cada
ser humano, como parte de una comunidad, pero sobretodo del misterio de
su propia voluntad y el llamado a la gracia de Dios. Dichos argumentos
pueden ser enriquecidos desde la fe enseñada por Jesús, los cuales
tienen una dirección objetiva y un camino en el estado "correcto" del
corazón y del espíritu humano el cual es una evidencia de un ejercicio
racional ; el acto de fe estructurado en el amor divino, no permite la
peligrosa interpretación del fanatismo ciego y perverso, ni del mito o
la mera superstición; no permite la verdad relativa del individuo en su
modelo social de diversos grupos de interés, tampoco se constituye en un
chantaje frente a un supuesto estado de salvación o condena en la
eternidad, puesto quien desde la humildad reconoce y refleja el amor
divino, acepta su camino, como el recién nacido que si bien, no
entiende, tampoco cuestiona la confianza en sus progenitores y en
quienes le aman.

La fe Cristiana alimenta el estado del corazón a través de la obediencia
de los mandamientos profesados en la Biblia y que Jesús resumió en dos:
amar a Dios sobre todas las cosas y amar al prójimo como a sí mismo. La
fe Cristiana se alimenta del amor y la caridad, en un camino hacia la
verdad absoluta, presente hoy en Jesucristo a través de la divina
revelación, expresada y guardada durante siglos como un tesoro
espiritual a través de las escrituras en los diversos libros que
componen la Biblia. En esta perspectiva , la presunción de un proyecto,
de vida terrenal y eterna, inundado de la paz espiritual y de felicidad
en el corazón , en el amor de Dios, se constituye en el referente de
quien la valida continuamente desde su voluntad y en libertad, en su
verdad individual, como lo afirma John Henry Newman:

*"Es la imaginación la que cada vez se entera más y más profundamente
del misterio y presencia de Dios como corazón, mente y consciencia que
trabajarán juntas. Es la persona como un todo que se mueve en la fe...es
el corazón encontrando el corazón"*[^229]

Esta afirmación tiene sentido en un ser humano que se reconoce en su
naturaleza espiritual corporal y mental ligada a la acción religiosa, de
tal manera que es la consciencia, la verdadera luz que diferencia la
acción lícita de la ilícita. La persona tiene entre su pecho un cierto
comando que dicta, no un mero sentimiento u opinión, tampoco una
impresión o visión de las cosas, sino una ley, una voz autoritaria que
demanda generar ciertas acciones y evitar otras; es algo superior al si
mismo, es algo sobre lo que la persona no tiene poder, o si lo ejerce,
le será de gran dificultad. Podrá desobedecerle y rechazarle, pero dicha
ley permanecerá. Las disposiciones que llevan a la fe , surgen de la
propia existencia de la consciencia, que propone a nuestras mentes un
ser exterior a nosotros y nos invita a ir más allá de nosotros mismos, a
la búsqueda de la trascendencia, a la búsqueda del significado de
aquella voz. La mente entonces necesariamente nos lleva a la idea de un
maestro escondido e invisible; y en la proporción en que se escucha su
palabra, será cada vez mas clara, sus lecciones más amplias y sus
principios mas consistentes; y quienes utilizan lo que ya tienen,
obtendrán más, comenzando por la obediencia inmersa en el amor, e irán
hacia la percepción íntima de la existencia de un Dios. Se creerá en su
existencia, no porque otros lo digan, sino por una aprehensión personal
de su verdad en una relación directa. Pero, existen también aquellas
personas que están contentas con si mismos; pensarán que, dadas las
circunstancias, sus condiciones son las mejores; solo desean estar
independientes, en su propio hogar, buscando sus propios gustos, sin
mirar hacia fuera; posiblemente con virtudes, o sin ellas, pero sin un
sentido religioso consistente o distintivo, simplemente viven y mueren.
Este es el carácter de muchos en la tierra, viven por todo lo que
aparece, en algún objeto de este mundo, pero no se elevan sobre este
mundo, es algo plano, que no lleva a las disposiciones de la fe. Quienes
atienden a las disposiciones de la fe, son personas activas, en el
sentido de que examinan la prueba que Dios ha revelado y serán
profundamente afectados; el otro tipo de personas son pasivas, en cuanto
a que esperan a que les sea comprobado, no será de su interés entrar en
las dificultades que ser activo implica, no se les ocurrirá que puedan
trascender más allá de si mismos, serán personas que no estarán abiertas
a las disposiciones de la fe[^230]. En las personas activas, esto
implica un movimiento, un caminar permanente, un proceso de conversión
inagotable en el que las bases de la fe Cristiana del individuo, no solo
buscan estar alineadas y en armonía desde la fe y la razón dispuestas a
la acción, sino en su certeza, confianza y esperanza en el corazón de
Jesús. La religión Cristiana, acepta la verdad científica, la cual no
contradice los principios del amor divino. Sin embargo, no es desde una
demostración científica, ni desde la naturaleza de los conceptos, sino
desde la vivencia personal de la fe en Jesucristo y en el corazón del
individuo, extendida a la comunidad a través de muchos siglos, que la
Cristiandad ha logrado desarrollarse de manera continua en millones de
seres humanos, con sus principios y valores desarrollados en lo que se
conoce como la doctrina Católica atesorada por la iglesia. Con un
efecto, que ante sus innumerables caídas y tropiezos, florece
nuevamente, no solo por acción de la fe de sus creyentes, pero en primer
lugar por el sustento del amor de Jesucristo quien también actúa
constantemente, tal como un bosque que se desarrolla no por la
perfección de las ramas de sus árboles, sino por el terreno en el que
está sembrado. Personas de todo tipo de formación intelectual, de
diferentes razas, experiencias de vida y orígenes culturales son como
los árboles de aquel gran bosque espiritual; es en cada una de ellas
donde se cuestionan, se validan y se perfeccionan permanentemente las
bases del ejercicio de la razón en la fe, a través de una relación
individual con Dios. La fe Cristiana tiene su esencia en un misterio: la
encarnación, muerte y resurrección de Jesucristo; y en su manifestación
a través de los siglos hay una realidad espiritual siempre debatida por
la sociedad del mundo en virtud de aquella prueba empírica que no
llegará. La certeza de la fe en la religión Cristiana se evidencia
también a través de acciones concretas de Jesús en la vida de sus
fieles, mediante señales que se traducen en acciones que sólo se pueden
entender, de corazón a corazón, en el silencio del individuo o de la
comunidad que las vive representadas en su iglesia, una iglesia
fuertemente cuestionada desde sus inicios. Sin embargo, Jesús como
cabeza de la iglesia, ha actuado, actúa y seguirá actuando en el
espíritu de las personas, que por voluntad propia y en plena libertad le
manifiestan y crecen caminando en su fe; y que como muchos misterios de
la ciencia, no se comprende en su totalidad, pero que influye en la vida
del ser humano, de la civilización y de su entorno natural. El misterio
de la fe tiene su gran bastión, su fuente, origen y finalidad en el amor
divino, el amor infinito e incondicional de Dios.

## Corolario II

El ser humano en algún momento de su evolución, durante el neolítico y
como parte de su naturaleza humana, a diferencia de los demás seres
vivos, comenzó a buscar el sentido de la muerte enterrando a sus seres
queridos y dando sus primeras pinceladas en búsqueda de explicaciones
cosmológicas, a partir de mitos y leyendas, haciendo de las tumbas
símbolos que dan un sentido de la vida después de la muerte. A través de
los siglos, esta búsqueda espiritual, alimentada inicialmente por el
chamán de la tribu, siguió su desarrollo hacia el encuentro de una
verdad con sentido espiritual, natural o sobrenatural a través de las
religiones, que a partir de la trascendencia y/o la inmanencia, intentan
aferrarse a uno o varios Dioses. Las religiones establecen un vínculo o
una revelación con el ser humano, que guía a cada persona desde su
verdad individual y a la sociedad en su difícil caminar por el mundo,
dando sentido a la existencia y al misterio; el mismo misterio que se
busca entender desde la filosofía, como primera ciencia, la teología en
su relación con la religión y al que apunta la ciencia actual en el
ámbito natural y del universo. Así, entre las miles de religiones que
hay en el mundo, entre las principales religiones monoteístas están el
Judaísmo, el Cristianismo y el Islamismo; entre las politeístas, el
Hinduismo y el budismo. La búsqueda del sentido espiritual del ser
humano desde la religión sigue siendo hoy una prioridad en el mundo, aún
entre quienes se definen como no practicantes de alguna religión. En
dicho contexto, el progreso y desarrollo del mundo moderno en sus
diferentes perspectivas ha llevado a una encrucijada a la sociedad, ya
que los principios y valores con su origen en las religiones , que
durante siglos sirvieron de marco para la búsqueda de sentido de la
existencia, son separados en el individuo en una sociedad que no les
atribuye valor alguno en la búsqueda de la verdad; la doctrina religiosa
ya no debe ser vista como un sostén y el secularismo religioso, separa
tajantemente la dinámica religiosa de la sociedad en su construcción de
principios y valores, esto bajo la justificación del bienestar, que ha
aportado al crecimiento de la civilización, pero que es entendido y
construido solo a partir del desarrollo científico y la técnica, como
algo puramente funcional. Esto sucede en el extremo de que lo único que
se afirma como cierto, es lo demostrable y lo que está en el terreno del
misterio, no se admite, creando una tensión en el ser humano; entre la
fe y la razón que ya no conviven en la sociedad. Por otro lado, el ser
humano por su naturaleza, tiene un cerebro que construye su verdad desde
la experiencia subjetiva y su relevancia en la verdad individual, hace
que sea incapaz de construir una teoría científica o filosófica, en la
que todos los individuos admitan una de sus verdades, como la verdad de
todos. Así se establece una lucha por el dominio del otro, o de la otra
comunidad, sociedad, o nación, dominio que ha estado presente en la
historia del mundo; y que desde el neolítico, sigue siendo una realidad
también entre diferentes grupos de interés. La respuesta a dicha
realidad es la negación de la verdad absoluta y la afirmación de muchas
verdades individuales que no convergen necesariamente. Desde el
Cristianismo, el cimiento único que permite ser la base en la
construcción de una sociedad que pueda coexistir como comunidad en medio
de la diferencia de la verdad individual, el que sostiene el desarrollo
de principios y valores aceptados de manera voluntaria, libre y natural,
es la gracia, de carácter vivencial y unificadora a través de la fe en
Dios, único ser supremo, poseedor, fuente y destino de la verdad
absoluta; por ende, camino de todo individuo, comunidad y sociedad que
le acepta. La gracia, es la manifestación del Espíritu Santo en el
individuo, amor del Padre y del Hijo en el misterio de la Trinidad, el
Dios único del Cristianismo. La gracia se obtiene con la humildad de
aceptar la condición humana a través del silencio, en la oración y
apertura del corazón, donde habita la esencia de las facultades de
voluntad y libertad del alma humana; la gracia es un obsequio de Dios a
todo ser humano por igual, sin jerarquías ni distinciones de ninguna
naturaleza. Pero, en este proceso, la fe y la razón actúan de manera
armoniosa e integral en cada persona, como lo afirma y lo explica Jhon
Henry Newman, "es el corazón encontrando el corazón".

[^1]: En la ciencia, la verdad absoluta, equivale a la teoría del todo;
    aunque existe una gran corriente que niega esa posibilidad dado el
    indeterminismo de la física cuántica, todavía bajo estudio y
    entendimiento.

[^2]: Distribución de la población mundial entre el 2015 y el 2060 por
    religión.<https://populationeducation-org.translate.goog/world-population-by-religion-a-global-tapestry-of-faith/?_x_tr_sl=en&_x_tr_tl=es&_x_tr_hl=es&_x_tr_pto=tc>

[^3]: Biografía de Marco Tulio Cicerón
    <https://www.biografiasyvidas.com/biografia/c/ciceron.htm>

[^4]: Biografía de Lactancio
    <https://ec.aciprensa.com/wiki/Lucio_Cecilio_Firmiano_Lactancio>

[^5]: Etimología de la palabra "Religión".
    [http://www.hispanoteca.eu/Foro/ARCHIVO-Foro/Religi%C3%B3n-religare-relegere.htm](http://www.hispanoteca.eu/Foro/ARCHIVO-Foro/Religión-religare-relegere.htm)

[^6]: Biografía de William James
    <https://www.biografiasyvidas.com/biografia/j/james.htm>

[^7]: Biografía de Ludwing Wittgenstein
    <https://www.biografiasyvidas.com/biografia/w/wittgenstein.htm>

[^8]: Biografía de John Hick <https://iep.utm.edu/hick/>

[^9]: El concepto de religión, Stanford Encyclopedia of philosophy, 2022
    <https://plato.stanford.edu/entries/concept-religion/>

[^10]: Es lo contrario de la trascendencia; la explicación está en el
    interior del "si mismo". <https://es.wikipedia.org/wiki/Inmanencia>

[^11]: "Homo Erectus" es más antiguo de lo que se pensaba
    <https://www.nationalgeographic.com.es/ciencia/homo-erectus-es-mas-antiguo-que-se-pensaba_15391>

[^12]: El hombre de Neardental, mucho más humano de lo que se creía
    <https://www.nationalgeographic.com.es/ciencia/hombre-neandertal-mucho-mas-humano-que-se-creia_14381>

[^13]: El hacha de Atapuerca
    <https://elpais.com/diario/2003/01/08/sociedad/1041980401_850215.html>

[^14]: La sima de los huesos en la frontera del conocimiento
    <https://www.atapuerca.org/es/ficha/ZC902F205-C003-50CB-65B8F2A0F3090121/la-sima-de-los-huesos-en-la-frontera-del-conocimiento>

[^15]: Evidence supporting an intentional Neardental burial at La
    Capelle Aux-Sanints
    <https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3890882/>

[^16]: Dama roja de Paviland
    <https://es.wikipedia.org/wiki/Dama_roja_de_Paviland> y la Dama roja
    del Miron
    <https://mujeresconciencia.com/2018/11/20/una-valiosa-sepultura-iberica-la-dama-roja-de-el-miron/> - -
    el entierro de gemelos más antiguo del mundo
    <https://historia.nationalgeographic.com.es/a/entierro-gemelos-mas-antiguo-mundo-tiene-31000-anos_15874>

[^17]: El Paleolítico definición y cronología
    [https://es.wikipedia.org/wiki/Paleol%C3%ADtico#Creencias](https://es.wikipedia.org/wiki/Paleolítico#Creencias)

[^18]: El neolítico definición y cronología.
    [https://es.wikipedia.org/wiki/Neol%C3%ADtico](https://es.wikipedia.org/wiki/Neolítico)

[^19]: Jericó es tal vez la población que ha estado habitada de manera
    constante desde hace diez mil años.
    [https://es.wikipedia.org/wiki/Jeric%C3%B3](https://es.wikipedia.org/wiki/Jericó)

[^20]: Gobekli Tepe: El Primer templo de la Historia.
    <https://historia.nationalgeographic.com.es/a/gobekli-tepe-primer-templo-historia_6363/4>

[^21]: Inglaterra parece haber resuelto el misterio del origen de
    Stonehenge
    <https://www.dw.com/es/inglaterra-parece-haber-resuelto-el-misterio-del-origen-de-stonehenge/a-54372161>

[^22]: Hombre de Pekin , fósiles que datan entre 500 a 200 Mil años AC,
    alguna vez se consideró como el eslabón perdido
    <https://es.wikipedia.org/wiki/Homo_erectus_pekinensis>

[^23]: Introducción a la economía China: los inicios de la época
    dinástica
    <https://zhuangziinstitute.org/tag/cultura-de-peilikan-y-cishan/>

[^24]: Neolithic period in China
    <https://www.metmuseum.org/toah/hd/cneo/hd_cneo.htm>

[^25]: La religión del neolítico
    <https://www.lacrisisdelahistoria.com/la-religion-del-neolitico/>

[^26]: La edad de los metales se estima vá desde el siglo VI AC hasta el
    siglo I AC; comienza con el trabajo del Cobre, el Bronce y el
    Hierro. <https://www.historiando.org/edad-de-los-metales/>

[^27]: La civilización implica un sistema social más organizado que la
    aldea o la tribu. Existen relaciones más complejas de comercio,
    escalas sociales, creencias o religiones , arte y tecnología. Existe
    también una historia escrita y un sistema sedentario a partir del
    centro urbano.

[^28]: Origen hipotético desde la tradición Eloista -- Yahvista de los
    libros del Tanaj (Judío ) o algunos libros del Antiguo testamento
    (Cristiano) https://es-academic.com/dic.nsf/eswiki/424202

[^29]: What is Judaism ?
    <https://www.chabad.org/library/article_cdo/aid/3710122/jewish/What-Is-Judaism.htm#Watch>

[^30]: La edad antigua comienza con la invención de la escritura y
    termina hacia el 476 DC con la caída del imperio Romano de
    occidente, para dar paso a la edad media. Además de los Sumerios,
    existieron un gran número de imperios en el mundo como el Arcadio,
    el Asirio, el Babilónico y hacia el oriente extremo las civilización
    veda y persa, y los imperios de la China Antigua. También están los
    imperios del Africa entre los más importantes el Imperio Egipcio y
    en la América Antigua el Imperio Maya entre otros.

[^31]: De acuerdo al momento histórico, el lenguaje y su interpretación,
    el Dios Judío ha recibido varios nombres tal como Adonai ó Elhoim (
    Hebreo), posteriormente YHVH --Yahweh ( Yahveh) y luego la forma
    latinizada Jeovhá más propia del Cristianismo.
    <https://www.jewishvirtuallibrary.org/the-name-of-god>

[^32]: Acerca de la religión Judía
    https://es.chabad.org/library/article_cdo/aid/3235655/jewish/Quines-son-los-judos.htm

[^33]: Historia del Pueblo Judío
    <https://www.jewishvirtuallibrary.org/history>

[^34]: Tipos de Judíos
    <https://www.myjewishlearning.com/article/tipos-de-judios/>

[^35]: El Cristianismo <https://ec.aciprensa.com/wiki/Cristianismo>

[^36]: Las religiones cristianas, protestantes y Ortodoxos
    <https://es.catholic.net/op/articulos/20581/cat/24/las-religiones-cristianas-protestantes-y-ortodoxos.html#modal>

[^37]: Biografía de Mahoma
    [https://www.Biografíasyvidas.com/Biografía/m/mahoma.htm#:\~:text=A%20los%20seis%20a%C3%B1os%20qued%C3%B3,comerciante%20respetado%20en%20la%20ciudad.](https://www.biografiasyvidas.com/biografia/m/mahoma.htm#:~:text=A los seis años quedó,comerciante respetado en la ciudad.)

[^38]: Biografía de Ismael
    [https://www.Biografíasyvidas.com/Biografía/i/ismael.htm](https://www.biografiasyvidas.com/biografia/i/ismael.htm)

[^39]: El Dios del Islam es Alá
    <https://www.islamreligion.com/es/articles/195/quien-es-allah/>

[^40]: ¿ Porque el islam ?
    <https://www.islamreligion.com/es/articles/496/por-que-el-islam/>

[^41]: La Meca
    [https://es.wikipedia.org/wiki/Jerusal%C3%A9n_en_el_islam](https://es.wikipedia.org/wiki/Jerusalén_en_el_islam)

[^42]: Definicion de Panteísmo
    [https://encyclopaedia.herdereditorial.com/wiki/Pante%C3%ADsmo](https://encyclopaedia.herdereditorial.com/wiki/Panteísmo)

[^43]: Se reconoce la existencia de varios Dioses, pero solo uno es
    digno de adoración.
    [https://es.wikipedia.org/wiki/Henote%C3%ADsmo](https://es.wikipedia.org/wiki/Henoteísmo)

[^44]: Periodo Védico
    [https://es.wikipedia.org/wiki/Periodo_v%C3%A9dico](https://es.wikipedia.org/wiki/Periodo_védico)

[^45]: La antigua Grecia
    https://www.worldhistory.org/trans/es/1-119/antigua-grecia/

[^46]: Invasión Aria a la India 1500 A.C
    [https://www.ecured.cu/Invasi%C3%B3n_aria_a_la_India](https://www.ecured.cu/Invasión_aria_a_la_India)

[^47]: Imperio Persa
    <https://mihistoriauniversal.com/edad-antigua/imperio-persa>

[^48]: A brief history of the cultures of Asia
    <https://www.khanacademy.org/humanities/ap-art-history/start-here-apah/brief-histories-apah/a/a-brief-history-of-the-cultures-of-asia>

[^49]: Historia de la India
    <https://www.lonelyplanet.es/asia/india/historia>

[^50]: El rig - veda es considerado el mas antiguo, data del siglo II
    AC. Sus autores son considerados poetas en la cultura Veda
    <https://www.elportaldelaindia.com/El_Portal_de_la_India_Antigua/Religion_Vedica.html>

[^51]: Introducción Veda <http://vedicheritage.gov.in/introduction/>

[^52]: En el Hinduismo son de gran importancia las escrituras
    Upanishads, Bhagavad-gita y las Agama
    <https://es.wikipedia.org/wiki/Hinduismo>

[^53]: Doce cosas que se deben saber sobre el Hinduismo
    <https://www.hinduamerican.org/blog/12-things-you-need-to-know-about-hinduism/>

[^54]: Literalmente Yoga significa unir, conectar, absorverse en
    meditación, es una práctica originaria de la cultura incipiente del
    rio Indo; actualmente existen muchos caminos del Yoga, algunos
    asociados desde sus inicios al budismo, al Jainismo y al Hinduismo.
    Algunos caminos para experimentar a Dios en el Hinduismo son: Karma
    Yoga, Bhakti Yoga, Jnana Yoga y Raja Yoga
    <https://www.hinduamerican.org/blog/12-things-you-need-to-know-about-hinduism/>

[^55]: La nueve creencias principales del Hinuduismo
    <https://www.himalayanacademy.com/readlearn/basics/nine-beliefs>

[^56]: El trimurti o tres formas
    <https://es.wikipedia.org/wiki/Trimurti>

[^57]: Cuatro factores del Hinduismo
    <https://www.himalayanacademy.com/readlearn/basics/four-facts>

[^58]: The origins of Buddhism
    <https://asiasociety.org/education/origins-buddhism>

[^59]: An introduction to Buddhism
    <https://www.pbs.org/edens/thailand/buddhism.htm>

[^60]: Las cuatro nobles verdades
    [https://es.wikipedia.org/wiki/Noble_camino\_%C3%B3ctuple](https://es.wikipedia.org/wiki/Noble_camino_óctuple)

[^61]: Buddhism, Scripts and texts
    <https://www.thebuddhistsociety.org/page/scriptures-texts>

[^62]: El Confusionismo enseña una verdad desde el equilibrio de dos
    energías contrarias pero complementarias, el yin y el yang ( ej. El
    calor y el frio, femenino y masculino, etc) y el Taoísmo rechaza el
    conocimiento racional y apuesta por la sabiduría intuitiva y la
    espontaneidad de acuerdo a la naturaleza de cada uno y al entorno de
    la naturaleza que le rodea.
    <https://universoyrealidad.com/2017/08/11/confucionismo-y-taoismo/>

[^63]: Baruch Spinoza
    <https://www.biografiasyvidas.com/biografia/s/spinoza.htm>

[^64]: En este sentido, la subjetividad puede darse de muchas maneras:
    "El tiempo es oro" es una construcción que refleja un entorno
    cultural; mientras en otras culturas vale más "vivir el presente".

[^65]: Bibliografía de Protágoras
    [https://es.wikipedia.org/wiki/Prot%C3%A1goras](https://es.wikipedia.org/wiki/Protágoras)

[^66]: Las personas sin religión tienden a crecer en ciertas zonas del
    mundo; especialmente en países desarrollados y en las clases
    sociales donde hay un incremento en el bienestar económico; sin
    embargo no sucede así en el grueso de la población mundial.
    <https://www.pewforum.org/2015/04/02/religious-projection-table/2050/percent/all/>

[^67]: Secularismo en el sentido de la separación de cualquier
    influencia de instituciones o dirigentes religiosos en la dirección
    de la sociedad, especialmente en el ámbito político.

[^68]: Se ha pasado de un extremo de apoyo espiritual a un extremo de
    apoyo racional en la base de la construcción de principios y valores
    sociales a través de una dinámica histórica de la humanidad cuya
    polémica se sale del alcance de este documento.

[^69]: Biografía de Jeremy Rifkin
    <https://www.biografiasyvidas.com/biografia/r/rifkin.htm>

[^70]: La civilización empática, Jeremy Rifkin, página 360

[^71]: Hay que diferenciar lo que se considera el fundamentalismo
    religioso , como un dogma religioso impuesto por la fuerza de la
    violencia a una dominación de otras culturas que ha estado presente
    en todas las religiones como parte de la evolución de la sociedad
    humana, del mensaje de convivencia y fraternidad resaltado desde la
    gran mayoría de las religiones y principios filosóficos.

[^72]: Biografía de Platón
    <https://www.biografiasyvidas.com/biografia/p/platon.htm>

[^73]: Génesis 1, 1-5 , La Biblia -- Latinoamerica, Edición revisada
    2005, texto íntegro traducido del hebreo y del griego.

[^74]: "Einstein, su vida y su universo" - Walter Isaacson, páginas 46 y
    47.

[^75]: Físicos UC dan explicación a "La discrepancia más grande entre la
    teoría y el experimento en la historia de la ciencia".
    <https://fisica.uc.cl/actividades-y-noticias/611-constante-cosmologica>

[^76]: Científico con BS en Física y Ciencias de la Tierra, Phd de
    Cambridge sobre historia y filosofía de la ciencia.
    <https://stephencmeyer.org/>

[^77]: "God of the gaps", how the supernatural explains what we can't ,
    Danica Dillion and Joshua Conrad Jackson, May 15 2023.
    <https://behavioralscientist.org/god-of-the-gaps-how-the-supernatural-explains-what-we-cant/>

[^78]: Biografía de Stephen Hawkin
    <https://www.biografiasyvidas.com/biografia/h/hawking.htm>

[^79]: En su libro "La Historia del Tiempo", Hawkins aceptaba la
    posibilidad de una mente superior creadora, de un Dios; en su último
    libro "El gran diseño" niega la existencia de Dios.
    <https://www.bbc.com/mundo/ciencia_tecnologia/2010/09/100902_hawking_dios_universo_wbm>
    https://www.bbc.com/mundo/ciencia_tecnologia/2010/09/100902_hawking_dios_universo_wbm

[^80]: Doctor en matemáticas de Oxford, Cristiano Evangélico
    <https://es.wikipedia.org/wiki/John_Lennox>

[^81]: ¿Ha enterrado la ciencia a Dios ?
    <http://www.boletinsalesiano.info/boletin-salesiano/68-etica/7617-ha-enterrado-la-ciencia-a-dios>

[^82]: Biografía de Gregor Mendel
    <https://ec.aciprensa.com/wiki/Gregor_Johann_Mendel>

[^83]: The Pontifical Academy of Sciences <https://www.pas.va/en.html>

[^84]: Biografía de Galileo Galilei:
    <https://www.biografiasyvidas.com/monografia/galileo/>

[^85]: Biografía de Leonard Susskind
    <https://profiles.stanford.edu/leonard-susskind>

[^86]: Entrevista, en episodio de "closertothetruth.com", Enero 27 de
    2016 , minuto 4.22
    <https://youtu.be/0p-Sqo83GX0?si=KmYZFv-g57lpNjp5>

[^87]: Hay una tendencia histórica en definir el alma como entidad
    separada del cuerpo. Definición histórica del Alma:
    <https://ec.aciprensa.com/wiki/Alma>

[^88]: Un alma perdida, es aquella que se aleja de Dios; que le rechaza,
    generalmente por sobervia.

[^89]: Definición de espíritu desde el catolicismo
    [https://ec.aciprensa.com/wiki/Esp%C3%ADritu](https://ec.aciprensa.com/wiki/Espíritu)

[^90]: El Espíritu y el cuerpo forman parte del mismo "ser". Definición
    del Espíritu, en la Teología Católico Cristiana:
    [https://ec.aciprensa.com/wiki/Esp%C3%ADritu](https://ec.aciprensa.com/wiki/Espíritu)

[^91]: Biografía de Santo Tomás de Aquino
    <https://mercaba.org/FICHAS/Santos/tomas_de_aquino_doctor.htm>

[^92]: Suma Teológica, Parte 1a, cuestión 83, sobre el libre albedrío,
    Santo Tomás de Aquino, <https://hjg.com.ar/sumat/a/c83.html#a1>

[^93]: Células nerviosas que ejecutan respuestas ante estímulos que
    reciben.
    [https://wCw.plantbehavior.org/about-us/](https://www.plantbehavior.org/about-us/)

[^94]: John Henry Newman , profeta de la verdad Católica.
    <https://www.mercaba.org/ARTICULOS/J/john_henry_newman_profeta_de_la.htm>

[^95]: Biografía de San Agustín de Hipona
    <https://www.aciprensa.com/recurso/3587/biografia-de-san-agustin-de-hipona>

[^96]: La conciencia de acuerdo al cardenal John Henry Newman, Letter to
    the Duke of Nortfolk (Section 5)
    <https://www.newmanreader.org/works/anglicans/volume2/gladstone/section5.html>

[^97]: Pablo Malo, psiquiatra, miembro de la Txori-Herri Medical
    Association y del grupo de psicorock The Beautiful Brains.
    Interesado en Psicología y Biología Evolucionista. En este aspecto
    hay diferencias conceptuales entre la ciencia y la religión
    Cristiano Católica.
    <https://evolucionyneurociencias.blogspot.com/2018/05/entrada-publicada-originalmente-en-la.html>

[^98]: Wild justice, The moral lives of animals, Marc Beckoff and
    Jessica Pierce <https://press.uchicago.edu/Misc/Chicago/041612.html>

[^99]: Mimosa Púdica o dormidera
    <https://es.wikipedia.org/wiki/Mimosa_pudica>

[^100]: ¿ Acepta la iglesia la teoría de la evolución ?.
    <https://es.catholic.net/op/articulos/21657/cat/133/acepta-la-iglesia-la-teoria-de-la-evolucion.html#modal>

[^101]: El hombre como centro de todas las cosas es un concepto alejado
    del Cristianismo Católico; en el ámbito teológico, existe una
    responsabilidad en la armonía con toda la creación en un permanente
    descubrimiento del "si mismo" frente al camino de fe tendido por
    Jesucristo, acorde al contexto histórico que le rodea.
    <https://es.catholic.net/op/articulos/60592/cat/164/exceso-antropocentrico.html#modal>

[^102]: Esta postura está sentada en la carta encíclica Humani Generis
    del Papa Pio XII:
    <https://es.catholic.net/op/articulos/21657/cat/133/acepta-la-iglesia-la-teoria-de-la-evolucion.html>

[^103]: Génesis 1, 20-31 Génesis 1, 1-5 , La Biblia -- Latinoamerica,
    Edición revisada 2005, texto íntegro traducido del hebreo y del
    griego.

[^104]: Explicación teológica sobre la Divina Trinidad:
    <https://www.aciprensa.com/noticias/12-claves-para-comprender-el-dogma-de-la-santisima-trinidad-54580>

[^105]: Explicación teológica, sobre quien es el Espíritu Santo:
    <https://www.aciprensa.com/recursos/quien-es-el-espiritu-santo-2226>

[^106]: "Summa Demoniaca",tratado de demonología y manual de
    exorcistas,2018, José Antonio Fortea,pág. 24

[^107]: Biografía del Cardenal Robert Sarah
    <https://www.aciprensa.com/noticias/87559/cardenal-sarah-nombrado-miembro-de-este-importante-dicasterio-de-la-curia-romana>

[^108]: Biografía de Anselm Grun
    <https://gcloyola.com/1000-anselm-gruen-osb>

[^109]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 38

[^110]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 28

[^111]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 29.

[^112]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 121

[^113]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 24

[^114]: El latín "Novermi me, Noverim Te", significa: "que me conozca a
    mi mismo y así te conoceré", San Agustín
    <http://buscandoadios.dominicos.org/articulos/noverim-me-noverim-te/>

[^115]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 129

[^116]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 79

[^117]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 20

[^118]: "La sabiduría de los padres del desierto", Anselm Grün,
    Ediciones sígueme Salamanca , 2017, pág 13.

[^119]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 160

[^120]: "La sabiduría de los padres del desierto", Anselm Grün,
    Ediciones sígueme Salamanca,2017, pág 52

[^121]: "La sabiduría de los padres del desierto", Anselm Grün,
    Ediciones sígueme Salamanca,2017, págs 54 y 55

[^122]: "La sabiduría de los padres del desierto", Anselm Grün,
    Ediciones sígueme Salamanca,2017, págs 56

[^123]: "La sabiduría de los padres del desierto", Anselm Grün,
    Ediciones sígueme Salamanca,2017, págs 35

[^124]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 17

[^125]: "La sabiduría de los padres del desierto", Anselm Grün,
    Ediciones sígueme Salamanca,2017, pág 36

[^126]: "La sabiduría de los padres del desierto", Anselm Grün,
    Ediciones sígueme Salamanca,2017, pág 100

[^127]: "La sabiduría de los padres del desierto", Anselm Grün,
    Ediciones sígueme Salamanca,2017, pág 110

[^128]: "La sabiduría de los padres del desierto", Anselm Grün,
    Ediciones sígueme Salamanca,2017, pág 92

[^129]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 58

[^130]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 169

[^131]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 275

[^132]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, págs 171 y 172

[^133]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 78

[^134]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 107

[^135]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 179

[^136]: "La sabiduría de los padres del desierto", Anselm Grün,
    Ediciones sígueme Salamanca,2017, pág 211

[^137]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 224

[^138]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 251

[^139]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 233

[^140]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 252

[^141]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 256

[^142]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 119

[^143]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 67

[^144]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 124

[^145]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 127

[^146]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 220

[^147]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 209

[^148]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 252

[^149]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 95

[^150]: "La sabiduría de los padres del desierto", Anselm Grün,
    Ediciones sígueme Salamanca,2017, pág 21

[^151]: "La sabiduría de los padres del desierto", Anselm Grün,
    Ediciones sígueme Salamanca,2017, pág 23

[^152]: "La sabiduría de los padres del desierto", Anselm Grün,
    Ediciones sígueme Salamanca,2017, pág 25

[^153]: "La sabiduría de los padres del desierto", Anselm Grün,
    Ediciones sígueme Salamanca,2017, pág 26

[^154]: "La sabiduría de los padres del desierto", Anselm Grün,
    Ediciones sígueme Salamanca,2017, pág 70

[^155]: "La sabiduría de los padres del desierto", Anselm Grün,
    Ediciones sígueme Salamanca,2017, pág 29

[^156]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 136

[^157]: "La sabiduría de los padres del desierto", Anselm Grün,
    Ediciones sígueme Salamanca,2017, pág 41

[^158]: "La sabiduría de los padres del desierto", Anselm Grün,
    Ediciones sígueme Salamanca,2017, pág 44

[^159]: "La sabiduría de los padres del desierto", Anselm Grün,
    Ediciones sígueme Salamanca,2017, pág 43

[^160]: "La sabiduría de los padres del desierto", Anselm Grün,
    Ediciones sígueme Salamanca,2017, pág 169

[^161]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 170

[^162]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 102

[^163]: "La sabiduría de los padres del desierto", Anselm Grün,
    Ediciones sígueme Salamanca,2017, pág 46

[^164]: "La sabiduría de los padres del desierto", Anselm Grün,
    Ediciones sígueme Salamanca,2017, pág 238

[^165]: "La sabiduría de los padres del desierto", Anselm Grün,
    Ediciones sígueme Salamanca,2017, pág 58

[^166]: "La sabiduría de los padres del desierto", Anselm Grün,
    Ediciones sígueme Salamanca,2017, pág 60

[^167]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 48

[^168]: "La sabiduría de los padres del desierto", Anselm Grün,
    Ediciones sígueme Salamanca,2017, pág 93

[^169]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 195

[^170]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 33

[^171]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 173

[^172]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 63

[^173]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 96

[^174]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 178

[^175]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 100

[^176]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 173

[^177]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 175

[^178]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 176

[^179]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 36

[^180]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 97

[^181]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 198

[^182]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 40

[^183]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 46

[^184]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 57

[^185]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 62

[^186]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 175

[^187]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 256

[^188]: "La sabiduría de los padres del desierto", Anselm Grün,
    Ediciones sígueme Salamanca,2017, pág 5

[^189]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 118

[^190]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 70

[^191]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 246

[^192]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 184

[^193]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 34

[^194]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 104

[^195]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 168

[^196]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 60

[^197]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 47

[^198]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 71

[^199]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 206

[^200]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 25

[^201]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 200

[^202]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 250

[^203]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 68

[^204]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 262

[^205]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 181

[^206]: "La fuerza del silencio", Cardenal Robert Sarah con Nicolas
    Diat, Junio 2019, pág 201

[^207]: Quien desee profundizar en ella, puede acudir a Santo Tomas de
    Aquino (Italia, 1224 - 1274), fraile teólogo y filósofo, Doctor de
    la iglesia Católica, perteneciente a la orden de predicadores; autor
    de Summa Teológica, un tratado de teología del siglo XIII, de gran
    influencia en la Cristiandad.<https://hjg.com.ar/sumat/>

[^208]: La palabra "don" indica algo que se recibe así, sin más, como
    regalo, como señal de alguien que nos ama y nos quiere alegrar con
    un objeto concreto o con un gesto profundo de
    cariño.<https://es.catholic.net/op/articulos/30246/cat/884/el-don-de-la-fe.html#modal>

[^209]: Biografía de San John Henry Newman
    <https://www.vaticannews.va/es/santos/10/09/san-john-henry-newman.html>

[^210]: "Fifteen Sermons Preached before the University of Oxford
    between A.A.1826 and A.D.1843" , Sermon 12. Love the Safeguard of
    Faith against Superstition, Jhon Henry Newman:
    <http://www.newmanreader.org/works/oxford/sermon12.html>

[^211]: Biografía de Albert Einstein
    <https://www.biografiasyvidas.com/monografia/einstein/>

[^212]: Biografía de Walter Isaacson
    <https://es.wikipedia.org/wiki/Walter_Isaacson>

[^213]: "Einstein, su vida y su universo". Walter Isaacson, Mayo
    2017,páginas 68, 118, 119.

[^214]: Biografía de David Hilbert
    <https://www.biografiasyvidas.com/biografia/h/hilbert.htm>

[^215]: Biografía de Erwin Freundlich
    <https://es.wikipedia.org/wiki/Erwin_Finlay-Freundlich>

[^216]: Einstein, su vida y su universo, Walter Isaacson página 35.

[^217]: Materia que llena el universo, concepto respaldado por Isaac
    Newton y la ciencia de la época
    [https://es.wikipedia.org/wiki/%C3%89ter\_(elemento)](https://es.wikipedia.org/wiki/Éter_(elemento))

[^218]: Gramática del asentimiento, John Henry Newman, ediciones
    encuentro , Madrid, 2020, páginas 51-74.

[^219]: Premio Novel en Física en 1965
    <https://www.nobelprize.org/prizes/physics/1965/feynman/biographical/>

[^220]: Primera sesión de tres, de las lecturas Messenger, Abril 28 de
    2014. "Boltzman y la flecha del tiempo", Universidad de Cornell,
    EEUU por Leonard Susskind, profesor y fundador del instituto de
    física teoría de la universidad de Stanford y amigo personal de
    Richard Feynman. <https://youtu.be/n7eW-xPEvoQ?si=1NTZoJOVP1ZoUwFC>

[^221]: Leó Szilaárd:
    [https://es.wikipedia.org/wiki/Le%C3%B3_Szil%C3%A1rd](https://es.wikipedia.org/wiki/Leó_Szilárd)

[^222]: Gramática del asentimiento, John Henry Newman, ediciones
    encuentro , Madrid, 2020, páginas 51-74.

[^223]: Gramática del asentimiento, John Henry Newman, ediciones
    encuentro , Madrid, 2020, página 93

[^224]: El abad San Antonio -
    <https://es.catholic.net/op/articulos/7656/san-antonio-abad-inaugurador-de-la-vida-eremitica#modal>

[^225]: San Antonio Abad , "Vida de San Antonio", Conferencia de
    comunidades monásticas del cono sur, cuadernos Monásticos, año 10,
    número 33-34 (1975) 171-234,Introducción, traducción y notas por los
    monjes de isla Liquiña - No.77
    <https://surco.org/sites/default/files/Vida_de_San_Antonio.pdf>

[^226]: El término sobrenatural aplica solo a Dios, admite algo que no
    está al alcance del conocimiento racional; pero algo sobre lo que
    actúa el ejercicio de la razón permitido unicamente por Dios y en su
    amor divino. Es una posición difícilmente aceptable cuando se
    considera al cerebro humano, como la única fuente con la capacidad
    potencial de explicarlo todo, aún la trascendencia humana.

[^227]: Biografía de Benedicto XVI.
    [https://es.catholic.net/op/articulos/22726/Papa-benedicto-xvi.html](https://es.catholic.net/op/articulos/22726/papa-benedicto-xvi.html)

[^228]: Benedicto XVI - Luz del Mundo, El Papa, la iglesia y los signos
    de los tiempos. Una conversación con Peter Seewald, página 162.

[^229]: John Henry Newman por John Davies , 2014
    <https://www.youtube.com/watch?v=n-xgG01WouU>. La lección de Newman,
    según Benedicto XVI: "El corazón habla al corazón", es el lema que
    sintetiza la vida de Newman. Nos da la perspectiva de su comprensión
    de la vida Cristiana como una llamada a la santidad, experimentada
    como el deseo profundo del corazón humano de entrar en comunión

    íntima con el Corazón de Dios.
    <https://es.catholic.net/op/articulos/49344/cat/162/la-leccion-de-newman-segun-benedicto-xvi-el-corazon-habla-al-corazon.html#modal>

[^230]: Dispositions for faith, Henry Newman
    <https://www.newmanreader.org/works/occasions/sermon5.html>
