---
title: "Parte 1"
format:
  html:
    toc: true
    toc-depth: 5
    number-sections: false
    theme: cosmo
    css: styles.css
---
# CAPITULO 1

## La conferencia de Solvay

El ser humano como individuo permanece en la búsqueda de una verdad
escurridiza, aparentemente inalcanzable; de manera simultánea, a través
de diversos campos de conocimiento como la razón, las ciencias, la
filosofía, la teología, se refleja su asombro y curiosidad al enfrentar
el misterio y lo desconocido. Los caminos de dicha búsqueda son
diferentes o contrapuestos en algunos casos, en otros casos son
complementarios y casi siempre son complejos. Sobre la definición de una
verdad absoluta, siglos de argumentaciones, documentos y disertaciones
entre los más distinguidos filósofos , científicos, académicos y
teólogos no han llevado a ningún consenso; el ser humano por si mismo,
ha sido incapaz de descubrir dicha verdad absoluta y es tanto así que su
posibilidad es negada por muchas personas desde diversas disciplinas del
pensamiento.

Se puede hablar de una verdad científica como el conocimiento objetivo y
real que permite entender que es el universo y la manera como funciona
un sistema natural y las leyes que le gobiernan, a partir de una
metodología concebida y desarrollada por el ser humano. Este
conocimiento puede ser compartido, revisado y actualizado
permanentemente; una definición de la búsqueda de una verdad absoluta a
partir de la verdad científica consiste en la explicación del
funcionamiento del universo bajo una sola ecuación: la teoría del todo,
expresada mediante el lenguaje de las matemáticas. Esta búsqueda sigue a
pasos agigantados, pero aún así la naturaleza y el universo no han sido
plenamente entendidos; su descubrimiento fue el sueño inalcanzable de
Albert Einstein. ¿ que tan lejos estaríamos de encontrar una verdad
absoluta a partir de la teoría del todo? es una pregunta sin una
respuesta clara; a pesar de los grandes avances, nuevas preguntas e
inquietudes surgen en el proceso de actualización constante del
conocimiento humano. Otra posición desde la verdad científica, es que la
verdad absoluta no existe, ya que su naturaleza es indeterminista,
interpretación que nace en la física cuántica, en la cual la verdad
surge de una probabilidad formada a escalas moleculares.
Independientemente de cual sea la concepción del universo en su
definición finita o infinita, determinista o indeterminista visto desde
la evolución de la ciencia y del conocimiento humano, la búsqueda de la
verdad absoluta por el camino de la ciencias tiene entonces un alcance
controversial, pero de gran relevancia para la humanidad, puesto que sus
hallazgos han permitido el desarrollo del bienestar de la civilización,
en detrimento del sufrimiento por su condición de debilidad frente a la
naturaleza y al individuo.

Otro camino para llegar a entender la verdad absoluta, parte de una
posición filosófica o teológica centrada inicialmente en el misterio de
lo sobrenatural; algo que no está al alcance del conocimiento racional y
humano, por lo tanto tampoco está al alcance de la verdad científica.
Dicho camino, alimenta una concepción difícil de admitir en la
modernidad y la época contemporánea ante la verdad científica, debido a
que "conocer" y "saber" el comportamiento predictivo en la descripción
de los eventos naturales que se obtienen desde las leyes descubiertas
por la ciencia, es una realidad que convence fácilmente. Aún cuando la
ciencia convive con grandes misterios, la comprensión y aplicación de
las leyes de la física permiten volar en un avión; pero hablar de Dios,
no es algo práctico y trae confusión en la impaciente razón humana. Por
lo tanto una posición sobrenatural, algo que no se puede conocer desde
los sentidos, ni entender desde la razón, implica la posibilidad de caer
en mitos, supersticiones, especulaciones y todo tipo de argumentaciones
que por lógicas que parezcan, pueden caer en el sentido ilógico de la
realidad. La filosofía como proceso de pensamiento admite en sus
ejercicios racionales aquella búsqueda de una definición de la
escurridiza verdad, antecediendo a la ciencia como se la conoce hoy
desde inicios de la civilización. Y las religiones del mundo, estudiadas
en la teología pretenden llegar desde una posición sobrenatural a
encontrar la esquiva verdad absoluta; cada religión enfrentando a su
manera aquellas posibles caídas en lo irracional. Es aquí donde entra un
conflicto en el ser humano de la sociedad contemporánea. En la sociedad
del progreso del siglo XXI y para completar la confusión en la búsqueda
de la verdad absoluta, entra en juego con mas fuerza que nunca otra
verdad, la verdad individual. Una verdad aún más compleja en su
definición, puesto que entra en el ámbito de lo subjetivo y lo relativo,
aquello que puede ser la verdad de un individuo, puede no serlo para
otro. En la sociedad del post modernismo, cuyo origen todavía en debate
se va gestando desde la mitad del siglo pasado de nuestra época, en su
develar se escribe la historia contemporánea; en este marco de acción,
la búsqueda de la verdad desde la filosofía se ha centrado en el ser
humano, como aquel que puede resolver los misterios que le rodean, dado
el poder que la ciencia y la razón han demostrado en el progreso de la
tecnología y la construcción de bienestar; la confianza en las
capacidades de la razón dominan el mundo contemporáneo. Lo que no es
razonable o de carácter científico, genera desconfianza. Por lo tanto,
lo sobrenatural fácilmente puede caer en el terreno de la desconfianza.
La confianza es la columna de las relaciones humanas que se edifican
desde la fe, en el escenario actual, la gran tendencia social es la
construcción de una fe, de manera consciente o inconsciente en el poder
de la ciencia y de la razón; buscando la verdad absoluta en un terreno
fangoso y carente de firmeza, puesto que la historia ha demostrado
durante siglos, la incapacidad humana de resolver las situaciones que no
están al alcance de la ciencia y la tecnología o de sus planteamientos
ideológicos: las cuestiones de convivencia, justicia y paz, o libertad,
son una pequeña muestra de ello. Si las civilizaciones antiguas
colapsaron en promedio cada 336 años por diversos factores[^1], no
existe una razón primordial como causa de dichos sucesos entendidos
desde las ciencias, pero un gran riesgo ha sido el de auto colapsar por
si mismas, circunstancia de la cual no somos excepción en un mundo
hiper-conectado; no cabe duda tampoco de que la misma voluntad de las
civilizaciones vista en su integridad del individuo como parte de un
todo forma parte de dicha posibilidad en cuanto a los caminos que se
elijen tanto para enfrentar adversidades comunes, como para el
desarrollo social, que como lo describe la historia fue por muchos
siglos a partir del dominio por la fuerza de la guerra y la esclavitud,
factores que, aunque en menor escala persisten en el presente, se han
logrado enmarcar y armonizar en mayor medida gracias a los entornos
jurídicos y políticos, que por siglos siguen aún en construcción. Pero
tanto en el presente, como en el pasado, la interpretación de la verdad
seguirá siendo clave en la subsistencia de la civilización del post
modernismo, puesto que de ella se derivan los principios y valores
humanos que fortalecen los sistemas de convivencia de toda civilización.
En dicha búsqueda e interpretación de la verdad ha jugado, como parte
integral de toda civilización las religiones, que desde la teología,
trata del entendimiento de la lógica revelada de Dios en las diversas
religiones y cuya influencia ha sido determinante en las relaciones del
individuo y la sociedad para dar sentido al significado del "ser", del
si mismo y del camino escogido por su comunidad considerado como lícito
o correcto, en una perspectiva que trasciende a lo sobrenatural y que a
partir de los principios y valores determinados a su cultura, se ha dado
sentido al progreso, que desde la ciencia queda circunscrito y por lo
tanto coartado al campo del mundo físico y material.

El camino de las religiones es tan antiguo como la humanidad misma; y
fue la religión la precursora de la filosofía y sistemas de pensamiento
que posteriormente dieron lugar a la ciencia y la razón como se conocen
en la edad contemporánea. Tanto las religiones, como la ciencia entran
en conflicto desde la edad media, pasando por el modernismo y hasta
nuestros días; pero es un conflicto aparente, puesto que es creado por
el ser humano, su condición de dominación "al otro" y la defensa de sus
intereses de grupo. En este documento se pretende señalar cómo la
religión Cristiana plantea la búsqueda del camino a la verdad absoluta
en Jesucristo y su regalo del amor, donde también tiene lugar una lógica
racional de la fe, sin ser esta su esencia y donde no se contradice con
la razón, ni con la verdad científica. Y se debe resaltar, que señalar
el camino no implica enseñar a caminar por él; aunque quedarán
planteados algunos aspectos , aprender a caminar por el sendero de la
religión Cristiana es parte de la vivencia profunda que cada individuo
decide por voluntad propia. Quien desee aprender a caminar por dicho
sendero deberá hacerlo a través de otras instancias, más apropiadas y
enriquecedoras que ha dejado en su legado Jesucristo a toda la
humanidad.

La humanidad siempre ha estado buscando una verdad absoluta, o al menos
una interpretación de la misma, en parte por su curiosidad intelectual y
natural no solo por entender su entorno cercano, sino el universo. Los
principios y valores[^2] que surgen de ella sirven de sustento para la
toma de las decisiones más complejas a las que se tiene que enfrentar;
porque los principios éticos y morales se derivan de dicha verdad,
porque las definiciones de desarrollo, bienestar y felicidad, son
aspiraciones en la vida de todo individuo a las que solo se puede llegar
en una civilización humana que pueda lograr de manera indefinida la
convivencia pacífica , con justicia y un equilibrio estable con la
naturaleza en todas las culturas e individuos que le componen; porque el
ser humano tiene inquietudes trascendentales sobre el sentido de la vida
y la muerte, inquietudes que no tienen respuesta para muchas personas
creando un gran vacío en su existencia e identidad; el existencialismo
de la filosofía moderna enseña que no debemos enfocarnos en esas
cuestiones del origen y la finalidad del "ser", que para su pensamiento
no están al alcance del ser humano, sino mas bien el foco debe dirigirse
a entender por medios racionales el bienestar terrenal para sacar el
máximo provecho de cada momento en una apología a las capacidades del
ser humano, que llevada a sus límites termina enfrentándose a la
realidad de su propia debilidad. El no admitir la existencia y la
búsqueda de una verdad absoluta, dado el subjetivismo y la relatividad
de la verdad individual, o la verdad parcial ofrecida por el campo
científico y la técnica, equivale a permitir la imposición de la verdad,
sus principios y valores de unos grupos de interés a otros; es este el
escenario en el que ha navegado la humanidad en la historia de todas las
civilizaciones que han emergido y desaparecido, en la antigüedad, por
imposición exclusiva de la fuerza, hoy de muchas otras variadas maneras
que tampoco descartan la guerra como expresión de dominio e imposición
de una verdad relativa a la condición humana.

## Avances de la ciencia

No existe ninguna duda hoy en día y a partir de aproximadamente el siglo
XV sobre los tremendos avances y la velocidad en la evolución y búsqueda
de una verdad científica, especialmente durante las últimas décadas. Los
beneficios técnicos generados a la sociedad por los avances de la
ciencia en diferentes ámbitos son indiscutibles; La humanidad se acerca
velozmente a una nueva dimensión de la aplicación de la ciencia a partir
de numerosas disciplinas como la inteligencia artificial, la robótica,
el aprendizaje de máquinas, la neurociencia o la bio genética que sin
duda alguna estarán en el vértice de discusiones de tipo ético,
discusiones relacionadas a valores y principios que implican
redefiniciones de los conceptos de bienestar social e individual.

Los inicios de la ciencia datan de entre el 3000 AC y el 3500 AC en
Mesopotamia y el antiguo Egipto; el avance de la ciencia moderna ha
permeado la revolución industrial a mediados del siglo XVIII, y también
a las llamadas revoluciones tecnológica e informática o sus
interpretaciones actuales. Pero, también ha generado grandes cambios
culturales que implican rompimientos drásticos en la definición de los
principios y valores de la humanidad en la era moderna. La sociedad
actual se encuentra en una etapa de transición donde el bienestar y la
felicidad comienzan a definirse en virtud de la influencia de la
ciencia, mas no en las decisiones de los científicos; en sus diferentes
y variadas definiciones y percepciones, el bienestar tiene como
ingrediente, la manera como la verdad científica influye en la
satisfacción personal, en la productividad laboral , en las relaciones
sociales, en la familia, en el poder de las naciones, en la política y
en toda esfera donde el conocimiento científico se convierte en el
factor esencial de la vida humana tanto a nivel individual como
colectivo. Los "Julio Verne" modernos predicen en su ciencia ficción,
escenarios inimaginables tanto para el bien de la humanidad como para su
autodestrucción.

Es tanta la influencia de la verdad científica, que la religión va
perdiendo espacio en la vida actual especialmente en el ámbito de los
grupos de interés que definen el progreso contemporáneo, ya que la
experiencia religiosa no se fundamenta en la metodología científica; La
aplicación del pensamiento lógico y racional ligados a la metodología
científica, está dejando el espacio para una crisis de principios y
valores, que en primera instancia puedan conducir a conflictos bélicos
de manera desmedida y con consecuencias impredecibles para las próximas
generaciones. Paradójicamente, aquellos científicos que más influyen en
la búsqueda de la verdad científica son los primeros en advertirlo.

En 1947 un grupo de científicos muy reconocidos , crearon el "Boletín de
los científicos atómicos" quienes se organizaron a partir del proyecto
Manhattan[^3] con el fin de advertir inicialmente sobre las
consecuencias de la bomba atómica. Hoy en día advierten al público en
general y a las naciones del mundo sobre los peligros y beneficios del
desarrollo científico con el fin de influenciar en las políticas
públicas de las naciones. Para este grupo de científicos el final de la
humanidad llegará las doce de la noche del reloj doomsday[^4]; el punto
es que según sus cálculos faltan noventa segundos para las doce!.
Amenazas a favor de un gran conflicto militar, el abuso a la naturaleza
que genera un cambio climático y el uso inadecuado de nuevas tecnologías
disruptivas son las principales causas.

Casi un siglo antes, en una de las reuniones científicas más
trascendentales para la humanidad "La 5a conferencia de Solvay"
realizada en octubre de 1,927 en Bruselas, donde aparecen en una misma
foto las mentes más brillantes de toda una época y quienes sentaron las
bases de la física cuántica que nos gobierna actualmente, hablaban
informalmente de Dios. Mientras Albert Einstein (Ulm , 1879 -- 1955,
Princetown)[^5] defendía la postura de un universo totalmente
determinista le decía a Niels Bohr (Copenhague, 1885 -- 1962,
Copenhague)[^6] "Dios no juega a los dados" dada la defensa de Bohr del
Principio de Incertidumbre[^7] de Heinsenberg (Wurzburgo, 1901-1976,
Munich)[^8] . Bohr le respondía a Einstein, "Einstein, deja de decirle a
Dios lo que debe hacer". En este caso la argumentación de fondo era
puramente científica. Sin embargo, ocurrió por casualidad y de manera
casual en los corredores del hotel una conversación que ha pasado
desapercibida, pero quedó registrada y tiene un fondo teológico
interesante. La conversación la sostuvieron varios científicos
prominentes cuyos aportes han sido fundamentales para el desarrollo de
la física moderna. Wolfang Pauli, Paul Dirac y Werner Heisenberg[^9];
Hablaron inicialmente sobre la posición de Max Planck quien defendía la
compatibilidad entre la ciencia y la religión como dos facetas
diferentes, Planck perteneció a la iglesia Luterana y dicen que se
convirtió al catolicismo al final de sus días; hablaron sobre el
pensamiento de Einstein en relación a un Dios personal que mantenía un
orden central; La posición de Paul Dirac, el más joven , asumía la
religión como algo puramente imaginativo y mitológico derivado de las
culturas primitivas; Pauli y Heisenberg creían de algún modo en la
religión, pero no les agradaba la idea de que la religión y las ciencias
fueran realidades separadas. Ya en aquella época de ebullición de la
teoría científica , deslumbraba la preocupación de ambos por el abandono
de la religión, en palabras de Wolfang Pauli:" "La completa separación
entre el conocimiento y la fe es en el mejor de los casos una medida de
emergencia, que permite un alivio temporal. En la cultura occidental,
por ejemplo, muy bien podría suceder en un futuro no muy lejano, el
momento en que las parábolas y símbolos religiosos perderán su capacidad
de persuasión aún para la persona promedio; cuando eso suceda, me temo
que la ética tradicional colapsará como un castillo de naipes y que
horrores inimaginables serán cometidos". Ese futuro no muy lejano es el
siglo XXI, el presente, en el que se evidencia la decadencia de los
principios y valores en la aplicación de la ciencia y la razón bajo el
umbral aislado de la razón y la fe en la búsqueda del progreso y el
bienestar humanos. A pesar de ello, no se puede caer en fatalismos, la
resiliencia de la humanidad ha salido a la luz en épocas terribles de
dominación de imperios usurpadores de muchas culturas o en momentos
posteriores a las guerras mundiales. Los principios , valores y la
religión no se han perdido, pero el estar de brazos cruzados, se
ensañará más en un panorama como el descrito por Wolfang Pauli. La
Cristiandad tiene una gran responsabilidad en la construcción de un
mejor futuro cercano; pero las demás religiones y formas de pensamiento
abundantes que en el mismo barco nos identifica y nos une como personas,
también deben percatarse de su responsabilidad en el fortalecimiento de
un mejor futuro como legado para las siguientes generaciones.

## Los misterios de la ciencia

La religión y la ciencia enfrentan misterios en la búsqueda de una
verdad absoluta. Ambas tienen una característica en común: comparten la
posibilidad de definir algo como un misterio, pero se insiste en su
búsqueda. La Biblia en el caso de la religión Cristiana es el documento
válido en el cual se puede encontrar una verdad de salvación, a través
de la divina revelación , la interpretación de su mensaje permanece en
el transcurrir de los siglos, el cual mediante la fe y la comunidad
adquiere sentido. Mientras los libros de ciencia tienen un contenido de
verdad científica sujeto a constantes revisiones y ajustes, presenta una
evolución a través del tiempo. Los misterios en la religión Cristiana y
en otras religiones son aceptados como parte de la verdad, mientras que
la búsqueda de la verdad científica acepta sus contenidos solo cuando se
demuestran a cabalidad a través de su metodología. Cuando el contenido
de los libros de ciencia no cumplen estrictamente con la metodología,
son descartados o se asumen como retos intelectuales a los que se somete
a un permanente escrutinio del intelecto humano en el transcurrir del
tiempo. Este proceso de constantes revisiones y ajustes lleva a nuevas
preguntas y misterios científicos en la búsqueda de una verdad, que en
ocasiones pareciera estar en un ciclo interminable de nuevas
inquietudes. A esto se refieren los misterios de la ciencia. Algunos de
ellos inciden en la vida diaria de la humanidad, en su desarrollo y
bienestar y otros satisfacen la interminable curiosidad del ser humano y
su sed de conocimiento. Entre la gran variedad de misterios científicos,
podemos mencionar algunos de ellos. La fuerza de gravedad desde los
tiempos de Isaac Newton(Lincolnshire, 1642 -- 1727, Londres)[^10], quien
formuló la ley de la gravitación universal en el siglo XVII, la
humanidad ha desarrollado abundantes proyectos científicos y técnicos a
partir de esta ley de la física , la cual predice que dos cuerpos con
masa se atraen proporcionalmente al producto de sus masas e inversamente
proporcional a la distancia que los separa. El beneficio de esta teoría
científica lo vivimos inconscientemente en las actividades diarias. Sin
embargo, no comprendemos que "es" la fuerza de gravedad. La fuerza de
gravedad la experimentamos desde el nacimiento de la historia de la
humanidad, no se sabe cual es su esencia, ni como se transmite; aún
cuando se conoce y se puede predecir su comportamiento. La fuerza de
gravedad, bajo la teoría de la relatividad, no es comprendida en la
forma como interacciona con las otras fuerzas de la naturaleza. Su
definición actual se fundamenta en la relación de una dimensión
espacio-temporal de los cuerpos en el universo, los que deforman con su
masa aquella dimensión[^11]. Así como a una moneda estática sobre una
sábana templada induce a un pequeño hundimiento sobre la sábana, de tal
manera que si se pone a rodar suavemente un balín sobre la sábana en
cercanías a la moneda, el balín rodará circundante hacia aquel
hundimiento. Así mismo, el espacio se deforma ante cuerpos estelares
como el sol y los planetas; así tienden a establecer órbitas en su
rededor; pero entender la gravedad es mucho más complejo , ya que el sol
no es el único que ejerce dicha transformación del espacio; la
complejidad aumenta cuando se intenta conocer como influyen todos los
elementos del universo en permanente movimiento, a grandes velocidades y
con grandes diferencias en su masa y en la densidad de la misma, no solo
en la curvatura del espacio, sino en su efecto en la transformación del
tiempo, en especial en partículas sub atómicas que se manifiestan a la
velocidad de la luz. En dicho caso ya no es la física clásica, sino la
física cuántica la encargada de estudiar dichos enigmas. Y es en este
nivel de lo tremendamente pequeño donde la física cuántica nos introduce
a conceptos como el de la entropía. Al introducir una buena receta de
alimentos crudos y un poco de agua en una olla a presión, permanecerán
en un estado inicial en equilibrio. Los alimentos están a la temperatura
del ambiente. Tan pronto se cierra la olla y se enciende el calor de la
estufa, comienza a fluir energía calorífica al interior de la olla. En
su interior , el agua hervirá y sus partículas se moverán a grandes
velocidades, estrellándose unas contra otras, produciendo burbujas; los
alimentos también se deslizarán por la presión, unos contra otros; se
pasará a un estado de completo desorden y alta temperatura al interior
de la olla. Finalmente, el experimentado cocinero quien ha mantenido en
su punto la temperatura, apaga la estufa, destapa la olla y los
alimentos estarán apetitosos; si se dejan enfriar volverán a su estado
de equilibrio final, similar al inicial , pero ya transformados. Dicha
tendencia al desorden, ante un aumento de la energía es la entropía,
acompañada de un trabajo, la cocción. La entropía tiene siempre una
misma dirección; los alimentos solo se cuecen si se les pone al calor,
pero nunca se cocinarán solos de manera espontánea, ni tampoco se
volverán crudos después de cocidos. En la escala del universo es mucho
más complejo, la entropía mide el grado de desorden gracias a la segunda
ley de la termodinámica[^12]; a nivel molecular, se sabe que la entropía
siempre aumenta. Vivimos en un universo en el cual, a medida que el
tiempo pasa, el desorden aumenta. Es la llamada flecha del tiempo. Y en
sistema aislado, el estado máximo del desorden es el orden, o un estado
de equilibrio, como sucede en la cocción de los alimentos. Supongamos
que tiramos un rompecabezas al aire , esperando a que cuando caiga lo
haga con sus fichas correctamente colocadas. Podrá pasar un tiempo casi
equivalente a la vida misma del universo y seguirá cayendo desarmado,
pero hay una muy pequeña probabilidad de que caiga bien armado; si esto
sucede llegó a su máximo nivel de entropía, el orden. La verdad
científica, entiende y puede predecir los efectos de la entropía y su
comportamiento, pero no entiende porqué sucede en la forma como se
conoce. Su aplicación es muy importante en la ingeniería a nivel
molecular y la tecnología utiliza sus principios, entendiendo el "cómo"
pero no el "porqué". El calor que se deriva de la entropía es una forma
de energía y la realidad es que los avances tecnológicos de la ciencia
se producen sobre el 5% del universo que conocemos, el cual está
compuesto por los átomos que conforman la materia que entendemos, la
materia de lo que están hechos nuestros cuerpos. El 68% es energía
oscura y el 27% es materia oscura[^13]. La energía oscura es la
responsable de la expansión del universo y la materia oscura interactúa
en la gravitación de los cuerpos en el plano espacio-temporal del
universo. Sobre la energía y materia oscuras es muy poco lo que se sabe,
aunque se ha comprobado su existencia por las relaciones entre las
medidas de expansión del universo que se conocen gracias al efecto
doppler[^14], la teoría de la relatividad de Albert Einstein y otras
técnicas científicas al alcance del estudio de los astrofísicos, que nos
ilustran esporádicamente sobre sus maravillosos hallazgos. El efecto
Doppler demuestra que las Galaxias más lejanas, presentan un corrimiento
hacia el rojo, lo que indica que está expandiéndose. Al observar la
luna, el sol o las estrellas en una noche despejada, tenemos la
sensación de que observamos el universo presente, pero gran parte de lo
que es y lo que no es detectado, por el más avanzado de los telescopios,
no solo es desconocido, sino que es mirar al pasado del universo,
millones de años atrás. En pleno post modernismo, somos tan ignorantes
como aquel antepasado que se situó en alguna montaña costera,
pretendiendo comprender con la vista en la lejanía del extenso mar, la
composición íntegra del planeta tierra. En síntesis, aunque conocemos la
estructura del universo en términos de su composición en la relación de
materia y energía; el conocimiento de las propiedades y el perfecto
entendimiento de la energía y la materia sigue siendo un gran misterio.
Y esta afirmación se corrobora cuando la ciencia busca entender los
agujeros negros, son puntos en el universo infinitamente densos y
pequeños. En nuestra vía láctea existe un agujero negro y al parecer en
casi todas las galaxias hay al menos un agujero negro[^15]. Se producen
por una atracción infinita de la materia debido a la fuerza de gravedad;
aunque se ha aprendido mucho sobre los agujeros negros, estos contienen
lo que se denomina como una singularidad: El punto donde las leyes de la
física como la conocemos actualmente pierden su validez y dejan de
operar. No entendemos desde la verdad científica lo que sucede en una
singularidad. A pesar de la gran velocidad en la que la ciencia avanza
hacia nuevas fronteras en la búsqueda de la verdad, se abren nuevas
fronteras. Una gran respuesta lleva a otra nueva gran pregunta o
posiblemente a muchas otras preguntas; esa ha sido la dinámica
científica a través de los siglos. Aunque no se percibe en nuestro
diario vivir, la humanidad sigue manteniendo un alto grado de ignorancia
en muchos campos. Recientemente en Julio 4 de 2012 la comunidad
científica anunció el descubrimiento de manera experimental del Bosón de
Higgs. Un avance extraordinario que permite afinar las predicciones del
modelo estándar, bajo el cual se puede explicar el comportamiento de la
materia conocida desde la física cuántica, o física en la escala de las
partículas. Aunque el avance ha sido extraordinario y sorprendente, este
modelo todavía tiene falencias[^16] ante temas como la fuerza de la
gravedad o el origen del universo, el cual es considerado también como
una singularidad. La comunidad científica apuesta por un modelo que
representa el origen del universo en una gran explosión o Big Bang[^17],
modelo propuesto por un sacerdote en 1927, llamado Georges Lemaitre
(Charleroi, 1849 -- 1966, Lovaina)[^18], quien desarrolló esta teoría
aceptada a partir de las ecuaciones de la teoría de la relatividad de
Albert Einstein. Los primeros microsegundos del Big Bang , llamados
época de Planck[^19] representan un estado desconocido del universo,
durante el cual la materia no existía, tampoco ninguna de las fuerzas de
la naturaleza conocidas existían, al parecer todo estaba unificado bajo
una fuerza única. Esta pequeña fracción de tiempo y lo que le antecede
es representado en una serie de hipótesis que se trabajan en este
momento desde las llamadas teorías de multiverso[^20], teoría de
cuerdas[^21], el universo originario de la nada[^22] y otras hipótesis
más[^23]. En este sentido, estamos ante el misterio del origen del
universo; pero algo si es una realidad desde la verdad científica : la
materia no existía en ese estado primigenio del universo. Inicialmente
ocurrió una expansión extraordinaria en la que ni la luz existía, puesto
que, si existiese el fotón portador de la luz[^24], todavía estaría
sujeto a una impresionante fuerza de gravedad, que como en los agujeros
negros, no dejaría escapar la luz. Pero la huella de las ondas
gravitatorias de aquella expansión, persistieron durante 380 millones de
años más. Hay evidencias muy fuertes de este periodo llamado
inflacionario[^25], en el cual el universo tuvo una tasa de expansión
increíblemente alta. Cuando la fuerza de gravedad dejó escapar el primer
fotón de luz, las ondas gravitacionales cargaban todavía un nivel de
energía que sería como una huella digital de aquellas primeras etapas
del universo. Recientemente en 1981, el científico Alan Guth
(Newbrunswick, 1947 - actualmente)[^26] quien propuso la teoría sobre
dicho periodo de crecimiento exponencial inicial del universo, ha tenido
la oportunidad de ver la evolución y los resultados de grandes
acontecimiento científicos ocurridos en los años 2013 y 2014, que
confirmaban su teoría. El telescopio PLANCK[^27], de la Agencia Espacial
Europea en el año 2013 y el equipo de varias instituciones científicas
involucradas en el proyecto BICEP2[^28] en el 2014, aplicaron una nueva
tecnología, una evolución de los radio telescopios, que detecta un
detalle de micro-ondas extremadamente particulares, sensibles y débiles
y que producen una vista similar a la de unos lentes polarizados
enfocados en objetos brillantes. Han logrado la primera fotografía del
universo primitivo, una especie de mapa térmico inicial, de increíble
precisión, que recientemente abrió una nueva etapa en la evolución de la
investigación cosmológica de la civilización humana. Fenómenos
inexplicables hasta dicho momento habrían sucedido. La ciencia predice
bajo el modelo standard la existencia de la antimateria en iguales
proporciones que la materia, posiblemente producidas en aquella gran
explosión, pero la antimateria no se ha detectado en las proporciones
esperadas[^29], no se entiende porqué ni como se aniquiló en los
primeros estados del universo; y aún su producción de manera
experimental es muy compleja. Otro aspecto intrigante es la forma del
universo, el cual podría ser curvo o plano. En un universo curvo dos
haces de luz que viajaran en paralelo regresarían al mismo punto de
partida; mientras si el universo es plano, seguirían en una misma
dirección de manera indefinida. La mayor parte de los científicos
cosmológicos están de acuerdo en que el universo es plano, aún cuando
todavía aparecen estudios que lo cuestionan[^30], sin embargo, como es
común en el razonamiento científico, de una interesante respuesta surgen
nuevos misterios. La ciencia predice en 13.8 billones de años la edad
del universo, pero la distancia estimada hacia el límite observable es
de 47 billones de años luz[^31]. Los límites observables del universo
son mayores a su edad. Tampoco hay respuesta para ello; al parecer la
energía oscura produce nuevo espacio en el universo, es decir, si dos
objetos del universo se alejan entre sí no solo por una velocidad que
los separa, sino porque se crea, al parecer, espacio nuevo entre ellos.
Cada objeto está separándose entre sí a una velocidad determinada, lo
cual genera la percepción desde cualquier lugar del universo, puesto que
todo se aleja, de que dicho lugar es el centro del universo; es decir ,
no existe un centro en el universo[^32] a pesar de que tiene su origen
en un punto inicial. Es entonces, una incógnita todavía entender lo que
ocurrió antes de la gran explosión y durante las primeras etapas de
existencia del universo, la manera como la energía oscura interviene en
el proceso de expansión del universo tampoco está del todo
definida[^33]. A pesar de estos y otros misterios que la humanidad
pretende descifrar desde la verdad científica, es sorprendente la
velocidad con la que el hombre está conociendo su hogar, llamado
universo. Si tuviéramos la vida del universo representado en una
enciclopedia de catorce tomos, donde cada tomo tuviera mil millones de
páginas, el homo sapiens apareció en el último párrafo de la última
página; y en la última palabra ha conocido lo que sabe sobre el
universo; y el último punto es el equivalente a nuestra sociedad
moderna. Es decir, la humanidad está recién llegada!.

Una característica de la física en el ámbito científico es la definición
de los objetos de estudio por "como funcionan" o por "lo que hacen" y
esto es descrito por las relaciones entre las ecuaciones que interpretan
las respuestas a las preguntas que surgen como hipótesis a lo largo de
los siglos; pero no define un objeto por lo que "es" en su escala
inicial o primaria; una mesa es una relación entre moléculas de diversos
tipos que nos permiten afirmar que la mesa "es" de madera, pero la
madera está constituida por moléculas o cuantos de energía, que a su vez
están constituidas por otras; y se siguen descubriendo nuevas formas de
la materia, sin que se comprenda del todo la partícula primaria que da
origen a la materia y por consiguiente de nuestra mesa; entre los
cuantos de energía y/o partículas, existen unas relaciones de
comportamiento identificadas bajo las leyes de la física; el modelo
estándar es la mejor explicación sobre de que está hecha la materia y
sus relaciones, entre ella la mesa, es materia que a su vez es energía y
que bajo el modelo estándar lo que conocemos de ella todavía de manera
imperfecta pertenece a una porción del 5% del universo; es nuestro mundo
material inmediato del cual podemos describir en gran medida y gracias a
la ciencia el "como funciona", podemos entender porque aquellas fuerzas
hacen que permanezcan unidas firmemente sus moléculas y se nos presenten
como madera para que le demos las formas que conocemos al diseñar una
mesa. La explicación de lo que "es" la materia, la energía, o el ser,
sigue siendo objeto de investigación, más allá de una explicación en
términos de la manera "como funciona" en las ciencias o de su
descripción a partir de las leyes de la física. En este sentido caben
otras formas de la razón como , la teología y la filosofía; una de sus
ramas es la metafísica, que estudia aspectos de la realidad inaccesibles
por las ciencias. Andrónico de Rodas (Siglo I AC)[^34], discípulo de
Aristóteles (Estagira, 384 AC --32 AC, Calcis)[^35] el gran filósofo
griego, al organizar las obras de su maestro puso después de las de
física aquellas que no encontraba como clasificar y las denominó como
"aquellas que van más allá de la física"; en sentido literal es el
significado de la metafísica, no como pensamiento substituto de la
física, sino complementario, siendo una rama de la filosofía utilizada
también en la teología, que intenta responder preguntas como ¿porqué
existe algo?, o ¿ Para qué existe ese algo ? en vez de la nada, pero,
¿que es la nada? o el "ser", entre otras causas primarias que dan
sentido a la existencia.

La comunidad científica atiende numerosos misterios sobre el universo ,
la naturaleza y el conocimiento del si mismo. Uno de los misterios más
apremiantes para la ciencia es el conocimiento del ser humano,
especialmente del cerebro, el órgano que desde la ciencia sirve como el
eje de conocimiento, comportamiento e inteligencia biológica del cuerpo
humano. Y aunque no lo parece, se sabe más sobre el comportamiento de la
naturaleza y del universo, que sobre el cerebro humano. La humanidad en
pleno siglo XXI percibe con mucho orgullo un gran avance a través de la
verdad científica; Y aunque en términos relativos es cierto si se
compara con el conocimiento de la humanidad en sus inicios, la grandeza
de muchos profesionales de la ciencia está en que pueden llegar a
sentirse como un chimpancé en un cohete, frente al conocimiento del
cerebro, del ser humano o de una verdad absoluta.

## La ciencia, la tecnología y el bienestar

La tecnología como reflejo de los avances científicos, generan en la
humanidad esa percepción de civilización desarrollada o moderna, una
percepción de una sociedad evolucionada y avanzada dado el bienestar
creado por las deslumbrantes aplicaciones de la ciencia y dadas las
comparaciones con la historia de civilizaciones antiguas y medievales.
De hecho, y así como lo anunciaba Wolfang Pauli con sus compañeros en el
siglo XVIII, es tanta la influencia del orgullo en la evolución
tecnológica y del pensamiento racional en la civilización moderna, que
la verdad desde la perspectiva de la Cristiandad es cada vez menos
explorada, mas tergiversada y menos entendida, aún por los mismos fieles
Cristianos. El siglo XXI comienza construyéndose como lo predijeron un
grupo de brillantes científicos hace doscientos años, sobre una base de
principios y valores con una clara tendencia a ser redefinidos
exclusivamente por el pensamiento racional, como consecuencia del
desarrollo científico. En este nuevo panorama la lógica de los
principios y valores, obedecerá al interés relativo de aquellos que
ostentan el poder y de la definición que tengan de "bienestar y de
felicidad" en lo que se considere el ideal de una civilización
desarrollada. He aquí una situación a la que tarde o temprano la
civilización desarrollada tendría que definir para evitar los ciclos de
decadencia de la civilización: ¿Quien es la persona o el grupo de
individuos, grupos sociales o naciones a quienes se debe seguir para la
construcción de esta nueva escala de valores y principios que guiará a
la humanidad ?. Hasta ahora en la historia de la humanidad ninguna
persona, nación o institución ha logrado ganarse dicha posición. A pesar
de que la verdad científica, encierra tantos misterios y carece de la
capacidad de dar sentido a la vida terrena o a la posibilidad de la
trascendencia y de proponer los principios y valores humanos de índoe
moral, la civilización se enfrenta a una seducción, una fascinación, una
atracción casi irreversible de seguir un pensamiento, exclusivamente
racional y científico, tal vez, debido al contagio de un deseo de
bienestar profundamente influenciado por el maravilloso desarrollo
tecnológico el cual nunca antes la civilización habría disfrutado y es
dicha capacidad el cimiento del progreso económico y el llamado del
desarrollo en la sociedad contemporánea.

El conocimiento científico ha alimentado el entendimiento de la verdad,
de una manera extraordinaria durante los últimos cien años . Como ya se
mencionó, el futuro que depara la aplicación de la ciencia, tanto en su
definición como en su aplicación, a partir de numerosas disciplinas
afectará el bienestar de la sociedad. Una definición básica de en la
actualidad del bienestar individual está en el orden de la satisfacción
y logro de un estado de tranquilidad y prosperidad de necesidades como
salud, alimentación, seguridad, comodidad, vivienda, educación y
trabajo; no solo en el plano físico, sino emocional y mental con matices
variados en las diversas culturas y cronologías.

Aún cuando la definición de bienestar puede diferir de acuerdo al
individuo o sociedad que le defina, es consecuente estar de acuerdo en
que la tecnología moderna ha contribuido considerablemente en la
construcción del bienestar de la humanidad en aquellos aspectos básicos
de su definición. Con el ánimo de tener una perspectiva , mencionaré
algunos casos de desarrollos tecnológicos derivados del conocimiento
científico y cuyo estado de desarrollo está muy avanzado; probablemente
en unas cuantas décadas se tendrá pleno control de las siguientes
tecnologías.

Computadores cuánticos: Gracias a varios elementos cognitivos, y a la
comprensión del concepto de entrelazamiento cuántico por la comunidad
científica ya se están construyendo los primeros computadores cuánticos.
El entrelazamiento cuántico[^36] implica que dos partículas con un mismo
origen a pesar de que estén en lugares apartados del universo tienen dos
o más estados y al afectar el estado de una de las partículas, se
afectará el estado de la otra partícula de manera simultánea. A partir
de esta propiedad de las partículas se definen los cubits[^37], los
cuales a diferencia de los bits de la tecnología de procesadores
actuales que tienen solo dos estados diferentes (cero y uno), los cubits
contienen ambos estados (cero y uno) de manera simultánea. Es algo que
no cuadra en la imaginación ya que el cerebro está adaptado para pensar
dentro de la cotidianidad de la vida. Los cubits implican mayor
capacidad de información y una lógica mas eficiente en la forma como se
desarrollan los algoritmos para la manipulación de la información. De
acuerdo al cofundador de la fábrica de microprocesadores, INTEL, Gordon
E Moore (San Francisco, 1929, Hawai) [^38], la capacidad de los
microprocesadores de la tecnología actual se duplicaría cada dos años,
pero la capacidad física de los mismos tendría un límite que se
alcanzará en las próximas décadas,luego no se podría incrementar la
capacidad. La nueva tecnología que comenzará a reemplazar la tecnología
de los microprocesadores , será la de la computación cuántica. Los
modelos de predicción del clima serán miles de veces más efectivos; las
simulaciones en la industria química incrementarán su capacidad de
manera exponencial y se crearán nuevos materiales imposibles de crear
con la tecnología actual. El sector financiero y el bio médico tendrá
impactos aún no descubiertos. En general habrá un impacto en todas las
industrias, tal vez muy superior al impacto generado por la masificación
del internet en el mundo actual. Otra técnica que avanza rápidamente es
el de la Nanotecnología[^39]. Es un campo digno de la imaginación y la
ficción. Consiste en dispositivos miniaturizados llamados nano
robots[^40] que poseerán ciertas capacidades autónomas que
revolucionarán muchas industrias; en el campo de la medicina los
tratamientos para enfermedades como el cáncer, pequeños nano bots podrán
transportar moléculas que contengan instrucciones para que las células
reaccionen de una manera determinada. En otro aspecto, pequeños drones
que simulan insectos y son alimentados por energía solar ya están
funcionando a nivel de laboratorio, solo basta tener creatividad para
entender la diversidad de usos que se les puede dar a estos pequeños
robots. En otra categoría tecnológica, a través de la Ingeniería
Genética nació la primera niña[^41] bajo fecundación "In Vitro" en julio
25 de 1978 . En este proceso se fecunda un espermatozoide y un óvulo
fuera del útero materno con el fin de crear un embrión en buenas
condiciones para transferirlo al útero materno y dar lugar a un
embarazo. A partir de ese momento nuevas técnicas de desarrollo de
embriones han surgido como la de embriones híbridos; bajo esta técnica
se mezcla la información genética del núcleo de una célula humana con
los genes mitocondriales de una célula animal, creando una célula mixta.
En enero del 2017[^42] se realizaron los primeros experimentos entre
células humanas mezcladas con células de cerdo, también se hicieron con
vacas. Ya se han realizado en el 2023 dos intentos de transplante de
corazón de cerdo a un humano alargando por poco tiempo la vida de los
pacientes[^43]. Esta investigación tiene como uno de sus objetivos el
entendimiento del desarrollo embrionario temprano, el conocimiento del
desarrollo de los órganos y otras aplicaciones médicas por definir como
el transplante de órganos y tejidos. Con objetivos similares, se ha
logrado la creación de un embrión de ratón en laboratorio, es decir un
embrión artificial, con algunos órganos de rata, a partir de células
madre de rata. En otra faceta de la investigación embrionaria, la
civilización contemporánea inicia una etapa de transición para decidir
como nacerán los bebés en el futuro , pasando de la procreación sexual a
la procreación en el laboratorio con embriones genéticamente
modificables. En noviembre del 2018 un Biofísico Chino anunció que
habían nacido el mes anterior dos bebés genéticamente modificados[^44].
El científico Chino utilizó la tecnología de edición genética llamada
CRISPR, descubierta hace treinta años y que permite localizar secuencias
genéticas específicas, cortarlas y modificarlas[^45]. Así, una faceta en
la ética de la modificación genética, pasó de ser ciencia ficción a una
realidad casi inmediata, puesto que aunque se presta para eliminar
riesgos de enfermedades, también se presta a efectos desconocidos en las
aplicaciones que se desarrollen, ya sea en seres humanos o de cualquier
otra especie. Estas deslumbrantes tecnologías son un ejemplo explícito y
real, que enfrentan el entendimiento del bienestar y la búsqueda de la
felicidad desde la filosofía de la ética o la moral y teología
tradicional en el contexto del progreso de la civilización.

La búsqueda del bienestar, no implica de manera necesaria y suficiente
la búsqueda de la felicidad. La relación entre bienestar y felicidad es
todavía motivo de debate, puesto que ambos términos pueden tener
diferentes interpretaciones; no está comprobado desde la verdad
científica, ni desde el razonamiento filosófico, que exista una relación
directa que implique que una mejora del bienestar de un individuo
implica necesariamente su felicidad. La verdad científica ha aportado
indiscutiblemente de manera positiva en la mejora de la calidad de vida
de los habitantes del mundo, mejorando así los indicadores de bienestar
tradicionales. No hay duda de que variables como el índice de longevidad
y el desarrollo económico influyen en dicha percepción. Gracias a los
avances en las ciencias y tecnologías de la salud el índice de
longevidad ha pasado de promedios de 50 años en los años de 1,800 hasta
más de los 80 años en el 2012.[^46] Una variable que mide el desarrollo
económico, como parte del concepto del bienestar, es la pobreza absoluta
definida como el ingreso per cápita menor a USD 1,90 por día; el cual
desde el año 1,800 muestra poca mejoría durante los siguientes cien
años, y es a partir de 1,990 que la tasa de reducción de la pobreza
absoluta presenta una mejora substancial , disminuyendo la pobreza de
1.9 billones de habitantes en 1990 (23.5% de la población mundial ) -- a
733.5 millones en el año 2015 -- una décima parte de la población
mundial; se espera que para el año 2030 la pobreza absoluta se reduzca a
479 millones de habitantes.[^47]

Nuevos desarrollos tecnológicos, influirán sin duda en la forma como las
nuevas generaciones vivirán en este mundo; la creatividad, la
imaginación y la razón humanas encontrarán nuevas aplicaciones en la
generación de bienestar. En el escenario actual, surgen graves
inquietudes respecto a los riesgos que implican las nuevas tecnologías,
no por su capacidad sino por la forma como la humanidad decida
emplearlas y sus implicaciones en las visiones, definiciones y
aspiraciones de cada cultura y comunidad. Decisiones implícitas en la
escala de principios y valores que servirán de guía al liderazgo
mundial. La computación cuántica y la inteligencia artificial combinadas
pueden llevar a un Gobierno a controlar cada aspecto y detalle de la
vida de sus ciudadanos. Hoy en algunos países, en los que aplicando
técnicas de big data e inteligencia artificial, se ha comenzado un
proceso de vigilancia permanente de sus ciudadanos mediante
identificación facial, control financiero y otras variables relacionadas
al comportamiento de sus ciudadanos en detalles como su afinidad o no al
líder político de turno. Los ciudadanos podrán ser castigados o
beneficiados de acuerdo a la interpretación del gobierno, de manera
inmediata. Con la misma tecnología, quienes lideran los mercados
globales deciden a través de la interpretación de volúmenes increíbles
de datos sobre el comportamiento de sus consumidores o clientes;
información que puede ser utilizada en tiempo real de acuerdo al grupo
de interés del gobierno, institución o poder económico que tiene acceso
a ella, entre ellos la manipulación de los nuevos medios de
comunicación. En cualquiera de los casos y debido a que el acceso a las
tecnologías de computación cuántica , es restringido dada la intensidad
en conocimiento y recursos para su desarrollo, el gran volumen de la
población mundial estará regido por los intereses de unos pocos grupos
de interés, de acuerdo a los principios y valores que les motiven. En el
caso de algunos gobiernos, una posible restricción y manipulación de la
libertad es evidente y en el caso de los mercados globales, la
manipulación de intereses y el enriquecimiento desproporcionado en
detrimento de las poblaciones vulnerables , o del ecosistema natural es
otro peligro evidente. La nanotecnología podría generar actos invasivos
en cualquier individuo, como sacar muestras de sangre o inyectar
moléculas en el cuerpo de una persona, sin su consentimiento. La nano
robótica aplicada como arma de guerra puede ser utilizada para espionaje
o la creación de micro artefactos explosivos dirigidos masivamente o
individualmente. La manipulación indebida en una escala de valores
humanos subjetiva, aplicada a la ingeniería genética , implica la
posibilidad de jugar con la vida humana en nombre de la investigación
científica. Es cercana la posibilidad de modificar el umbral del dolor
en el ser humano para conformar ejércitos con seres humanos "diseñados"
para la guerra. Aún cuando los beneficios de la ciencia y la tecnología
son innumerables durante el último siglo, también es cierto que la
creación de la tecnología de guerra mantiene el balance global en un
equilibrio tambaleante; y las nuevas tecnologías dirigen a la
civilización a escenarios nunca antes previstos. No existen las
garantías para que las nuevas tecnologías no incrementen los riesgos de
auto destrucción de la humanidad, ya no solo de la civilización. Retos
de gran complejidad, algunos arrastrados por la historia, otros nuevos,
se vislumbran en la construcción de la civilización humana, parten de
hechos que abarcan desde la injusticia social, el deterioro de la
naturaleza, el dominio y la imposición del poder, la dominación de unas
naciones sobre otras, entre muchos otros dilemas que asaltan
constantemente a la población de un mundo hiper conectado. Es un
conjunto de retos entrelazados en un mundo de relaciones globales y
grandes diferencias culturales de los pueblos, que cada vez tienen más
efectos regionales y locales; se abarcan cuestionamientos desde ámbitos
políticos , filosóficos y teológicos; muchos de estos retos han
demostrado ser más complejos y permanentes, de lo que la capacidad de la
razón y la inteligencia humanas pudieran dar para encontrar soluciones
definitivas. Indiscutiblemente se está forjando una nueva cultura global
frente a estas realidades que influirán en el porvenir de la humanidad.
La responsabilidad de un cambio de escala y re definición de principios
y valores se viene gestando desde la visión de una verdad teológica
asumida por las diferentes religiones y filosofías del mundo medieval,
hasta un punto de convergencia con inicios en el siglo XVIII, en el
llamado de la ilustración y el humanismo Europeo en occidente y su
influencia en el resto del mundo; su influencia tiende en la edad
contemporánea a una interpretación racional y científica de la realidad
global, realidad que está sujeta al entendimiento de la naturaleza
humana y del si mismo; una condición bastante desconocida que desde la
ciencia implica el conocimiento profundo del cerebro humano como fuente
de la consciencia , donde finalmente se devela la responsabilidad en la
construcción de las escalas de principios y valores, en el individuo y
la comunidad. Pero la ciencia, como en el entendimiento del universo se
enfoca en definir el cerebro por lo que hace, o por la manera en que
funciona, así el ser humano tendría su consciencia, aún sin entender, en
el cerebro y si la ciencia logra entenderla, su definición será dada por
la descripción de cómo funciona. La consciencia es un componente de lo
que es el "ser" humano. En este sentido la comprensión del ser humano
abarca una amplitud de conocimiento de una dimensión extraordinaria. Si
desde la ciencia se lograra entender completamente al ser humano, sería
un aporte grandioso al entendimiento de la verdad, en tal caso,
tendríamos la capacidad de conocernos a un nivel tan profundo e
inequívoco, que sabríamos como civilización, como enfrentar y resolver
los riesgos y conflictos que nos asechan constantemente; podrían las
diferentes culturas, pueblos y comunidades de las naciones, acordar en
concordancia con tal conocimiento científico, las decisiones que como
individuos y como un todo social se tomarían sin mayores esfuerzos,
puesto que la misma ciencia indicaría los pasos para hacerlo. Al menos,
aquella parte de la verdad concerniente a la convivencia pacífica de la
humanidad no podría ser negada, sería evidente para todo ser humano,
pues no solo se esclarecerían cuales son los verdaderos principio y
valores que gobernarían al ser humano, sino como se llegaría a ellos en
un acuerdo común de la humanidad. La ciencia llevaría de la mano a la
civilización sin temores de autodestrucción y posiblemente en estados
diferentes de lo que pudiera ser el bienestar, la felicidad y el
progreso para su conservación por cuanto las leyes del universo lo
permitieran.

El entendimiento de una verdad absoluta necesariamente pasa por el
entendimiento de la verdad en el ser humano. Una manera de llegar a
dicho entendimiento, es su expresión en dos formas opuestas que definen
tal relación; una en la que es imposible imposible llegar a una verdad
absoluta, puesto que las verdades individuales están por encima de ella
y la otra que afirma que las verdades individuales dependen de una
verdad absoluta. Aquella forma de la verdad individual que rechaza la
existencia de una verdad absoluta, apunta hacia el relativismo
filosófico que ha estado presente en las diferentes formas del
pensamiento del ser humano. Pero, desde la ciencias, la verdad
individual también puede ser entendida, se manifiesta a partir de
aquello que experimenta la persona en su cerebro en su propia vivencia
diaria, en su experiencia subjetiva. Subjetiva porque estaría sujeta a
interpretación por el individuo y porque no necesariamente podría ser
entendida por otro individuo. Podría decirse que la verdad individual es
una verdad subjetiva inmersa en la experiencia subjetiva de cada ser
humano. La experiencia subjetiva, desde la neurociencia está implícita
en la descripción de como funciona un elemento del cerebro llamado
cualias o qualias, a través del cual la consciencia puede manifestarse
como experiencia en el individuo. El debate sobre su existencia está en
el límite entre la filosofía y la neurociencia; en la neurociencia
existen defensores sobre su existencia y también quienes rechazan dicha
posibilidad. Uno de sus defensores nos define la función de las qualias
en el cerebro humano, pero antes debemos entender, al menos
superficialmente, como funciona el cerebro, así es como la ciencia hace
su definición de lo que el cerebro "es".

## ¿Quien soy yo?

Entendiendo el papel del cerebro desde la ciencia, fuente de la razón y
del conocimiento humano, se podrían identificar elementos pertenecientes
al "si mismo", elementos que son parte del estudio de la neurociencia.

En dicha perspectiva la ciencia ha comenzado recientemente a fortalecer
su comprensión del cerebro humano, el cual encierra otros misterios. Los
presupuestos económicos de las naciones más desarrolladas se están
incrementando considerablemente para entender como funciona nuestro
cerebro. ¿Quién soy yo? es una pregunta que cada individuo se ha hecho
desde tiempos inmemoriales desde la perspectiva teológica, filosófica y
científica. El entendimiento y conocimiento del funcionamiento del
cerebro podría arrojar luces sobre respuestas a esta inquietud
milenaria.

No se sabe, que impulsó el desarrollo del cerebro humano tal como lo
conocemos, es un misterio científico[^48]. Recordando que el ser humano
está recién llegado,el proceso de evolución del cerebro equivale a una
muy pequeña fracción de la existencia del universo. La teoría mas
aceptada es que el cerebro humano se desarrolló tan solo entre hace 70 y
30 mil años, por mutaciones genéticas accidentales hacia una nueva forma
de comunicación, que utilizando un tipo de lenguaje, le permitió pensar
de manera sin precedentes. El historiador Yuval Noah Harari (Kiryat Ata
, 1976 - Actualmente)[^49] lo llama la revolución cognitiva; o la
mutación del árbol del saber.[^50]

La gran contribución a la teoría de la evolución del biólogo Inglés
Charles Darwin (The Mount, 1809 -- 1882, Down House)[^51] , estipula que
las especies que tengan mayor capacidad de adaptación al medio natural
son las que sobrevivirán; esto sucede mediante el proceso de selección
natural, el cual ocurre a través de ciclos de mutaciones genéticas
durante miles de generaciones. Este proceso de selección natural llevó a
las aves a desarrollar poderosas alas y cuerpos adaptados para cruzar
los aires; al guepardo a ser el mamífero más rápido del mundo; al
tiburón a ser el cazador implacable de los océanos con su dentadura
comparable a la de una sierra. De igual, la observación científica nos
informa que la selección natural hizo que el ser humano desarrollara el
cerebro más poderoso sobre la tierra. Al igual que las alas, las piernas
y la dentadura, el cerebro es un órgano que tiene una función, como la
de cualquier otro órgano entre los seres vivos. Su función principal
inicial es la de entender y predecir el medio natural, el ecosistema en
el que vive con el fin de sobrevivir.[^52] Para ello en su desarrollo
primigenio, sus funciones básicas fueron las relacionadas a la
movilidad, desarrollando consecuentemente una capacidad de predicción
mínima, pero indispensable para sobrevivir. El razonamiento del tipo "Si
me muevo en dirección al desierto moriré por falta de agua, pero si de
muevo hacia el lugar donde hay agua y alimento, sobreviviré". Otras
especies apostaron a la inmovilidad para sobrevivir; por lo tanto no
necesitaron de un cerebro que coordinara su movimiento.

El cerebro evolucionó representando las fases por las que ha pasado, de
adentro hacia afuera; en lo más profundo está la parte más antigua , el
tallo encefálico donde se regulan las funciones básicas como la
respiración y el latido del corazón. Luego está el complejo R, donde se
regula la territorialidad, la jerarquía social y en general las
características reptilianas heredadas de hace millones de años. Luego,
envolviendo el complejo R está el sistema límbico propio de los
mamíferos. Esta es la zona responsable de las emociones. Por último está
la corteza cerebral , la cual evolucionó a partir de nuestros
antepasados primates. Es en la corteza cerebral, también llamada materia
gris, donde ocurren la percepción, la imaginación , el pensamiento, el
juicio y la decisión. El astrónomo y científico Norte Americano Carl
Sagan (Brooklin, 1934 -- 1996, Seatle )[^53] afirmaba que la
civilización es un producto de la corteza cerebral.[^54] Otras especies
que también tienen cerebro, no han llegado al desarrollo de sociedades
de un nivel de complejidad tan alta. El Chimpancé y el Bonobo, son las
especies animales más cercanas a la nuestra. Importantes características
que marcan diferencias entre el cerebro humano y el de el Chimpancé se
han encontrado recientemente confirmando que el cerebro humano, es
considerado por muchos científicos como la corona de la evolución; es un
cerebro único[^55]. El cerebro también encierra grandes números como el
universo: está constituido por aproximadamente 86 billones de neuronas
(materia gris), billones de axones y dendritas (materia blanca) y
trillones de conexiones o sinapsis.[^56] La neurona es la célula
encargada de recibir, procesar y transmitir la información. Los axones
llevan la información a otras neuronas y en sus terminaciones están las
dendritas, las cuales hacen contacto con las dendritas de otras
neuronas, dichos contactos son las sinapsis. Durante este gran recorrido
de la evolución, en algún momento nuestros antepasados comenzaron a
desplazarse y a moverse; esto dio origen a una de las principales
funciones del cerebro, "la capacidad de predecir".[^57] Desplazarse
implica peligros y por ello el cerebro desarrolló capacidades
sensoriales que generan un contexto del mundo exterior a través del cual
se realiza el desplazamiento. Sin dicho contexto no habría un rumbo
claro hacia donde desplazarse. El cerebro está en permanente estado de
ajuste y atento para anticiparse a un estímulo determinado que permite
el control del movimiento; este es el origen de la mente, el control
cerebral del movimiento organizado dio origen a la generación y
naturaleza de la mente; un estado funcional del cerebro mediante
sincronizaciones de pulsos rítmicos que lleva a diferentes estados
mentales. Los pulsos rítmicos son percepciones discontinuas que se
originan en los sentidos e interpretan una realidad continua. Esta
interpretación se hace a través de nueva información externa que llega
de manera permanente al cerebro y que lo retroalimenta generando una
capacidad de predicción. El cerebro entonces debe priorizar la
información que recibe para cotejar la información externa con la
información interna y así decidir para ejecutar una acción. La
complejidad expresada por los procesos mentales y la comprensión de la
mente todavía son un enigma, especialmente cuando todo este proceso
ocurre de manera diferente en cada ser humano. Este aspecto arroja ya
ciertos elementos sobre lo complejo que pude ser descifrar el origen de
una verdad individual. Desde la interpretación científica, la realidad
no existe en el cerebro humano, lo que se forma es una especie de
interpretación de información externa e interna de cada
individuo,interpretación que será diferente en términos estrictos a
partir de experiencias y vivencias en cada individuo. La existencia de
la realidad es un debate vigente desde el razonamiento filosófico y
teológico, pero el hecho de que la realidad sea una interpretación en el
cerebro, no significa que no exista. Una canción activa diferentes
experiencias y recuerdos en cada ser humano, algunos similares pero
nunca iguales; la canción es una realidad, al menos en la mente de su
autor. Cada ser humano tiene una verdad propia, ya que todo ser humano
tiene un "si mismo" , único como una huella digital. Extendiendo este
concepto a otras especies, la realidad puede ser interpretada de maneras
muy extrañas entre diferentes especies de organismos vivos que tengan
cerebro. Basta con imaginar lo que es la realidad para un murciélago.
Rodolfo Llinás (Bogotá, 1934-actualmente)[^58], es uno de los
neurocientíficos más destacados del mundo quien escribe en su libro "El
cerebro y el mito del Yo" :

"El sistema tálamo-cortical es casi una esfera isocrónica[^59] cerrada
que relaciona sincrónicamente las propiedades del mundo externo
referidas por los sentidos con las motivaciones y memorias generadas
internamente. Este evento, coherente en el tiempo, que unifica los
componentes fraccionados tanto de la realidad externa como de la interna
en una estructura única es lo que llamamos el si mismo "[^60]. Es decir
, para la ciencia el si mismo, se explica completamente en un sistema
cerrado que logra interpretar eventos del medio externo con eventos
internos del individuo. Esto sucede en un sistema que está en permanente
actividad; la función del cerebro está regulada por la transmisión de
pulsos o impulsos continuos eléctricos y químicos de las neuronas; si se
pudiera observar un estado mental del cerebro en el tiempo, se verían
juegos de ondas oscilando con diferentes frecuencias e intensidades,
entrelazadas y viajando de una zona a otra del cerebro permanentemente,
inclusive durante los estados más profundos del sueño.

Rodolfo Llinás hace una ilustración sobre otras características del
cerebro humano que marcan una gran diferencia frente a especies
cercanas: es la capacidad de aprender. La capacidad de aprender, la
construcción del conocimiento del cerebro humano es un estado funcional
y además una propiedad intrínseca del cerebro desarrollada durante
millones de años. La capacidad de conocer no necesita aprenderse; solo
debe aprenderse el contenido particular del conocimiento en lo que
refiere a aspectos particulares del ambiente[^61]. El poder de aprender
e interpretar el medio ambiente externo es una función que mejora la
capacidad de predicción, pero para que todo esto suceda, el cerebro
durante su proceso de evolución ha logrado interiorizar o representar
las características del mundo externo en un espacio funcional interno.
Esto lo hace emulando la realidad mediante imágenes anticipatorias,
plasmadas en una especie de plataformas para planeación de
comportamientos o acciones dirigidas, de eventos futuros que provocarán
la consiguiente reacción o comportamiento. Estas plataformas de
planeación reciben el nombre de patrones pre motores y es allí donde
nace la consciencia[^62], aún por descifrar, en todas las formas
vivientes. La capacidad de predecir y de aprender, constituyen la base
del razonamiento y que en conjunto con la consciencia del "si mismo" y
la creatividad en el cerebro humano forman parte de aquella verdad
individual que hace único a cada individuo. La creatividad en el cerebro
humano forma parte del proceso de aprender y es una de las funciones más
complejas aún no entendidas. De acuerdo a una investigación realizada en
Enero del 2018 por el PNAS[^63], una de las conclusiones afirma: "La
creatividad sigue siendo una función compleja que requiere de
investigación adicional para descubrir sus múltiples manifestaciones en
el cerebro. Indiferentemente a algunos aspectos del aprendizaje que han
sido localizados de manera precisa en regiones del cerebro , funciones
complejas como la creatividad, son posiblemente un producto similar de
complejos mecanismos neuronales que comprometen a todo el cerebro." En
dicho estudio se utilizaron métodos de redes neurológicas y se modelaron
habilidades de pensamiento creativo individual como función de la
conectividad del cerebro como un todo. Se encontró una red cerebral
comprendida por regiones con sistemas autónomos, sistemas transicionales
y sistemas ejecutivos.

Aquella capacidad del cerebro, de conocimiento y aprendizaje, a través
del razonamiento como lenguaje común en la especie humana, constituye
una gran diferencia frente a otras especies. Existe en cierto grado de
desarrollo del cerebro en otras criaturas vivientes, pero en ninguna
alcanza el desarrollo suficiente para entender, un lenguaje
avanzado,como el lenguaje de las matemáticas. Es la supremacía humana en
la capacidad de comunicación el componente que unifica y complementa el
criterio en la verdad científica; pero aún así, el ser humano en su
complejidad como ser vivo, experimenta en su espacio funcional interno,
en su cerebro y su cuerpo, situaciones del "si mismo" que no logra
comprender , ni comunicar de manera precisa; es, entre varios aspectos,
el caso de la consciencia.

## La consciencia

La definición de consciencia en el ser humano está ligada a la
interpretación del si mismo y del mundo externo, a partir del
conocimiento; también la consciencia es un punto de argumentación
filosófico como origen en la elección de una acción de tipo moral en el
ser humano y en este caso también una frontera con los principios y
valores desarrollados a partir de la teología. En pocas palabras, es una
especie de nodo siendo en muchos aspectos misterio para el ser humano.
Desde el ejercicio racional, la consciencia es la mente entendiendo el
cerebro. Se podría entonces hablar de diferentes niveles de consciencia,
existiendo la manifestación de la consciencia en su forma mas básica en
los animales, pero a un nivel de mayor complejidad en el ser humano.

Para el caso de otras especies , varios neurocientíficos de prestigiosas
universidades firmaron un manifiesto en la universidad de Cambridge,
Inglaterra en el año 2012: \" La ausencia de un neocórtex no parece
impedir que un organismo pueda experimentar estados afectivos. Hay
evidencias convergentes que indican que los animales no humanos poseen
los sustratos neuroanatómicos, neuroquímicos y neurofisiológicos de los
estados de consciencia, junto con la capacidad de mostrar
comportamientos intencionales. En consecuencia, el peso de la evidencia
indica que los humanos no somos los únicos en poseer la base neurológica
que da lugar a la consciencia. Los animales no humanos, incluyendo a
todos los mamíferos y aves, y otras muchas criaturas, entre las que se
encuentran los pulpos, también poseen estos sustratos
neurológicos".[^64]

La manifestación incipiente de la consciencia animal, una consciencia
primaria, está presente en el ser humano, pero en ambos casos, son un
enigma desde la verdad científica. La consciencia primaria está
vinculada con los aspectos sensoriales; el perro puede no ser consciente
de ser perro, pero si de que está en peligro frente a otro perro
agresivo, es decir es consciente del miedo, lo mismo que el ser humano;
sin embargo, la consciencia del ser humano tiene características únicas
a su especie, se identifica como persona, tiene conciencia de los
estados morales y se pregunta sobre su pasado y su futuro. El homo
sapiens se diferencia de cualquier otra especie a nivel de consciencia
por que se pregunta sobre su fe a un nivel espiritual que trasciende su
propia existencia, como principio religioso, que implica una capacidad
de hacerse las preguntas sobre el significado de su existencia, en el
sentido metafísico del significado del "ser" , en el si mismo. No existe
una mínima evidencia de una búsqueda de un sentido metafísico de su
existencia en otra especie; sin embargo, haciendo una circunscripción de
la religión en términos filosóficos relativistas hacia una religión
materialista[^65], se podría investigar en el mundo natural otra
definición de fe, distante del entendimiento de una fe objetiva y
trascendente.

El cerebro como órgano funcional de algunas especies vivientes, en su
evolución para poder predecir el movimiento ha desarrollado una compleja
red de señales electro químicas que permiten interpretar el mundo
externo. Para ello se vale de órganos sensoriales que en la mayoría de
las especies se situaron en la parte de adelante del cuerpo que comanda
el movimiento, en la cabeza. En ella están la mayoría de órganos de los
sentidos, supongamos la vista y el olfato[^66]. Y en este proceso
evolutivo el lenguaje humano permite comunicar las ideas con diferentes
rangos de acierto y veracidad, incluso dependiendo de la cultura y el
idioma; la afirmación "siento dolor" es clara y objetiva puesto que
implica una verdad respecto a una circunstancia que se desea expresar,
pero si se añade una sola palabra "siento mucho dolor", - mucho - puede
tener diferentes interpretaciones en grados de intensidad en el receptor
de la comunicación. Es una experiencia subjetiva que al comunicarse
refleja una verdad subjetiva. Cuando un ser humano puede "ver" un balón
, lo que sucede es que el conjunto de fotones reflejado por el balón ,
llamado estímulo es recibido por el ojo bajo una frecuencia de una señal
determinada por la composición química del balón. Esta señal es
traducida por las células de la retina del ojo en una señal electro
química y enviada a través del nervio óptico al cerebro. La frecuencia
de la señal es interpretada por el cerebro como un color, puede ser,
"rojo". El color rojo no pertenece al balón, es una interpretación de
nuestro cerebro, pero para el individuo que percibe la señal es su
realidad, es parte de su experiencia subjetiva. Sin embargo, dicha
experiencia puede variar en cada individuo; quienes sufren de
daltonismo, podrían ver el balón rojo de otro color. La experiencia
subjetiva se puede componer además de lo que se conoce desde la
psicología humana como sensación. Una sensación, no necesariamente
proviene de un estímulo externo, podría ser un evento intrínseco, es
decir, se tiene la sensación de calor, aunque la temperatura no ha
subido. O se tiene la sensación de que dicha persona me podría engañar;
una sensación envuelta en la propia experiencia subjetiva. La visión
completa del gol, en los fanáticos del futbol se convierte en una
emoción, que también forma parte de la "experiencia subjetiva" y que
puede ser colectiva ante el grito al unísono en un estadio. Las
emociones, han sido un mecanismo inconsciente diseñado para sobrevivir,
como dice Rodolfo Llinás "Esto huele mal, no se lo coma. Esto huele
bien, copule con ello[^67]. Este mecanismo es burdo, amplio y vigilante.
Dicho mecanismo , pareciera que tiene un rango que es limitado y a la
vez extraordinariamente poderoso en su capacidad de identificar olores
relacionados con las emociones que generan los patrones de
comportamiento automático, motores necesarios para sobrevivir."[^68]
Cuando una emoción deja de ser un evento momentáneo y perdura en el
tiempo entra a jugar en el nivel consciente del individuo en un largo
plazo, implica un pensamiento de orden racional; así se define un
sentimiento en el lenguaje de la psicología. El ejemplo clásico, es el
de la pareja que siente "mariposas en el estómago" al conocerse
(emoción), pero después de un periodo pertinente decide construir una
relación duradera, en dicho caso, ambos han pensado de manera racional
sus opciones y han tomado una decisión voluntaria (sentimiento). En el
cerebro humano, la experiencia subjetiva como parte de la consciencia se
puede expresar de alguna manera a través de la creatividad y de los
estados mencionados: estímulo, sensación, emoción y sentimiento.

Entonces el "si mismo", consciente, dado que se identifica con su
realidad no solo desde su experiencia subjetiva, sino desde su capacidad
de pensamiento racional y científico, posee verdades objetivas y
subjetivas acordes con su experiencia de vida y que forman parte de la
construcción de su verdad individual; y a partir de ella, cada individuo
procede en su vida diaria a la toma de decisiones o comportamientos
intencionales que se expresan desde la voluntad humana y pueden tomar
una connotación de tipo moral desde la conciencia, siendo esta parte de
la consciencia[^69]. Tanto la consciencia como la voluntad, son
elementos relacionados entre sí, manifestados en el "si mismo" en un
nivel o estado diferenciado al del resto de las especies, un estado
enigmático; todos estos son ingredientes del si mismo, que todavía se
están descubriendo y entendiendo. Otra variable hace aún mas complejo el
entendimiento del "si mismo" desde la experiencia subjetiva es la noción
de libertad de acción o el libre albedrío. Es en la manera como se
regula el libre albedrío en la sociedad humana, en gran parte, el
resultado en la regulación de los principios y valores de la
civilización; es en su comprensión esquiva del si mismo donde la verdad
científica entra a formar parte de un gran nudo, sobre el cual la
filosofía y la teología tienen un aporte fundamental. Es en el libre
albedrío, donde la racionalidad autónoma que desde el cerebro de cada
individuo, o en su interpretación de comunidad se pueden generar
conflictos de interés, ya que en la experiencia subjetiva no se aplica
un lenguaje común a todo grupo de interés o individuo tal como debe
suceder con la verdad científica; ni aún la comunidad de la neurociencia
está de acuerdo en la existencia o el significado del libre
albedrío[^70]. Existe en este sentido, otra especie de singularidad
cerebral, tal como en el origen del universo, la ciencia queda con un
reto todavía por descifrar.

Si bien, la ciencia no comprende aún, ni se fundamenta en el aspecto
subjetivo de la consciencia, si hace un aporte continuo y extremamente
valioso, de gran ebullición a partir de la edad media, desde la
experiencia objetiva y la razón, en un lenguaje común, bien comprendido
como expresión de su búsqueda, a una velocidad excepcional en términos
de nuevos descubrimientos y en el complejo laberinto de la mente
entendiendo al cerebro. En dicho laberinto, la mente tiene la capacidad
de abstraerse desde fuera de la verdad científica y posicionarse en el
campo del pensamiento lógico y articulado de la filosofía en un
cuestionamiento también con un valor de pensamiento extraordinario con
el fin de entender y explorar desde otro punto de reflexión el
significado de la experiencia subjetiva[^71].

En la cultura occidental con gran influencia de la naciente filosofía de
la antigua Grecia, se manifestó inicialmente, a través de la filosofía
medieval la consciencia como evidencia de la existencia del individuo,
es parte intrínseca de su verdad individual. Descartes[^72] (La Haye
1596 -- 1650, Estocolmo) manifestó la existencia del si mismo como parte
del saber en su famosa frase "pienso, luego existo"[^73]. En todas las
demás especies de seres vivos sobre la tierra, la capacidad de
razonamiento y de expresión de la consciencia es de menor desarrollo y
complejidad a la del ser humano, incluso algunos investigadores podrían
negar que algunas especies animales tengan consciencia por falta de
evidencia científica, argumentando por ejemplo la imposibilidad del auto
reconocimiento ante un espejo. Desde otra perspectiva filosófica una
posición que admite una barrera infranqueable para entender el nivel o
el estado de consciencia de un animal, o un ser vivo, es que ningún ser
humano es dicho "animal" ni se puede convertir temporalmente en uno para
dar una respuesta objetiva. En la búsqueda de una definición de
consciencia, única, en cualquier ser vivo, incluido el mismo ser humano
se llega a una frontera entre la verdad científica y la verdad
filosófica[^74]; La consciencia tiene características "subjetivas" que
no la hacen igual para todos los seres humanos. Una persona no puede
entender plenamente la consciencia de otro ser humano. Tal vez podría
haber un alto nivel de empatía, entendida como la capacidad de comunicar
o experimentar la emoción o el sentimiento del otro individuo, pero de
hecho un ser humano no puede experimentar la misma consciencia de otro
ser humano, ni mucho menos la de un ser vivo de otra especie. El
carácter de la experiencia subjetiva de la consciencia radica, no solo
en el porqué de su origen, si no en su interpretación; la interpretación
y la posterior comunicación de una emoción o de un sentimiento diferente
al entorno del "si mismo". La capacidad del lenguaje del ser humano y
sus diferentes y variadas formas de expresión son otro aspecto que se
añade en dicho intrincado escenario; el "carácter de subjetividad"
implica que cada persona le dé un significado diferente a la
interpretación de la consciencia de otro individuo, ya que dicha
interpretación será influenciada por la verdad individual en el "si
mismo" de quien hace la interpretación. El juego de descubrir figuras en
las nubes además de la creatividad como parte funcional del cerebro, es
una forma de descubrir diferentes niveles de consciencia ante un mismo
escenario: un niño podrá experimentar sensaciones, y emociones
diferentes a las de otro niño. El "nudo ciego", relacionado a la
definición de los principios y valores al que se enfrenta la verdad
científica es el entendimiento bajo una teoría de comportamiento
infalible, de la experiencia subjetiva como parte de la consciencia , de
manera objetiva y racional , en otro individuo diferente al "si mismo".
Es en este sentido de la consciencia, en la cual la verdad científica se
cuestiona desde la filosofía y la teología en la búsqueda y definición
de la experiencia subjetiva. Una manera de evidenciar aquella
afirmación, es a través de las cualias[^75] como uno de los elementos de
la experiencia subjetiva; este es un camino que además exige entender la
verdad individual que se encierra en la consciencia de cada ser vivo.
Este aspecto es de gran relevancia, puesto que si, un ser humano pudiera
alinear perfectamente su propia verdad individual, con la de los demás
seres humanos, a través de un cimiento único, en dicho caso podría
existir una base sólida para la construcción de los principios y valores
de la sociedad. Sin embargo, está vigente el debate de si la ciencia
moderna podría en un futuro llegar a demostrar que esa posibilidad sea
válida. En caso contrario, como una realidad que cobija el post
modernismo, queda una tarea monumental al individuo para la búsqueda y
edificación de aquel cimiento único, que parte de una verdad absoluta,
incomprendida por la humanidad e inexistente para muchos, puesto que
forma parte del misterio que envuelve al ser humano, tanto en el
conocimiento del si mismo como del universo. Aquel cimiento único es
superior a la limitación de la civilización en el entendimiento de su
consciencia desde la verdad científica. Es desde una perspectiva
teológica y filosófica que se puede encontrar aquel camino marcado por
un amor omnipotente y superior al del amor humano; un cimiento al que se
llega unicamente a través de la fe, constituyéndose en la médula del
mensaje del Cristianismo y que implica la vida espiritual de cada
individuo no reconocida por la definición científica por "lo que hace" o
por "la manera como funciona", pero presente en el misterio del
conocimiento del "ser", desde muchas perspectivas y buscado desde
inicios de la civilización. El misterio, como elemento común a toda
forma de pensamiento humano tiene la capacidad de exasperar al ser
humano y a la civilización, por su incapacidad de entenderle, o por el
contrario cabe la posibilidad de admitirle como parte de su "ser", en
cuyo caso se requiere de la voluntad de asimilar que, por más desarrollo
científico y noción de progreso y bienestar presentes, el misterio
estará siempre marcando los límites del entendimiento. Las cualias, son
una evidencia desde la neurociencia de la incapacidad del ser humano de
desarrollar una comunicación perfecta para entender la verdad individual
y por ende la de un todo social. Son además una razón más para admitir
la debilidad del ser humano para encontrar una verdad absoluta por sus
propios medios; y cuyo vacío existencial, puede terminar en el camino
fácil de la negación o indiferencia de la posibilidad de tan anhelada
verdad.

## La experiencia subjetiva y las cualias

Continuando con la guía de Rodolfo Llinás, la razón principal en las
reflexiones anteriores relacionadas a la manera como se comprende la
mente y el cerebro, es llegar a este punto de encuentro entre la ciencia
y la filosofía para confirmar la imposibilidad de una comunicación
perfecta para el entendimiento de la verdad individual del ser humano
desde su experiencia subjetiva, implicando su incapacidad para conocer
una verdad absoluta partiendo del simple hecho de que si no es capaz de
entender a otro ser humano, mucho menos podría entender una verdad
absoluta: las cualias encuentran desde la ciencia su expresión final
internamente; esta expresión forma parte de lo que conocemos como
experiencia subjetiva, que involucra también el entendimiento de los
sentimientos:"Bien sea una experiencia producida por la activación de
las vías sensoriales debida a estímulos externos, bien por estimulación
experimental eléctrica (o química) en diversas áreas del cerebro, o bien
por acciones iniciadas en el interior como en los sueños.(\...) Al
parecer las cualias se relacionan no solo con neuronas particulares en
sí, sino más aún, con la geometría dinámica de los patrones de actividad
eléctrica que las neuronas son capaces de producir. Aunque la
complejidad de la forma como operan las cualias no ha sido determinada
en su totalidad, la investigación científica ha demostrado que ante
estímulos directos en el cerebro, se puede modificar su experimentación
a nivel de consciencia en un individuo"[^76]. A manera de
experimentación se pueden recrear y modificar sensaciones a partir de
estímulos directos en el cerebro de un individuo que supongamos, le
genera la sensación del color azul, pero entender el "como funciona" no
implica el entender su esencia o su origen. En dicho sentido, la
ciencia, es cuestionada en su capacidad de llegar a entender los
sentimientos como el amor, más allá de sus mecanismos funcionales,
biológicos y químicos. "Continuamente se discute si algún día llegaremos
a comprender en términos científicos un fenómeno tan escurridizo, e
incluso se debate si algún día llegaremos a una explicación hipotética,
basada en procesos físicos-neurales que resulte satisfactoria y
completa".[^77] Desde la neurociencia , Rodolfo Llinás afirma: "Desde el
punto de vista de funcionamiento del cerebro, para mi , las cualias
deben ser la suma final , el aspecto de nuestro yo que se refiere a
-nuestra propia existencia-"[^78]. Sin embargo, a pesar de que pueda
llegar a existir en las próximas décadas un entendimiento perfecto de
cómo operan las cualias y como es su funcionamiento al interior del
cerebro, persiste la gran inquietud de si con entender su función mental
, se logra tener la capacidad de entender plenamente la consciencia del
otro diferente al "si mismo" de manera "objetiva" y aún mas lejos está
todavía la posibilidad de descifrar la esencia de la voluntad o el libre
albedrío y la conciencia de lo moral, más allá de los elementos
funcionales y biológicos que la componen.

Si el cerebro humano no está en capacidad de lograr la vivencia, de
entendimiento cognitivo perfecto de la verdad individual "del otro", de
su experiencia subjetiva, entonces sería imposible construir un modelo
racional de principios y valores que involucre la experiencia subjetiva
de cada ser humano para una alineación social común, exclusivamente
desde el conocimiento del cerebro. El nudo ciego, para definir
principios y valores en el ser humano, no se podría desatar solo desde
un proceso mental exclusivo del cerebro.

Desde la perspectiva filosófica, en una búsqueda del entendimiento del
"ser", existen también argumentos sólidos que confirman lo que la
ciencia ya viene admitiendo.

Thomas Nagel (Belgrado, Yugoslavia - 1934)[^79] en su ensayo (1974) ¿
Que se siente ser un murciélago ?[^80] no se refiere directamente al
término cualias, pero aborda la cuestión de la experiencia subjetiva. Su
trabajo es una expresión de la dimensión y complejidad subjetiva de la
consciencia en el ser humano. Para Nagel, la definición sobre el
carácter subjetivo de la consciencia está sujeto a que un organismo debe
tener algo que lo determine a "ser" ese organismo (de cualquier
especie), un condicional para que dicho organismo pueda tener diferentes
estados mentales conscientes. En esta definición, la subjetividad va más
allá de la definición de sensación o de estados funcionales de la
expresión de estados conscientes. No tenemos idea en que consiste dicho
carácter subjetivo (algo) de la experiencia de la consciencia de un
organismo debido a que lo conectamos a un solo punto de vista, el punto
de vista del ser humano; el punto de vista de su cerebro, de su
capacidad mental. Thomas Nagel profundiza en su explicación tomando al
Murciélago como referente. Este mamífero se determina a "si mismo" por
el hecho de que tiene experiencia; pero su experiencia sensorial para
comprender el mundo es incomprensible para el ser humano ya que se
fundamenta en el sonar o ecolocación, que puede identificar las
características de un árbol, de acuerdo al reflejo en altas frecuencias
de sus sonidos percibidas por sus órganos sensoriales e interpretadas
por su cerebro. Ciertamente, incomprensible en este caso no se refiere a
que no conozcamos la mecánica de funcionamiento del cerebro del
murciélago, como lo hace la ciencia, si no que el ser humano no tiene la
capacidad de vivir la experiencia del murciélago ya que no lo "es"; pero
si puede imaginarlo aunque únicamente bajo las limitaciones que le
ofrece su propia experiencia, bajo las sensaciones y estados de
consciencia propias del ser humano. De esta forma la imaginación aunque
podría ser una aproximación, no es una realidad. El punto central es que
un ser humano podría imaginar "yo (ser humano) siendo un Murciélago"
pero no un "Murciélago siendo un Murciélago". Hace falta el algo que
permita vivir esa experiencia subjetiva. Las experiencias conscientes
tienen en cada caso un componente subjetivo sobre el cual podemos
descubrir, describir y hasta manipular de manera experimental su
funcionamiento, pero no la podemos concebir o comprender en toda la
magnitud, en la realidad interna del ser que lo experimenta. Esta
explicación aplica también para el caso entre organismos de una misma
especie. Dos personas podrán tener una alta empatía, entender e imaginar
los sentimientos o la experiencia consciente del otro; pero el carácter
subjetivo de la experiencia del otro no se podrá concebir o entender en
toda la magnitud de su realidad. Ni siquiera el lenguaje con sus
diferentes matices y alcances lo pueden hacer en ningún proceso de
comunicación, por avanzado que este sea. El lenguaje no puede expresar
lo que siente una persona ciega de nacimiento frente a su experiencia de
los objetos de color "rojo". La misma naturaleza propia del ser humano,
como especie con una capacidad de inteligencia racional monumental, no
le permite entender en esencia las cualias o la experiencia subjetiva
plenamente hasta que no se desarrolle un método o una teoría que permita
pensar en ello.

## Un punto de vista

Uno de los argumentos de Thomas Nagel, en referencia al entendimiento de
las cualias o de la experiencia subjetiva radica en la dificultad de que
el ser humano solo pueda entender o generar el conocimiento requerido a
partir de su propio cerebro, diseñado a través de sus funciones mentales
para sobrevivir mediante las decisiones adecuadas. La evolución del
cerebro humano ha llegado a todas luces mucho más lejos; ha desarrollado
la verdad científica para generar bienestar a partir de descubrimientos
y aplicaciones científicas como las ya descritas; ha generado
conocimiento para entender el cosmos y muchos otros misterios sobre la
civilización humana. Pero, si la verdad científica tiene su cimiento en
la capacidad de predicción y entendimiento de su entorno, como un evento
externo al ser humano a partir del cerebro, ¿ será la metodología
científica capaz de explicar la experiencia subjetiva como un evento
interno del ser humano, a tal punto que pueda predecir el comportamiento
desde la consciencia de cada individuo? o ¿ podría llegar a entender la
esencia de la voluntad en el ser humano ?. El estudio del cerebro
humano, su capacidad mental y la metodología científica no tienen una
respuesta sobre estas cuestiones, que pasan a ser parte del misterio en
la búsqueda de la verdad desde la ciencia. Los mismos científicos, como
seres humanos en su naturaleza, no están de acuerdo en la respuesta;
quienes bogan por un ser humano cuya consciencia y voluntad pueden ser
decifrados desde la causalidad molecular, están en el campo de a
filosofía cientifica o materialismo científico,[^81]que nada tiene que
ver con el método científico; también están los que han hecho de la
ciencia una religión o una ideología[^82], o los científicos que
practican alguna religión de manera coherente con su profesion, entre
ellos una larga lista de científicos cristianos de todos los
tiempos[^83]. Por consiguiente, el mismo razonamiento lógico, que nace
del cerebro y la mente humana, creadora de la metodología científica
puede determinar en el si mismo, la imposibilidad del diseño científico
como el único punto de vista para el conocimiento de un cimiento único
exclusivamente racional y empírico de principios y valores que esté
unificado en la consciencia de todos los individuos de la especie
humana. Si imagináramos una solución a esta situación, estarían las
ciencias humanas en la búsqueda de algo similar a una teoría del todo a
nivel de la consciencia humana; también con un gran componente de
experiencia subjetiva en la realidad de cada ser humano, en su verdad
individual. Entre muchas definiciones de aquella búsqueda, el filósofo
Aleman Friedrich Nietzsche [^84] (Röcken, 1844 -- 1900,Weimar) acude en
este sentido al desarrollo del "perspectivismo", este punto de vista
ampliamente debatido en su doctrina filosófica, en el la cual no hay
hechos objetivos. En dicho caso, la objetividad, se logra a partir de la
diversidad subjetiva o desde múltiples perspectivas; pero los
detractores de esta posición advierten que aún la diversidad subjetiva
no implica la verdad como en el caso de aquella falacia que afirma que
"trillones de moscas no pueden estar equivocadas". A diferencia de
Nietzsche, en el presente contexto la experiencia subjetiva forma parte
de una verdad individual, sobre la cual, el si mismo está en una
permanente búsqueda consciente a través de la fe, de la existencia de
una verdad absoluta, que trasciende la capacidad del entendimiento del
ser humano; una fe que va más allá de una definición en la simple
emoción o sentimiento y que implica el reto y la frustración de dicha
búsqueda, aceptando el misterio como parte de la realidad humana, un
misterio que está presente en la verdad científica, pero también en
otras formas de razonamiento, como la filosofía y la teología.

## La verdad individual

El avance de la tecnología en las comunicaciones y el nuevo mundo de la
información desarrollado desde la verdad científica, no podría llegar a
un estado en el cual dos seres humanos pudieran entender completamente
la verdad individual de cada uno de ellos. La verdad científica nació de
hechos deterministas; aquellos eventos medibles y que no dan lugar a
especulación. Son el cimiento de la ciencia experimental de Newton y que
gobiernan gran parte de la vida diaria de la humanidad. Este aspecto
determinista de la verdad individual ha llevado a la concepción de un
lineamiento filosófico que en la cultura occidental tuvo sus primeras
manifestaciones en los pensadores de la antigua Grecia (Siglo IV a.c)
[^85], siendo esta una corriente que se fue estrechando en la edad
media, hasta llegar a un plano de explicación puramente objetivo y
racional, del sentido y esencia de la vida en el ser humano, filosofía
soportada y revitalizada por varios filósofos[^86] de la edad media;
dicha corriente de pensamiento ha sido también el sustento para la
definición de los principios y valores que entran a regir la naturaleza
del progreso moderno y del mundo contemporáneo. Pero, la evolución de la
verdad científica también parte de hechos indeterministas; aquellos
eventos probables, que gobiernan la física cuántica y que en la
tecnología contemporánea desempeñan un papel fundamental en la vida
diaria. La verdad científica, en términos de validación experimental y
en su metodología, se basa en la aproximación de la capacidad del
pensamiento racional humano unido en estos dos tipos de eventos reales:
deterministas e indeterministas.

Desde la verdad científica y el pensamiento racional la búsqueda
continuará hasta encontrar, si es posible, esa teoría, bajo un evento
experimental , que le permita al individuo desde su verdad entender ese
algo de su comportamiento en su consciencia subjetiva, en su conciencia
moral y en su voluntad, que no se conoce; y que, aún , si existiese
dicho entendimiento, tendría que desarrollar la capacidad de
comunicación perfecta, para dar a conocer a otro individuo de manera
precisa su realidad subjetiva.

La interpretación de la verdad individual en términos relativos a cada
ser humano, no tiene un marco de aceptación general como si lo tiene la
metodología científica. Pero, dicha verdad es una realidad en cada ser
vivo y en la que el ser humano se siente fuertemente impulsado a
entender. Esta frontera entre el razonamiento y la imaginación desde la
naturaleza humana no es el único camino en la búsqueda del entendimiento
de la verdad individual. Ante esta situación, el individuo, podría
decidir de manera radical sentarse en la verdad científica como única
alternativa para el entendimiento de la verdad individual a partir del
estudio de la materia; podría encaminarse a complementar dicha búsqueda
desde el plano filosófico, o podría estar abierto a la búsqueda desde un
camino teológico, que implica la religión y la fe que le alimenta en su
espiritualidad; o podría hacerlo desde una combinación de dichos
caminos, asumiendo sus limitaciones como ser humano frente al misterio.
Bajo dicha premisa y dado el contexto expresado en capítulos anteriores,
se hace necesario resaltar que existe una verdad individual con origen
biológico en un "si mismo" definido desde la verdad científica y
filosófica de manera parcial. La verdad individual encierra toda la
dimensión del "ser" de cada individuo y puede ser transmitida de manera
parcial a otro individuo mediante el lenguaje y sus alternativas de
comunicación como parte de su experiencia subjetiva en el "sentir" de
cada individuo; es una verdad que busca ser experimentada desde todas
las alternativas que nos ofrece la naturaleza humana; una verdad que es
la fuente de inspiración de manera "voluntaria" de millones de seres
humanos para intentar transmitir aquel "sentir" desde sus propias
sensaciones, emociones y sentimientos a través de un lenguaje subjetivo,
como el arte, la poesía, la música y todo aquello que le complementa,
que incluso, a veces sustituye el lenguaje sobrio y racional. El arte es
un intento del ser humano de dar a entender su verdad individual; un
complemento del lenguaje imperfecto, que en diversas instancias comunica
la cultura de una generación o de una sociedad. El conocimiento de la
verdad individual es de importancia vital en la construcción de la
sociedad y de la comunidad; puesto que si no existe la manera de alinear
la verdad de millones de individuos bajo "algo" que tenga un sentido
unificador, con un fin aceptado de manera universal, entonces, cada
individuo edificará sobre su propia interpretación de la verdad o la de
su grupo de interés. Los principios y valores estarían siempre
condicionados y limitados por la interpretación de la verdad de un
individuo o de un grupo de individuos, entrando así en un interminable
ciclo de auto adjudicaciones de la verdad; creando así los efectos de la
dominación de unos a otros, de unas comunidades a otras. No es difícil
advertir dicha circunstancia en la historia de la civilización. Dicho
ciclo podría encontrar su fin, si los principios y valores pudieran
tener su origen en la existencia de un cimiento único, capaz de
interpretar entre millones de individuos, aspectos comunes que permitan
llegar a acuerdos en la definición de un modelo de principios y valores
universalmente aceptados.

El ser humano es el único que explora su propia verdad individual y que
intenta entender el "si mismo"; el ser humano es la única especie que
hace un gran esfuerzo para que su propia verdad individual sea
comprendida por otro ser humano, e incluso intenta comprender la verdad
individual de otras especies, diferentes a la propia. El ser humano es
la única criatura que "trasciende", más allá de su capacidad racional y
mental, en la búsqueda de su verdad individual, desde su experiencia y
verdad subjetiva, incluso, más allá de la vida como la conoce y la
experimenta con el fin de dar sentido a su existencia. El ser humano es
la única especie que constantemente se cuestiona , acumulando el
conocimiento y la experiencia , generación tras generación y a través
los siglos para entender su propia verdad individual y la de su
comunidad, expresada en múltiples y variados rasgos culturales , con
cuestionamientos sobre el significado de la vida y la muerte en el "si
mismo" y en la vida en sociedad. Esa capacidad de trascender en el
entendimiento de su verdad individual, le lleva al la búsqueda y el
entendimiento de una verdad aceptada por la comunidad y por la sociedad,
es la capacidad que le lleva a la búsqueda desde otras instancias de
respuestas que la verdad científica aún no tiene, es la búsqueda de una
verdad absoluta, que para muchos es un imposible. Es la búsqueda que
admite una alternativa a la exasperación existencial, el reconocimiento
de aquel cimiento único que parte de tal verdad misteriosa, columna
vertebral en la construcción de los principios y valores de la
humanidad. Uno de los caminos que ha marcado la historia del ser humano
para dar respuesta a estas inquietudes es a través de las diferentes
religiones, estudiadas por la teología. Es aquí donde el "si mismo" está
enmarcado en un contexto diferente, construido en diversas culturas
milenarias, de acuerdo a las experiencias de sus comunidades y
sociedades, dando cabida e intentando comprender el sentido subjetivo de
su propia verdad. A diferencia de las ciencias y de la filosofía
contemporáneas[^87] que exaltan sus virtudes bajo marcos de pensamiento
que niegan la posibilidad de trascender el mundo natural para la
explicación y el sentido de la existencia humana, la religión Cristiana
lo hace admitiendo la posibilidad de una existencia sobrenatural, una
existencia superior al ser humano, en la que se reconoce su debilidad en
el entendimiento de una verdad absoluta por sus propios medios, entre
otras, por su capacidad mental limitada en el mapa funcional de su
propio cerebro; pero ello conlleva a un esfuerzo propio de la naturaleza
humana y de ningún otro ser y es la "fe", más allá de una definición
biológica en la emoción o el sentimiento; es la fe la que da la
posibilidad al conocimiento de aquel cimiento único, entendida más allá
de un simple mito o superstición como parte de la experiencia subjetiva
del si mismo.

## Corolario I

Recapitulando, hemos recorrido como desde el cerebro humano, el órgano
resultado de la selección natural, que ha permitido sobrevivir a la
especie humana entendiendo y proyectando el medio ambiente en el que
sobrevive, inicialmente mediante la predicción de la movilidad y luego a
través de la ciencia, el ser humano, desde su facultad racional, intenta
comprender no solo los misterios de la cosmología y del universo, si no
los misterios que encierra cada individuo en la definición de su verdad
individual y de su consciencia, de sus principios y valores como insumos
requeridos para la construcción de la civilización. Esta búsqueda que
trasciende a cada individuo, ha evolucionado a través de la filosofía,
incluso antes que la ciencia, como pensamiento racional, cuestionando el
único punto de vista como expresión del cerebro humano. En el trayecto
que sigue, se acudirá a la posibilidad de la trascendencia como
alternativa a su negación. Ese "algo" o ese "vacío" racional, que es
admitido como misterio consciente, pero que admite la posibilidad de una
verdad absoluta que se sostiene en un cimiento único, hace que cada ser
humano busque y entienda su propio "ser" y el de su comunidad en un
contexto más complejo; una dimensión que no cabe en su totalidad en la
verdad científica y su metodología aplicada a la materia, pero que
apunta hacia la búsqueda de la misma verdad absoluta. Esta búsqueda del
ser humano se basa en la teología como fuente de búsqueda de respuestas
que no se han podido encontrar a través de la verdad científica ni
filosófica. En el contexto de la teología, la búsqueda de la verdad es
extrapolada más allá de la mente entendiendo al cerebro; es una búsqueda
que parte de un un ser humano que en su integridad, en el si mismo, es
mucho mas complejo que lo que la verdad científica ha podido identificar
y que se niega a definirse solo como un cerebro con una función mental.
Y como intuyeron los científicos en la conferencia de Solvay, es la
religión, como expresión teológica, desde la verdad individual y social,
con la fe como manifestación de su experiencia objetiva y subjetiva, la
que ha sostenido las columnas de la ética, la moral y los principios y
valores que han guiado la civilización humana, con sus aspectos
positivos y negativos y su visión de progreso hasta nuestros días.



[^1]: ¿ Are we on the road of civilisation collapse ? , Luke Kemp,
    investigación sobre riesgo existencial de la universidad de
    cambridge, 2017,
    <https://www.bbc.com/future/article/20190218-are-we-on-the-road-to-civilisation-collapse>

[^2]: Los principios gobiernan lo que se considera como moralmente
    correcto e incorrecto, el derecho a la vida o la libertad, son los
    pilares inamovibles que indican el camino a seguir por el individuo
    y la sociedad; los valores, están en armonía con los principios y
    describen la forma de actuar; una persona honesta tiene el gran
    valor de guardar fielmente el dinero de otra persona, aún
    desconocida.
    <https://psicologiaymente.com/social/diferencias-entre-valores-y-principios>

[^3]: Proyecto de investigación y desarrollo de las primeras armas
    nucleares <https://es.wikipedia.org/wiki/Proyecto_Manhattan>

[^4]: Bulletin of the Atomic Scientists.
    [https://thebulletin.org/doomsday-clock/current-time/#](https://thebulletin.org/doomsday-clock/current-time/)

[^5]: Biografía de Albert Einstein, físico premio nobel quien desarrolló
    la teoría de la relatividad, base de la física moderna.
    [https://www.Biografíasyvidas.com/monografia/einstein/](https://www.biografiasyvidas.com/monografia/einstein/)

[^6]: Biografía de Niels Bohr, físico premio novel quien se destacó por
    su investigación sobre la estructura de los átomos y la radiación
    que emana de ellos
    <https://www.biografiasyvidas.com/biografia/b/bohr.htm>

[^7]: Este principio marca un límite entre la física clásica y la física
    cuántica; esta última se describe en términos de "cuantos" o
    paquetes de energía, por lo que a cada estado estacionario de un
    átomo le corresponde todo un numero de parámetros que especifican la
    probabilidad de transición de dicho estado a otro. Es decir, se
    pierde la "exactitud" de la física clásica.- Los sueños de los que
    está hecha la materia, El desarrollo de la mecánica cuántica ,
    Werner Heisenberg, páginas 330-343.

[^8]: Biografía de Werner Heisenberg, físico Alemán que formuló el
    principio de incertidumbre

    <https://www.biografiasyvidas.com/biografia/h/heisenberg.htm>

[^9]: Por Werner Heisenberg, Conversation: Science and religion
    <https://www.edge.org/conversation/werner_heisenberg-science-and-religion>

[^10]: Biografía de Isaac Newton , fundador de la física clásica
    <https://www.biografiasyvidas.com/biografia/n/newton.htm>

[^11]: ¿ En realidad que es la gravedad ?
    <https://spaceplace.nasa.gov/what-is-gravity/sp/>

[^12]: Segunda Ley de la Termodinámica y Entropía
    <https://www.fisicalab.com/apartado/segundo-principio-termo>

[^13]: ¿ Que es la energía oscura y la materia oscura ?
    <https://spaceplace.nasa.gov/dark-matter/sp/>

[^14]: El mismo efecto del sonido que se percibe en una motocicleta
    cuando se acerca y se aleja de un observador, se refleja en los
    colores de las estrellas, de acuerdo a su velocidad y dirección de
    desplazamiento.

[^15]: ¿Que es un agujero negro ?
    <https://spaceplace.nasa.gov/black-hole-rescue/sp/>

[^16]: Recientes experimentos cuestionan la validez del modelo estándar,
    a través del cual se ha modelado con bastante perfección durante las
    últimas décadas las leyes de la física cuántica; eso podría implicar
    un desafío para la comunidad científica en un futuro inmediato,
    puede ser el descubrimiento de algo completamente desconocido en
    relación a las leyes que gobiernan el universo.
    [https://www.europapress.es/ciencia/laboratorio/noticia-experimento-desafia-modelo-estándar-fisica-particulas-20210323112121.html](https://www.europapress.es/ciencia/laboratorio/noticia-experimento-desafia-modelo-estandar-fisica-particulas-20210323112121.html)

[^17]: ¿Que es el Big Bang? <https://spaceplace.nasa.gov/big-bang/sp/>

[^18]: Alexander Friedman propuso tres modelos del universo entre 1922 y
    1924; Lemaitre confirmó en 1927 el modelo de expansión del universo
    y Edwin Hubble en 1929 lo ratificó con sus observaciones. Biografía
    de Georges Lemaitre
    <https://www.biografiasyvidas.com/biografia/l/lemaitre.htm>

[^19]: Desde el tiempo cero hasta el tiempo 10^-43^ segundos.
    [https://es.wikipedia.org/wiki/%C3%89poca_de_Planck](https://es.wikipedia.org/wiki/Época_de_Planck)

[^20]: Hipótesis milenarios, que implican la existencia de muchos
    universos, posiblemente en estados paralelos
    <https://www.quimica.es/enciclopedia/Universos_paralelos.html>

[^21]: Las Teoría de cuerdas se basan en estados vibracionales de la
    materia, no en partículas.
    https://www.investigacionyciencia.es/revistas/investigacion-y-ciencia/neurociencia-de-los-hbitos-606/teora-de-cuerdas-12292

[^22]: Un universo que nace de las leyes de la física y la fuerza de la
    gravedad a partir de "la nada", es la posición de dos científicos de
    gran trayectoria , Stephen Hawkins y Leonard Mlodinov en su libro
    "El Gran Diseño".

[^23]: Teoria del campo unificado
    [https://www.quimica.es/enciclopedia/Teor%C3%ADa_del_campo_unificado.html](https://www.quimica.es/enciclopedia/Teoría_del_campo_unificado.html)

[^24]: Partículas u ondas que constituyen los fenómenos
    electromagnéticos.

[^25]: ¿ Que dice la teoría inflacionaria sobre el universo?
    <https://www.universidadviu.com/es/actualidad/nuestros-expertos/que-dice-la-teoria-inflacionaria-sobre-el-universo>

[^26]: Biografía Alan Guth <https://physics.mit.edu/faculty/alan-guth/>

[^27]: Foto del universo primitivo realizado por el telescopio PLANCK de
    Agencia Espacial Europea
    [https://www.i-cpan.es/es/content/planck-desvela-la-fotograf%C3%ADa-m%C3%A1s-detallada-del-nacimiento-del-universo](https://www.i-cpan.es/es/content/planck-desvela-la-fotografía-más-detallada-del-nacimiento-del-universo)

[^28]: Desde la década de los 90 se realizan en diversos lugares del
    mundo investigaciones de tipo experimental. El proyecto BICEP
    comenzó investigaciones del 2006 al 2008 , el BICEP2 es una
    continuación del mismo
    <https://lweb.cfa.harvard.edu/CMB/bicep2/science.html>

[^29]: El origen de la materia
    <https://www.investigacionyciencia.es/revistas/investigacion-y-ciencia/la-geodinamo-399/el-origen-de-la-materia-4337>

[^30]: ¿Que forma tiene el universo ?
    <https://www.investigacionyciencia.es/noticias/qu-forma-tiene-el-universo-un-nuevo-estudio-mantiene-que-estbamos-muy-equivocados-17989>

[^31]: ¿ Si el universo actual es de 14 billones de años luz, como es
    posible observar objetos a 47 billones de años luz de distancia ?
    <http://www.astro.ucla.edu/~wright/cosmology_faq.html#DN> Edward L.
    (Ned) Wright , obtuvo su grado PhD en astronomía de la universidad
    de Harvard en 1976. Luego de enseñar en el departamento de Física de
    MIT, ha sido profesor en UCLA desde 1981.

[^32]: ¿ Donde está el centro del Big Bang ?
    <http://www.astro.ucla.edu/~wright/nocenter.html> Edward L. (Ned)
    Wright , obtuvo su grado PhD en astronomía de la universidad de
    Harvard en 1976. Luego de enseñar en el departamento de Física de
    MIT, ha sido profesor en UCLA desde 1981.

[^33]: ¿ What might be speeding up the universe expansion
    ?<https://www.quantamagazine.org/why-is-the-universe-expanding-so-fast-20200427/>

[^34]: Biografia de Andrónico de Rodas
    <https://www.biografiasyvidas.com/biografia/a/andronico_de_rodas.htm>

[^35]: Biografía de Aristóteles
    <https://www.biografiasyvidas.com/monografia/aristoteles/>

[^36]: 80 años del entrelazamiento cuántico de Einstein, Podolsky y
    Rosen
    <https://www.scientificamerican.com/espanol/noticias/ochenta-anos-del-entrelazamiento-cuantico/>

[^37]: ¿Que son los cubits?
    <https://platzi.com/tutoriales/1098-ingenieria/1521-que-son-los-cubits/>

[^38]: Gordon Moore: <https://es.wikipedia.org/wiki/Gordon_Moore>

[^39]: La ciencia que manipula la materia a una escala molecular para
    resolver problemas
    <https://www.genome.gov/es/genetics-glossary/Nanotecnologia>

[^40]: Escala medida en nanómetros. Un nanómetro es una millonésima
    parte de un milímetro.

[^41]: A cuatro décadas de la primera concepción in vitro
    <http://www.scielo.org.mx/scielo.php?script=sci_arttext&pid=S0301-696X2018000400363>

[^42]: Salk News: "New findings highlight promise of chimeric organisms
    for science and medicine" ,
    <https://www.salk.edu/news-release/new-findings-highlight-promise-chimeric-organisms-science-medicine/>

[^43]: Milestone Pig-to-Human Heart Transplant May Pave the Way for
    Broader Trial, Scientifican American, Octubre 2023
    [https://www.scientificamerican.com/article/milestone-pig-to-human-heart-transplant-may-pave-the-way-for-broader-trial/#:\~:text=In%20January%202022%20Griffith%20and,failed%2C%20and%20he%20passed%20away.](https://www.scientificamerican.com/article/milestone-pig-to-human-heart-transplant-may-pave-the-way-for-broader-trial/#:~:text=In January 2022 Griffith and,failed%2C and he passed away.)

[^44]: MIT Technology Review :
    <https://www.technologyreview.com/2018/11/25/138962/exclusive-chinese-scientists-are-creating-crispr-babies/>

[^45]: Las cinco preguntas más importantes sobre CRISPR
    <https://www.investigacionyciencia.es/noticias/las-5-preguntas-ms-importantes-sobre-crispr-cas9-17711>

[^46]: Our world in Data, Life expectancy:
    <https://ourworldindata.org/life-expectancy#life-expectancy-has-improved-globally>
    -- World Population Growth
    <https://ourworldindata.org/world-population-growth#all-charts-preview>

[^47]: The number of people in extreme poverty
    <https://ourworldindata.org/extreme-poverty>

[^48]: De animales a Dioses, Yuval Noah Harari, página 21.

[^49]: Biografía de Yuval Noha Harari
    <https://www.ynharari.com/es/acerca-de-2/>

[^50]: De animales a Dioses, Yuval Noah Harari,página 35.

[^51]: Charles Darwin: <https://es.wikipedia.org/wiki/Charles_Darwin>

[^52]: "El Cerebro y el Mito del Yo", Rodolfo Llinás, página 20-23

[^53]: Biografía de Carl Sagan
    <https://es.wikipedia.org/wiki/Carl_Sagan>

[^54]: "Cosmos", Carl Sagan, paginas 276 - 277

[^55]: Scientifican American, "What makes our brains special ?", Diana
    Kwon.
    <https://www.scientificamerican.com/article/what-makes-our-brains-special/>

[^56]: Frontiers in Human Neuroscience: "The human brain in numbers: a
    linearly scaled-up primate brain", Suzana Herculano-Houzel
    <https://www.frontiersin.org/articles/10.3389/neuro.09.031.2009/full>

[^57]: "El cerebro y el Mito del Yo", Rodolfo R.Linás , páginas 25 --
    59,

[^58]: Biografía de Rodolfo Llinás
    <https://es.wikipedia.org/wiki/Rodolfo_Llinás>

[^59]: Las neuronas en el cerebro, se pueden comunicar entre si, en un
    mismo periodo de tiempo.

[^60]: "El Cerebro y el Mito del Yo", Rodolfo Llinás, página 147.

[^61]: "El Cerebro y el Mito del Yo", Rodolfo Llinás, página 67.

[^62]: "El Cerebro y el Mito del Yo", Rodolfo Llinás, página 64.

[^63]: "Robust prediction of individual creative ability from brain
    functional connectivity", Proceedings of the National Academy of
    Sciences of the United States of America- PNAS.
    <https://www.pnas.org/content/115/5/1087>

[^64]: La declaración sobre la consciencia de Cambridge, Julio 7 de
    2012.
    [https://www.animal-ethics.org/declaracion-consciencia-cambridge/#:\~:text=La%20Declaraci%C3%B3n%20fue%20proclamada%20de,por%20Low%2C%20Edelman%20and%20Koch.](https://www.animal-ethics.org/declaracion-consciencia-cambridge/#:~:text=La Declaración fue proclamada de,por Low%2C Edelman and Koch.)

[^65]: Schaefer, D. O. (2012). Do Animals Have Religion?
    Interdisciplinary Perspectives on Religion and Embodiment.
    Anthrozoös, 25(sup1), s173--s189.
    [https://doi.org/10.2752/175303712X13353430377291](../Ciencia_religión/Schaefer,%20D.%20O.%20(2012).%20Do%20Animals%20Have%20Religion%3F%20Interdisciplinary%20Perspectives%20on%20Religion%20and%20Embodiment.%20Anthrozoös,%2025(sup1),%20s173–s189.%20https://doi.org/10.2752/175303712X13353430377291)

[^66]: "El Cerebro y el Mito del Yo", Rodolfo Llinás, página 72.

[^67]: "El Cerebro y el Mito del Yo", Rodolfo Llinás, página 192.

[^68]: PAF, Patrones de acción fijos; responsables de las reacciones
    automáticas, no requieren ser pensadas, como inclinar la cabeza para
    escuchar mejor un sonido débil.

[^69]: La Conciencia, con \"c\", se refiere al conocimiento moral y
    ético de lo que está bien y mal, mientras que consciencia, con
    \"sc\", se refiere a la capacidad de percibir la realidad y
    reconocerse en ella, incluyendo aspectos sensoriales y emocionales.

[^70]: Free will is only an illution if you are, too. Scientifican
    American, Jan 16 2023
    <https://www.scientificamerican.com/article/free-will-is-only-an-illusion-if-you-are-too/>

[^71]: Otros aportes surgen desde la filosofía de la fenomenología
    trascendental desarrollada por Edmund Husserl (República Checa 1859
    -- 1938 ); en la cual se hace referencia a una explicación racional
    del carácter subjetivo de la experiencia humana.
    <https://www.biografiasyvidas.com/biografia/h/husserl.htm>

[^72]: Biografía de Rene Descartes
    <https://www.biografiasyvidas.com/biografia/d/descartes.htm>

[^73]: Principio en latín de la filosofía Racional de René Descartes,
    "Cogito ergo, sum" en el "Discurso del Método" 1,637; la traducción
    literal el latín puede ser también "pienso, por lo tanto soy".

[^74]: La verdad filosófica es un tema de gran amplitud y profundidad de
    pensamiento pertinente a varias corrientes filosóficas; ya que el
    mismo cerebro lo permite, se acudirá tan a una fuente que cuestiona
    la verdad subjetiva en los términos de la explicación racional.

[^75]: Cualias o Qualias, cualidades subjetivas de las experiencias
    individuales. Aunque este concepto todavía está siendo debatido en
    su significado, para el contexto del presente documento se hacer
    referencia a la experiencia subjetiva de cada individuo.
    <https://es.wikipedia.org/wiki/Qualia>

[^76]: "El Cerebro y el Mito del Yo", Rodolfo Llinás, páginas 243-244.

[^77]: "El Cerebro y el Mito del Yo", Rodolfo Llinás, páginas 245.

[^78]: "El Cerebro y el Mito del Yo", Rodolfo Llinás, página 258.

[^79]: Thomas Nagel , filósofo de la mente en el pensamiento
    post-moderno <https://www.infoamerica.org/teoria/nagel1.htm>

[^80]: Ver documento completo ¿Que se siente ser un murciélago ?:
    <https://pdfs.semanticscholar.org/3c41/da79e03876d1cf69f5784e880aabd4844c91.pdf>

[^81]: Materialismo científico
    <https://es.wikipedia.org/wiki/Materialismo_científico>

[^82]: Definición del cientificismo
    <https://www.unav.edu/web/ciencia-razon-y-fe/cientificismo-positivista-y-ciencia-positiva-hoy#b>

[^83]: The society of catholic scientists
    [https://catholicscientists.org](https://catholicscientists.org/)

[^84]: Biografía de Frederich Niestzsche
    <https://www.biografiasyvidas.com/biografia/n/nietzsche.htm>

[^85]: La filosofía de Aristóteles, continuación de la filosofía de
    Sócrates y Platón postula al hombre como sujeto de la razón y del
    alma. Aristóteles puede ser considerado como el primer investigador
    científico en el estricto sentido de la palabra.
    <https://www.biografiasyvidas.com/monografia/aristoteles/>

[^86]: En esta línea de pensamiento están Rene Descartes (Suecia, 1596 -
    1650), Baruc Spinoza (Holanda , 1632 -- 1677), Immanuel Kant (Rusia
    , 1724 -- 1804), Friedrich Nietzsche (Alemania, 1844 -- 1900) entre
    otros.

[^87]: En el marco de la filosofía contemporánea se ha excluido la
    posibilidad de Dios en la mayoría de los casos, excepto por aquellas
    filosofías que se derivan de alguna religión.
