---
title: "Parte 5"
format:
  html:
    toc: true
    toc-depth: 5
    number-sections: false
    theme: cosmo
    css: styles.css
---
# **CAPÍTULO V**

## La iglesia Cristiana

No tendría sentido el ejercicio de la razón en la fe, el definir el amor
o la maldad, la santidad de la Virgen María, la concepción de la sagrada
familia o una miríada de aspectos teológicos Cristianos, si su punto
departida en la fe se dejara a cargo del ser humano, como en cualquier
grupo de interés. Todo acto de fe humano, como la aceptación de una
fecha de cumpleaños que surge de la confianza en sus progenitores o
familiares, pero podría estar equivocada, ya que el ser humano no es
perfecto. Sin embargo, si la confianza está en Dios mismo, no es
factible ninguna forma de error. La fe de los primeros seguidores de
Jesús, es reflejada y transmitida a través de la gracia del Espíritu
Santo con la misma transparencia, en todos los seguidores de Jesús y en
todo tiempo histórico; y esto solo ha sido posible porque la fe ha sido
abrazada de manera contundente, como un regalo de Dios mismo, regalo que
puede ser asumido con libre albedrío y la voluntad asertiva de quien
desea escudriñar aquel mensaje de salvación del corazón encontrando el
corazón. La fe surge de la confianza en Jesús, en quienes fueron
instruidos por Él; y aquellos portadores de su enseñanza, los apóstoles
con su mensaje y acciones construyen la iglesia con la transmisión de
una tradición custodiada durante dos milenios; la fe y la tradición son
complementadas por las sagradas escrituras representadas en la Biblia.
Los tres componentes son un trípode en el que se sostiene la religión
Cristiano Católica: sobre la fe, sustentada en el amor divino ya se han
expuesto argumentos, en adelante se extenderá el ejercicio de la razón a
la doctrina de la iglesia Católica constituida también a partir de la
tradición de la comunidad Cristiana, la que adquiere vigor al tener su
guía en la Biblia, considerada por la teología Cristiana como la palabra
de Dios. Tanto fe, como tradición y el mensaje Bíblico apuntan a una
misma verdad absoluta. Incluso cuando el ejercicio de la razón suena en
el mundo actual como el camino válido para el encuentro con Dios, se
debe dejar en claro que no deja de ser un sofisma seguir el dogma
Cristiano como un camino suficiente para relacionarse con Jesucristo. El
dogma, es solo un medio de entendimiento de la fe Cristiana, el cual
tiene un valor secundario, pero importante. El verdadero y necesario
camino es el crecimiento en el amor, solo en el amor que se paga con
amor, el amor que no espera recompensa desde la acción en la caridad, el
amor como "alimento espiritual" que llega si se decide amar a Jesucristo
estableciendo una relación objetiva y directa con Él, a través de la
oración y en el silencio de la manera en que Jesus, siendo Dios mismo,
lo ha enseñado al mundo. Muchos Cristianos lo entienden así, sin
preocuparse por las profundidades del dogma, puesto que como los
primeros Cristianos, no caen en el fideísmo de una fe ciega, sino
acudiendo a la sensatez del sentido común tallado en el alma y que
florece como sabiduría al intentar ser imagen de Jesús. El sentido de la
doctrina Cristiana es un legado importante de la historia del
Cristianismo, el cual termina estableciendo una columna vertebral que
unifica la descripción y entendimiento de la fe, hasta donde el misterio
lo permite como sucede en la ciencia moderna; fe sustentada en la divina
revelación, que nace y se desarrolla de manera natural en el
Cristianismo primitivo como guía para el conocimiento de la palabra de
Dios a partir de la tradición y de las sagradas escrituras, en momentos
en los que el desarrollo del pensamiento filosófico y teológico del ser
humano enfiló otras doctrinas para suprimir o atacar el Cristianismo
pocas décadas después de la muerte y resurrección de Jesucristo, como
aún sigue sucediendo al separar la fe de la razón. El desarrollo del
dogma ha sido otro de los regalos del Espíritu Santo en la guía de la
iglesia, el dogma encierra los principios y valores, que con firmeza ha
defendido la iglesia, sin entender con ello un llamado a la violencia de
la cual también ha sido víctima, pero también victimaria a partir de
echos causados por la debilidad humana, no por el mensaje de Jesucristo,
que en dicho sentido fue asumido por Él con una enseñanza clara y firme
al entregarse, siendo Dios, a una pasión descarnada e injusta, sin
llamar a la violencia como era de esperarse, sino derramando su infinita
misericordia. Así lo entendieron sus apóstoles, siendo el primero San
Esteban[^1], quien al asumir el mensaje de Jesús, perdonó a sus
ejecutores, pues le dieron muerte a pedradas a causa de su fe. El
llamado a la firmeza de los principios y valores expresados en la
doctrina del Cristianismo es una convicción de fe en un camino de amor
que no es negociable, puesto que es una actitud que lleva a la verdad
absoluta. La doctrina Cristiana ha perdurado por la la fe y la firmeza
de sus argumentos frente a los de quienes le han rechazado a través de
los siglos, tal como la firmeza de los argumentos entre Bohr y Einstein
se debatieron en busca de la verdad científica; o como el estudiante de
tesis se debate ante sus jurados, o como el aspirante político en sano
debate se defiende ante sus detractores. Así, pues aun en nuestros días
continua la confusión del mundo, no solo sobre el sentido de la doctrina
Cristiana, sino sobre Jesús mismo.

Judas el Galileo, posiblemente nació el mismo año que Jesús. Fue un
líder zelote, que comprendía aquella secta Judía que se reveló contra el
pago de impuestos a Roma y que promovía una revolución que terminó en un
ataque en Séforis por parte de los Romanos[^2] , probablemente Jesús
quien vivió en una época marcada por las escandalosas diferencias entre
ricos y pobres, le eran familiares las proezas de Judas el Galileo,
llamado también el falso profeta. Jesús se habría desplazado con su
hermanos de nacimiento desde Nazaret. "Que Jesús tenía hermanos, a pesar
de la doctrina Católica de la perpetua virginidad de su madre, María, es
prácticamente indiscutible". Aquella es una interpretación de Reza Aslan
(Teheran, 1.972 - actualmente)[^3], un historiador contemporáneo que ha
escrito sobre algunos aspectos de la vida de Jesús.[^4] Como es sabido,
la historia puede tener muchas formas según su autor; H.G Wells,
historiador ateo del siglo pasado plantea que se debe separar la
historia y la teología, entonces añade que materialmente apareció Jesús
bajo la figura de hombre en Judea en el reinado de Tiberio César y es
del hombre de quien la historia ha de ocuparse. Según Wells, Jesús era
un profeta que predicaba a la manera de los profetas Judíos, de unos
treinta años y se ignora por completo su modo de vida antes de que
comenzara su predicación, puesto que las únicas fuentes directas de
información acerca de la vida y enseñanza de Jesús son los cuatro
Evangelios[^5]. En otro caso, un periodista investigador Ruso[^6]
aseguró haber encontrado documentos que probarían la estadía de Jesús en
la India durante su juventud, incluso algunos aseguran que estuvo en los
himalayas estudiando budismo en el Tibet, otros aseguran que visitó
Inglaterra, algunos confirman que sobrevivió a la muerte en la cruz y
terminó sus últimos años en Japón[^7], otros consideran a Jesús como
parte de un mito. Desde varias religiones existe otra interpretación,
desde la religión Judía una visión y otra desde el Islamismo. Entonces
Jesús, no sería interpretable, puesto que podrían existir cientos de
interpretaciones sobre su identidad, su vida y su mensaje. Sin embargo,
después de tantos siglos, hay una verdad sobre Jesús válida para
millones de Cristianos. Curiosamente, la misma inquietud que existió en
tiempos de Jesús, no ha variado en nada ya que quienes creyeron en Él ,
fue porque lo acompañaron inicialmente y recibieron directamente sus
enseñanzas; la confianza en los primeros Católicos, nacía de su vivencia
con Jesús, quien constantemente hizo un llamado de fe, camino que ya
había sido abonado por Dios Padre desde el Antiguo Testamento, por
generaciones milenarias de Judíos a través de la Divina Revelación. La
concepción de la iglesia Católica para aquellos que se revisten de la
fe, entienden que su cabeza es Jesucristo y su guía el Espíritu Santo;
Jesús al morir en la Cruz dejó a los apóstoles, sus primeros discípulos
con la tarea de digerir aquel mensaje de amor y de extenderlo por los
confines de la tierra. Son ellos entonces, los primeros seres humanos
que reciben el Espíritu Santo, con el acompañamiento de la Virgen María,
madre de Jesús y quienes constituyen inicialmente la iglesia Católica
como institución humana. Con el correr de los siglos, aquellos fieles
creyentes se constituyeron primero en miles y luego en millones de seres
que buscan aquella presencia del Espíritu Santo en sus vidas; son todos
ellos el cuerpo de la iglesia, con Jesucristo a la cabeza y con la
Virgen María como madre e intercesora de la iglesia; el apóstol Pedro,
como guía humana de los primeros discípulos o padres de la iglesia
Católica, todos ellos son quienes verdaderamente constituyen la iglesia
Cristiano Católica. Para quienes desconocen la fe en la religión
Cristiano Católica, posiblemente la entienden desde la razón como una
ideología promovida por el Papa de turno, la curia y todo el estamento
eclesiástico y el conjunto de instituciones jurídicas, propiedades e
iglesias en forma de edificios que se han construido durante
generaciones como patrimonio cultural y lugar de culto; otros la
confunden y la definen como una filosofía y aunque de la doctrina
Católica se desprenden ambas vistas, no es ninguna de ellas.

## La doctrina de la iglesia Católica

El mundo de las ideas, portadoras desde la era de Platón de un
razonamiento del "objeto" definido en una forma abstracta desde la mente
del ser humano, ha pasado a través de los siglos por pensadores y
filósofos que proponen diversas maneras de interpretarlo y su relación
con el mundo real; de aquel mundo filosófico se desprenden las
ideologías que parten de la interpretación de la verdad, su discusión y
búsqueda , desde una serie de principios y valores construidos por el
ser humano y su respectivo grupo de interés, con el efecto de
convertirse en una verdad relativa; relativa a cualquier idea que se
desea relacionar, siendo cualquier otra idea la que le sostiene, o la
que le rechaza, pero sin un terreno fértil en el cual se pueda anclar.
Por ello existen ideologías políticas, económicas y de diversa índole
que varían en su esencia constantemente; por ello también la tendencia a
resaltar a la iglesia como si estuviera constituida solo por el Papa y
su séquito; se pretende entender a la iglesia Católica como una
ideología de algunas personas extendida a millones de individuos
ingenuos. Pero, cuando aquellos principios y valores son considerados
como una verdad absoluta desde la fe, la doctrina tiene un valor
superior a toda ideología humana para aquellos que viven dicha fe; en el
caso de la doctrina Católica, nace del mensaje y la "presencia" de Dios
en el mundo. Ahora bien, no es tarea fácil comprender desde el ejercicio
de la razón en la fe el porqué para el Cristiano Católico, la doctrina
de la iglesia es la única y verdadera que expresa el mensaje de Jesús. A
partir del pensamiento teológico y filosófico, surgen entonces
centenares de defensores de aquella doctrina desde los primeros
Cristianos a través de los siglos, hasta el presente. Uno de ellos,
quien ha inspirado la siguiente sección sobre la Doctrina Católica, fue
San Jhon Henry Newman, quien desde las vísperas del siglo XIX, entregó
parte de su vida a la búsqueda de aquella doctrina. Newman,
contemporáneo de Darwin, nació en una familia de gran prestigio y su
Padre fue banquero; no pasó necesidades de niño, pero en su
adolescencia, su padre quebró y esto detuvo la bonanza financiera de su
familia. Newman quien siempre se caracterizó por su capacidad
intelectual , tuvo además una crisis de salud y tuvo en aquel entonces
el llamado de Dios, la gracia, solo entendida en la experiencia
subjetiva de cada ser humano. Tuvo Newman educación en el Trinity
College de la universidad de Oxford, en Inglaterra. Newman y su familia
tenían influencia del Calvinismo, una rama de la Cristiandad, sin
embargo, inicialmente perteneció al Anglicanismo, la iglesia Cristiana
protestante nativa de Inglaterra. Siendo Newman uno de sus mejores
exponentes ya en la edad madura emprende aquella labor para fortalecer
las bases del Anglicanismo, pero en dicho viaje intelectual y
filosófico, termina por convertirse al catolicismo. Entre sus miles de
notas, cartas y libros escritos se encuentra "Un ensayo sobre el
desarrollo de la Doctrina Cristiana"[^8] escrito en 1845; una época
convulsionada por el auge el pensamiento racional y el humanismo. Es
este gran documento, sin ser el único en la historia de la iglesia
Católica, el que a continuación sirve de base para la respuesta a
aquella inquietud planteada relacionada a la veracidad, consistencia y
transparencia de la doctrina Cristiano Católica.

### El proceso de desarrollo de las ideas

De acuerdo a Newman, en el ser humano el proceso de "desarrollo" de las
ideas[^9], es aquella característica de su mente de estar siempre
dispuesto a juzgar las cosas que le anteceden. No aprende tan rápido
como juzga: no se le permite a nada a justificarse por si solo: el ser
humano compara, contrasta, abstrae, generaliza, conecta, ajusta,
clasifica y obtiene todo su conocimiento en asociación con aquellos
procesos mentales. Aquellos aspectos mentales que se juzgan pueden ser
cosas que suceden, opiniones que van y vienen, otros están fijos en la
mente por una buena razón o sin ella, ya sea que se relaciona con
cuestiones de hecho o principios de conducta, puntos de vista del mundo
, prejuicios o pura imaginación; en algunos casos dichos aspectos son
confundidos en la mente con el objeto que representan y en algunos casos
no son más que meras ideas, que se confunden con objetos reales. La idea
que representa un objeto o un supuesto objeto le corresponde en la suma
total de sus posibles aspectos, sin embargo, las ideas pueden variar en
la consciencia de los individuos; y en proporción a la variedad de
aspectos bajo la cual se presenta en las diferentes mentes, es que está
la convicción y profundidad del argumento en la expresión de su
realidad; aquella visión de Newman, está en linea con la experiencia
subjetiva y la verdad del si mismo, que no puede ser perfectamente
expresada; tal como se ha revisado en la definición de las cualias y el
conocimiento científico actual del cerebro y la mente del ser humano
presentado en los primeros capítulos. Todos aquellos aspectos de una
idea son capaces de amalgamarse y definirse en el objeto al que
pertenecen. No existe sin embargo, un aspecto lo suficientemente
profundo como para determinar los contenidos de una idea real, no existe
un término o proposición que sirva para su definición. Ahora bien, una
representación es mas justa y exacta que otra y aún cuando una idea
pueda ser compleja, es permitido por conveniencia, considerar todos sus
distintos aspectos como ideas separadas. Si se trae esto al mundo
animal, con el gran conocimiento que se tiene sobre su vida y la
estructura de alguno en particular, no se puede llegar a una perfecta
definición de ninguno de ellos, pero si se puede enumerar una serie de
características a través de su descripción; así mismo, no se puede
encapsular en una fórmula mediante un hecho intelectual, o sistema de
pensamiento, como el de la filosofía de Platón, tampoco mediante un
fenómeno histórico de una doctrina y conducta señalada en un momento
dado. De tal manera, en ocasiones se intenta identificar la idea
central; en el caso de la Cristiandad, puede ser vista como un ambicioso
ensayo sobre un trabajo sobrenatural que, frente a la creación, los
inventos, la verdad científica y la razón del ser humano, se traduce en
una tarea incomprensible para la civilización. Pero, esta idea puede ser
interpretada por otros de variadas maneras como el intento de
restauración de la raza humana, algo de filantropía , una vía a la
inmortalidad, o la expresión espiritual de un servicio religioso, o la
salvación de los elegidos, o la libertad mental, o la unión del alma con
Dios. Newman, entonces define el aspecto central de la Cristiandad como
la encarnación de Jesús, es decir Jesús hecho hombre a partir de quien
nacen también tres aspectos de su enseñanza: el sacramental, el
jerárquico y el ascético[^10], los cuales siendo propios de la
revelación no se excluyen entre sí. Por otro lado, la Cristiandad es
dogmática, devocional y práctica a la misma vez; indulgente y estricta,
es luz y oscuridad , es amor y es miedo. Regresando a las
características de una idea, sea real o no, es de una naturaleza capaz
de absorber y poseer la mente del ser humano, entonces se puede decir
que "tiene vida", es decir que vive en la mente del individuo en el que
la idea reside. Cuando aquella idea es impulsada al público y a la masa
social y además llama la atención, deja de tener un estado pasivo y se
puede convertir en un principio activo en aquellas mentes e individuos,
llevándoles a una nueva forma de contemplarse a si mismos desde su
experiencia subjetiva y en su verdad individual con una aplicación de la
idea en varias direcciones y una propagación por diferentes rumbos. Al
comienzo las personas no entenderán por completo que mueve aquellas
ideas y las expresarán y las explicarán de manera inadecuada. Habrá una
agitación del pensamiento y una acción entre las mentes. Habrá un tiempo
de confusión cuando los conceptos estén en contradicción y la idea
estará en entredicho, si algo saldrá en realidad de aquella idea, o de
cual será el punto de vista que será también punto de partida para
otros. Al final y luego de un tiempo, algún aprendizaje saldrá a la luz;
un "punto de vista" será modificado o expandido por otro, y se combinará
con un tercer punto de vista; hasta que la idea a la cual pertenecen
estos varios aspectos, estará en cada mente de manera separada cuando al
comienzo estaba para todos juntos. ¿ Como la idea será tolerada por
otros sistemas ?, ¿como los afectará? , ¿que tanto se combinará con
ellos cuando interfiera con ellos ?, es algo que saldrá poco a poco a
flote; la idea será criticada por su enemigos y defendida por sus
seguidores, la multitud de opiniones serán recolectadas, comparadas,
ordenadas, rechazadas o aceptadas. En razón de su vigor, la idea se
presentará por si sola en la vida social diaria cambiando la opinión
pública, fortaleciendo o debilitando los fundamentos de un orden
establecido. Así, la idea crecerá como un código de ética, en un sistema
de gobierno, un campo teológico, un ritual, de acuerdo a su capacidad:
dicho cuerpo de pensamiento laboriosamente ganado será algo más que
representativo de la idea vista sustancialmente en sus inicios, su
imagen completa es vista como una combinación de diversos aspectos, con
las sugerencias y correcciones de muchas mentes y la ilustración de
muchas experiencias. Newman llama dicho proceso, que puede ser largo o
corto en el tiempo, como el "desarrollo" de la idea, siendo la
germinación o maduración de alguna verdad o aparente verdad en un gran
campo mental. De cierto modo, la experiencia subjetiva de quienes
expresan dicha idea tiende a converger a un mismo punto de vista,
después de muchas divergencias, como cuando se mezclan varios colores en
un frasco que al principio carece de una sola tonalidad y luego de
agitarle repetidamente se obtiene el tono y color deseados. Así mismo,
este proceso "no podrá ser un desarrollo", a no ser que el ensamble de
aspectos que constituyen su última concepción, realmente pertenezcan a
la idea de la cual comenzaron. El desarrollo de una idea, no es como una
investigación escrita en papel, en la que el avance sucesivo es una
evolución pura, sino que es asumida través de comunidades de personas,
sus liderazgos y guías: se emplean sus mentes como instrumentos y
dependen de ellas mientras se utilizan; adicionalmente, así como una
idea tiene capacidad de modificar algo, también puede ser modificada o
por lo menos influenciada por el estado de las cosas en las que se
desempeña debido a que es dependiente en diferentes maneras de las
circunstancias que le rodean. Una idea ante los cambios e influencias ,
en sus diferentes esferas de acción , grandes o pequeñas, puede ser
interrumpida, retardada, mutilada o distorsionada mediante la violencia
externa, puede ser impedida o dirigida por ideas contrarias, puede ser
depravada por la intrusión de principios externos a ella; o incluso
puede ser colapsada por el desarrollo de algunas de sus inconsistencias
originales en la misma idea. Entonces, cualquier riesgo de corrupción de
la idea por el relacionamiento con el mundo que le rodea, será
experimentado, si una gran idea tiene la capacidad de ser entendida y
más aún si es exhibida completamente. Las ideas en su comienzo no son
una medida de sus capacidades, ni de su alcance. Al comienzo nadie sabe
lo que es, ni su valor. Puede permanecer un tiempo dormida; podría
intentar, si fuera el caso, gatear y probar el terreno que le rodea y
sentir su camino. De tanto en tanto producirá discusiones que fallarán y
en consecuencia la idea será abandonada. Será una idea en suspenso, no
se sabe a donde se dirigirá; fluctuará de un lado a otro y finalmente
obtendrá una dirección definitiva; comenzará en un nuevo territorio, se
enfrentará en controversia, con nuevos peligros y esperanzas a partir de
nuevas relaciones; viejos principios reaparecerán bajo nuevas formas. La
idea cambiará con ellos para permanecer igual; para que la idea esté
viva tendrá que cambiar y para que sea perfecta tendrá que cambiar
frecuentemente, pero manteniendo su esencia.

### Clases de desarrollos de las ideas

Aun cuando este tópico puede ser de muy amplio espectro [^11], Newman
hace una aclaración , en relación al desarrollo de las ideas, para
evitar confusiones en el proceso de razonamiento. Se debe tener en
cuenta en primer lugar que la "palabra" es utilizada comúnmente, como en
el presente caso, en tres sentidos: de manera indiscriminada como
defecto del lenguaje, para el proceso de desarrollo verdadero o no, y
por otro lado para el resultado verdadero o no verdadero, es decir
confiable o no confiable a la idea de la que parte. Un desarrollo falso
o no confiable es una corrupción. Es de anotar que los desarrollos
matemáticos, o sistemas de verdades derivadas de las ecuaciones o
definiciones matemáticas, no caben en el presente tema, aunque hay
cierta analogía. En aquellos desarrollos no puede haber corrupción,
debido a que son conducidos en una estricta demostración. Tampoco pueden
ser corruptos los desarrollos físicos, como por ejemplo el desarrollo de
un animal, o de la naturaleza vegetal; y aunque no son tema de la
presente argumentación, si entran en consideración junto a los
desarrollos matemáticos en cuanto a que pueden ser tomados como una
ilustración general y directa hacia la que se puede orientar la atención
del tema en consideración. Tampoco se consideran corruptos los
desarrollos materiales, que aunque afectados por el ser humano, siguen
siendo físicos; se habla en este sentido por ejemplo de Irlanda o los
Estados Unidos como grandes desarrollos en el sentido de que aquellos
países poseen fértiles campos, abundantes productos, profundos ríos,
posiciones centrales de comercio, grandes fábricas y demás. En este
mismo sentido de desarrollo material, se puede considerar el desarrollo
humano de la naturaleza como en una gran hidroeléctrica, es decir, la
adaptación a los propósitos de utilidad y belleza, siendo el intelecto
humano el poder desarrollador; de igual manera se pueden incluir los
desarrollos tecnológicos descritos en los primeros capítulos, que parten
de la verdad científica y que en muchos casos, su propósito y utilidad
redunda en el bienestar del ser humano.

Ahora bien, cuando la sociedad y sus diferentes clases o "grupos de
interés" son el tema central de las ideas, el desarrollo puede ser
"político"; tal como se observa en el desarrollo de los estados o los
cambios de la constitución. Donde existe la civilización de un modo u
otro, de alguna manera existe la pretensión del desarrollo. Cuando un
imperio se extiende, acude al llamado de sus aliados, o por el balance
de poder, o por la necesidad de demostración de fortaleza o por el miedo
de sostener sus fronteras, en dichos casos el desarrollo es material,
pero es la idea que le brinda unidad y fuerza a su movimiento.

Los desarrollos políticos son el crecimiento de las ideas, son
caprichosos e irregulares en cuanto a su contenido. Son influenciados
por el carácter de sus soberanos, la caída y engrandecimiento de los
hombres o mujeres de estado, el curso de las batallas y las innumerables
vicisitudes del mundo. En algunos casos las ideas discordantes se
conectan bajo algún tipo de concesión o nombre. Como en el caso de las
coaliciones políticas o los procesos de entendimiento religioso; de
ambos casos normalmente no se espera algo bueno. Esa es una función de
los grupos de interés , como comités o grupos directivos y su principal
aspiración en sus conciliaciones y concesiones, es hacer ver a los
contrarios como si fueran lo mismo, o para garantizar acuerdos donde no
existe otro tipo de unidad. Es así como los desarrollos, reacciones,
reformas, revoluciones y cambios de varios tipos están mezclados entre
sí en la historia actual de los estados, como en las sectas filosóficas,
de tal manera que es muy complejo exhibir en ellos cualquier análisis de
carácter científico; generalmente, el proceso intelectual es entonces
aislado del práctico y es posterior a él. En los conflictos
parlamentarios, las personas primero sacan sus conclusiones por la
presión de los eventos externos o la fuerza de los principios, que no
conocen; luego, tienen que hablar y buscan sus argumentos: se publican
panfletos sobre el tema en debate, aparecen artículos escritos desde
donde cada parte asegura sus posiciones, como si fuesen de "la mayoría".
Otros desarrollos, aunque políticos, son extremamente subjetivos y
consecuentes con las ideas de los que ellos mismos son una muestra.
Newman , en este aspecto, refleja una realidad que no solo aplica para
el medievo, sino para el post modernismo; el carácter de la verdad
individual, impuesta por algunos grupos de interés a la sociedad u a
otros grupos de interés, parte de un liderazgo guiado por la experiencia
subjetiva de sus expositores. Es así como el desarrollo de las ideas
políticas están a merced de los individuos y el curso de las
circunstancias, siendo el afán del progreso económico con sus diferentes
tonos y matices conceptuales y culturales propios de cada lugar el gran
evento que domina en los últimos doscientos años a la humanidad.

En otros desarrollos, el carácter intelectual es tan prominente, que es
llamado lógico. Es el caso del desarrollo en las cortes de la ley, como
en la doctrina Anglicana de la "Real Supremacía" del siglo XVI , en la
que el rey se declara jefe supremo de la iglesia de Inglaterra en
reemplazo del Papa; dicha declaración se lleva a cabo con tal nivel de
consistencia y aplicación minuciosa, que aún la historia de las
constituciones no tienen; no solo se desarrolla en estatutos, o en
artículos sino en premisas a un gran nivel de detalle; de nuevo, cuando
una nueva filosofía es introducida como medida de una legislatura, o en
las concesiones que se hacen a un partido político, o en una política
comercial o agrícola, se dice generalmente, "no se ha encontrado el
punto final", dejando así un camino para futuras sesiones, las
siguientes generaciones lo decidirán. Pareciera entonces que hubiesen
alcances y características incomprendidas.

Otro tipo de desarrollos es el histórico, siendo la opinión de las
personas, hechos y eventos formada de manera gradual; el juicio que en
principio correspondía a unos pocos, termina a la larga extendiéndose a
través de la comunidad y atiende a una recepción general por la
acumulación y concurrencia del testimonio. Entonces, algunos estamentos
autoritarios mueren, otros ganan un poco, y otros son recibidos como la
verdad. Las cortes de la ley, los procedimientos del congreso o del
parlamento, los medios de comunicación, las cartas, la industria de los
historiadores y bibliografías y el pasar de los años son los
instrumentos de este tipo de desarrollo de las ideas.

Los desarrollos éticos, no son propiamente materia de argumentación y
controversia, pero son naturales y personales, substituyendo la estricta
inferencia lógica o racional, por lo que es congruente, deseable,
piadoso, apropiado, o generoso. Esta aproximación de Newman es un
reflejo en términos del desarrollo de las ideas, de lo que a la ciencia
atañe, en parte, en el estudio del cerebro humano respecto a la
complejidad en su expresión de lo subjetivo y lo mental; que como se ha
revisado, es un camino de largo recorrido que aún está en sus pasos
iniciales que marca un límite en el conocimiento que el ser humano tiene
actualmente sobre el "si mismo". Para Newman, ciertos objetos excitan
las emociones y sentimientos, así que lo sentimientos implican "objetos"
y "responsabilidades". Entonces, la consciencia, cuya existencia no se
puede negar, es una prueba de la doctrina de un gobierno moral; que por
si solo brinda un significado y un alcance; esta es la doctrina del
juicio y el juicio que viene es un desarrollo del fenómeno de la
conciencia. Sin embargo, es claro que las pasiones y afectos actúan en
nuestras mentes antes que la presencia de los propios objetos; y su
actividad obviamente será un antecedente de extrema convicción en favor
de la existencia de aquellos objetos legítimos, asumiendo que son
desconocidos. Entonces, el principio social , como objeto, que es innato
en el ser humano, le ofrece una sanción divina a la sociedad y al
gobierno civil. Y las oraciones por los muertos, implican ciertas
circunstancias de su estado a partir de las cuales surgen las
devociones; y los ritos y las ceremonias, que son formas naturales a
través de las cuales la mente se reconforta de ciertas emociones. Y
algunas veces, el cultivo de la admiración y el amor hacia lo grandioso,
lo nunca visto, lo más alto, ha hecho al ser humano abandonar su secta
hacia una doctrina más Católica. Ya lo anotaba Aristóteles, nutriendo
este tipo de desarrollo en su definición del hombre feliz. Luego de
mostrar en su definición de felicidad la inclusión del placer como la
idea más obvia y popular sobre la felicidad, el va más allá para decir
que los bienes externos son necesarios para llegar a ella, aún cuando
esta definición no dice nada; es decir, cierta prosperidad como
ejercicio moral, no por una necesidad lógica requerida por el hombre
feliz. A pesar de que dicha definición es tan lejana en el tiempo,
pareciera que aplica muy bien a la sociedad contemporánea, que en
últimas instancias en su afán del progreso sin dirección, se preocupa
profundamente por un bienestar a toda costa, sin tener una clara
expectativa respecto a su alcance, o una premisa que en su lógica, le
garantice al ser humano su felicidad. La religión, que busca también la
felicidad puede ser reducida al campo de los sentimientos, siendo
evidente entonces que es un interés muy personal; haciendo referencia a
un escritor Frances, recalca Newman "o\... estoy extrañamente
equivocado, o este sentimiento religioso no es la expresión completa de
la naturaleza religiosa del ser humano". La religión, es según Newman,
algo muy diferente y algo de mayor extensión. Hay problemas en la
naturaleza humana, en los destinos humanos, que no pueden ser resueltos
en esta vida. Esta apreciación de Newman se contrapone a la posición de
la razón y la verdad científica, en la cual el ser humano con toda su
capacidad de entendimiento, desde su cerebro y su mente, puede descifrar
todo tipo de problema o circunstancia, no solo en cuanto al origen
comportamiento y la extensión del universo y sus secretos, sino al
interior de cada individuo. Continúa Newman, afirmando que aquellas
situaciones o problemas que dependen del orden de las cosas que no se
pueden conectar con el mundo conocido, pero que incesablemente agitan la
mente del ser humano con el deseo de comprenderle, encuentran la
solución en el origen de toda religión; su objetivo principal es
descubrir las creencias y doctrinas que contiene, o que se supone
contiene. Otras inquietudes incitan al ser humano a abrazar la
religión\...¿ Donde se origina la moralidad? ¿ A donde lleva ?. ¿ Es
esta auto existente obligación de hacer el bien, un factor aislado, sin
ningún origen, sin un objetivo ?. ¿No concede dicha obligación al ser
humano, o más bien , no revela un origen, un destino mas allá de este
mundo ?. La ciencias de lo moral, por estas inquietudes espontáneas e
inevitables, conducen al ser humano al ámbito de la religión, y le
muestran una esfera desde la cual, el no las ha derivado. Entonces las
fuentes certeras y consistentes de la religión, son desde otro punto de
vista, los problemas de nuestra naturaleza humana o la necesidad de
buscar aspectos morales para sancionar, un origen y una dirección, un
objetivo o una aspiración. La religión asume muchas otras formas mas
allá del puro sentimiento; aparece en la unión de doctrinas, preceptos y
promesas. Esto es lo que verdaderamente constituye una religión; es su
carácter fundamental, mas allá que una pura forma de la sensibilidad, o
un impulso de la imaginación, o una variedad poética. Cuando se
descompone en sus elementos verdaderos, en su naturaleza esencial, la
religión deja de ser un puro consentimiento personal y se convierte en
un poderoso y fructífero principio de asociación. Es considerada como la
luz de un sistema de creencias y dogmas. La verdad en dicho caso no es
una herencia de un individuo, sino que es absoluta y universal; el ser
humano, busca profesarla en comunidad. Una sociedad religiosa, entonces
resulta de manera natural de los elementos naturales de la religión y
cuando se ha formado, cuando cierto número de personas están unidas por
un credo religioso común, son entonces gobernados por los mismos
preceptos religiosos; en dicho caso, alguna forma de gobierno es
necesaria; ninguna sociedad puede durar tal vez ni una semana, o ni unas
horas, sin un gobierno. El momento en que una sociedad se conforma, por
el hecho de su formación, llama a un gobierno, el cual proclama una
verdad común, esta verdad es lo que une y conecta a dicha sociedad, la
cual promulga y mantiene aquellos preceptos que dicha verdad produce. La
necesidad de un poder superior, de una forma de gobierno, está inducida
en el hecho de la existencia de una sociedad religiosa, en cualquier
clase de sociedad, desde la tribu del neolítico hasta nuestros días.
Nuevamente, el gobierno, entonces obedece a los grupos de interés,
cualquiera que sea su naturaleza y sus relaciones, que terminan de una
otra forma acudiendo a la difusión y proclamación de lo que en el
momento histórico se pretende entender como verdad, o parte de la misma.

Por último, están los desarrollos metafísicos de las ideas, los cuales
son meros análisis de la idea contemplada y termina en su exacta y
completa demarcación; así, Aristóteles dibuja el carácter del magnánimo,
como un hombre benigno, bondadoso o benevolente; Shakespeare concibe a
Hamlet o Ariel; y así, en el marco de la sagrada teología, la mente es
empleada en desarrollar ideas solemnes, que sostiene y atiende
implícitamente sin ser influenciada por sus reflejos y poderes
racionales. De acuerdo a Newman y en especial en el catolicismo, la
mente que está habituada al pensamiento de Dios, de Cristo y del
Espíritu Santo, naturalmente se asimila con una curiosidad devocional a
la contemplación del objeto de su adoración y comienza a formar
declaraciones acerca de Él, sin saber a donde le conduce, o que tan
lejos le llevará. Una proposición, llevará necesariamente a otra, y una
segunda a una tercera; luego alguna limitación es requerida; y la
combinación de los opuestos, serán frescas evoluciones de la idea
original, que entre otros nunca será completada. Este proceso, es su
desarrollo y resulta en una serie, o un cuerpo de proposiciones
doctrinales, hasta que lo que era una impresión de la imaginación se
convierte en un sistema o creencias en la razón. Ahora bien, estas
impresiones son obviamente individuales y completas sobre otras ideas
teológicas, debido a que son impresiones de objetos; así, los
desarrollos en las doctrinas de la Santísima Trinidad y la encarnación
de Jesús, son meras porciones de la impresión original y modos de
representarla. Como Dios es uno, esa es la impresión que el mismo nos da
de ser único; no es una cosa en partes; no es un sistema; ni es nada
imperfecto con necesidad de una contraparte. Es la visión del objeto.
Cuando rezamos, rezamos no a un ensamblaje de nociones o a un credo,
pero si a un ser individual; cuando hablamos de Dios, no hablamos de una
ley o una manifestación. El ser humano religioso, en su propia medida
tiene una idea o visión de la unidad de la Santísima Trinidad, de su
hijo encarnado y de su presencia, no como un número de características,
atributos y acciones, no como un sujeto de un número de proposiciones,
pero como un individuo , independiente de las palabras, como una
impresión que converge a través de los sentidos. Las creencias y dogmas
viven en aquella idea para la que fueron diseñados que expresara, y que
solos son intrínsecos y son necesarios, porque la mente del ser humano,
sujeta a su experiencia subjetiva, no puede reflejar aquella idea de un
solo tajo, no puede utilizarla en su unidad e integridad, sin antes
resolverla en una serie de aspectos y relaciones.

Con respecto a la Cristiandad, suponiendo las verdades que la componen
como sujetas a la posibilidad del desarrollo, dicho desarrollo será de
uno de los tipos señalados. Siendo la encarnación de Dios en el hombre,
en su hijo Jesús, la doctrina central, el episcopado y sus
manifestaciones será una instancia de un desarrollo político, la
teología un desarrollo lógico, la fecha de nacimiento de Jesucristo un
desarrollo histórico, la Santa Eucaristía , un desarrollo moral y el
credo de Atanasio[^12] un desarrollo metafísico.

## El desarrollo genuino contrastado con la corrupción

Siendo la fe válida, en el corazón encontrando el corazón a través de la
gracia derramada por el Espíritu Santo, buscada por el ser humano en su
experiencia subjetiva y su verdad individual, en el silencio y la
oración directa con Dios; y regresando a la inquietud sobre la fe
Cristiano Católica, en relación a si misma, si es genuina tal como se
entiende en el presente; si es lógica e históricamente representativa de
la fe expresada por los primeros discípulos de Jesús, en dicho sentido,
Newman hace una afirmación sobre la doctrina de la iglesia Católica: el
catolicismo moderno, no es más que una simple legitimización del
crecimiento y complemento de la doctrina de la iglesia primitiva, es
decir, el desarrollo natural y necesario, en el que su divina autoridad
está incluida en la divinidad de la Cristiandad. Para ello Newman
comienza por determinar que es una "corrupción" con el ánimo de
diferenciarla de lo que es un "desarrollo" de la doctrina. En primer
lugar, una corrupción es una definición atada a cosas organizadas de
manera única. Una roca puede ser convertida en polvo, pero no ser
corrupta. La corrupción, es en sentido contrario, el rompimiento o
resquebrajamiento de la vida, en preparación a su terminación. Es el
estado de un cuerpo antes de su disolución; comienza cuando la vida ha
alcanzado su perfección y es la secuencia o continuación de aquel
proceso hacia la perfección, siendo simultáneamente el reversar y el
deshacer de lo que era antes. Hasta que aquel punto de regresión es
alcanzado, el cuerpo tiene su propia función y una dirección y objetivo
en su acción, en la naturaleza y sus leyes; esto es ahora un perder de
los atributos y manifestaciones de años anteriores; y con ellos el vigor
y los poderes de la nutrición, la asimilación y la auto reparación. Con
esta analogía como guía, Newman define siete notas de variada
pertinencia, independencia y aplicabilidad para diferenciar los
"desarrollos" genuinos de una idea , de su estado de corrupción y
decaimiento de la siguiente manera: en la idea no existe corrupción se
se retiene que es de un solo y mismo tipo, si tiene los mismos
principios, si mantiene la misma organización, si sus comienzos
anticipan sus fases siguientes, si sus últimos fenómenos protegen y
completan los iniciales, si tiene un poder de asimilación y
resurgimiento, y si contiene una acción vigorosa de principio a fin. Es
el desarrollo de las ideas que componen la Doctrina Católica y reflejan
la fe de su iglesia; esto es entonces explicado por Newman a partir de
siete notas , a través de las cuales se desea confirmar la unidad e
identidad de la idea consigo misma, desde la primera hasta la última
nota, que actúan como filtros que pueden ser considerados como
independientes o como uno solo en su totalidad[^13].

### Primera nota de un desarrollo genuino -- Preservación de Tipo

La preservación de tipo parte de la analogía sobre el crecimiento
físico, en el cual las partes y proporciones de la forma desarrollada,
aunque alterada, corresponde a las que fueron sus comienzos. El animal
adulto está hecho de lo mismo, que cuando nació; los pájaros no crecen
como peces. San Vicente de Lérins (Toul, ? - 450, Islas Lérins)[^14]
adopta esa ilustración en referencia a la doctrina Cristiana, que dice
"Deja el alma de la religión, imitar la ley del cuerpo, que mientras los
años pasan continúa su desarrollo y se abre en razón de nuevas
proporciones, sin embargo permanece idéntico a lo que era. Los brazos
del bebé son pequeños, los del joven son largos , sin embargo son lo
mismo". Un líder popular, podría tener diversas profesiones, podría
cortejar partidos políticos y alejarse de ellos, podría contradecirse en
sus palabras o deshacer sus propias decisiones, sin embargo podría
conservar con firmeza sus objetivos, o su adherencia a ciertas doctrinas
básicas, lo que le da unidad a su carrera e imprime en sus seguidores
una imagen de direccionamiento y gran consistencia, lo que muestra una
fidelidad de su tipo de principio a fin. Sin embargo, las últimas
instancias o estados del desarrollo de las ideas, podrían sugerir que la
unidad de tipo no es consistente con su desarrollo. No se debería ceder
ante la presión de negar toda variación , ni una modificación
considerable de la proporción y la relación en el tiempo, en las partes
o aspectos de una idea. La mariposa, es el desarrollo, pero en ningún
sentido, la imagen del capullo. Más profundos y misteriosas son las
variaciones consistentes o inconsistentes con la identidad de un
desarrollo político o religioso, que las de un cuerpo físico. La
historia de las naciones pueden actuar como una analogía, en su curso y
conexión tan estrecha del desarrollo de las mentes y las ideas. Se puede
decir que Inglaterra en la antigüedad apoyaba de la manera más fiel a la
Santa sede, pero la Inglaterra moderna ha sido por momentos su enemigo;
sin embargo, esto no puede llamarse una corrupción; esto ha sucedido en
muchas naciones y no por ello, estos grandes cambios pueden llamarse
corrupciones. De una manera similar, las ideas pueden permanecer, aún
cuando su expresión es indefinidamente variable; no se puede determinar
si el desarrollo de una idea es verdadero o no, sin un conocimiento
detallado y profundo , más allá de la experiencia del simple factor de
su variación, tampoco los instintos emocionales sirven como criterio.
Ahora bien, las verdaderas perversiones y corrupciones generalmente no
parecerían ser algo externo a la doctrina en la que se originan, como lo
son las cambios y variaciones propias de un verdadero desarrollo. Cuando
Roma cambió de ser república a un imperio, fue realmente una alteración
política, fue una corrupción; pero, en apariencia el cambio fue menor.
Las antiguas oficinas o las funciones del gobierno permanecieron: solo
fue que el emperador, o el comandante en jefe, las concentró en él. Una
idea no siempre conserva en si, la misma imagen externa; esta
circunstancia, sin embargo, no es lo suficientemente fuerte como para
debilitar su identidad sustancial. Al contrario, por esa misma razón la
unidad de tipo se convierte en la garantía de la salud y consistencia de
los desarrollos de las ideas, cuando es persistentemente preservada
independientemente de su número o de su importancia.[^15]

### Segunda nota -- continuidad de los principios

Así como en las creaciones matemáticas las figuras son formadas bajo
distintas fórmulas, las cuales son las leyes que representan y bajo las
cuales han sido desarrolladas, así sucede en los asuntos éticos y
políticos. Se dice que la vida de las doctrinas son consistentes con la
ley que las envuelve. Los principios son abstractos y generales, las
doctrinas se relacionan con hechos, las doctrinas se desarrollan y los
principios a primera vista no; las doctrinas crecen y se engrandecen,
los principios son permanentes; las doctrinas son intelectuales, los
principios son éticos y prácticos. Los sistemas viven en los principios
y representan doctrinas. La responsabilidad personal es un principio, el
ser de Dios es una doctrina; de esta doctrina toda la teología obtiene
su curso, mientras su principio no es del todo más claro bajo el
evangelio que en el paraíso, y depende, no en la creencia de un
gobernador todopoderoso, sino de la consciencia. Aún así, la diferencia
entre las doctrinas, algunas veces solo existe en la manera como se
vean; y entonces, la doctrina en una filosofía es principio en otra. La
responsabilidad personal puede tener una base doctrinal y desarrollarse
por ejemplo como Pelagianismo. Esta doctrina fue considerada une herejía
en el siglo V, Pelagio (Britania, 360 -- 422, Alejandría )[^16] , quien
afirmaba la excelencia de la creación y el libre albedrío sobre el
pecado original y la gracia; consideró la fuerza moral de la voluntad
humana, cuando está fortalecida por el ascetismo como suficiente en si
misma para conseguir y desear el noble ideal de la virtud. El valor de
la redención de Cristo era en su opinión, limitado principalmente a la
formación de la doctrina y al ejemplo que Jesús puso en la balanza, como
contrapeso frente al mal ejemplo de Adan, de manera que la naturaleza
mantiene la habilidad de someter al pecado y ganar la vida eterna aún
sin la ayuda de la gracia de Dios, es decir sin la ayuda del Espíritu
Santo.[^17] Puede ser entonces, sometido a discusión si la infabilidad
es un principio o una doctrina de la iglesia de Roma, y el
dogmatismo[^18] un principio o una doctrina de la Cristiandad. La
consideración de los pobres es una doctrina de la iglesia considerada
como un cuerpo religioso y un principio cuando es vista como un poder
político. Las doctrinas son a los principios , como las definiciones de
los axiomas y postulados matemáticos. En el tratado de los elementos de
Euclides (Grecia,330 AC -- 275 AC, Alejandría )[^19] , su postulado No.
15 dice, "si dos rectas se cortan entre sí, entonces se crean ángulos
opuestos por el vértice iguales entre sí" y el No.17 , dice, "en
cualquier triangulo la suma de cualesquiera de dos de sus ángulos, es
menor que dos ángulos rectos". Estos postulados son desarrollos, no de
los tres primeros axiomas[^20] Euclidianos, los cuales se requieren en
la demostración, pero si, de la definición de un ángulo recto. Euclides
busca aquellos desarrollos a partir de la definición del
rectángulo[^21], y encuentra varios casos particulares a partir de una
verdad general, que "el todo es igual a sus partes". Un desarrollo de
ideas, para ser creíble, fiel y certero, debe retener ambas, la doctrina
y el principio con el cual comenzó. La doctrina sin su correspondiente
principio, está vacía, sino sin vida. Por otro lado, el principio sin su
correspondiente doctrina, puede ser considerado como el estado de las
mentes religiosas en un mundo escéptico, visto de manera relativa a la
revelación; es decir, los hijos de Dios dispersos y alejados. Esto
también lleva generalmente a la solución en la cual los extremos de la
paradoja se encuentran y conducen a las reacciones absurdas de los
individuos, bajo la presencia de algún principio o condición que es
dominante en sus mentes de comienzo a fin. Si una de las dos
alternativas contradictorias es necesariamente verdadera bajo cierta
hipótesis, entonces la negación de una, lleva por simple consistencia
lógica y sin razones directas, a la recepción de la otra. No solo sucede
esto en los desarrollos de las ideas políticas, sino en la Cristiandad,
que en algunos casos es un pilar y base de la verdad o por el contrario
en ella está el anticristo. Por otro lado, la definición de las cualias
mencionadas en capítulos iniciales permiten mostrar la dificultad de
comunicación que existe entre las personas en la apropiación de la
experiencia subjetiva del otro individuo; esto es explícito de acuerdo a
Newman en la ciencia de la gramática, la cual permite otra instancia
para la existencia de leyes especiales en la formación de los sistemas.
Algunos lenguajes tienen más elasticidad que otros y mayores
capacidades. Entonces, la dificultad de la explicación del hecho, no
puede llevar a la duda del mismo. Es el caso de la fe. Algunos lenguajes
tienen la capacidad de un mejor manejo de palabras compuestas, no se
sabe por qué, en otros lenguajes no existe dicha capacidad. Se percibe
cierta genialidad en cada lenguaje y descubrir esto es materia de
estudio detallado. Cuando los algunos escritores entonces, intentan tal
vez a partir de alguna teoría, ir un poco más allá de las capacidades de
su lenguaje, son entonces cuestionados. Un ejemplo de las capacidades de
los lenguajes es la sutileza y dificultad para entender la formación de
los nombres propios en personas particulares. En las obras de ficción,
los nombres o títulos de los caracteres presentados deben ser
inventados; hay autores expertos en ello, mientras otros autores son
poco afortunados en ello. Algunas novelas intentan interpretar apellidos
extranjeros y fallan; lo que cada lector piense, es difícil de analizar:
es el caso en el que los apellidos son construidos bajo una ley que solo
es exhibida en circunstancias muy particulares y cuyas reglas de
formación se basan en ciertas, pero profundas determinaciones. Así mismo
sucede en los sistemas de física o sistemas morales, que se desprenden
de nombres célebres y proceden de asumir ciertas condiciones que son
necesarias para cada estado o etapa de su desarrollo. La teoría
Newtoniana de la gravedad está basada en ciertos axiomas y la aplicación
de la ciencia en propósitos prácticos dependen de la hipótesis de que lo
que sucede hoy, sucederá mañana. Sucede en aspectos militares, en los
que el descubrimiento de las armas desarrollaron la ciencia del ataque y
la defensa. Así mismo, los estados tienen sus respectivas políticas a
partir de las cuales avanzan y las cuales son las condiciones de su
bienestar el cual, en el post-modernismo, ha tenidos logros sin
precedentes en el desarrollo de la civilización, pero que de manera
generalizada, con sus excepciones y en su momento histórico está sujeto
a no tener rumbo, ni timón; es per sé , un sistema de desarrollo hiper -
competitívo y sin fin, con aspiraciones de dominio económico y
tecnológico, estimulado por el individuo y su grupo de interés. Aún así,
las naciones y estados tienen características que les distinguen en sus
políticas de desarrollo particular. Todo esto se lleva a cabo , no solo
por actos y leyes formales, pero además por el carácter ético y la
energía espontánea de las personas que comprenden las naciones. Los
principios políticos de la Cristiandad, si es que se puede ser correcto
usar el término de política divina, están expresados en el sermón del
monte[^22]. Al contrario que en muchos imperios , los Cristianos
conquistan cediendo; ganan influencia apartándose de ella; poseen la
tierra, renunciando a ella. Todas estas instancias, muestran, como se ha
observado en algunas de ellas, que la destrucción de las leyes
especiales o principios de desarrollo que las componen son su
corrupción. Así, como en las naciones, se puede decir que el espíritu de
las personas se ha perdido, no se refiere a que esta o aquella actuación
se ha cometido, o a aquella medida llevada a cabo, pero que ciertas
lineas de pensamiento o conducta que les ha dado grandeza, han sido
abandonadas. Entonces la continuidad o la alteración de los principios
sobre los que una idea se ha desarrollado , son una segunda marca de
discriminación entre un verdadero desarrollo y una corrupción[^23].

### Tercera nota -- El poder de asimilación

En el mundo físico, lo que tenga vida se caracteriza porque tiene
crecimiento, y sin él, se llega al final de la vida. Lo que crece , lo
hace porque toma para su propia substancia materia externa; y esta
absorción o asimilación se completa cuando la materia apropiada hace
parte de lo que crece y entra a ser parte de su unidad. Dos cosas no se
convierten en una, excepto si existe el poder de asimilación de una o la
otra. Dicha analogía puede servir para ilustrar ciertas peculiaridades
en las ideas. No siendo así en las matemáticas y en otras creaciones de
tipo abstracto, que como el alma, son solitarias y auto-dependientes;
pero las doctrinas y sus aspectos relacionados a las personas no están
en el vacío, sino en un mundo repleto de ideas y estas se hacen camino
por si mismas mediante la interpretación y se desarrollan por absorción.
Los hechos y las opiniones que han sido así exploradas en otras
relaciones y agrupadas en otros centros de gravitación, han sido
gradualmente atraídos a una nueva influencia y sometidos a una nueva
soberanía. Son modificados, revisados de nuevo, o puestos a un lado,
dependiendo de cada caso. Un nuevo elemento de orden y composición viene
a formar parte de ellos; y su vida es probada por su capacidad de
expansión, sin desarreglo o disolución. Un proceso diverso, conservador,
asimilador, sanador, pulidor, un poder unificador, es parte de la
esencia y es el tercer examen de un desarrollo de las ideas creíble y
fructífero. Entonces, el poder del desarrollo de las ideas es una prueba
de vida no solo de su discurso, sino especialmente de su triunfo. Una
idea viva se convierte en muchas, sin embargo permanece como una. El
intento del desarrollo de las ideas muestra la presencia de un principio
y su aceptación muestra una idea, los principios estimulan el desarrollo
y las ideas lo concentran. El desarrollo de las ideas es un proceso de
incorporación; el Islam se podría considerar tan solo un desarrollo
externo compuesto de otras teologías, sin embargo nadie puede negar que
existe en dicha religión una idea viva, que ha sido tan fuerte, tan
amplia, tan duradera que se ha conectado con la historia de la
humanidad. ¿Porqué se ha seguido desarrollando después de su primer
sermón ?, si es meramente una idea política, o teológica como
normalmente se piensa, si es el caso, como parece serlo, es algo que no
puede ser determinado sin un profundo conocimiento de aquella religión.
En la Cristiandad, la opinión cuando es materia prima, es llamada
filosofía o escolástica; cuando sobra y se ha rechazado, se denomina
herejía. Las ideas son más abiertas a influencias externas en sus
comienzos que más adelante; es así como la gran mayoría de escritores
que consideraron la iglesia medieval como corrupta, buscan dicha
corrupción en los primeros cuatro siglos, no en la llamada edad oscura
de la iglesia. Que una idea más rápidamente se consolide, más con estas,
que con aquellas ideas, no significa que ha sido indebidamente
influenciada, es decir corrupta por ellas, pero sí que ha existido un
antecedente de afinidad hacia ellas. En política, las ideas también son
propuestas, discutidas, rechazadas o adoptadas y algunas veces carecen
de sentido o son imposibles; otras veces son verdad o verdad parcial en
subordinación con otras ideas, con las cuales y como consecuencia son
absorbidas en parte o del todo, dependiendo de que tanta afinidad hay
entre ellas. Entre más fuerte y viva sea una idea, es decir, entre mayor
poder tiene para ejercitar la mente de las personas, más propensa está a
proporcionar credibilidad, seguridad y confianza en si misma ante el
peligro de la corrupción[^24].

### Cuarta nota -- Anticipación de su futuro

Cuando una idea está viva, esto es, es ejerce la influencia y es
efectiva, es seguro que se desarrolle de acuerdo a su propia naturaleza
y las tendencias que se le cargan en el largo plazo podrían bajo
circunstancia favorables presentarse tanto temprano como tarde y la
lógica es la misma en todas las ocasiones, las instancias de desarrollo
que vendrán aun cuando vagas y aisladas, pueden ocurrir al puro
principio y pasará un lapso de tiempo para que se perfeccionen. Como los
desarrollos de las ideas son en gran medida solo aspectos de la idea de
la cual proceden y en todos ellos hay consecuencias de ello, el orden en
que ocurren en la mente de los individuos es un evento accidental; y no
es extraño, aquí y allá, que diferentes casos o ejemplos de enseñanza
avanzada puedan ocurrir en los puros comienzos, que en el transcurso de
la historia no sean encontrados sino hasta un periodo tardío. El hecho ,
entonces, de aquellas declaraciones tempranas o recurrentes que son
posteriormente completamente realizadas, es una evidencia de que aquel
perfeccionamiento sistemático está alineado con la idea original. San
Pacomio (Tebas, 292 - 348, Tabennisi)[^25], el primer autor de la regla
monástica, mantuvo una gran biblioteca y mantenía conferencias y
disputas en temas religiosos sobre interpretación de la escritura o
puntos teológicos, tres veces por semana; San Basilio (Cesarea, 329 --
379, Cesarea)[^26], el fundador del monacato en el Ponto[^27], es uno de
los Padres Griegos que dejó grandes enseñanzas en sus tratados
teológicos; San Jerónimo (Estridnó, 340 -- 420, Belén)[^28], autor de la
versión latina de la escritura vivió como un monje pobre en una celda en
Belén. Estos casos , son más que excepciones en el carácter del
monaquismo temprano; además ellos muestran su capacidad de anticiparse a
la historia, siendo la literatura consistente con sus ideas. Otra
evidencia entonces, sobre la credibilidad y confiabilidad de un
desarrollo de ideas es su anticipación definitiva en un periodo temprano
en la historia de la idea a la que pertenece[^29].

### Quinta Nota -- Secuencia lógica

Lógica es la organización del pensamiento y siendo así, es la seguridad
para que un desarrollo intelectual sea fructífero, coherente y aceptado
fielmente. La necesidad de usar la lógica es innegable, sobretodo en el
sentido de que sus reglas no deben ser transgredidas. El hecho de que
esto no sea tenido en cuenta en cada instancia de un desarrollo
doctrinal es debido a las variedades de la constitución mental, ya sea
en comunidades o en individuos, en las que grandes o aparentes verdades
son implantadas. En todo caso, la pregunta que debe hacerse es si un
desarrollo de ideas puede ser otro, en cualquier caso, diferente a una
operación lógica; pero si por esto significa un razonamiento consciente
de unas premisas a una conclusión, obviamente la respuesta es negativa.
Una idea ante uno u otro de sus aspectos crece en la mente permaneciendo
allí; se vuelve familiar y distintiva y es vista en sus relaciones;
lleva hacia otros aspectos y estos de nuevo hacia otros, de manera
delicada, profunda, original, de acuerdo al carácter intelectual y moral
del recipiente; entonces un cuerpo de pensamiento es gradualmente
formado sin que sea reconocido lo que hay en él. De tiempo en tiempo,
las circunstancias externas exigen una declaración formal de los
pensamientos que vienen a existir en la profundidades de su mente; y
pronto el recipiente de la idea comenzará a defenderla; y luego de nuevo
un proceso de mayor alcance tendrá lugar, en el que se analizarán sus
declaraciones y la dependencia asertiva de una con la otra. Entonces la
persona recipiente de la idea, expresará sus declaraciones como
consecuencias y les buscará sus principios, los que aquí serán
discernidos por una percepción moral y adoptados con simpatía; y la
lógica aparecerá para organizar e inculcar lo que ninguna ciencia le ha
dado en ganancia. Y entonces, de la misma manera, los procesos
intelectuales son cargados de manera silenciosa y espontánea en la mente
de un grupo o escuela, dada la necesidad de salir a la luz mas adelante,
son entonces reconocidos y sus características son acomodadas
científicamente. Y luego la lógica tiene la función adicional de la
propagación; la analogía, la naturaleza del caso, el antecedente, la
probabilidad, la aplicación de principios, su congruencia, su
legitimidad, son algunos de los métodos de prueba en el desarrollo de la
idea, que continua de mente en mente y se establece en la fe de la
comunidad. Cada argumento tiene un propósito inmediato; las mentes
desarrollan la idea paso a paso, sin mirar atrás o sin anticipar su
objetivo, también sin la intención de formar un sistema. Después, desde
luego, el sentido lógico que cubre el todo se traduce en un examen para
que el proceso sea verdadero, no una corrupción o una perversión por su
naturalidad evidente; y en algunos casos por la precisión, claridad y la
majestuosidad de su avance y la armonía de sus proporciones, tal como la
altitud, el agraciado follaje y ramaje en el desarrollo de una especie
vegetal. El proceso de desarrollo de las ideas, tiene la capacidad
entonces de ser una expresión lógica; y ha sido en ocasiones llamado
racionalismo contrastado u opuesto a la fe. Sin embargo, una doctrina u
opinión que es sometida a un desarrollo podría ser racionalista y como
es en su origen, así mismo pueden ser sus resultados: y a pesar de que
puede ser desarrollada erróneamente, es decir un razonamiento
incorrecto, el desarrollo en si, merece al menos su reconocimiento, como
al afirmar la inquietud frente a un hecho histórico; tal es el caso, de
si el evangelio de San Marcos, lo escribió él, con, o antes , que San
Mateo. El racionalismo es el ejercicio de la razón, en vez de la fe en
asuntos de la fe; pero lo que generalmente muchas personas no pueden
entender es: como si puede ser fe, el hecho de adoptar las premisas del
razonamiento lógico, o simplemente no aceptar las conclusiones, por no
creer en ellas. Al mismo tiempo, se podría dar por hecho como ya fue
revisado en el presente documento, que el proceso que sucede al interior
de la mente, en el cerebro, es de más complejidad y alcance y presenta
mayores alternativas de decisión que unicamente lo que es "lógico"; en
cuyo caso, el ser científico lo asume como de su propio campo y lo puede
utilizar para ser compartido con otras mentes, personalmente extrañas,
en el sentido verdadero, tanto para las ideas en cuestión como para su
desarrollo. Por aquella capacidad del cerebro y la mente y de la verdad
individual, entonces, los Santos Apóstoles podrían sin palabras conocer
todas las verdades concernientes a las altas doctrinas de la teología,
las cuales posteriormente, de manera honesta, transparente y abundante
fueron desarrolladas a través del argumento por aquellos que
participaron a través de las controversias. El continuo avance y
determinado camino a que pertenecen una doctrina, política o institución
y que inspira el sentido común de la humanidad, aquello en lo que se
convierte en últimas, es la argumentación consecuente de lo que fue en
su primera instancia. Una doctrina, entonces profesada en sus años
maduros ya sea por una filosofía o una religión, es posiblemente un
desarrollo verdadero de ideas, no una corrupción , en proporción a su
impresión de ser el argumento lógico de su enseñanza original[^30].

### Sexta Nota -- Acción conservadora según su pasado

Aquellos desarrollos de ideas que contradicen y reversan el curso de la
doctrina que ha sido desarrollada antes que ellos y de los cuales
surgieron, son ciertamente corruptos; una corrupción es un desarrollo en
aquel estado en el que cesa de ilustrar y comienza a distorsionar las
ganancias de su historia previa. La corrupción es la regla de la
creación, o mas bien el fenómeno mediante el cual se presenta, en el que
la vida, en un camino de transición, comienza a terminarse mediante una
acción imperceptible y gradual; La debilidad no es más que producto del
poder y los eventos se mueven en ciclos. Las flores primero florecen y
luego se caen; lo mismo que la fruta, primero madura y luego se pudre.
El proceso de fermentación , si no se para en el punto preciso, corrompe
el licor que ha creado. Existe de la misma manera, un límite al
conocimiento humano, tanto escritores sagrados como profanos son
espectadores de que un exceso de sabiduría lleva a lo absurdo; y en el
mundo de los estados políticos, estos nacen y caen, siendo los
instrumentos de su grandeza, los mismos que se convierten en las bombas
de su destrucción; de ahí el refrán popular, todo en exceso es dañino.
El verdadero desarrollo de ideas, puede ser descrito entonces, como algo
conservador en el curso del desarrollo que le antecede siendo realmente
esos antecedentes y algo más a su lado: es una adición que ilustra , no
que oscurece, que corrobora, no que corrige el cuerpo de pensamiento del
cual procede; y esta es la característica que contrasta con la
corrupción. La verdadera religión es el culmen y la perfección de las
religiones falsas; combina en una lo que sea que haya de bueno y
verdadero, independientemente , en los rezagos de cada una de ellas. Y
de la misma manera el credo Cristiano Católico es en su mayor parte una
combinación de verdades separadas, las cuales sus críticos se han
dividido entre ellos de manera errática. En este sentido, si una mente
religiosa ha sido educada y está sinceramente vinculada en alguna forma
de religión errática y luego es alcanzada por la luz de la verdad, podrá
entonces remover el error de la verdad sin perder lo que ya tiene
ganado, pero ganando lo que no ha alcanzado; aquellos principios de la
misma fe que inicialmente le ha llevado a una doctrina equivocada,
también le podría llevar a la verdadera; y aquella porción de su
doctrina original, será indirectamente rechazada en la recepción de la
verdad que se le opone. La verdadera conversión está siempre en el
terreno de lo positivo, no en el carácter negativo. Ahora bien, en la
historia de la antigua Roma, en el tiempo en el que los privilegios
ganaron en las tribunas de las gentes favoreciendo la ambición propia,
el desarrollo de las ideas se convirtió en corrupción , es entonces
necesaria la prueba aquí expuesta, la de la tendencia a conservar lo que
previamente existía[^31].

### Séptima Nota -- Vigor crónico

La corrupción de una idea, en el sentido de su apariencia, es de cierta
manera un accidente o afectación de su desarrollo, siendo el final de un
curso de acción, una transición de estados que lleva a una crisis; es un
proceso rápido. Mientras las ideas viven en las mentes de las personas,
están en constante crecimiento hacia un desarrollo más completo: no se
estacionarán en su corrupción, más allá de antes de que suceda; y su
disolución será el siguiente estado al cual tiende la corrupción. La
corrupción, no puede entonces perseverar en el tiempo, entonces la
duración en el tiempo es otra prueba para un desarrollo de ideas
verdadero, fructífero y creíble. La sobriedad es una característica de
aquellas personas mas indispuestas a los cambios, temen a las reformas e
innovaciones, además si son demasiado profundos prefieren sufrir algunas
calamidades antes de que se pueda aplicar el remedio. La posibilidad de
una corrupción lenta , no les incomoda. En otro sentido, las
revoluciones generalmente son violentas y cambiantes; de hecho son la
trayectoria de una corrupción. El curso de las herejías es siempre
corto; es un punto intermedio entre la vida y la muerte del desarrollo
de las ideas, o algo más parecido a la muerte, o algo, que si no resulta
en su muerte, se resuelve en algo nuevo, posiblemente opuesto y en el
curso del error, algo con lo que se pierde toda conexión; y solo así, un
principio herético puede continuar con vida por muchos años mas. Primero
tomando un curso de acción y luego otro rumbo. Es cierto que la
descomposición es una forma de corrupción, es lenta, es un estado en el
que no hay una acción violenta o vigorosa; aun cuando sea de carácter
conservador o destructivo, la influencia hostil es lo suficientemente
fuerte como para que se mantenga débil la vida, pero no para que termine
rápidamente su proceso. Así, se conocen opiniones, manejos y sistemas,
que son de un aspecto imponente y venerable, pero que carecen de
integridad en su interior y se mantienen vivos por el hábito de su
consistencia; o por su dependencia de una institución política; o se
convierten casi, en características de un país, o hábitos de una raza, o
en modas de una sociedad. Y después, a la larga, dejan de funcionar de
un momento a otro y mueren bajo una tajante influencia externa. Es el
caso también de las supersticiones que permanecen en una población, las
que no tienen un curso de acción, ni tienen una historia. Así es como
una corrupción se diferencia de un desarrollo de ideas al decaer por su
acción energética o por su carácter transitorio[^32].

## Corolario V

La doctrina de la Iglesia Católica es un reflejo de la fe primitiva, que
nace cuando los padres de la iglesia defienden con la razón el legado de
Jesucristo frente a los argumentos de otras filosofías y doctrinas que
han intentado suprimirla o debilitarla desde entonces, como sucede hoy
al separar la fe de la razón. Su desarrollo ha contribuido a la
interpretación de la divina revelación y al legado de Jesucristo
expuesto en la Biblia, frente a los avatares y exigencias de cada época.
El dogma o principios de la iglesia Católica y su doctrina son la
columna vertebral para el entendimiento de la fe a partir de la palabra
de Dios y para el conocimiento de Jesús en quienes están abiertos a la
gracia del Espíritu Santo; es además un elemento que unifica la
comunidad Católica bajo una misma iglesia. Jhon Henry Newman, teólogo y
filósofo convertido del anglicanismo Inglés al catolicismo, durante su
proceso de conversión , en su ensayo sobre el desarrollo de la doctrina
Católica, se permitió revisar la doctrina Cristiana desde sus inicios y
concluir de manera positiva su veracidad y rectitud frente a una posible
corrupción. Las siete notas de Newman que llevan a dicha conclusión son
la preservación de tipo, la continuidad de los principios, el poder de
asimilación, la anticipación de su futuro, la secuencia lógica, la
acción conservadora según su pasado y el vigor crónico. Dicha visión de
la doctrina Católica está plenamente vinculada con la formación y
desarrollo de la civilización, especialmente del mundo occidental, con
el cual la iglesia como un solo cuerpo está entrelazada a lo largo de su
historia.

[^1]: San Esteban
    <https://es.catholic.net/op/articulos/72125/cat/913/san-esteban.html#modal>

[^2]: Antigua ciudad de Galilea , actualmente en el estado de Israel
    [https://es.wikipedia.org/wiki/S%C3%A9foris](https://es.wikipedia.org/wiki/Séforis)

[^3]: Biografía de Reza Aslan
    [https://www.rezaaslan.com](https://www.rezaaslan.com/)

[^4]: El Zelote, la vida y la época de Jesús de Nazareth, escrito por
    Reza Aslan , páginas 68 a 78. <http://rezaaslan.com/>

[^5]: Breve Historia del mundo, H.G Wells, páginas 147 - 154

[^6]: Nicolas Notovich propuso en 1887 dicho acontecimiento, pero fue
    posteriormente desmentido, puesto que admitió la falsedad de la
    información.

[^7]: Unknown years of Jesus
    [https://en.wikipedia.org/wiki/Unknown_years_of_Jesus#:\~:text=He%20spent%20six%20years%20in,at%20the%20age%20of%2029.](https://en.wikipedia.org/wiki/Unknown_years_of_Jesus#:~:text=He spent six years in,at the age of 29.)

[^8]: An Essay on the Development of Christian Doctrine, Jhon Henry
    Newman <https://www.newmanreader.org/works/development/>

[^9]: On the Process of Development in Ideas, Jhon Henry Newman,
    <https://www.newmanreader.org/works/development/chapter1.html#section1>

[^10]: Aspectos que para su entendimiento se requiere de un estudio más
    profundo de la Teología Cristiana, que el pretendido en el presente
    documento.

[^11]: On the Kinds of Development in Ideas, Jhon Henry Newman
    <https://www.newmanreader.org/works/development/chapter1.html#section2>

[^12]: Credo de Atanasio,
    <https://ec.aciprensa.com/wiki/Credo_de_Atanasio>

[^13]: Genuine Developments Contrasted with Corruptions
    <https://www.newmanreader.org/works/development/chapter5.html>

[^14]: Biografía de San Vicente de Lerins
    [https://ec.aciprensa.com/wiki/San_Vicente_de_L%C3%A9rins](https://ec.aciprensa.com/wiki/San_Vicente_de_Lérins)

[^15]: First Note of a Genuine Development---Preservation of Type
    <https://www.newmanreader.org/works/development/chapter5.html#section1>

[^16]: Biografía Pelagio, monje de origen Británico
    <https://www.biografiasyvidas.com/biografia/p/pelagio.htm>

[^17]: Pelagio y Pelagianismo
    <https://ec.aciprensa.com/wiki/Pelagio_y_Pelagianismo>

[^18]: El Dogmatismo es un pensamiento filosófico originario de la
    antigua Grecia ( siglo VI -- VII AC), probablemente a partir de
    Tales de Mileto; se caracteriza por la defensa de que hay verdades
    absolutas; posición contraria al escepticismo, el cual está
    caracterizado por la duda constante.
    [https://economipedia.com/definiciones/dogmatismo.html#:\~:text=El%20dogmatismo%20es%20una%20doctrina,se%20opone%20frontalmente%20al%20escepticismo.](https://economipedia.com/definiciones/dogmatismo.html#:~:text=El dogmatismo es una doctrina,se opone frontalmente al escepticismo.)

[^19]: Matemático Griego, Padre de la geometría
    <https://www.biografiasyvidas.com/biografia/e/euclides.htm>

[^20]: Axiomas Euclidianos: i) dados dos puntos se puede trazar una
    recta que los une ii) cualquier segmento puede ser prolongado de
    forma continua en una recta ilimitada en una misma dirección iii) se
    puede trazar una circunferencia en cualquier punto y radio
    cualquiera iv) todos los ángulos rectos son iguales v)por un punto
    exterior a una recta se puede trazar una recta paralela.

[^21]: El perímetro de un rectángulo es igual a la suma de todos sus
    lados
    [https://es.wikipedia.org/wiki/Rect%C3%A1ngulo](https://es.wikipedia.org/wiki/Rectángulo)

[^22]: En el Cristianismo Católico, las bienaventuranzas nacen del
    sermón del monte. Todos anhelamos ser felices:
    <http://es.catholic.net/op/articulos/18376/todos-anhelamos-ser-felices.html>

[^23]: Second Note---Continuity of Principles, Jhon Henry Newman
    [https://www.newmanreader.org/works/development/chapter5.html#section2](../Ciencia_religión/Section%202.%20Second%20Note—Continuity%20of%20Principles)

[^24]: Third Note---Power of Assimilation
    <https://www.newmanreader.org/works/development/chapter5.html#section3>

[^25]: Biografía San Pacomio
    <https://es.catholic.net/op/articulos/34785/pacomio-santo.html#modal>

[^26]: Biografía de San Bacilio
    <https://ec.aciprensa.com/wiki/San_Basilio_el_Grande>

[^27]: Modo de vida en que las personas viven en aislamiento del mundo
    bajo votos religiosos y sujetos a una regla fija como monjes,
    monjas, frailes o como religiosos en general
    <https://ec.aciprensa.com/wiki/Monacato>

[^28]: Biografía San Jerónimo
    [https://www.aciprensa.com/recursos/Biografía-3423](https://www.aciprensa.com/recursos/biografia-3423)

[^29]: Fourth Note: Anticipation of Its Future
    <https://www.newmanreader.org/works/development/chapter5.html#section5>

[^30]: Fifth Note---Logical Sequence
    <https://www.newmanreader.org/works/development/chapter5.html#section4>

[^31]: Sixth Note---Conservative Action upon Its Past
    <https://www.newmanreader.org/works/development/chapter5.html#section6>

[^32]: Seventh Note---Chronic Vigour
    <https://www.newmanreader.org/works/development/chapter5.html#section7>
