---
title: "Parte 3"
format:
  html:
    toc: true
    toc-depth: 5
    number-sections: false
    theme: cosmo
    css: styles.css
---
# **CAPÍTULO III**

## El amor como cristal espiritual

La revelación en la religión Cristiana, confirma algo irrefutable para
una persona de fe: toda la creación, el universo que seguimos
descubriendo, las fuerzas de la naturaleza y todas las especies
vivientes incluidos el ser humano son en esencia, en su raíz o en su
génesis: "muy buenos"[^1]. La maldad, existe, pero carece de
demostración científica; la perfección de las leyes de la ciencia sobre
las que descansa la verdad científica no pueden confirmar que en ellas
mismas exista algo de maldad en el mecanismo perfecto del universo. Nada
de esto sería posible sin que en toda la creación actuara desde el
principio el amor divino; algo esencialmente superior al amor humano. En
la vivencia espiritual del amor divino, Dios no preparó la muerte para
los hombres[^2]; esta es un resultado de la voluntad de la familia
humana al alejarse de Dios en plena libertad. Frecuentemente se presenta
la situación en la cual, cuando un hijo se aleja de sus padres, sin
acoger el consejo previo a un peligro inminente, resbala en él. Si el
padre es amoroso, solo deseará rescatarle y el hijo le buscará
arrepentido. En un sentido amplio, la humanidad busca a Dios
incansablemente; la herida espiritual causada por su desobediencia
permanece abierta y solo el amor de Dios le puede resarcir. Dios ha sido
siempre fiel a su palabra y la humanidad ha conservado su libertad, pero
ella es su mayor escollo, puesto que cada vez que tiende a construir sus
propios caminos alejados de Dios para alimentar su vacío espiritual,
termina sufriendo su propia esclavitud, su yugo al dominio del "otro",
su propia caída; pero Dios permanece como aquel padre misericordioso,
dispuesto a levantarle, una y otra vez. Para darle sentido a dichas
afirmaciones, continuaré con el ejercicio de la razón desde la fe
Cristiana, como un camino hacia la verdad absoluta, que es, Jesucristo.
Pretendo argumentar cómo el amor de Dios, bastión inquebrantable de la
fe, está siempre presente en dicho camino, de manera transparente, en su
perfección pura y diáfana de su amor infinito y no como simple
herramienta de adoctrinamiento o moralización. Aunque es tarea imposible
definir el amor divino, si es factible acariciar en su superficie algo
de su luminosidad al compararse desde algunos aspectos que se reflejan
ante la manera imperfecta del ser humano. Tal como la transparencia de
un cristal permite que sea observado temporalmente por el diáfano
reflejo de una luz y en aquel ejercicio se puede identificar la
turbiedad del cristal, así se podrá intuir la experiencia manifestada
desde el amor de Dios, que advierte sobre la turbiedad del cristal
espiritual que permanece en el ser humano y la civilización que
construye cada día. No sin antes dejar sentado que quien tenga como
deseo sumergirse en aquel amor divino, debe acudir a la Biblia, a los
textos y recursos teológicos de la religión Cristiana, o simplemente
debe abrirle las puertas de su corazón a Jesús, para que le guíe en
aquel camino de fe del "corazón encontrando al corazón", como lo afirma
Newman, puesto que es bajo su amparo que se hace la presente reflexión.
La luminosidad del amor divino vista a través de los cristales de la
misericordia, la justicia, la paz, la naturaleza, el sufrimiento y la
sabiduría permitirán identificar algo de la turbiedad en la naturaleza
humana.

## La misericordia

La misericordia, en su etimología, proviene del latín "misere," -
miseria , - "cordis" , - corazón -- "ia" hacia los demás. Implica tener
reconocer la miseria del otro y tener un corazón solidario y bondadoso,
o de compasión con el sufrimiento del necesitado, que deriva en la obra
y la acción de la caridad. La misericordia y la caridad están
estrechamente vinculadas. También, la misericordia está acompañada de la
empatía, aquella capacidad de ponerse en la situación, buena o mala, de
otro ser humano, de intentar vivir su experiencia, su verdad individual
en el si mismo. Tanto la compasión como la empatía llevan a la caridad y
están más vinculadas a un valor emocional y del sentir de la naturaleza
humana; siendo la misericordia más vinculada a una virtud espiritual
desde la religión Cristiana y también, de diferente manera, desde otras
religiones o filosofías de vida.

La empatía es más factible desarrollarla entre los individuos
pertenecientes a grupos de intereses comunes, pero puede ocurrir entre
individuos pertenecientes a diferentes grupos de interés. La empatía ha
sido crucial en el desarrollo económico de la civilización, ya que los
lazos comerciales entre diferentes grupos sociales, se fortalecen
inicialmente a partir de ella. En dicho caso hay una especie de
simbiosis y de interés común en el que, como individuo o grupo social se
puede desarrollar una acción de colaboración, de ayuda, o de tipo
comercial hacia otro individuo o grupo social; siempre esperando una
retribución. Pero, la empatía tiene también como resultado el entender
la dificultad o el sufrimiento de otro individuo o grupo social, que
genera una acción de caridad, demostrada en la ayuda desinteresada al
individuo o grupo social por el que se siente empatía. La civilización
empática es expresada ya sea a través de las profundas raíces de una
economía globalizada, o a través de la caridad , de ayudas individuales
o masivas, que gracias a la comunicación tecnológica se pueden realizar
entre las diversas culturas globales. [^3]

La sociedad contemporánea está evolucionando hacia la construcción de
una civilización empática, más allá que a una civilización orientada a
la misericordia. Los desastres naturales en la sociedad moderna pueden
activar la empatía de gran parte de la población mundial en un instante;
el tsunami del 26 de Diciembre del 2004 en Asia con más de 225 mil
muertes es una muestra, en la cual, la caridad de millones de personas
en el mundo estuvo actuando con frente a los cientos de miles de
personas que quedaron destrozados física y emocionalmente. La caridad en
el mundo estuvo presente como elemento fundamental para sobrellevar la
mayor pandemia de los últimos cien años, el COVID-19. Jeremy Rifkin
(Denver, 1945 -- actualmente )[^4] en su libro "La civilización
empática" hace una caracterización de la evolución de la empatía en la
sociedad moderna en la cual "La seguridad individual aumenta la empatía"
, entendiéndose como parte importante de la seguridad individual, la
seguridad económica y material. Rifkin identifica tres etapas en la
evolución de la empatía social. Una primera etapa en la que, la sociedad
sub desarrollada y pre industrial se esfuerza por sobrevivir y en la
cual los valores tradicionales religiosos y familiares se imponen en la
organización de la vida social en la que predominan las jerarquías. Una
segunda etapa en sociedades en proceso de desarrollo económico, en la
que los valores materialistas y racionales se imponen, en este sentido,
la acumulación de riqueza se convierte en una fuerza liberadora. Y una
tercera etapa en la que el individuo post materialista, experimenta una
transformación hacia valores de índole no material , en lo que se resume
como la aspiración a una mejor "calidad de vida". En una investigación
realizada en el año 2005, se encuentra que en el año de 1971 los
materialistas superaban a los no materialistas en las seis naciones
occidentales para las que se hizo la investigación. En el año 2005 los
post materialistas, igualaban a los materialistas en esos seis países,
marcando así una tendencia de la mayor oleada de extensión empática en
toda la historia de la humanidad. Sin embargo, concluye Rifkin, aquellos
en esta tercera etapa de la evolución empática se reducen a las
poblaciones acomodadas de las naciones mas desarrolladas y a los
enclaves de clase media de los países en desarrollo. Sin embargo, llegar
a este punto de desarrollo económico, ha implicado un desgaste
desenfrenado de los recursos naturales del planeta que en algunos
aspectos podrían ser irreversibles y con efectos de incremento sobre la
pobreza global; otro aspecto implícito en el desarrollo económico es la
distribución de la riqueza en el mundo cuya tendencia genera división y
controversia. [^5] Concluye Rifkin " La pregunta es si esa minoría que
está experimentando esta oleada empática aun a costa de empobrecer el
planeta y a gran parte de la especie humana , será capaz de traducir sus
valores post materialistas en un plan de acción cultural, económico y
político que pueda dirigir, tanto a ellos como a sus comunidades , hacia
un futuro mas sostenible e igualitario a tiempo de evitar el
abismo"[^6]. Es de anotar entonces que si, la empatía en su mejor
expresión de evolución social de acuerdo a los principios y valores
desarrollados por la humanidad del progreso moderno está estrechamente
ligada, a la aspiración de una riqueza individual como manifestación del
bienestar y como condición liberadora para construir una "calidad de
vida", entonces, el reto para lograr una cierta igualdad económica[^7] y
estable a nivel global, es bastante complejo; según la tendencia global
del índice de gini medida desde el año 1950 hasta el 2020, la
desigualdad absoluta medida en USD tiende a incrementarse
considerablemente, aunque la medida en términos relativos tiende a
disminuir un poco a partir de 1990[^8]. La empatía en el sentido de la
Cristiandad ha sido estudiada por Edith Stein desde una perspectiva
psicológica y desde la fenomenología, corriente filosófica que estudia
la relación del mundo con la consciencia; el legado de Stein merece
atención especial en capítulos posteriores de este documento.

La relación misericordia -- empatía, expuesta por Rifkin queda en este
sentido estancada , ya que la dirección empática condicionada a un
materialismo que tiende a ser egocéntrico, dista de formar parte del
significado de la misericordia Cristiana, sostenida por el amor que se
entrega al prójimo sin condiciones. La luz de la gracia de Dios
desarrolla esa capacidad de entender lo que se puede vislumbrar como un
anhelo ante la turbiedad de la humanidad por alcanzar el estado ideal
del cristal espiritual y transparente de la misericordia.

## El cristal de la misericordia

Los primeros Cristianos, entendieron la verdadera misericordia desde un
sentido completamente nuevo en aquel entonces, un significado con su
esencia en el amor divino; en ellos sus comunidades participaban de un
principio económico diferente, en el cual compartir la riqueza desde la
bondad del corazón era su esencia. La tiranía de los reyes y emperadores
de la época definía la forma de dominación económica. El amor humano
estaba todavía despierto y activo, aún en el post modernismo, por ello
se refleja en acciones de empatía y caridad, especialmente a través de
miles de instituciones con influencia teológica[^9], entre ellas la
iglesia Cristiana. La situación en la actualidad es la de una humanidad
encaminada hacia una misericordia -- empática como expresión de
principios y valores, no necesariamente originada en la bondad y en el
amor, sino en un valor correlacionado a la riqueza material generador de
bienestar, a través de una aspiración a construir cierta calidad de
vida, en el cual el si mismo está en primer lugar y solo si se satisface
su necesidad, se puede pensar en la comunidad. Es así como la
misericordia en la humanidad tiene un sentido ambivalente. En este caso,
la humanidad construye una distancia cada vez mayor con la misericordia
divina, entendida en un contexto de fe desde la religión Cristiana.

La misericordia en la Cristiandad es la única, entre todas las
religiones y filosofías de vida de la civilización humana que, enseñada
por Jesucristo, implica la posibilidad de una entrega total del si mismo
por la acción de caridad o bondad, en el rescate del sufrimiento del
necesitado o incluso en la acción del perdón. La acción misericordiosa
de Dios está presente desde antes del hecho mismo de la creación; y tal
vez, este es el acto más representativo del amor divino. El amor divino
actúa desde la fe, a través de la caridad desinteresada y la
compasión[^10], en la misericordia. La fe y la razón cristianas culminan
en una acción desde la caridad que nace en el si mismo fortalecida por
la gracia del Espíritu Santo; la misericordia divina se expresa, no
unicamente mediante la empatía, si no como fruto del amor divino en un
sentido tan amplio que aplica aún para el enemigo; en este sentido la
caridad es inagotable e infinita en su alcance, algo que "va más allá de
la razón". También la misericordia de Dios, se expresa en un acto, tal
vez, mucho más misterioso, que como en la caridad, requiere de la
humildad y de la acción del Espíritu Santo: el perdón. Siendo así, la
revelación Divina en la palabra de Dios nos hace entender de manera
simbólica que el ser humano es pecador por voluntad propia. Su
desobediencia al único Dios de amor parte de su propia libertad y se
transforma en pecado en la medida en que se aleja de su padre, Dios;
queda entonces a merced de su propia debilidad, en ocasiones intentando
reemplazar a Dios, en ocasiones quedando a merced del mal espiritual. El
libro del Génesis describe el pecado original en el cual el ser humano
desobedece, tentado por el espíritu del mal, a Dios cuando ordena "no
comerás del árbol de la ciencia del bien y del mal"[^11]. El Vestigio
del pecado permanece latente en todo ser humano, se hereda porque la
humanidad es una gran familia. El ser humano estaba destinado a vivir en
un lugar donde no existía el sufrimiento ni la muerte, era el hogar
abundante en el amor divino, en una vida con un componente espiritual
embebido en el Espíritu Santo , hogar en el cuál el bien y el mal no
co-habitaban en el espíritu del ser humano. Pero ocurrió la
desobediencia del mandamiento en torno al conocimiento y al deseo de ser
igual a Dios. Este fue el pecado original, pecado que tiene su raíz en
la soberbia, contraria a la humildad y que además marcó a toda las
generaciones de la humanidad. La esencia del pecado nace del libre
albedrío del ser humano por actuar de manera injusta contra Dios y por
consiguiente contra si mismo. Quien no ama a Dios y a su prójimo, no
puede amarse a si mismo. La manera incorrecta de actuar , es el castigo
en sí, el cual no es causado por Dios, si no por el distanciamiento
voluntario de Dios. Es el origen humano del dolor y del sufrimiento. Es
el origen de la muerte. Pero , la omnipotencia de Dios, entendida y
experimentada desde la fe, es capaz desde su misterio de revertir aquel
dolor y sufrimiento humanos, para transformarlos de la mano de Jesús en
un retorno a Dios. Solo Dios, en su gracia infinita es capaz de sacar el
bien de todo mal. Es un fruto de su infinita misericordia, un misterio
inalcanzable por la razón humana. El catecismo Católico dice así: El ser
humano no nace con el pecado original a nivel individual; ¿Cómo el
pecado de Adán vino a ser el pecado de todos sus descendientes? .Todo el
género humano es en Adán "sicut unum corpus unius hominis (\"Como el
cuerpo único de un único hombre\") (Santo Tomás de Aquino, Quaestiones
disputatae de malo, 4,1). Por esta \"unidad del género humano\", todos
los hombres están implicados en el pecado de Adán, como todos están
implicados en la justicia de Cristo. Sin embargo, la transmisión del
pecado original es un misterio que no podemos comprender plenamente.
Pero sabemos por la revelación que Adán había recibido la santidad y la
justicia originales no para él solo sino para toda la naturaleza humana:
cediendo al tentador, Adán y Eva cometen un pecado personal, pero este
pecado afecta a la naturaleza humana, que transmitirán en un estado
caído (cf. Concilio de Trento: DS 1511-1512). Es un pecado que será
transmitido por propagación a toda la humanidad, es decir, por la
transmisión de una naturaleza humana privada de la santidad y de la
justicia originales. Por eso, el pecado original es llamado \"pecado\"
de manera análoga: es un pecado \"contraído\", \"no cometido\", un
estado y no un acto.[^12] El Papa Francisco lo resume así: "¿Por qué
somos pecadores? Porque existe el pecado original. Un dato que se puede
constatar. Nuestra humanidad está herida, sabemos reconocer el bien y el
mal, sabemos que es el mal, intentamos seguir el camino del bien pero a
menudo caemos por causa de nuestra debilidad y escogemos el mal. Es la
consecuencia del pecado original , del cual tenemos plena consciencia
gracias a la revelación. El relato del pecado de Adan y Eva , la
rebelión contra Dios que leemos en el Génesis, sirve de un lenguaje
imaginativo para exponer algo que realmente ha sucedido en los orígenes
de la humanidad."[^13] En su justicia divina y en su omnipotencia, Dios
respeta el libre albedrío del ser humano y sufre con el pecado humano.
Como lo afirma el Papa, su secuela no es tan misteriosa como parece; el
mismo reflejo del pecado original persiste como evidencia, en el
ejercicio de la razón en la fe, día a día. Cuantas veces se escucha la
historia de aquel hijo que despreciando los lineamientos de sus Padres,
desobedece, dirigiéndose a un lugar que le han prohibido. El sufrimiento
de sus Padres es aún mayor cuando aquel hijo es ultrajado. ¿ Que no
darían sus Padres por haberle retenido?. La humanidad con su
desobediencia decidió abandonar el hogar de Dios, a pesar de su
advertencia. Y es en el acto de misericordia divina que Dios le brinda
la oportunidad al ser humano de regresar. Misericordia que se alimenta
de un amor divino que adquiere sentido en la muerte y resurrección de
Jesucristo, entregando su vida por el perdón de cada ser humano a través
de toda la historia de la humanidad. El ser humano por si mismo, en
muchos casos es incapaz de perdonar aún a su hermano de sangre. En la
primera descendencia de Adan y Eva, Caín mató a Abel por celos; durante
siglos y hoy mismo se masacran a miles de hermanos inocentes
justificando de una u otra forma las guerras. La misericordia divina
aparece como un reglo de Dios para vencer el pecado. Es como el grito
desesperado de los Padres a su hijos! regresen a casa por favor!. Y esta
es la esencia de la misericordia, pues si no fuera ese el caso, la
humanidad no hubiera tenido la oportunidad de regresar al jardín del
edén, no sin antes reconocer y resarcir su falta. La humanidad con sus
inventos, pensamientos, ideologías y acciones, intenta , pero no es
capaz de cerrar la brecha espiritual que abrió al ofender a Dios.
Entonces la misericordia actúa , para aquel individuo o grupo social que
se reconoce como ser humano, débil y pecador , pero poderoso y vencedor,
no en la violencia, sino en el amor y en el perdón acompañado de la mano
de Dios. La humanidad cae, el individuo cae, pero para Dios lo que vale,
es que tenga la capacidad de levantarse nuevamente, una y otra vez. Y ,
a pesar de las continuas ofensas a Dios, le sigue respetando su propia
voluntad a la humanidad y le sigue perdonando si se lo pide y nunca a
ningún individuo le impone sus mandamientos. Dios en su sabiduría
perfecta, perdona también de manera individual a quien de tantas maneras
le rechaza continuamente; y es esta la máxima expresión de la
misericordia de Dios, que actúa desde el amor incondicional a través del
perdón, desde el amor divino. Esta acción misericordiosa es un llamado
mediante el lenguaje de la fe, en el corazón del ser humano, en su
verdad individual y con la ayuda del Espíritu Santo. Solo cuando el
mensaje de Dios es escuchado con humildad en las profundidades del
silencio en el alma de cada individuo, inclusive aún después de actuar
constantemente en la degradación más alta e inimaginable, aún si el
mensaje es aceptado en el último instante de su vida, en el momento en
que el individuo abre su corazón a Dios, tal como lo expresa Newman, es
el corazón del individuo encontrando el corazón de Dios, en ese momento
misterioso el individuo experimenta, vive y siente el verdadero
arrepentimiento ante Dios. Es tal vez una de las expresiones más
contundentes y poco entendidas, que reflejan el amor divino como efecto
de la verdadera fe. Sobre esto dice el Papa Francisco "La iglesia
condena el pecado porque debe decir la verdad. Dice -- esto es pecado -.
Pero al mismo tiempo abraza al pecador que se ofrece como tal, se acerca
a él, le habla de la misericordia infinita de Dios. Jesús ha perdonado
incluso a aquellos que lo condenaron en la cruz y lo despreciaron..." y
sigue ..."..Dios, que ha entregado a su hijo por nosotros, no puede mas
que revelarse como misericordia. Dios es un Padre, primoroso, atento,
dispuesto a acoger a cualquier persona que de un paso adelante o que
tenga el deseo de dar un paso hacia casa. Él está allí contemplando el
horizonte, nos aguarda, nos está ya esperando. Ningún pecado humano, por
muy grave que sea, puede prevalecer sobre la misericordia o limitarla."
[^14] La encarnación, muerte y resurrección de Jesucristo que se hace
misterio y realidad durante la eucaristía es el culmen de la fe en la
religión Católica; sin este acto misericordioso, sería imposible que el
ser humano, aquel que es obediente en el amor divino y humilde en el
reconocimiento de su débil condición pecadora, pudiera regresar por si
mismo a casa. Aunque propio de cada uno (cf. ibíd., DS 1513), el pecado
original no tiene, en ningún descendiente de Adán, un carácter de falta
personal. Es la privación de la santidad y de la justicia originales;
pero la naturaleza humana no está totalmente corrompida: está herida en
sus propias fuerzas naturales, sometida a la ignorancia, al sufrimiento
y al imperio de la muerte e inclinada al pecado ,esta inclinación al mal
es llamada \"concupiscencia\"[^15]. El Bautismo, dando la vida de la
gracia de Cristo, borra el pecado original y devuelve el hombre a Dios,
pero las consecuencias para la naturaleza, debilitada e inclinada al
mal, persisten en el hombre y lo llaman al combate espiritual.[^16]

Aún en un mundo encaminado a la empatía post materialista, la expresión
de la misericordia divina en el ser humano, es muy real y es palpable
desde la vida de personas desbordadas en su fe en la vivencia de la
gracia de Dios; La misericordia adquiere un significado presencial a la
luz de Jesús, que va mucho más allá de la misericordia del ser humano.
Su misericordia parte del amor divino, es fuente de alegría, de
serenidad y de paz. Es condición para nuestra salvación entendida como
el regreso al paraíso, a la compañía de Dios. Es la palabra que revela
el misterio de la Santísima Trinidad. Es el acto último y supremo con el
cual Dios viene a nuestro encuentro. Es la ley fundamental que habita en
el corazón de cada persona cuando mira con ojos sinceros al hermano que
encuentra en el camino de la vida. Es la vía que une a Dios y al ser
humano, porque abre el corazón a la esperanza de ser amados para siempre
no obstante el límite de su pecado. La madre Teresa (Skopie , 1910 --
1997, Calcuta)[^17] es una de las tantas representantes de esta
misericordia divina, transmitida por las enseñanzas de Jesús a sus
discípulos.

### La madre Teresa, un cristal de misericordia

Aunque la aspiración de un ser humano a enriquecer su misericordia desde
las enseñanzas de Jesús, parecieran ser utópicas en la sociedad del
progreso, tan solo hasta hace pocas décadas la Madre Teresa de Calcuta
le dio una lección, que todavía perdura, a la humanidad sobre la
aplicación de la visión de la misericordia divina a través de la
caridad. Parte de su legado es el de ayudar a los "mas pobres de los
pobres". Sus acciones de extender el amor de Dios a aquellas personas
que han perdido su dignidad ante la sociedad, en palabras de la Madre
Teresa: "El desprecio que los marginados reciben de la sociedad es la
mas despreciable de las pobrezas", dadas sus condiciones de pobreza
material, inanición o enfermedad, las acciones de la Madre Teresa llevan
todavía la esperanza, incluso a aquellas personas moribundas , o de
cualquier creencia religiosa o condición , de sentirse seres humanos
amados por Dios. En la época de Jesús les llamaban leprosos , hoy les
llaman desechables. La lección de la Madre Teresa es una muestra
tangible de las enseñanzas de Jesús en sus acciones para con los
leprosos; en una época, tan lejana y tan cercana a la vez, en que las
personas eran expulsadas de sus comunidades y su dignidad reducida a una
mínima expresión. A pesar de que la pobreza extrema se ha reducido
considerablemente en términos absolutos durante las últimas décadas,
todavía más de 700 millones de personas viven en condiciones
traumáticas. La Madre Teresa sigue ayudando a través de la congregación
de las "Hermanas misioneras de la caridad"[^18] en más de 137 países; el
objetivo de su congregación dice así "El objetivo de la Sociedad es
saciar la sed infinita de Jesucristo en la Cruz por amor y por almas
viviendo de los cuatro votos en un espíritu de confianza amorosa,
entrega total, y alegría, acompañando a cada uno al amor perfecto de
Dios y del prójimo y haciendo a la iglesia plenamente presente en el
mundo de hoy." Pero , el concepto de pobreza que quiere difundir la
Madre Teresa, va mucho más allá de la pobreza material. La Madre Teresa
decía que en los países desarrollados, a pesar de que también había
pobreza material , aunque menos visible, había una pobreza "peor" que la
pobreza material. En una entrevista realizada en Lima en 1989 decía
"...En todos ellos ( países ricos ) hay una muchedumbre de personas que
sufren soledad, desamor, enfermedades físicas y morales, que constituyen
una pobreza mayor que la material y más difícil de solucionar. Si
alguien necesita un pedazo de pan, basta ofrecérselo para saciarlo; si
necesita descanso, basta una cama. Pero ante un ser humano abandonado,
no basta la ayuda material, se precisa una ayuda efectiva y espiritual
que es mucho más difícil."[^19] En los servicios que prestaba en estos
países, era para ella un tipo de pobreza peor que la pobreza extrema,
ver la soledad de los ancianos o la sed de amor de los adictos a las
drogas. En la sociedad contemporánea, este tipo de pobreza "espiritual"
fuertemente señalada por la Madre Teresa, es algo sobre lo que la verdad
científica no tiene explicación. El apoyo de la ciencia de la salud
mental es de suma importancia y juega un papel vital en la sociedad del
progreso; pero sin las recetas y las dosis de "amor", como las aplican
personas extraordinarias incluida la Madre Teresa, el apoyo desde las
ciencias de la salud puede caer en el vacío. El camino de la humanidad,
puede estar siendo trazado hacia una sociedad post modernista que queda
atrapada en un "vacío espiritual"; un vacío que se intenta sobreponer
desde una espiritualidad elaborada por y para el si mismo, teniendo como
cimiento la empatía propia y no la misericordia de Dios. Es entonces
indispensable preguntarse si para la sociedad del progreso, de la
técnica y de la ciencia, de los países que aspiran a ser
"desarrollados", el camino de la empatía humana es suficiente, o si las
lecciones de la Madre Teresa, deben ser tomadas en serio y de qué
manera.

La misericordia en la Cristiandad se manifiesta a través de la
invitación, al perdón. El perdón divino solo se origina en la justicia
de Dios; pero el ser humano está en la capacidad de imitar a Jesús, en
su entrega total del si mismo, aún para perdonar. Un perdón con raíces
en Jesús, en el amor divino, no es un perdón interesado. Una madre
verdaderamente amorosa, es capaz de entregar su vida por su hijo para el
obtener perdón a un castigo cruel. En relación al perdón, existen
diferentes grados del perdón en los marcos de justicia de las naciones,
varían de acuerdo a los criterios de la definición del pago en forma de
castigo o retribución a la sociedad por los actos realizados en su
contra; la administración de la justicia es en diferentes grupos de
interés, definida con diferentes formas del perdón; en algunas
sociedades, de acuerdo a las circunstancias puede ser imposible
obtenerlo; en otras hay una flexibilidad mayor. El perdón es también una
decisión personal como parte de la cultura social que se refiere a las
acciones , en teoría, menos traumáticas para la sociedad tal como las
ofensas personales, la generación de rumores dañinos, los actos de
desamor, y una gran gama de comportamientos culturales de las relaciones
interpersonales. Desde esta perspectiva el perdón es abordado y aplicado
de diferentes formas por las diferentes religiones, tradiciones
culturales, filosofías e interpretaciones desde la verdad individual. En
dicho sentido, el perdón , en términos generales no es un acto
"indispensable", como si lo es la aspiración al bienestar del si mismo,
o a una calidad de vida digna en el contexto del progreso social
moderno; el perdón no forma parte importante de los modelos de
principios y valores contemporáneos, por ende, no se enseña, no se
refleja en la mayoría de los sistemas de educación técnica y en muchos
casos es perfilado como signo de debilidad.

La misericordia de Dios, siendo algo sobrenatural, también actúa en su
misterio entre los seres humanos desde el perdón; un perdón infinito que
tuvo a Jesús como su primer exponente en su reconocida frase "Padre,
perdónalos porque no saben lo que hacen"[^20], mientras soportaba un
sufrimiento desconsolador y una humillación indigna, estando clavado en
la cruz. Quienes logran entrar en la gracia de Dios, con una fe
verdadera pueden llegar a actuar de una manera que fácilmente podría ser
entendida como un acto irracional. Maria Goretti (Corinaldo,
1890-Nettuno,1902)[^21] una niña, parte de una humilde familia campesina
Cristiana, tuvo seis hermanos. Su Padre falleció cuando ella tenía nueve
años, luego María tuvo que hacerse cargo de sus dos hermanos menores
mientras su madre hacía lo posible para mantener a sus hijos trabajando
y abandonándolos por largas horas. Compartían la casa con otra familia,
dadas sus condiciones económicas; otra familia, de principios y valores
diferentes. Ella tuvo el Don de la fe desde temprana edad, aquella fe
que no cuestiona y que camina de la mano con el mensaje de Jesús;
expresaba un profundo amor hacia Él y hacia la Virgen María; desde
pequeña se proponía a evitar todo pecado. Pero, sucedió algo digno de
las mejores escenas de terror. Alessandro , de 20 años, quien vivía en
la misma casa, hijo de la familia con la que compartían, comenzó a hacer
propuestas indecentes a la niña. Tan solo ella de once años de edad, al
rechazar las propuestas perversas por parte de Alessandro, este planeó
el momento preciso para intentar violarla; pero ella al no dejarse, fue
salvajemente acuchillada; María Goretti, sobrevivió habiendo sido
alcanzado el corazón , el pulmón izquierdo y el intestino. Sufrió el
dolor indescriptible durante veinte largas horas, durante las cuales los
médicos de la época no se explicaban como podía mantener su estado de
conciencia y sobrevivir a la magnitud de las heridas mortales. Durante
sus últimos alientos, el sacerdote que la atiende le pregunta ¿ María,
perdonas de todo corazón a tu asesino? Y ella que había estado en
constante oración y ofreciendo su dolor a la Virgen María, le responde
"Sí, lo perdono por el amor de Jesús, y quiero que él también venga
conmigo al paraíso. Quiero que esté a mi lado\... Que Dios lo perdone,
porque yo ya lo he perdonado." María recibe la comunión y la
extremaunción, y posteriormente fallece tranquila. Por otro lado,
Alessando es juzgado y condenado a treinta años de prisión y trabajos
forzados. Su comportamiento perverso y malvado sigue en su cautiverio;
pareciendo esa ser su actitud incuestionable. Sin embargo, seis años más
tarde tiene un sueño, en el que Maria Goretti le reitera su perdón y
esto genera un cambio abrupto en su comportamiento, arrepintiéndose
profundamente y de manera inexplicable según sus carceleros; pidiendo
perdón públicamente y a la familia de Maria Goretti. Cumplió 27 años de
castigo, tres menos por buen comportamiento y tan pronto obtiene su
libertad, en navidad de 1937 visita a Assunta, madre de María Goretti:
-\"Assunta, ¿puede perdonarme? -Si María te perdonó -balbucea-, ¿cómo no
voy a perdonarte yo?\". Luego comulgaron juntos ante una comunidad
sorprendida. Pero, la vida de Alessandro continúa, muy apegado a la
palabra de Jesús, tanto así que es aceptado en la orden de los
Capuchinos, donde termina sus días 24 años después. Fallece en 1970, a
sus 88 años; antes de morir deja una carta, que termina así: "Pienso que
la religión con sus preceptos no es una cosa que se pueda menospreciar,
sino que es el verdadero consuelo, el único camino seguro en toda
circunstancia, hasta las más dolorosas de la vida".[^22]

## La justicia 

No es difícil entender cómo el amor tergiversado en los principios y
valores de ciertas ideologías propias del ser humano entró a formar
parte del progreso mercantilista de los último siglos, convirtiéndolo
muchas veces en un producto más, vaciando su significado espiritual.
Para ilustrarlo, entre muchas formas de su desfiguración, es ya bastante
normal, observar la manera como el sexo y el erotismo se han convertido
desde 1870[^23] en una herramienta más de comercialización, llevando en
muchos casos, a veces de manera subliminal a la degradación de la
dignidad de la mujer, siendo esta una dimensión de la "injusticia
social[^24]", que aún se evidencia desde el modernismo. En este tipo de
eventos, como en muchos otros, la razón actúa justificando el progreso
económico. Sin embargo, la naturaleza "lícita " o "ilícita" del estado
del corazón del ser humano, fuente de la justicia en sus diferentes
esquemas y culturas, sigue manifestándose, aunque de manera cada vez mas
infructuosa, ya que aquella naturaleza intrínseca del amor tiende a ser
reemplazada por una interpretación puramente funcional de la razón en el
nivel público y social. No se puede negar que la justicia humana, en
términos generales, es cada vez más equitativa en su acceso y en su
aplicación; hoy es más factible que un ciudadano promedio del mundo
pueda recurrir a la justicia, aún frente a un ciudadano de las más altas
jerarquías sociales. Siglos atrás, el imperio del terror a quien pensara
en contra del rey o emperador era la forma conveniente de la ley. El rey
o el emperador podía fácilmente manipular sus inconveniencias y disputas
a su favor frente a un ciudadano de menor jerarquía social; pues muchas
veces era el mismo rey quien impartía la justicia. Hoy es posible juzgar
incluso a un presidente, a un primer ministro o a un individuo con gran
poder económico y político. No cabe duda de que el derecho y la ley
humanas han evolucionado en el sentido correcto que dicta el corazón y
tiene a la verdad científica como uno de sus mejores aliados, aunque no
necesariamente esto implique que la administración y aplicación de la
justicia sea equitativa y transparente en nuestros días.

La justicia, además de su connotación de igualdad en su aplicación para
todas las personas, termina por reflejar el estado de convivencia en
paz, deseado en todos los aspectos de la vida; aspectos que se reflejan
en la dignidad humana al interior de los variados grupos de interés, ya
sea grupos económicos, grupos sociales, instituciones públicas o en las
naciones. Debe argumentarse que en términos relativos la justicia
humana, representada en la dignidad del ser humano está en una mejor
posición que hace veinte siglos en su aspiración de convivencia. Tan
solo recientemente en la historia de la humanidad, entre 1945 y 1948, se
crea a través de las Naciones Unidas una "Declaración Universal de los
Derechos Humanos" como un ideal común para todos los pueblos y naciones.
A pesar de aquel gran logro, el camino para alcanzar tal ideal presenta
sin embargo la turbiedad propia de la naturaleza humana, es un camino
aún con muchos aspectos por corregir. Como herencia de los imperios y
culturas greco romanas, hoy en día persisten diversos esquemas novedosos
de esclavitud con cifras escandalosas.[^25]Uno de los derechos más
básicos es el derecho al trabajo, con cifras absolutas de desempleo
crecientes durante las tres últimas décadas[^26], el acceso de la
población al empleo en el mundo en términos porcentuales, medido como la
fuerza laboral empleada frente al total de la población en edad de
trabajar ha disminuido entre 1991 y 2019. [^27] La migración global
causada en gran medida por la acción de la injusticia se ha duplicado
desde el 2016 hasta el 2020.[^28]La creciente inequidad en la
distribución del ingreso económico, se debe enfrentar al crecimiento
exponencial de la población mundial[^29] y al calentamiento global,
fruto de un desaforado consumo de recursos naturales. El dominio geo -
político de unas naciones frente a otras conlleva a una impresionante
carrera armamentista. Todas estas variables y muchas otras más[^30], en
su conjunto, contribuyen enormemente a la "injusticia social" en un
complejo mapa de interacciones culturales y políticas sobre los cuales,
la civilización contemporánea a pesar de los esfuerzos de los liderazgos
mundiales se encuentra en una encrucijada para enfrentarla. Vista dicha
encrucijada como la turbiedad del cristal espiritual, sigue predominando
la ley del más fuerte en términos de desarrollo económico como bastión
del progreso moderno y el poder militar como la ecuación válida para
mantener el equilibrio entre las naciones, partiendo aún de la falta de
una única visión sobre el significado y adjudicación del poder mundial,
de manera coherente, transparente y equitativa en cuanto a la aplicación
de una justicia ya muy escrita y desarrollada a través de los siglos;
significado que adquiere diversos matices y alcances de acuerdo a la
cultura, región del planeta y a la influencia de los grupos de interés
que mayor poder puedan ejercer. El efecto de la "dominación" de unos a
otros, es la turbiedad del cristal espiritual, que sigue siendo una
herencia de la historia de la humanidad, un principio de acción en el
mundo contemporánea que aún es la causa de disputas de toda índole. La
injusticia se convierte entonces en una fuente de violencia; la
convivencia, entendida como la coexistencia pacífica de la sociedad
partiendo del respeto mutuo, sigue estando en entredicho aún cuando el
desarrollo científico y la tecnología ha incrementado considerablemente
los indicadores de bienestar. Es esta otra evidencia del efecto adverso
en la justicia que se vislumbra en la humanidad al carecer de un modelo
de principios y valores, que considere al ser humano en toda su
dimensión, más allá de su capacidad intelectual y productiva, como ser
espiritual. La justicia está directamente vinculada con la búsqueda de
la paz: "La paz no es la mera ausencia de la guerra, ni se reduce solo
al establecimiento de un equilibrio de las fuerzas adversarias, ni surge
de una dominación impuesta, sino que se llama con exactitud y propiedad
, la obra de la justicia."[^31]

### La justicia sin Dios

El ser humano pretende estandarizar su código de principios y valores
fundamentados en el sentir del amor humano, cuya raíz no depende de una
interpretación del "estado correcto" del corazón en el amor divino, sino
en la variabilidad del significado del razonamiento a veces
resquebrajado en la moral de los grupos de interés, que logran
arrinconar el amor de Dios, en nombre de su interpretación de la verdad
individual; verdad, que con su componente de una realidad subjetiva del
"si mismo", por su naturaleza no puede ser definida desde la razón de
manera íntegra, transparente y objetiva dejando al descubierto la
turbiedad del cristal espiritual de la humanidad. Entonces, la humanidad
desde su amor propio y débil, con la evidencia histórica de una
capacidad limitada en la búsqueda de una visión de la aplicación de una
justicia considerada "correcta" , ha entrado en un prolongado juego de
ajedrez, en el cuál, el grupo de interés mejor acomodado en términos de
la definición de progreso vigente, interpreta e impone "su" verdad
individual , desde el ejercicio truncado de la razón, que cómo lo
explica Newman, queda a disposición de lo que es un acuerdo puramente
funcional. Lo que funciona y se demuestra para todos "está bien". Está
bien entender el bienestar como una de las columnas del progreso, como
un acuerdo implícito en el desarrollo de la sociedad contemporánea que
no se niega como objetivo común en la civilización; pero la acción final
para lograrlo queda truncada al desconectar dicho objetivo con un
principio aceptado por la humanidad a escala global, que defina si la
forma o el medio de lograrlo es correcto, lícito o no. Al no existir
dicho principio, la forma correcta la definen los grupos de interés más
poderosos.Un recordatorio de situaciones que reflejan dicha afirmación
es la inequidad presentada ante la pandemia del covid19, frente a la
cual, a casi año y medio de desarrollo de la vacuna, en los países de
bajos ingresos solo se logra vacunar a una reducida proporción de su
población a un costo mucho más alto que el de los países ricos[^32];
esto cuando se han producido en dicho momento suficientes dosis como
para vacunar, al menos una vez, a mas del noventa por ciento de la
población mundial. Al alejar el amor de Dios, queda solo un acuerdo que
tiende a independizarse de la naturaleza del corazón del ser humano, que
proviene de Dios mismo. La ley del ser humano es necesaria y debe
reflejar los principios y valores que la determinan y es un regocijo
determinante para la construcción de la civilización. Pero cuando se
nutre la justicia de la humanidad , unicamente y de manera superficial
por pocos grupos de interés, que tienen el poder para influenciarla,
esta, se convierte en ley que juega a ser la ley superior, incluso a la
ley natural del amor. Un grupo de interés, tal como una nación que
define la pena de muerte como el máximo castigo para una serie de faltas
que evidencian una acción indebida es un ejemplo de justicia válida
donde no tiene cabida la misericordia, mientras otro grupo de interés,
otra nación, las mismas faltas pueden tener un castigo menos drástico.
En ambos casos, la verdad individual como fuente de principios y valores
propios de cada grupo de interés , tiene interpretaciones diferentes.
Otro ejemplo, son los mecanismos de decisión ideológica que afloran
desde diversas posiciones políticas; en una democracia, la
interpretación de la verdad individual se somete a consideración de una
mayoría o de varios grupos de interés, mientras en un régimen
totalitario, lo decide un individuo o su circulo político cerrado; en
dicho caso la libertad se define al amparo de ambas posiciones, en la
democracia se define en los límites de la ley definida en los sistemas
jurídicos en los que se desarrolla, quedando expuesta muchas veces a la
influencia de determinados grupos de interés con mayor poder político;
mientras en el régimen depende de los avatares y vicisitudes del grupo
político dominante bajo el imperio de la fuerza. Esto ha sido así
dependiendo del momento histórico del grupo social y sus intereses.
Cuando los principios y valores son construidos y guiados desde la
interpretación de una verdad individual, fundamentada en una
manifestación cada vez más débil del deseo humano y cimentada
exclusivamente en el carácter racional y funcional influenciado desde
los grupos de interés de mayor poder , o de un solo individuo, el rumbo
de la justicia de la sociedad moderna queda a merced de un sentido y
validación manipulable por la imperfección de la naturaleza humana.
Caminar hacia una justicia objetiva y absoluta es un ingrediente
indispensable para la convivencia humana en armonía, de manera
indefinida, con su origen y destino en una verdad absoluta. Se puede
interpretar esto como una utopía, pero ,aun así, la pregunta de fondo es
si la humanidad está en la búsqueda de dicho sendero de justicia o si lo
ha descartado de manera permanente. Se puede leer en el cristal
espiritual de la justicia desde lo más profundo del ser que se debe
caminar hacia la convivencia, la paz y la felicidad de la comunidad
global y del individuo como ser humano en un esquema de bienestar. Un
rumbo equivocado es un camino hacia un concepto de justicia social
aparente, es también lo que lleva a confundir el bienestar con la
felicidad. El gran historiador Yuval Noah Harari , lo expresa de la
siguiente manera "(...) si es así, entonces toda nuestra comprensión de
la historia de la felicidad puede estar descaminada. Quizá no sea tan
importante que las expectativas de la gente se cumplan y que gocen de
sensaciones placenteras. La principal cuestión es si las personas
conocen la verdad acerca de si mismas. ¿ Que pruebas tenemos de que en
la actualidad la gente comprenda esta verdad mejor que los antiguos
cazadores-recolectores o los campesinos medievales ?"[^33]. Noah Harari,
hace una crítica, en la que un ciudadano del mundo en los comienzos de
la civilización en la cual la historia demuestra que trabajaba tres días
de la semana, tenía tiempo suficiente para recoger una cosecha que le
permitiera alimentarse con su familia por una semana y el resto del
tiempo lo dedicaba a construir relaciones sociales. Mientras en el mundo
contemporáneo un ciudadano promedio de un país no desarrollado, en una
gran ciudad, puede trabajar incansablemente de ocho a diez horas al día,
seis días a la semana, y escasamente logra alimentase él y su familia.
Así, el amor del ser humano se ve reflejado con turbiedad desde lo que
considera por si mismo como el estado "correcto" del corazón visto desde
el cristal espiritual de la justicia; y seguirá siendo profundamente
controversial mientras no encuentre en la luz del amor espiritual un
camino diáfano que le lleve al destino deseado.

## El cristal de la justicia en el amor divino

El cristal espiritual de la justicia es un misterio embebido en la
misericordia infinita de Dios, por ello entender la justicia de Dios es
más un asunto de fe; la justicia de Dios es perfecta, es una justicia
inmersa en el perdón; pero exige el arrepentimiento en la humildad del
espíritu humano. ¿En que se diferencia de la justicia humana ?. Por un
lado, también hay una exigencia a la obediencia a una ley, pero una ley
de amor, mucho más sencilla y comprendida por cualquier ser humano, en
cualquier lugar del mundo y sometida a una autoridad suprema que es Dios
mismo, por lo tanto el grupo de interés, es reemplazado por el interés
de Dios; un interés de llevar a la humanidad a un estado de justicia
verdadero y absoluto a través de su amor divino. Entonces, permeando los
terrenos de la fe, Dios está interesado sin distinciones de ninguna
naturaleza en todos los seres humanos. El fin último de Dios con los
seres humanos, no es mantener un modelo económico determinado, ni una
felicidad disfrazada de bienestar, ni favorecer a un grupo de interés u
al otro. El fin último de Dios con la humanidad es llevarla a su
encuentro tanto en su vida terrenal como en su vida espiritual. Se puede
decir entonces que la justicia de Dios es salvífica; busca la santidad
del ser humano para llegar al paraíso. En especial, Dios se preocupa más
por aquellos individuos que permanecen en el "el estado incorrecto del
corazón". Dios, se alegra más por aquellos individuos que corrigen el
estado de su corazón, que por aquellos que van por un camino lícito o
correcto. Dios busca llevar a cada ser humano a un estado de paz y
felicidad eterna, arraigada y fusionada en el misterio de su propio
amor, su propia santidad; un camino que se comienza a recorrer en la
vida terrena de cada persona. Así lo expresa el Papa Francisco: "Para Él
(Jesús), lo que cuenta realmente es alcanzar a los lejanos y salvarlos ,
como el buen pastor que deja a la grey para ir a buscar a la oveja
perdida. Entonces, como hoy, esta lógica y esta actitud pueden
escandalizar, provocan la queja de quien está acostumbrado siempre, y
solamente, a hacer que todo entre en sus propios esquemas mentales y en
la propia puridad ritualista, en lugar de dejarse sorprender de la
realidad, por un amor y una medida mas grandes."[^34]. Para alcanzar
dicho estado superior, la justicia de Dios que es perfecta, exige
obediencia, pero no obliga, al cumplimiento de los diez mandamientos,
alimentados en el amor divino y que son la ley de Dios. Mientras, la ley
de la humanidad sigue estando ligada en diferentes medidas a la ley del
talión "Ojo por ojo, diente por diente"[^35], la justicia Divina , se
mide por el estado del corazón en el "amor" de cada ser humano en su
verdad individual. La justicia espiritual se rige por el único estado
del corazón aceptado que parte de la voluntad y el libre albedrío del si
mismo y es "amar a Dios sobre todas las cosas" ; y en términos de una
vida comunitaria es "amar al prójimo como a si mismo". Es una ley de
obediencia que actúa por convicción, no por obligación, se nutre de la
libertad de la conciencia y la guía de la gracia de Dios, de tal manera
que dicho estado del corazón, puede ser aceptado o rechazado por cada
ser humano. No es un sometimiento, como si lo es la justicia humana.
Como se ha mencionado, además, cada ser humano independiente de su
creencia, conoce sin necesidad de aparentar, sin necesidad de justificar
y de manera transparente, el estado en el camino del bien o del mal, de
su propio corazón. Así es que en todo momento, desde el si mismo y desde
su verdad individual, puede una persona saber si está en el camino de un
amor divino, camino al que Dios permanentemente le invita. "Cuando los
paganos , que no tienen ley cumplen naturalmente lo que manda la ley,
están escribiendo ellos mismos esa ley que no tienen , y así demuestran
que las exigencias de la ley están grabadas en sus corazones. Serán
juzgados por su propia conciencia, y los acusará o los aprobará su
propia razón el día en que Dios juzgue lo más íntimo de las personas por
medio de Jesucristo"[^36]. Dios, en su justicia, además le ofrece a cada
ser humano que le acepta una ayuda incondicional para llegar a Él,
porque sabe que el camino no es fácil; Dios conoce el corazón de cada
ser humano y por ende su debilidad. Así que, por voluntad propia, cada
ser humano recibe la gracia del Espíritu Santo en su propio corazón en
el bautismo y entonces la justicia de Dios actúa en el corazón de la
persona desde la misericordia divina y a través del perdón. Así lo
afirma el Papa Francisco: "En el libro de la sabiduría (12, 18-19)
leemos: - Tú dueño de la fuerza juzgas con clemencia y nos gobiernas con
mucha indulgencia \[...\]. Actuando así has enseñado a Tú pueblo que el
justo debe amar a los hombres; ademas has llenado a tus hijos de dulce
esperanza, pues Tú concedes después de los pecados la posibilidad de
arrepentirse.- la misericordia es un elemento indispensable en las
relaciones entre las personas para que haya hermandad. La sola medida de
la justicia no basta. Con la misericordia y el perdón, Dios va mas allá
de la justicia, la engloba y la supera en un evento superior en el que
se experimenta el amor que está en la base de una verdadera
justicia"[^37] ; Dios está a la espera de cada ser humano, no para
juzgarle; sino para perdonarle, una y otra vez, siempre con la intención
de que el individuo encuentre el arrepentimiento en su corazón porque no
existe ser humano que no sea pecador; pero, también espera la misma
actitud de su parte con las demás personas. Esta es una gran evidencia y
manifestación del amor divino. No funciona a través de un documento
legal, ni desde un juicio racional con preguntas, evidencias científicas
y acusaciones. Tiene un alcance mucho mayor, en el alma de la persona.
Es un misterio que solo puede ser asimilado por quienes lo viven desde
la fe. Pero es solo con la ayuda de Dios que el hombre en su condición
débil y humana, puede caminar hacia el estado "correcto" del corazón.
Sin amar a Dios, no es posible amar al prójimo; entendiéndose, como el
"más" prójimo, al si mismo. Si no existe el amor por el si mismo, que
nace desde al amor de Dios, no es posible tener misericordia, ni perdón
hacia los demás seres humanos. Todo adquiere más sentido, si el ser
humano vive la fe , no solo como un requerimiento voluntario para
acercarse al amor Divino, si no en su actuar diario. Y es así como la
fuerza del amor divino e infinito se encuentra en el silencio, al
interior del si mismo, mediante la oración: es la forma de conocer la
justicia de Dios. Quienes se encuentran en su corazón con el corazón de
Dios, estarán en estado de "gracia"; siendo esta otra manifestación del
amor divino que premiará al ser humano en su justicia a través de un
nuevo nacimiento espiritual, después de la muerte del cuerpo, con una
vida espiritual eterna, en un estado de felicidad permanente y de
encuentro con la revelación del misterio de la verdad absoluta. En el
misterio de la justicia de Dios, de acuerdo a su divina voluntad y en
perfecto conocimiento del corazón de cada individuo, quienes permanecen
en el estado desviado o "incorrecto" de su corazón y quienes rechacen de
manera contundente el corazón de Dios, conservaran su vida espiritual
después de la muerte, pero estarán alejados de Dios por siempre porque
han cerrado la más mínima posibilidad del actuar de la gracia del
Espíritu Santo en si mismos como seres espirituales semejantes a Dios.
La justicia perfecta de Dios ha llevado a la humanidad a un estado de
vida terrenal como condición para superar y borrar su pecado original,
su estado de concupiscencia evidente en la justicia humana; a pesar de
la traición de la familia humana a Dios, Él ha permitido un nuevo
nacimiento espiritual a quienes cumplan con su ley de amor. Quienes no
lo desean, estarán abandonados en una vida espiritual, incluso desde su
vida terrenal, a merced del odio y la soberbia eternas que compartirán
entre sí. En este sentido, en el cristal de la justicia divina,
simplemente Dios en su omnipotencia no deja entrar a su paraíso de
santidad espiritual a quien no demuestra en la profundidad del si mismo,
de su ser y de sus acciones, que al menos tiene el mínimo deseo de
hacerlo a través de la doble ley del amor. Carlo Acutis (Londres
1991,Monza 2006)[^38], posiblemente el joven Cristiano que en este siglo
lo ha entendido desde su fe con mayor claridad lo afirma cuando decía
"La tristeza es dirigir la mirada hacia uno mismo, la felicidad es
dirigir la mirada hacia Dios. La conversión no es otra cosa que desviar
la mirada desde abajo hacia lo alto"[^39].

La justicia de Dios refleja desde muchos rincones filosóficos, e incluso
desde los espacios más conservadores del Cristianismo medieval, a Dios
como un Dios castigador; ¿ cual sería entonces el significado aquel que
enseña el Cristianismo, cuando afirma que Dios es lento a la ira , pero
rico en misericordia ?. El mismo sentido lo entiende un padre o una
madre que ama a sus hijos en el diario vivir; cuantas veces habrá tenido
que castigar a sus hijos con el fin de corregirles solo porque desean lo
mejor para sus hijos. En un sentido teológico Cristiano el castigo de
Dios, es más bien un equilibrio "perfecto" entre justicia y misericordia
por la humanidad[^40]. Un Dios que se queda impasible frente a los actos
perversos de la humanidad, no sería un Dios amoroso; no le importarían
sus hijos. En teología, esa es la característica principal de un dios
deísta que no corresponde al Cristianismo. El Papa Benedicto XVI define
así el castigo de Dios: "No es Dios quien nos impone algún mal para
curarnos, pero Dios me deja, por así decirlo, a la lógica de mi acción
y, dejado a esta lógica de mi acción, soy ya castigado por la esencia de
mi mal. En mi mal está implicado también el castigo mismo; no viene del
corazón, viene de la lógica de mi acción, y así puedo entender que he
estado en oposición con mi verdad, y estando en oposición con mi verdad
estoy en oposición con Dios, y debo ver que la oposición con Dios es
siempre autodestructiva, no porque Dios me destruya, sino porque el
pecado destruye".[^41]

El cristal diáfano en su pureza perfecta de la justicia de Dios como
manifestación de su amor que parte de la fe, es en un contexto secular
un mito, un cuento de hadas, una utopía. Y aunque solo desde la razón es
imposible entender dicha justicia perfecta, es cierto que desde la
verdad científica, no se puede demostrar que dicha justicia es algo
imposible; el pensamiento puramente racional, simplemente descarta la
posibilidad de una justicia construida desde un amor perfecto, aún
cuando la razón, la ciencia y la fe están unidas en el ser humano por el
mismo misterio.

Sin embargo, si se puede entender y se puede comprobar racionalmente,
que la humanidad tiene todavía mucha sed de justicia; la historia de
muchos siglos demuestra que la humanidad está herida con el sentido que
le ha dado a la justicia: esto es lo que enseña la narración sobre Noé
en el antiguo testamento, en los orígenes de la humanidad cuando Dios
amenaza con exterminar la humanidad por su constante incapacidad de
vivir a la altura de las exigencias de su justicia y su paz: « He
decidido acabar con todos los seres humanos, porque la tierra, a causa
de ellos, está llena de violencia » (Gn 6,13). En estos relatos de
antigüedad milenaria, cargados de profundo simbolismo, ya se existía el
llamado de Dios a la convivencia en un mundo nuevo en el que todo está
relacionado y en el que que el auténtico cuidado de nuestra propia vida
y de nuestras relaciones con la naturaleza es inseparable de la
fraternidad, la justicia y la fidelidad a los demás[^42]. En el antiguo
testamento aparecen claros indicios que perduran hasta hoy, sobre la
batalla que la humanidad enfrenta permanentemente frente a la
injusticia, una batalla en la que la concepción de justicia de los
hombres le lleva a apartarse de Dios: "La palabra y el concepto de
misericordia parecen producir una cierta desazón en el hombre, quien,
gracias a los adelantos de la ciencia y de la técnica como nunca fueron
conocidos antes en la historia, se han hecho dueños y han dominado la
tierra mucho más que en el pasado (Cfr, Gn 1.28). Tal dominio sobre la
tierra entendido tal vez unilateral y superficialmente parece no dejar
espacio a la misericordia"[^43]. La luz de la justicia, la misericordia
y el perdón, se sobreponen y se entrelazan la una con la otra; pero solo
adquieren fuerza en el misterio del amor perfecto de Dios, porque solo
desde su inagotable fuente, el amor se paga con amor y este se traduce
en su medida; mientras estas luces sean impuestas ciegamente desde la
turbiedad de ley del ser humano, la injusticia en la historia de la
civilización humana seguirá siendo un anhelo sin la respuesta deseada,
un anhelo, al que infructuosamente se desea llegar solo a través de las
ciencias humanas, un anhelo que lleva a la búsqueda incansable de la
paz, desde toda cultura en la civilización humana, porque está escrito
en el corazón buscando el corazón.

## La búsqueda de la paz

La paz, como complemento de la justicia, es un elemento aún lejano en la
civilización del post modernismo. No es fácil entender el grado de
deformación del amor humano a través de la historia de las guerras;
desde los actos de perversión, atrocidad y barbaridad que ni si quiera
alcanza a ser imaginada por una criatura viviente diferente al mismo ser
humano. El número de guerras ha disminuido durante los últimos siglos y
el porcentaje de la población que ha fallecido por su causa tiene la
misma tendencia, sin embargo en términos absolutos las guerras de los
últimos tiempos han sido cada vez más cruentas y salvajes; y presentan
todavía grados extremos de mortalidad dada su modalidad, en especial con
la población inocente[^44] . Los más atroces "genocidios" han sido más
abundantes en los siglos recientes, debido a que hay más gente para
matar y mejores maneras de hacerlo en gran escala a partir de la
tecnología utilizada, cada vez más efectiva en las condiciones de la
guerra o del exterminio. La búsqueda de la paz en el contexto de la
cultura humana, ha llevado a una estructura de relaciones políticas y
diplomáticas entre las naciones contemporáneas, anclada todavía por
muchas de las naciones , en sus deseos de dominación bajo esquemas
sustentados en la guerra "justa". Las primeras pinceladas para el marco
de su definición en el post modernismo llegan desde la antigua Grecia a
partir de Platón y Aristóteles, luego por Cicerón, quienes se proponían
encontrar una teoría de la justicia de la guerra que fuera más allá del
interés de algunos grupos de la época, como los imperios o
pseudo-estados. Aquellos filósofos, sin embargo, cayeron en el equívoco
de llegar a sostener incluso el principio en el cual la guerra se
justifica si es iniciada por los pueblos más civilizados, dado que será
justa en la medida en que traerá mayor libertad y prosperidad a los
pueblos atacados o derrotados, confundiendo así un ideal humano con sus
propios los intereses. Fue luego, hacia el siglo IV desde la Cristiandad
que San Agustín concluye que no siempre la paz es preferible a la
guerra, pues algunas situaciones de paz son perversas así que el empleo
de la fuerza para terminar con ellas puede ser legítimo. Pero, debe
entonces encontrarse el origen de tal perversa injusticia y definir a
que tipo de injusticias se refiere dando como primera causa de una
guerra justa el castigo por las injurias sufridas y sus derivados, como
segunda causa el castigo a un pueblo que no ha hecho lo propio con
quienes, de entre los suyos han cometido atropellos, lo que hoy se
define como "agresión indirecta", y como tercera causa el castigo por
restituir lo que injustamente ha sido robado. San Agustín propone un
principio y es descartar cualquier guerra ofensiva, es decir las
expansiones de imperios, las glorias o conquistas no caben en su legado.
Santo Tomás ya en el siglo XIII complementa luego a San Agustín, en lo
que hoy se conoce como la "legítima defensa" y define tres cosas para
que una guerra sea justa. Primero que haya sido autorizada por el
príncipe bajo cuyo mandato se hace la guerra dado que el cuidado de la
república ha sido encomendado a los príncipes, a ellos compete defender
el bien público de la ciudad, del reino o de la provincia sometidos a su
autoridad. Segunda causa, que quienes son atacados lo merezcan por
alguna causa, entre ellas las mencionadas por San Agustín; a veces, sin
embargo, hay que obrar de manera distinta por el bien común o también
por el de aquellos con quienes se combate.Y por tercera causa, que sea
recta la intención de los contendientes; es decir una intención a
promover el bien o evitar el mal, implica no actuar con exceso de
codicia o crueldad: "En efecto, el deseo de dañar, la crueldad de
vengarse, el ánimo inaplacado e implacable, la ferocidad en la lucha, la
pasión de dominar y otras cosas semejantes, son, en justicia,
reprochables en las guerras (...) puede, sin embargo, acontecer que,
siendo legítima la autoridad de quien declara la guerra y justa también
la causa, resulte, no obstante, ilícita por la mala
intención."[^45]Santo Tomás afirma que quien va a la guerra debe
esforzarse por demostrar que es lícita, por cuanto que la guerra es
ilícita y por tanto es pecado, con algunas excepciones ya mencionadas.
El problema radica en la fuente de legitimidad para matar a individuos
en nombre de una justicia que administran sus estados; respecto a esto
Santo Tomás parte del principio de que el "hombre está más obligado a
proveer a su propia vida que a la ajena" (Santo Tomás, 1959, VIII:
447)[^46], no es lícito matar por matar, pero si la intención es
positiva, salvar la propia vida; y no existe alternativa, el daño
causado al agresor no es moralmente reprochable. Este principio
trasladado a la conducta de los estados, salvaguarda el derecho del
agredido a tomar las armas para proteger su soberanía o su
independencia. En el siglo XVI aparece el Español Francisco de Vitoria
(Burgos, 1483 -- 1546, Salamanca)[^47], el fray dominico, expandió la
obra de Santo Tomás. España vivía una situación particular, pues al
colonizar las indias el debate sobre el derecho de los Indios estaba
vigente y Vitoria contempló la necesidad de defender a los individuos
frente a los hipotéticos abusos de sus propios estados, sean cuales
fueren sus identidades y banderas; además el dominico advirtió que
algunos de los peores abusos se cometían también entre nativos. Se
desarrolla, a partir del legado de Santo Tomás, una cuarta causa y es el
derecho de los individuos sobre los de sus propios estados, con la
novedad de que no es necesario que exista vínculo alguno entre el estado
que decide intervenir y las víctimas. Vitoria defendió la igualdad de
los nativos y la potestad para poseer y administrar sus tierras. La idea
del derecho de gentes cobró fuerza y fue hilada a la siguiente cuestión:
toda violencia ejercida contra un semejante por diferencias de fe o por
dominación era insostenible; un principio que hubiese sido de gran
utilidad para evitar las guerras de las cruzadas que sacudieron la
Europa de siglos de su reciente pasado. El razonamiento que le cobija es
"si todo ser humano, creado a imagen y semejanza de Dios, posee libre
albedrío y toda la tierra y bienes naturales estaban a la libre
disposición de los individuos, ni las creencias ni la dominación sobre
las posesiones ajenas pueden aceptarse. Todo ser humano, en
consecuencia, sea cual sea su raza, credo o pensamiento, grado de
posesión de bienes o modelo de sociedad tiene derecho a existir y a ser
respetado en su dignidad humana, común por voluntad divina."[^48] Dicho
principio forma parte del diálogo intelectual de los siglos siguientes
que dieron lugar , después de la segunda guerra mundial a la declaración
universal de los derechos humanos en 1948. Otras causas justificadas
aparecen posteriormente como, la de la guerra preventiva[^49], que tiene
muchos críticos. Hoy es claro que por un lado aparece la posición
llamada realista, en la que la guerra se justifica y es una mera
continuación de la política, dicha perspectiva no asume el término de
justicia o injusticia en la guerra, aunque tampoco lo rechaza; considera
las guerras como algo fatal y su estudio constituye un marco fundamental
sobre el que se puede trabajar para entender el curso de lo que sucede a
nuestro alrededor. Para este grupo el aspecto moral no aplica una vez se
entra en conflicto. El grupo opositor a dicho pensamiento es el de los
pacifistas, quienes asumen el reto de encontrar los medios morales que
la justifican; los ya mencionados pertenecen a este grupo. En el mundo
actual, se busca un punto medio entre ambas posiciones, uno de los
filósofos más reconocidos en el estudio de la guerra justa en nuestros
días es Michael Walzer(New York,1935 - actualmente)[^50], quien desde
una aproximación del método inductivo, a partir del estudio de casos,
llega a conclusiones similares al de los pensadores Cristianos con el
fin de encontrar una moral práctica capaz de generar amplio consenso.
Entre sus aportes están la posición de la defensa nacional, la
intervención humanitaria, la discriminación y la equidad en el
combate[^51]. Todas ellas caen en algunas de las causas mencionadas, con
algún grado de innovación; Waltzer, con respecto a la legítima defensa,
acude a una necesidad en casos extremos, pensando en que hubiese
sucedido si la Alemania de Hitler hubiese salido victoriosa, necesidad
que se traduce en la suspensión temporal del respeto debido a los
civiles del bando rival, a toda infraestructura o al principio de
proporcionalidad en el combate. Dicha necesidad puede ser activada por
el estado agredido, solo si se encuentra contra las cuerdas y si se
constata que las prácticas habituales del agresor menosprecian todo tipo
de principio moral, como el derecho a la libertad , al de no ser
esclavizado. Respecto a la segunda causa, retoma la posibilidad de
intervención cuando el estado en el que operan grupos armados
irregulares (narcotraficantes,terroristas, piratas, mafias, etc) no
tiene la capacidad de detectar y controlar dicha amenaza por sus propios
medios. Waltzer, en relación a la tercera causa va más allá y propone el
derecho de imponer al agresor normas inusuales como un desarme total o
parcial, o límites a su rearme bajo vigilancia internacional, con la
intención de evitar que se reproduzca la situación que dio pie a la
agresión. Las posiciones de Waltzer tienen sus críticos, en un proceso
que todavía sigue en construcción bajo búsqueda de consensos, pero que
en última instancia no puede aún ser implementado en su cabal
cumplimiento , puesto que no existe el poder global capaz de administrar
y ejercer su control.

Es así, como la civilización contemporánea obtiene como resultado, una
superficial paz global, la cual, descansa sobre la permanente amenaza de
miles de bombas atómicas e inversiones permanentes en armamento de
manera desproporcionada. Así se ha construido una paz aventurada e
insegura como lo expresan los científicos del reloj de doomsday. A pesar
de que es evidente, si se compara el mundo de hoy con el mundo antiguo y
medieval, la probabilidad de que un ciudadano actualmente no perezca en
una guerra, es mucho mayor. Sin embargo, es mucho más controversial
afirmar, si el cimiento de la paz actual, derivado de un pensamiento
humano, en el cual existe un orden de las naciones estado con mayor
control de sus ciudadanos que en función de la riqueza económica y del
músculo del armamentismo tecnológico, tenga la capacidad de mantener un
equilibrio global permanente y de relativa calma en relación a la guerra
como mecanismo de dominación y distribución del poder entre las
naciones. Puede ser que la probabilidad de las guerras desproporcionadas
entre las naciones disminuya temporalmente mientras se acude a un
equilibrio armamentista, sostenido por pocos grupos de interés en las
naciones del mundo, y por sus líderes cada vez más amarrados a sus
propias verdades e ideologías. Sin embargo, la posibilidad de las
guerras más atroces y sanguinarias, es permanente y va en ascenso; y el
precio que la humanidad tuviera que pagar sería a todas luces nefasto e
incalculable, dadas las nuevas tecnologías de destrucción masiva y la
gran población mundial. La humanidad actual ha decidido convivir con
este riesgo. Un riesgo sustentado en un imperfecto amor humano alejado
de Dios y en su definición de justicia.

## El cristal de la paz desde al amor de Dios

El amor divino ofrece una paz diferente y muy poco explorada. La paz, en
el lenguaje de Dios, es fuente de una verdadera justicia y viceversa. En
el sentido Cristiano, la paz parte del individuo, del si mismo y se
extiende a su comunidad, la sociedad, los diferentes grupos de interés y
a finalmente a las naciones, siendo así el modo de evitar guerras y
conflictos armados. En su verdad individual, el ser humano busca un
estado de consciencia que le lleve a una paz sustentada y fortalecida
desde un equilibrio interior; el Cristianismo evita que dicho encuentro
caiga en el egoísmo del si mismo, al entender la paz como un bien
exclusivo tanto para el si mismo como para su grupo de interés, así no
es una paz esencialmente definida en el encuentro con la comunidad, no
es una paz abierta que implique "amar al prójimo como a ti mismo",
incluso al enemigo. La paz que nace solo de la fuerza y razonamientos de
la filosofía mental , es temporal y débil como la débil naturaleza del
ser humano; para que subsista y crezca debe tener su origen y sostén en
un amor superior y en eso se diferencia el Cristianismo en su búsqueda
al de cualquier otra filosofía o religión humanas. La propuesta del
Cristianismo es un desafío desde la fe a la razón, puesto que hace un
llamado a su búsqueda, más allá de cualquier límite y superando
cualquier barrera, un punto al que el ser humano por si mismo no puede
llegar. La paz que llega a quien crece en la fe de Jesucristo, es una
paz incondicional, un regalo desde la gracia del Espíritu Santo. La paz
en el amor divino no es fácil de encontrar, de mantener, ni de crecer en
el tiempo; implica tener una fuente de sustentación superior al si
mismo, fuente de amor externa que fortalece al corazón del individuo,
solo llega a ella cuando se decide amar a Dios sobre todas las cosas; el
corazón buscando el corazón. Cuando la paz viene del Espíritu Santo,
manifestado en el corazón del ser humano, la fuente que abraza dicho
equilibrio, tiene su origen en Dios como ser supremo y penetra en el
individuo humano como un todo, en su alma y se irradia hacia el alma de
quienes le rodean, su comunidad, la sociedad y las naciones. Pero la paz
de Dios va incluso mucho mas lejos; por ser fuente en el amor de un ser
divino, en la verdad individual de quien la acepta, se expresa desde el
misterio, el mismo que une la fe , la ciencia y la razón. Un misterio
que genera una fortaleza espiritual indescriptible en quienes la llevan;
en este sentido, su acción es como la de un escudo que protege la fuente
del amor humano en el estado "correcto " del corazón, brindándole la
capacidad de superar la turbulencia, la injusticia, el odio y el ruido
del mundo; así toda invitación a la guerra o la violencia queda sosegada
a un lejano y último plano. En este sentido, la paz interior es un
estado de reconciliación abierto, supremo y permanente con nuestros
semejantes y por ende de la civilización entera, con el si mismo, con la
creación, con la naturaleza y principalmente con Dios en su trinidad.
También como misterio, quien en su camino de fe está en la paz de Dios,
adquiere una valentía espiritual tal, que puede llegar incluso a no
temer a la muerte, algo profundamente irracional desde la perspectiva
humana. El primer exponente de la paz es Jesús, quien contradijo la
milenaria ley del talión propuesta por la humanidad y promulgada en el
antiguo testamento "Al que te golpea en una mejilla, preséntale también
la otra "[^52]. Es la actitud de la no violencia. Jesús , siendo Dios,
fue el primer mártir que rescata el amor divino y como Él lo dice, "La
paz que yo les doy no es como la que da el mundo"[^53]. No es una paz
que nace en la naturaleza, ni en el ser humano. Muchos mártires con
aquel "Don" de la paz le han seguido a lo largo de la historia, en su
valiente intento por dar a conocer el amor de Dios como fuente de una
paz verdadera y absoluta, fuente que solo se multiplica porque quien
recibe el amor de Dios lo regresa con creces. Como la justicia divina,
siendo esta una paz perfecta y a cuyo encuentro se puede caminar en esta
vida , se puede llegar a ella en todo su resplandor en el nacimiento a
la vida espiritual en Dios, después de la muerte como la conocemos, en
sus límites de la materia. Es comprensible que quienes no están en el
camino de la fe del amor divino en la religión Cristiana, vean esta paz
como una utopía, por lo demás inalcanzable, puesto que no tienen el
ejemplo de Jesús, Dios encarnado. Un gran error de la humanidad desde el
modernismo, es pretender de manera indiferente a la fe , que separar el
amor del análisis de la razón, teniendo como fin la búsqueda de una paz
duradera , le llevará a una paz estable y permanente en todos los
rincones de la tierra; durante la trayectoria de la civilización, esta
opción se ha intentado incansablemente, pero esto nunca ha sucedido. Se
continúa viviendo en el mundo del post modernismo, situaciones en las
que la paz sostenida e impuesta por el grupo de interés dominante, está
siempre vacilando en un escenario similar al de un campo minado en el
cual, un paso en falso pueda tener consecuencias desastrosas; la
historia ha demostrado que, una y otra vez, se llega a una paz que
permite ciertas guerras "justas", de acuerdo a la interpretación de cada
grupo de interés o nación, tal como sucedió en la antigua Grecia; son
circunstancias en las que el amor Divino pasa a un plano irrelevante.
Aquellos son acuerdos de paz construidos sobre ambientes superfluos y
poco duraderos, que se desvanecen con el tiempo como castillos de
naipes. El origen de la segunda guerra mundial fue una primera guerra
mundial mal terminada. Y la gran mayoría de conflictos , provienen de
una paz impuesta por unos grupos de interés a otros. En el desarrollo de
la civilización, la paz también es fruto del poder tecnológico. En
palabras del historiador H.G Wells (Bromley, 1866 -- 1946, Londres)[^54]
"La ciencia física facilita poder, poder sobre el acero, sobre la
distancia, sobre la enfermedad. Que aquel poder sea usado bien o mal ,
depende de la inteligencia moral y política del mundo."[^55] La paz como
se construye hoy, podría fundamentarse en principios y valores
transparentes y sólidos afianzados en un amor, real, tangible y posible
desde la verdad individual de cada ser humano; y con la posibilidad de
extenderse en su comunidad, grupo social o nación. Pero el racional
humano en la búsqueda de la paz moderna, evita o manipula la
inteligencia moral, se confunde en una paz construida muchas veces sobre
un principio fruto del miedo, alejado del amor que enseña Jesús. Entre
más capacidad de persuasión violenta tenga una nación, o un grupo de
interés por su capacidad y sus acciones bélicas, no solo podrá someter
de acuerdo a su propia noción de justicia en el llamado a la "razón de
estado" o "seguridad nacional", a grupos o naciones mas débiles, si no
que será respetada por las demás naciones o grupos de interés; es una
mímica del pensamiento Darwinista en el orden del dominio y
supervivencia del más fuerte. Una paz fruto del camino del amor, la
misericordia y la justicia divinas; o una paz fruto del camino del
miedo, esa es la gran diferencia entre la paz humana y la paz ofrecida
por un Dios de amor, una paz que tiene sus raíces en la humildad cuyo
principal exponente es Jesucristo.

El amor divino, no es tan utópico ni imaginario como se supone en la
sociedad contemporánea; es real y de efectos tangibles y medibles. Se
manifiesta también en la paz de la verdad individual del ser humano de
diferentes formas; cientos de miles y tal vez millones de vidas, incluso
desconocidas han sido portadores de acciones o de algún mensaje de paz,
que en todas las expresiones culturales y religiosas de la humanidad, se
han manifestado y han dejado un legado que da sentido a la construcción
de la paz. Estas personas con sus vidas son ejemplos vivos de la paz de
Dios en la humanidad. Un legado reciente , en la forma poco convencional
de la búsqueda de la paz, fue la del Papa San Juan Pablo II (Wadowice,
1920 - 2005 ,Ciudad del vaticano)[^56], quien en su juventud vivió en
carne propia la injusticia de la segunda guerra mundial, primero durante
la invasión Alemana a Polonia y luego, desde la persecución de la Unión
Soviética a la iglesia Católica en Polonia. Nunca dudó en mantener el
amor divino como herramienta fundamental para no participar de manera
violenta en ninguna de las dos circunstancias, como si lo hicieron
muchos de sus amigos. San Juan Pablo II, decidió en su juventud
abandonar el amor de una mujer y cultivar el amor de Dios. Lo utilizó
como instrumento e inspiración, en batallas de argumentos con los
líderes comunistas y políticos de la época. Tanto así, que fue
considerado como enemigo ideológico de la Unión Soviética y hay quienes
afirman que fue uno de los principales artífices de la destrucción del
muro de Berlín y la caída del comunismo como se conoció. San Juan Pablo
II, es prueba de que un verdadero estado de paz, desde la verdad
individual es alcanzable y es posible proyectarlo en la sociedad, a
pesar de las barreras y dificultades del mundo. La paz es posible desde
el estado "correcto" del corazón, desarrollado en la esencia del amor
divino de Dios; y además puede tener logros casi imposibles, irrigándose
a través de los grupos de interés, o a naciones enteras. El amor divino,
se manifiesta de acuerdo a la voluntad de Dios en quienes buscan la paz
así no sean fieles creyentes Cristianos, pues su semilla está sembrada
en toda persona. Otro caso que supera la utopía es el de Mahatma Gandhi
(Porbandar, 1869 -- 1948, Nueva Delhi)[^57], pacifista mundialmente
conocido como defensor de la no violencia, su religión era el Hinduismo
y sin embargo fue admirador de Jesús , e influenciado por su propio
concepto del amor, como opción unificadora entre las religiones[^58]. En
dicho tipo de vivencias, los seres humanos, aún sin el conocimiento
profundo de Jesús, aceptan la posibilidad de la paz desde el amor en su
corazón; de manera individual y en ocasiones excepcionales, la
extrapolan a sus propios grupos de interés y naciones. De esta manera
una gran nación como la India se independizó de manera pacífica de la
Gran Bretaña, sin sangrientas guerras de independencia como ha sucedido
en gran parte del mundo. Otra forma con efectos reales de vivir la paz
desde una fe consolidada en la religión Cristiana, es a través del
ejemplo de la vida de los Santos que han permanecido en la verdad de
Jesús, siendo la Virgen María la principal exponente de esta Santidad.
La madre espiritual de la humanidad, quien al recibir el amor divino y
la gracia de Dios, es escuchada por su hijo Jesucristo, e intercede por
la paz de cada ser humano y de la humanidad como un todo. Otra luz
espiritual entre muchas, es la vida de San Francisco de Asís (Asís,
1182- 1226, Imperio Romano)[^59], una persona quien en su juventud
incluso participó en la guerra, desarrolló posteriormente en su corazón
muchas virtudes entre ellas la paz en Dios; no solo entre los hombres si
no con la naturaleza. En la fe Cristiano Católica, la devoción por
alguno de los Santos o por la Virgen María, son caminos de una gran
riqueza espiritual que Jesús ha dejado para llegar a Él y a su
interpretación del amor divino.

## El amor y la naturaleza

El amor tal como se expresa en la actualidad, en cuanto a su
responsabilidad frente a la naturaleza es una muestra de otra gran
debilidad humana. Es sinónimo de una forma de progreso aprobado de
manera subliminal por la humanidad ya que generalmente se acompaña del
bienestar del individuo; si la explotación de los recursos de la
naturaleza permiten una economía fuerte, funciona bien así, entonces se
asume que está bien para todos. Sin embargo, los esquemas de progreso
económico de las naciones están llevando contra las cuerdas a la
naturaleza y su reacción, que ya se percibe, es tremenda e impredecible
en sus efectos negativos para la humanidad. La mayoría de los
científicos del mundo podrían estar de acuerdo en que la humanidad va
por el camino equivocado en su modelo de desarrollo; pero aún si una
minoría no está de acuerdo, es suficiente para que cada grupo de interés
haga la interpretación desde la verdad individual que le conviene. Sin
entrar en detalle en un tema que abarca polifacéticos y complejos
frentes, solo es necesario dar un vistazo a un indicador que no requiere
de mucho análisis para entender la gravedad de la situación que tendrá
que enfrentar la humanidad. En el año 2019 , Chennai , la sexta ciudad
más grande de la India, con una población de 7 millones de habitantes,
literalmente se quedó sin agua debido a un cambio en la fortaleza y
tiempos del sistema de corrientes de vientos, llamados monzones[^60]. Se
calcula que en las próximas dos décadas una cuarta parte de la población
mundial del mundo tendrán graves problemas por escasez de agua, en la
categoría de estrés hídrico extremadamente alto[^61]; el crecimiento de
la población y el modelo de desarrollo económico, entre algunos de los
factores hacen que el indicador de abastecimiento de agua renovable, de
fuentes internas como ríos y aguas subterráneas por habitante en la
tierra, tenga una tendencia de caída vertiginosa durante los últimos
cincuenta años.[^62] En el momento en que estalle esta crisis a nivel
global, tan solo el tema del agua tendrá un enfrentamiento entre
múltiples grupos de interés. No hay un camino concreto, tan solo
acuerdos parciales y compromisos mediocres para poder resolver este tipo
de situaciones; el consenso sobre el cambio climático en el mundo
moderno está en sus inicios. Posiblemente la humanidad tendrá que
cambiar sus hábitos alimenticios, nuevas tecnologías de producción de
proteína artificial aparecerán y esquemas novedosos de desarrollo
sostenible tendrán que surgir. En cualquiera de los escenarios, habrá un
drástico ajuste en la interpretación de la nueva "verdad individual"
desde los diversos grupos de interés, entre ellos las naciones. Pero el
punto en consideración, es si en ese nuevo escenario, será la presión
económica de ciertos grupos de interés, que desde sus principios y
valores y bajo modelos de desarrollo económico auto sostenible impondrán
un esquema para atender el dictamen de la naturaleza, o se diseñará un
nuevo esquema de responsabilidad global sustentado desde el estado
"correcto" del corazón. Los nuevos esquemas tendrán que responder a
situaciones como el costo del acceso al agua en las poblaciones más
necesitadas. Pareciera desenfocada una posición de la humanidad en
cuanto a dar prioridad a la conservación de la naturaleza sobre el
desarrollo económico; pero en sus inicios y durante muchos siglos, la
humanidad sentía el respeto incondicional por la naturaleza ya que
convivía en su sustento diario con ella; la sentía y experimentaba
estando en su contacto en la vida diaria. Hoy esto se olvida. Todavía
quedan muestras de esta actitud original entre las tribus indígenas
milenarias de ciertos lugares del planeta, en la que se manifiesta a
través de sus mitos y leyendas el valor de corresponsabilidad
comunitaria y la convivencia como parte integral de la naturaleza[^63].

## El cristal de la naturaleza desde el amor de Dios

La naturaleza en el contexto de la religión Cristiana, es parte de la
creación y en si misma se expresa la magnificencia de un Dios
omnipotente capaz de componer, como en una bella melodía de lírica
trascendente o en una única maravillosa y santa obra de arte, el
escenario de la vida en plena manifestación de su amor divino, a partir
de la vida de miles de especies diferentes , de hacerlo en una sincronía
perfecta, donde todas las criaturas son "buenas" y dependen unas de
otras. El ser humano fue creado por Dios teniendo como materia prima a
la misma naturaleza, por ello es más bien su hermana antes que su
madre[^64]; un principio teológico de creación compatible con la verdad
entendida desde la teoría de la evolución científica[^65]. Dios al
compartir su Espíritu, como "aliento de vida" al ser humano, le dio
autoridad sobre ella [^66]. El ser humano, al ser creado a imagen y
semejanza de Dios, tiene el libre albedrío y una capacidad intelectual
muy superior al del resto de las criaturas; desde su imagen y semejanza,
Dios le transfiere al ser humano la responsabilidad frente a su
interacción y cuidado de la naturaleza, la obra excelsa perteneciente a
Dios. En el entendimiento del mensaje de Dios, la existencia de la
naturaleza misma es un acto de amor divino y como tal, cada vez que la
humanidad le destruye, esta agrediendo dicho acto de amor, está
agrediendo a un Dios que puso la creación a su disposición, para una
interacción y usufructo desde el mismo amor; sin que por ello el ser
humano sea dueño y señor de la naturaleza, pues debe responder y cuidar
de ella. En el misterio del amor divino, fuente de la creación, el
universo mismo como expresión de la naturaleza, está a la expectativa de
una redención, una salvación donde la crueldad de la naturaleza,
entendida desde la óptica humana, dejará de existir; promesa válida en
aquellos que tienen fe , ya que a partir de la muerte y resurrección de
Jesucristo nace también la esperanza para la naturaleza[^67]. En esta
expresión que dista del racional científico humano, está claro el
mensaje de la esperanza de la naturaleza, desde la fe y la gloria de los
hijos de Dios, que no es otra cosa que la vida eterna en el amor divino.
Significaría esto, ¿ que la creación, la naturaleza y los seres
vivientes de otras especies nos acompañarán en la vida eterna ?[^68].
Nadie sabe de manera precisa como es la vida eterna en su forma
espiritual, si es claro que solo el ser humano es pecador y por tanto
podrá ser redimido en su salvación, más el resto de criaturas no son
pecadoras; por ello el proyecto de salvación es más un "estado" del alma
humana en la que se podrá disfrutar del amor de Dios, no un lugar como
se podría interpretar, por ello el resto de criaturas no disfrutarán del
reino de los cielos en el mismo sentido del estado del alma y espíritu
del ser humano en su encuentro con Dios. Pero Dios en su sabiduría,
posiblemente tendrá un plan de armonía en el amor divino no solo con
Dios y nuestros semejantes, sino con otros seres partícipes de la
creación. En su misterio, tal vez Dios lo quiera así, sabiendo que para
el ser humano, parte de su felicidad en el estado "correcto" del corazón
es su admiración por el encanto y magnificencia de su propia obra, la
naturaleza.[^69]

### La casa común

El cuidado de la casa común lo manifiesta el Papa Francisco , en la
carta encíclica "Laudato Si", así[^70]: "Esta hermana clama por el daño
que le provocamos a causa del uso irresponsable y del abuso de los
bienes que Dios ha puesto en ella. Hemos crecido pensando que éramos sus
propietarios y dominadores, autorizados a expoliarla. La violencia que
hay en el corazón humano, herido por el pecado, también se manifiesta en
los síntomas de enfermedad que advertimos en el suelo, en el agua, en el
aire y en los seres vivientes. Por eso, entre los pobres más abandonados
y maltratados, está nuestra oprimida y devastada tierra, que « gime y
sufre dolores de parto » (Rm 8,22). Olvidamos que nosotros mismos somos
tierra (cf. Gn 2,7). Nuestro propio cuerpo está constituido por los
elementos del planeta, su aire es el que nos da el aliento y su agua nos
vivifica y restaura.". Laudato Si , es un llamado al diálogo global que
hace el Papa Francisco, a toda la humanidad y en especial a los fieles
Cristiano Católicos, a liberar a la naturaleza de un yugo impuesto de un
progreso definido en un consumo sin fin, inmerso en una cultura del
desperdicio y la exuberancia, que conlleva al exterminio de los recursos
planetarios en un ámbito extremadamente amplio y preocupante, y que
afecta no solo a la naturaleza sino a la población humana más necesitada
de la tierra; que tiene que enfrentar no solo la disminución de su
capacidad básica de supervivencia, si no de los desastres naturales a
los que queda expuesta con mayor frecuencia y sin capacidad de
contemplación de los débiles gobiernos de muchas naciones. La miopía del
ser humano en este sentido, la expresa el Papa así: "Si miramos la
superficie, más allá de algunos signos visibles de contaminación y de
degradación, parece que las cosas no fueran tan graves y que el planeta
podría persistir por mucho tiempo en las actuales condiciones. Este
comportamiento evasivo nos sirve para seguir con nuestros estilos de
vida, de producción y de consumo. Es el modo como el ser humano se las
arregla para alimentar todos los vicios autodestructivos: intentando no
verlos, luchando para no reconocerlos, postergando las decisiones
importantes, actuando como si nada ocurriera."[^71] La encíclica
"Laudato Si", en su extensión es una continuación no solo del llamado
Bíblico desde el Antiguo Testamento; asunto expuesto también por San
Juan Pablo II y por el Papa Benedicto, sobre la importancia del cuidado
de la casa común como responsabilidad ante Dios[^72], es también un
llamado a todas las instancias científicas y religiosas, que aportan
diferentes aproximaciones a la realidad, para actuar de manera
orquestada y entrar en un diálogo productivo para ambas. Una vez más
queda explícita la relación entre la razón desde la verdad científica y
la religión Cristiana, en la cual mas allá de una negación del aporte
indiscutible de la ciencia , se hace una crítica del uso indebido desde
su capacidad tecnológica y de su visión de progreso material, a todas
luces sujeta a la voluntad del ser humano[^73] y en particular a los
grupos de interés que con mayor poder de influencia y decisión, se
nutren de su propia capacidad, eludiendo así su responsabilidad frente a
la comunidad y entendiendo dicho progreso como un disfraz del dominio
como coartada de una libertad ilusoria para los más desfavorecidos;
entre ellos las demás especies vivientes. El maltrato indiscriminado
hacia otras especies o criaturas es, sin mas ni menos, un perjuicio del
estado "incorrecto del corazón" de quien no ama más allá del si mismo;
puesto que en su acción destructiva ofende la creación de Dios, pero que
aún mas allá, termina manifestándose de alguna manera contra el mismo
ser humano, ya sea como individuo o como comunidad. "El corazón es uno
solo, y la misma miseria que lleva a maltratar a un animal no tarda en
manifestarse en la relación con las demás personas".[^74]

### El llamado de la naturaleza a Francis Collins

Pocos seres humanos pueden negar la admiración y el respeto que por
momentos han sentido hacia alguna manifestación de la naturaleza, ya sea
en la perfección de sus leyes físicas, desde los incontrolables
desastres naturales, o en la interacción con otros seres vivos. Pero,
cuando se ha crecido al menos un pizca en la fe del amor de Dios, se
puede escudriñar un poco más allá del sentido estético de la belleza del
universo y así, descubrir una esencia de la bondad divina. Es un
entrelazamiento expresado como un asombroso regalo de Dios sobre el que
solo se puede sentir una admiración y una responsabilidad que invade por
completo a quien la vive. Hay que recordar que Dios en la Cristiandad
creó el universo y todo lo hizo "bueno". Este estado "correcto" de la
naturaleza es una expresión del amor divino, percibido por quienes
tienen una postura de su corazón, también cimentada en el amor. Ahora
bien, este tipo de experiencias forman parte de un ejercicio racional de
la fe, que si bien no puede demostrar el amor divino en un entorno
científico, tampoco puede ser negada su trascendencia en millones de
seres humanos que sienten un amor indescifrable por la naturaleza, ya
sea desde sus profesiones, sus experiencias puntuales o su admiración
pasajera. El efecto del amor divino expresado en la naturaleza, incluso
puede cambiar vidas en pocos segundos. El ser humano al encontrar en el
interior de su corazón la armonía con el corazón de Dios, en un lenguaje
perfectamente silencioso y armonioso con la naturaleza, puede llevarle a
tomar decisiones trascendentales en su verdad individual al descubrir la
manifestación de Dios a través de su creación. Este es el caso de
Francis Collins[^75] (Staunton, 1950-Actualmente) , científico genetista
investigador del genoma humano , director del National Institutes of
Health, en Maryland, EEUU. Collins en su juventud, mientras debatía y
descubría, en su interior el estado de su fe tuvo una experiencia con la
naturaleza que describe así: " Hecho un lío con todo esto, una preciosa
tarde (uno de esos raros momentos en que tuve tiempo libre cuando era
residente de medicina) me fui a hacer senderismo a la Cordillera de las
Cascadas en el noroeste de los Estados Unidos. Era un día soleado, con
el cielo de un azul perfecto, y tuve esa experiencia que a veces se nos
concede de no tener ninguna distracción que nos impida pensar en lo que
realmente importa. Dejé el automóvil y empecé a subir por una ruta de
senderismo. No tenía ni idea de dónde estaba y es increíble que no me
perdiera. Cuando subía por el camino, giré en una curva y me encontré
con un escarpado precipicio delante de mí, desde cuya parte superior
debía de haber estado cayendo un pequeño hilo de agua. Al bajar por el
precipicio, aquel pequeño hilo se congeló, dejando un salto de agua
congelada fulgurante al sol que se dividía en tres cascadas. Nunca había
visto nada semejante. Contemplar esta maravilla de la naturaleza era
como para quitarle el aliento a cualquier persona, espiritual o no. Pero
a mí me marcó en un momento en el que pude entender que ésa era una
oportunidad para hacerme la pregunta que todos nos tenemos que hacer
alguna vez. ¿Creo en Dios? ¿Estoy listo para contestar sí a esa
pregunta? Y sentí que toda mi resistencia se derrumbaba. No de una
manera que pueda explicar con precisión en términos de «sí, estudié este
argumento lógico y aquel teorema». No, fue simplemente la sensación de
poder decir: «Estoy listo para entregarme al amor que Dios representa y
que ha venido a mí. Estoy listo para dejar a un lado toda resistencia y
convertirme en el creyente que, pienso, Dios quiere que yo sea». Caí de
rodillas y dije: «Esto es lo que quiero. Cristo, ven; sé mi Salvador y
cambia mi vida. No puedo hacerlo por mí mismo, y quizás mañana piense
que estaba loco, pero hoy esto es real. Es lo más real que me ha
sucedido jamás"[^76] . Finalmente Collins terminó aceptando su fe, más
allá del ejercicio racional de la fe, y años después lo confirmó
escribiendo un libro sobre el evolucionismo teísta: "Cómo habla Dios".
Es este un testimonio de como el lenguaje de Dios, aparece en la verdad
individual desde el silencio y en la sincronía con la naturaleza,
uniendo la ciencia y la religión en la experiencia de fe de un gran
hombre de ciencia[^77].

## El sufrimiento del ser humano

El ser humano como parte y criatura de la naturaleza desde una vista
evolutiva, está también sujeto al sufrimiento; siendo el dolor una de
sus manifestaciones básicas, comprendido por la ciencia y dominado hasta
cierto punto en un intento por evitarlo; pues es completamente
antagónico al deseo de bienestar o felicidad. A ningún ser vivo le
interesa sentir dolor; en la humanidad, vencer el dolor es sinónimo de
progreso. Aceptar el sufrimiento o el dolor es irracional. Pero el
dolor, tiene un sentido lógico en la naturaleza, pues sirve como alarma
para anticiparse a la enfermedad; es la alarma de escape, ante la
confrontación con un enemigo; sirve como guía para evitar el camino
difícil y espinoso.

Paradójicamente, el dolor como manifestación del sufrimiento, ha
contribuido de cierta forma a la supervivencia de la humanidad, pues ha
sido una guía frente a los enclaves en los cuales el clima y los
desastre naturales, favorecen o desfavorecen la existencia de las
civilizaciones. Solo basta recordar a Pompeya o los recientes desastres
naturales que ocurren, con mayor frecuencia en nuestros días. El ser
humano entonces, ha logrado hasta ahora convivir con una naturaleza que
ocasionalmente le castiga; aún cuando su aspiración al dominio de la
misma, es cuestionable.

Más allá del dolor como expresión del sufrimiento, el sufrimiento en sí
se manifiesta además a través de un amplio espectro de posibilidades. En
los seres humanos como en las demás especies vivas, hay un sufrimiento
constante por el asecho de las enfermedades, el hambre y la misma lucha
por la supervivencia.

Fuera del ámbito de la naturaleza, el sufrimiento adquiere otra
tonalidad, pues se manifiesta como consecuencia de las acciones que un
individuo impone a otro; o que una civilización impone a otra. Es un
sufrimiento más humanizado, que aunque amparado en un término empático,
puede llegar a ser el más temible de los sufrimientos. Se conocen
diariamente, casos en los que el ser humano, demuestra que es el único
ser vivo capaz de disfrutar con el sufrimiento inducido en otro ser
humano, o en otro ser vivo. No solo desde el castigo físico o la
tortura, sino a través de la injusticia, la subordinación descompuesta
en la esclavitud, o la explotación de otro ser humano. El sufrimiento
inyectado en la civilización humana, por ella misma, en las guerras, es
tal vez el más incomprendido de los sufrimientos. Es así, como el
sufrimiento produce miedo, y el miedo juega al dominio del otro; otra
forma de cercenar la libertad del individuo.

El sufrimiento en el ser humano se expresa también a través del arte,
pues es una condición que toca el color emocional y sentimental en la
estética de la humanidad. En la sociedad moderna, el sufrimiento se
escuda constantemente en la música, donde el aniquilamiento del amor en
el plano sentimental produce el desconcierto del alma , al que se canta
con fervor, como una oda subliminal de superación del dolor del corazón.
Es este último , tal vez el más doloroso de los sufrimientos, puesto que
su complejidad tanto en la evidencia como en el tratamiento, es de
espectros amplios y confusos.

Es el dolor espiritual el que está presente de una manera singular en el
ser humano; en el se refleja también la soledad y el abandono de los
mayores; en el maltrato de los niños y en las consecuencias de la
descomposición y dignidad del individuo y de la familia, por ende de la
sociedad. Este es otra versión del sufrimiento que podría estar
reflejado en las tasas de suicidio o que se refleja en algún tipo de
enfermedad mental. Es paradójico como la civilización humana en los
momentos en que ha logrado el desarrollo científico y técnico como nunca
antes en su historia, con sus implicaciones sobre las oportunidades de
bienestar, se enfrenta a tasas de suicidio, con números absolutos que
oscilan en los cientos de miles, se incrementaron entre 1980 y 2007
considerablemente[^78] , con decrecimientos entre el año 2000 y el
2019[^79]; sin embargo en algunos países las tasas de suicidio
permanecen creciendo a pesar de los esfuerzos realizados para su
prevención. No es factible , hablar de un sufrimiento espiritual en el
plano científico; puesto que la espiritualidad no está demostrada por la
ciencia; sin embargo, en su verdad individual millones de seres humanos
en el mundo buscan constantemente como parte del bienestar,
explicaciones y remedios, tanto al sufrimiento físico como al
espiritual. El sufrimiento en última instancia, sin importar quien lo
padezca, ni su jerarquía social, raza, sexo, religión, capacidad
intelectual; ni cual es su intensidad, su forma u origen, es aquel
estado natural y espiritual, que hace que todo ser humano se sienta
igual a otro ser humano, pues a través de él, el ser humano descubre su
inmensa vulnerabilidad y sin importar de cuanta soberbia se haya
alimentado en su alma, a través del sufrimiento podrá descubrir la
humildad.

## El cristal del sufrimiento en el amor de Dios

En la religión Cristiana, el sufrimiento es uno de los misterios más
manipulados e incomprendidos, pero que adquiere un sentido sobrenatural
desde la verdadera fe. La humanidad sufre por haber merecido su vida
terrenal frente al pecado original en su ofensa a Dios; pero también por
su esperanza de merecer su vida eterna y espiritual, en su
reconciliación con un Dios de amor. A pesar de su aparente
contrasentido, es tal la manifestación de Dios en el amor divino, que
fue aceptado como condición de su muerte en la cruz por su hijo
Jesucristo, para ofrecer la oportunidad a la humanidad de borrar su
pecado y así abrirle nuevamente las puertas del reino de Dios. Es esta
la manifestación más grandiosa del amor divino y de la obediencia del
mismo Jesús a su Padre, otra expresión de la capacidad infinita del amor
del Hijo de Dios, por la humanidad; una manifestación reconocida solo
desde la humildad y la fe del individuo, puesto que como criatura de
Dios, el ser humano, muy bien podría haber sido abandonado a su suerte,
ante el pecado. El sufrimiento, desde la humildad, puede entenderse
entonces como una consecuencia, un camino de regreso a casa, un estado
de purificación por la desobediencia de la humanidad ante Dios; Un
precio que Jesucristo, por amor, decidió pagar en la cruz; y que además
, cada persona desde su fe, puede ofrecer como una oportunidad de
reivindicación, de arrepentimiento, de erradicación de la soberbia y de
otras manifestaciones de su pecado o el de sus semejantes. Visto así, el
sufrimiento es un medio en el camino que conduce a Dios; y desde el
misterio de la fe , es necesario asumirlo , como consecuencia de un acto
voluntario de ofensa al amor divino cometido por la gran familia humana.
Dios asumió el sufrimiento de la humanidad en Jesucristo, no como una
realidad para evadir o eliminar de la vida en el ser humano, pero si
como una condición de vida terrenal que se debe enfrentar, no eludir; y
al hacerlo adquiere otro sentido en la vida, puesto que le recuerda al
individuo una manera de asumir su humildad frente a Dios, de la misma
manera que Jesús lo asumió con el amor del Padre , en el dolor de su
propio cuerpo. Entonces el sufrimiento se convierte en un camino para
regresar al amor divino y acercarse así a Dios; y, por ende, siempre en
el misterio, el sufrimiento está ligado al amor, por ende se enfrenta de
la mano de Dios; el ser humano por su cuenta no tiene la capacidad de
asumirlo en toda su dimensión, puede evadirlo o confortarse mentalmente,
pero en sus manifestaciones más complejas no le puede asumir solo. Del
mal mayor del pecado original de la humanidad contra Dios, Él en su
omnipotencia, ha sacado la misma salvación de la humanidad: solo Dios
sabe extraer el mayor bien de todo mal, incluido el sufrimiento, pues lo
ha convertido en amor infinito. En aquellas personas que ante la grave
enfermedad asumen por su voluntad una posición de humildad y se acercan
a Dios en la búsqueda de su misericordia obtienen como recompensa la
gracia de Dios y un cambio en sus vidas. Ante situaciones adversas,
quienes aman al que sufre, manifiestan su amor de manera desinteresada;
esa es la misma presencia de Dios. El sufrimiento como expresión de
amor, exalta la máxima expresión de la fe a través de la caridad, en
aquellas circunstancias desconcertantes en las que el ser humano, no
admite y no termina de comprender, hasta que acude a la misericordia de
Dios, incluso, en aquel instante previo a la muerte. No rendirse ante el
sufrimiento, pero rendirse ante Dios, tiene como regocijo su amparo, su
mano bondadosa que acude en su auxilio desbordándose en bienes
espirituales, ante un ser humano que ha descubierto su impotencia, así
Dios, a través del sufrimiento también se manifiesta; no de la manera
deseada por el ser humano, quien daría todo por eliminar todo
sufrimiento por si mismo.

Un Padre y una madre, pueden llegar a padecer mucho sufrimiento, pero lo
hacen solo por el amor a sus hijos. De la misma manera que Jesus, sufrió
por la humanidad. Esta relación amor y sufrimiento, se observa en las
relaciones de pareja, en la educación de los hijos, en las relaciones
con los seres cercanos, en los círculos familiares y en la verdadera
amistad; es una condición humana con sesgos de irracionalidad,
fácilmente verificable desde la verdad individual, en toda escala
social. Jesús, vivió el sufrimiento también como un ser humano, sintió
desconsuelo, angustia y abandono antes de ser violentamente
ultrajado[^80].Sin embargo, Jesús obedece, lo acepta y lo enfrenta, con
la oración y el amor del Padre. Jesús, enseña de manera sencilla, cómo
del sufrimiento llega un bien mayor, aún cuando el ser humano no lo
comprende: "La mujer se siente afligida cuando está para dar a luz ,
porque le llega la hora del dolor. Pero después que ha nacido la
criatura se olvida de las angustias por su alegría tan grande; piensen:
un ser humano ha venido al mundo! Así también ustedes ahora sienten
tristeza , pero yo los volveré a ver y su corazón se llenará de alegría
, y nadie les podrá arrebatar ese gozo, cuando llegue ese día ya no
tendrán que preguntarme nada."[^81] ¿ Porqué Dios permite el
sufrimiento, si tanto amor siente por la humanidad ?. Por una parte,
Dios sufre con el sufrimiento de cada ser humano. Dios no desea el
sufrimiento del individuo, pero es más fuerte su disposición a que el
ser humano, sea una criatura hecha a su imagen y semejanza. Para que
esto suceda , Dios respeta a toda costa el libre albedrío y la voluntad
del ser humano, la misma que causa el sufrimiento de sus congéneres. Si
no fuese así, todo ser humano viviría en un sufrimiento permanente, ya
que en su condición de criatura, no tendría libertad en la manera en que
dispone de ella; en un grado superior y diferente al que dispone el
resto de la naturaleza. Puede no existir una razón científica, pero toda
criatura viviente en la naturaleza, prefiere por simple intuición vivir
en libertad; en la humanidad, la libertad es una condición invaluable;
ningún individuo es feliz bajo una manipulación o control perpetuo por
parte de otro individuo. Esta manifestación, en el extremo del dominio
total del otro ser humano, conduce a la esclavitud, la que aún
persistiendo en la sociedad moderna, es detestada y rechazada desde la
condición espiritual en el estado correcto del corazón; esta es una
evidencia, en el ejercicio racional de la fe, explícita en la aspiración
a la libertad. El amor que Dios nos enseña es contrario a dicha imagen
de toda esclavitud, incluida la esclavitud del pecado; el amor de Dios
es un amor incondicional, pero sujeto por su propia fidelidad, al libre
albedrío del individuo y de la humanidad. Es por esto que Dios permite
el sufrimiento que también parte de la voluntad del individuo, o la
voluntad de la propia humanidad; siendo por ello, la libertad, causa de
amor o sufrimiento en el ser humano. Desafortunadamente, la humanidad ha
elegido aprender por el camino, del sufrimiento , por cuenta propia. Sin
embargo, la manipulación racional condiciona a Dios por su supuesta
incapacidad de eliminar el sufrimiento, causado por el ser humano. Las
guerras, la injusticia humana, la tortura y todo tipo de sufrimiento
inducido por un individuo a otro, o por una civilización a otra, es en
este caso consecuencia de la voluntad de los seres humanos, en la cual
Dios no interfiere, pero si condena y de una manera muy explicita: Debes
amar al prójimo como a ti mismo. El sufrimiento causado por la violencia
en cualquiera de sus formas corresponde al estado "incorrecto" del
Corazón; es el resultado de una formación espiritual contraria al amor y
redundante en odio, crueldad, rencor, resentimiento y venganza. Ahora
bien, el otro tipo de sufrimiento, es el causado por la naturaleza, tal
como las enfermedades y desastres naturales. Tiene su raíz en la
condición humana de ser una sola familia y parte de la misma naturaleza,
en la cual la humanidad terminó abatida por su desobediencia; nuevamente
fue la voluntad del ser humano, la misma que le impuso dicha condición.
Dios no lo deseaba y lo advirtió a los padres de la humanidad, la
desobediencia de alimentarse del árbol de la ciencia del bien y del mal,
hizo que el ser humano se reconociera en su condición pecadora y que
como consecuencia tuviera su destierro del hogar santo y espiritual de
Dios; tal vez, si la familia humana hubiese obedecido a Dios, no hubiese
conocido nunca la maldad, ni hubiese actuado en ella. Dios lo quiso así:
la humanidad como una familia obediente a la única ley , la ley del amor
que trasciende hacia la santidad de Dios. Pero, la humanidad al
desobedecer, se apartó de Dios; Jesús le brinda una nueva oportunidad,
una nueva alianza con un Dios siempre fiel, para llegar al amor divino.
Todo individuo que sea obediente en los mandamientos del amor tendrá su
recompensa, tanto en su vida terrenal , como en la vida eterna. Este
aspecto último , solo tiene sentido en la fe y en la gracia; solo
aquellas personas que estén ávidas del Espíritu Santo podrán
experimentarlo y vivirlo de manera integral. Aún cuando la condición
humana sea susceptible al sufrimiento, no es este el deseo del amor
divino de Dios; todo ser humano que decida vivir cobijado por el amor de
Dios , tendrá a su alcance la felicidad terrenal, donde el sufrimiento
no es condición permanente, y se le abrirán las puertas para la
salvación de su alma en la felicidad de la vida eterna, estado
espiritual en el cual el sufrimiento, no existe. Y es importante aquella
aclaración; el llamado de Dios en la divina revelación, es a la búsqueda
de la felicidad que inicia en la vida terrenal[^82], no a la búsqueda
del sufrimiento. Entonces, el sufrimiento tiene bajo la religión
Cristiana, un fin muy claro y es el de ser un medio para llegar al
máximo estado del amor divino, que es el regreso de la humanidad, al
hogar de Dios en la vida eterna; el sufrimiento , en un individuo con fe
inquebrantable, se convierte en el culmen del amor a Dios. He aquí otra
manipulación racional: la interpretación de la religión Cristiano
Católica en la invitación al sufrimiento, no significa , que se debe
buscar el sufrimiento, puesto que en la condición humana se le encuentra
en un constante ir y venir, divagando entre la alegría como expresión de
la felicidad y el dolor como expresión del sufrimiento; pero si llega,
se debe enfrentar con la disposición de la gracia divina en el corazón;
solo así puede ser sobrellevada una situación de sufrimiento que limita
en la impotencia del si mismo, que se convierte en misterio no deseado y
en mayor medida cuando llega al extremo de la muerte; pero que gracias a
Jesucristo, permite colmar el significado de la vida terrenal en la
felicidad eterna. Tal vez, Dios en su sabiduría lo ha definido de esa
manera, con el fin de que el ser humano, se cuestione y regrese a su
encuentro al hacer que se enfrente con su debilidad; y aunque para
entenderlo a cabalidad se requiere de la fe y la gracia divina, en el
ejercicio racional de la fe, también hay una explicación evidente en el
diario vivir. El individuo, en condiciones de bienestar y felicidad
aparente, se olvida por completo de Dios y muchas veces hace alarde
desde su ego, de su gran capacidad de dominio sobre la vida; más aún en
la sociedad del progreso tecnológico, donde en apariencia todo se puede
dominar. Pero tan pronto se enfrenta a una situación adversa, de suprema
intensidad, dolor o angustia, en el reconocimiento del máximo
sufrimiento del si mismo, en el estado de impotencia absoluta, ya sea en
un momento de desconcierto y súplica, o de exigencia a su destino
mortal, es en esos instantes cuando el individuo y la sociedad reconocen
por la fuerza su condición de fragilidad humana, su vulnerabilidad. Es
este reconocimiento una evidencia , una aseveración racional y al mismo
tiempo incomprendida. Y es aquí donde entra la voluntad humana, desde
los diferentes matices del misterio de la fe, en el si mismo, en su
verdad individual, a encontrarse con el amor de Dios o a rechazarle. La
misericordia de Dios se derrama en aquellos que tienen una fe suprema,
pero siempre aceptando desde la humildad, la voluntad de Dios, puesto
que el sufrimiento del que se hace parte puede ser utilizado por Dios,
como un remedio espiritual ya sea en beneficio de otro ser humano, de un
alma en pena, de una comunidad, o de la misma humanidad, siempre para un
bien mayor; en el mismo sentido, en que Jesus, por amor, ofreció su
sufrimiento y su muerte para la salvación de la humanidad. Es entonces,
en dicho sentido, el sufrimiento una expresión del amor divino, algo que
no podría ser entendido por un ser humano que no tenga la disposición de
encontrar la gracia de Dios desde su encuentro con el Espíritu Santo, en
las profundidades de su propio silencio. El misterio del sufrimiento es
tan poderoso permeado desde al amor divino, que hay muchas personas que
han decidido con fuerte voluntad vivirlo intensamente desde la humildad
y lo han ofrecido a Dios Padre como lo hizo Jesús; no como exigencia,
sino como ofrecimiento espiritual. Algo que desde la crítica superficial
se deriva en el absurdo, pero que en la experiencia subjetiva y la
verdad individual de quienes lo encuentran en una auténtica fe, lo
experimentan y lo viven desde la gracia en el mismo misterio del amor.
El sufrimiento es en ocasiones, la forma como Jesus decide seguir
enviando señales de amor a la humanidad. Se puede convertir en un camino
hacia la santidad, que en la historia de iglesia Cristiano Católica se
ha manifestado una y otra vez, miles de veces en determinadas
circunstancias y personas con aquel "Don" al cual no todos pueden
acceder; es el misticismo, un misterio espiritual.

### Marta Robin y el Don del sufrimiento en el amor de Dios

Marta Robin ( Châteauneuf-de-Galaure, 1902 --
1981,Châteauneuf-de-Galaure)[^83] fue una persona cuyo testimonio de
vida en el sufrimiento, representa a aquellos que han decidido difundir
sabiamente el brillo del amor divino, desde una posición que abraza
constantemente el dolor de la miseria humana. La vida de Marta Robin, es
un testimonio del mensaje del amor divino, es dar a conocer el amor de
Dios desde un escandaloso y humilde sufrimiento en el más puro silencio.
A sus 16 años , comenzó a tener los primeros síntomas: fiebres, migrañas
persistentes, vómitos. En 1918, entra en coma, luego su diagnóstico es
de encefalitis letárgica. La enfermedad avanza, con periodos de leve
mejoría, a los 17 años sus piernas se paralizan; a los 28 años tiene una
parálisis del tracto digestivo por lo que no puede alimentarse. A sus 39
años tiene una afectación de los nervios oculares y la luz le hace
sufrir, por esto debe permanecer en la penumbra. Pronto cae en una vida
donde la cotidianidad de sus sufrimientos es lo único que tiene,
olvidada y convertida en una carga para su familia; sin ningún porvenir,
ningún proyecto de futuro le es posible. Escribe a su amiga en 1928 , a
la señora Delatour : \" Me siento molida física y moralmente. Estaría
mucho mejor bajo tierra que sobre ella, a mi parecer. (\...) Usted, mi
dulce Amiga que es tan buena y me comprende tanto, me perdonará ser tan
poco valiente\". Es así, en este límite de la impotencia del si mismo,
cuando Marta toma conciencia de su condición y gracias a una visita de
los religiosos Capuchinos, comienza a comprender como Dios incluso puede
utilizar el sufrimiento para salvar las almas; toma entonces dos
decisiones fundamentales: vivir tanto como más puede y unir por amor ,
su sufrimiento al sufrimiento de Jesús torturado y crucificado. Marta,
decide obedecer a sus doctores y luchar contra el dolor en la medida de
sus capacidades; no se entregó sin su lucha personal, pero si ofreció su
sufrimiento. Decide que tendrá que buscar la manera de pagar sus
remedios y no convertirse en una carga para sus Padres. Paulatinamente,
sus adversidades corporales se van convirtiendo en fuente de vida y
esperanza.[^84]

Podría considerarse a Marta Robin, como una persona muy valiente y digna
de un reconocimiento y admiración por su fe; por transmitir el mensaje
de Jesús en su vida de una manera literal y desde una sabiduría extrema.
Gran respeto se puede manifestar sobre una persona que con una fuerza de
voluntad indecible, logra una vida ejemplar, manifestando el amor desde
una condición de sufrimiento y dolor permanentes. Pero, hay algo que va
mucho más allá de todo esto, algo que no tiene explicación desde la
ciencia ni la razón, pero que solo en el si mismo de su ser, en su
propia verdad individual puede tener explicación; es en este escenario ,
en el que la fe obra paulatinamente desde la voluntad de quien la vive
en su travesía del corazón buscando al corazón, que se ratifica en la
unión con el corazón de Jesús; y en el caso de Marta Robin, ocurrieron
fenómenos propios de aquellas personas místicas[^85] escogidas por Dios
y cuya respuesta de aceptación influiría en la vida y la fe de miles de
personas; que, de una u otra manera ya sea mediante un dialogo directo
con Marta Robin, o a través de su legado, también incorporan en su
propia fe el amor de Dios; esta es una expresión del misterio de la fe.
La expresión racional de la fe, en personas como Marta Robin se
convierte en fe verdadera en el transcurso de sus propias vivencias. Y
es así como la dualidad amor-sufrimiento, de Jesús en la cruz se
manifiesta hasta nuestros días; y son estas señales, evidencias del amor
divino en quien las vive directa o indirectamente, más allá de su
contenido conceptual , evidencias suficientes pero no necesarias, que
como parte de un entorno de comunidad aún más amplio, impulsan, dan
fuerza y mantienen viva la religión Cristiana. Veamos algunas de estas
evidencias en Marta Robin. El primer punto a destacar es el cambio de su
voluntad de aceptación de Dios, tan repentino, pero además cargado de
una fuerza espiritual , sin la cual, posiblemente Marta Robin no habría
logrado sobrevivir tantos años. Una persona, prácticamente desahuciada y
alimentada, casi que únicamente con la eucaristía a través de su
vida[^86], que pudo reflejar tanta alegría y dar sabio consejo a miles
de personas a lo largo de su vida, además de realizar un proyecto de
dimensiones globales, no podría hacerlo sin la gracia del Espíritu
Santo. "Luego de la visita de los Padres Capuchinos, cuando todavía
abarcaba ciertas dudas sobre su decisión de cambiar radicalmente su
forma de ver la vida, iluminada desde lo alto, comprendió que esta
llamada era adecuada. Todo coincidió y recibió como una "efusión del
espíritu" según la expresión consagrada. El espíritu Santo se adueñó de
ella y le dio tanto su misión como las fuerzas para asumirla. Al
siguiente día , un 4 de Diciembre de 1928 en la noche, cuando estaba
todavía temerosa de su decisión Jesús se le apareció y después de
haberla tranquilizado tres veces, le preguntó si aceptaba sufrir por la
conversión de los pecadores en general y de Châteauneuf en particular. A
partir de ese día, estaba totalmente dedicada a Dios y resuelta a
aceptar todas las pruebas por los pobres pecadores , y solo nuestro
señor puede saber lo que sufrió desde entonces"[^87]. Un cambio
espiritual radical, que desde una explicación racional podría
justificarse tan solo con la actitud de un persona decidida; pero que
además, por su legado, claramente para aquellos que viven la fe, es algo
que tiene un contenido mucho más trascendental. Marta escribiría "En
cierto momento temí ya no tener fuerza, ni voluntad para cosa alguna.
¡Que angustia!. Pero Jesús me rehízo en si mismo y únicamente para Él
solo. Es como una vida nueva\...siento avidez, y verdadera hambre y sed
de trabajar por el amor y la gloria de Dios\..."[^88]. El segundo punto
a destacar, es aún más misterioso en el espectro divino a que
corresponde, pero al mismo tiempo no deja de ser una señal, desde la
experiencia de la fe. Los estigmas, son la vivencia de la pasión y el
sufrimiento de Cristo, pueden manifestar físicamente sus llagas, en
manos y pies , los relacionados a la corona de espinas y el sangrado del
costado en algunos casos, y en otros casos sin señales físicas externas,
llamados estigmas invisibles. Un poco más de 300 casos se han reportado
y en los que se piensa, son consecuencia de una acción divina; siendo
San Francisco de Asís en el siglo XIII el primero en manifestarlos,
también en muchos otros santos, siendo los estigmas más sobresalientes
los del beato Padre Pio, durante el siglo XX[^89]. Los estigmas no han
sido utilizados por la religión Cristiano Católica como elementos
indispensables para promover la fe, pero como en el caso de Marta Robin,
son elementos que, más allá de quien los padece, quienes tienen la
oportunidad de observarlos y enfrentarlos, indiscutiblemente entran en
un cuestionamiento desde su verdad individual, directamente en su propia
fe, puesto que dicha realidad no puede ser tan solo evadida, como si
nada ocurriese. El fenómeno es atestiguado por tanta gente que parece
absolutamente indiscutible , más de cincuenta personas interrogadas
vieron que la sangre manaba de las llagas de Marta. Los estigmas,
aparecieron en 1931, no duraron durante toda la vida de Marta con
excepción de los de la frente. Marta dice al respecto, interrogada por
Jean Guitton, quien le diría : "Pero, se dice, que los estigmas causan a
la vez mucha alegría y mucho dolor". "Si, a la vez, pero no puede
pensarse en un gozo humano o sensible; es un gozo vivo pero divino, un
gozo totalmente interior y como es un sufrimiento extremo, interior para
empezar, si Dios no nos diera su apoyo se produciría la muerte".[^90] Al
respecto para la ciencia, la causa de los estigmas, no ha sido aún
identificada y permanece como ejemplo de una intrincada relación entre
la medicina, la psiquiatría, la psicología , la espiritualidad y el
cuerpo humano [^91]. Hay quienes atribuyen los estigmas al fanatismo
religioso y una posible causa desde la manifestación emocional; sin
embargo, queda en entredicho, si aquellas personas como Marta Robin,
pueden tener tales trastornos psicológicos dadas sus capacidades de
comunicación, su indiscutible carisma por quienes la conocieron, su
capacidad de aconsejar a miles de personas durante su vida y su
capacidad para crear y liderar proyectos, dignos de cualquier persona
que tuviera su salud en su máxima capacidad. Es en este sentido, en el
cual muchas personas que la conocieron, deciden, fortalecer su fe, o
simplemente apartarse de ella. Naturalmente , el tema de los estigmas ha
sido aprovechado por embaucadores y todo tipo de personajes que solo
buscan algún protagonismo; en el caso de Marta y muchos otros místicos
Cristiano Católicos, también se han levantado sospechas, y han tenido
gran resistencia al interior de la misma iglesia Cristiano Católica;
pero , en los casos verdaderos, siempre partieron de la humildad y el
deseo de evitar su divulgación pública. El tercer elemento a considerar
que surge de la vida en sufrimiento de Marta, es la creación de los
Foyer (Foco -- Hogar); un proyecto algo temerario y de características
excepcionales naciendo de una mujer con tantas limitantes físicas. Solo
la seguridad del Espíritu Santo, que trabajó en lo profundo de su
corazón, pudo generar tal confianza, como para continuar con dicha
tarea. En el caso de Marta, varias veces Jesús le habló de su obra
evangelizadora para la Gloria de Dios " Te he escogido para reanimar en
el mundo el amor que se extingue, para servirme de auxiliar y revelar mi
obra. Haré de ti una llama de ese incendio que quiero encender en la
tierra".[^92] Varias veces lo hizo, y en sus escritos personales, Marta
manifiesta su temor y la propia incomprensión de aquella intención
divina; sin embargo, en algún momento sus relatos escritos dicen "¡Que
martirio y que suplicio para mí!\...estaba sofocada de angustia de solo
pensar en lo que tenía que decir, temía tanto hablar. Pero el Señor
había insistido con tal autoridad esta vez, que no podía esperar más".
El primer Foyer comenzó como una escuela para niñas y señoritas, en su
población natal Châteauneuf; y a pesar de lo fácil que es escribirlo en
dos líneas , la historia de cómo sucedió está supeditada a muchas mas
complejidad, dadas las condiciones políticas de la época, la situación
de la población, el hecho de ser mujer y además enferma, la falta de
dinero y muchos obstáculos más. Sin embargo, el núcleo de esta obra, no
es solo el hecho de que haya sucedido, sino, el hecho de que Marta no se
sintiera capaz de involucrarse o de sentirse fundadora del proyecto , ni
de su empoderamiento paulatinole tomó cierto tiempo participar
totalmente en el proyecto."Luego no pensó que las personas que la
rodeaban pudieran dirigir la escuela , poco a poco fue cambiando y
finalmente aceptó formar a los miembros de la obra, pero sin sentirse
aún capaz de impulsar por si misma una obra de gran influencia, y sin
poder ver aún, aparentemente, la forma que podría adoptar
posteriormente. Más tarde afirmaba -- Cuando pienso que el Foyer empezó
por la escuela de niñas, aún me estremezco".[^93] Marta había
encomendado el proyecto a la Virgen María y estuvo acompañada también
por su amor divino y protector. Este breve relato , señala como una
persona postrada en el sufrimiento tiene la capacidad de haber
diseminado su obra , aún después de su muerte, no solo con el Foyer de
Châteauneuf sino, con 76 Foyers en cuatro continentes[^94]. Marta Robin,
representa así, en un sentido profundamente religioso, la fortaleza del
amor actuando y señalando su capacidad divina, despertado por el
sufrimiento y el dolor humano, que solo adquiere sentido en el
sufrimiento de Jesús por la humanidad. El amor de Dios, en la dualidad
amor -- sufrimiento, se resalta en quien lo vive , en su experiencia
subjetiva; y a su vez se irradia en quienes reciben su luz, ante la
cercanía y la vivencia de personas como Marta Robin; que finalmente se
traduce en el reconocimiento de la verdad de Jesucristo a través de una
fe inquebrantable.

## La sabiduría

Durante los últimos siglos, a partir de la ilustración ( Mitad siglo
XVIII -- primeros años del siglo XIX ), la sabiduría en el ser humano se
ha estado transformando, anclada a una definición vinculada al
razonamiento científico, la tecnología y al conocimiento interpretado
desde el beneficio de un bien común, como en la salud social; o en otros
casos como desde la capacidad y habilidad individual o colectiva como
motor de la productividad y del llamado progreso económico. En
diferentes escenarios, la sabiduría le ha rendido tributo a la razón
cada vez con mayor insistencia, a través de la formación técnica a
partir de los esquemas educativos que mejor responden a los estándares
de productividad y eficiencia establecidos por los modelos económicos
que se desprenden de la noción de bienestar y felicidad;estos, a su vez
cimentados en los principios y valores con diferentes sentidos para cada
grupo social, cultura humana, o nación; pero unificados en la concepción
de un mundo llamado desarrollado, aquel que ha alcanzado los más altos
estándares del progreso moderno en términos de beneficios económicos y
altos estándares de bienestar. Jeremy Rifkin lo resume así: "El progreso
era una idea nueva y revolucionaria de la que había pocos precedentes.
En esta nueva visión, el tiempo ya no era un medio para preparar la
segunda venida de Cristo, sino un medio para plasmar la nueva idea
temporal del progreso. Creer en el progreso es creer en un futuro que
siempre mejora y, sobre todo, perdura. El progreso no tiene fin. Es
incontenible, implacable. Nos lleva al futuro donde no hay límites ni
fronteras, un futuro infinitamente expansivo e intemporal. El progreso
material es nuestro pasaje a la inmortalidad, la forma de engañar a la
muerte , de superar una existencia fugaz. La ciencia y la tecnología se
han convertido en el nuevo medio de lograr la salvación . En tiempos de
crisis miramos a la ciencia y a sus productos tecnológicos para que
rescaten a una humanidad pecadora de las fuerzas del caos que tantas
veces interfieren en nuestros esfuerzos por disfrutar de la seguridad.
La ciencia moderna y la tecnología son los mesías seculares de un mundo
materialista. Son las garantes de nuestra seguridad y a la larga, de
nuestra inmortalidad. Mediante la ciencia y la tecnología podemos
extender nuestro control al futuro , a las fuerzas de la naturaleza y a
la duración de nuestro cuerpo. Viviremos más y mejor, disfrutaremos de
una buena vida y moraremos en un edén terrenal hecho por nosotros, donde
la abundancia material actuará como una barrera contra los estragos del
tiempo y los embates de la muerte"[^95]

Sin embargo, la misma ciencia y la tecnología, no garantizan, la
construcción de un modelo de principios y valores que le sirvan de
sustento a la humanidad en la búsqueda de la justicia, la paz y la
convivencia permanente; es el cuestionamiento planteado desde la
conferencia de Solvay y el de cómo los grandes avances tecnológicos,
además de los indiscutibles beneficios sociales, conllevan en muchos
casos a posiciones éticas, que dependen de los principios y valores
sobre los que descansan. La creación de un nuevo conocimiento que
aplique al progreso económico, ha logrado supeditar a un plano de
trivial importancia, la discusión sobre la sabiduría construida por
siglos por la humanidad, en el plano de la fe y la razón; tal vez en
virtud de la experiencia histórica que ha ejercido la religión en
general, en su perspectiva de fanatismo religioso, en su apropiación del
poder humano, o en los intentos infructuosos de llegar a un consenso
académico y político desde la ilustración hasta nuestros días. En
octubre del 2006 un grupo de trabajadores de la universidad de Harvard ,
responsable de revisar el currículo de educación general , propuso que
todos los estudiantes siguieran un curso obligatorio sobre "razón y fe".
La propuesta sacudió al mundo académico y se convirtió en objeto de
debate en todo el País. Las autoridades religiosas y varios académicos
se volcaron en apoyo de la propuesta, sosteniendo que la institución
educativa más venerable del país por fin había entrado en razón y
reconocía el papel esencial que desempeña la fe en la mayoría de las
personas. Una encuesta realizada en la UCLA[^96] en aquella misma época
reveló que el 79% de los estudiantes universitarios de primer año creían
en Dios y que un 69% rezaba y hallaba fuerza, apoyo y guía en sus
creencias religiosas. A los profesores más laicos de Harvard les
preocupaba que obligar a los estudiantes a seguir ese curso pudiera
abrir la puerta a un renacer religioso en el campus y a exigencias de
introducir la religión en otros apartados del currículo. Se resistían en
reabrir el antiguo debate sobre la fe y la razón que tantos
enfrentamientos había originado durante casi dos siglos. Más importante
aún , les preocupaba que se llevara a implantar un curso similar en las
universidades de todo el país. Finalmente, la propuesta fue rechazada de
plano.[^97] Hoy en día la fe desde la sabiduría humana es vista como una
simple expresión emocional, con ingredientes irracionales, un tanto
reflejo de algún mito de perfil medieval, un tanto dañina para un modelo
de progreso en una fiera competencia desenfrenada en el crecimiento
económico; el valor de la fe Cristiano Católica, y de otros entornos
religiosos, en términos de la sabiduría milenaria, tiende a desaparecer
en el ecosistema de la gran mayoría de diversos grupos de interés, en su
intrincado y complejo modelo de interacción social, en su influencia y
poder global, mas no en el individuo. La persona humana, guarda en su
interior aquella reverencia y respeto por quienes considera dignos del
bien de la sabiduría, pero el freno contradictorio que el mundo ha
impuesto a su búsqueda y entendimiento para fines del encuentro de
principios y valores terrenales y trascendentales, lleva a las crisis de
identidad y frustración propias de una sociedad en la que el individuo
no puede separarse de su entorno como ser social.

Esta situación ha traído una gran consecuencia, cuya solución se
constituye en uno de los retos con efectos que serán determinantes, en
el camino y redefinición del progreso moderno. Por un lado está el
legado histórico de la concentración de conocimiento, formación técnica
o desarrollo de capacidades y habilidades individuales. La debilidad de
la sabiduría humana relacionada con el conocimiento , atraviesa en este
siglo por el dilema de la continuidad en los niveles desproporcionados
de acceso al conocimiento más reciente, al conocimiento y a la formación
de carácter técnico y productivo que genera algún reconocimiento de
valor, la mayoría de las veces asociado a la riqueza material; La
velocidad de creación del nuevo conocimiento de valor económico frente a
la velocidad[^98] de la distribución del mismo , en una población que se
multiplica constantemente, especialmente entre los más desfavorecidos es
uno de los grandes retos y dilemas humanos. La historia misma de la
humanidad describe como la concentración e interpretación limitada del
conocimiento humano, ha sido una constante universal, lo que lleva a
preguntarse si se alcanzará algún día un estándar con rasgos de
uniformidad en el acceso al conocimiento de valor en todos los
individuos que la conforman. Pasando desde la civilización de la antigua
Mesopotamia, donde la invención del primer alfabeto era de acceso para
la aristocracia imperial, siguiendo por los poderosos imperios de
grandes extensiones geográficas, donde el conocimiento sobre la técnica
de la guerra, la agricultura, y los metales, era parte del círculo de un
emperador; continuando en una edad media de clases y escalas sociales
con privilegios circundantes a los reyes de cada época, cultura y forma
de gobierno -- ya con perfil de estado; hasta la reciente llegada de la
revolución industrial, donde nace el poder económico exponencial en los
estados -- nación y hasta nuestros días en la era de la revolución
científica-tecnológica. En todos aquellos episodios de la historia
humana, el conocimiento de valor para cada época ha estado en manos de
unos pocos grupos de interés. La idea del acceso universal del
conocimiento humano, fue tal vez por primera vez propuesta por el
imperio Griego con el nacimiento de la ciencia de la época, desde la
filosofía de Aristóteles y Platón; pero aún, en nuestros días el mundo
presenta un esquivo desequilibrio en la civilización contemporanea.

Desde la perspectiva del entendimiento de la sabiduría en el plano
individual, en su capacidad como guía de principios y valores para la
vida misma y su entorno espiritual, tampoco hay una solución clara al
conflicto que se da entre la propuesta de la sociedad y la percepción
individual.

En el esquema de las naciones modernas , es la apropiación de la
definición de la sabiduría humana desde el poder político y de decisión
sobre la vida de millones de seres humanos, a través de variados y
multifacéticos grupos de interés, que poco a poco van imponiendo sus
principios y valores, en un ir y venir ideológico muchas veces
polarizado por la misma falta de su entendimiento y que desde una
interpretación de la verdad individual, se van extrapolando e imponiendo
sobre diversas comunidades carentes al mismo acceso a aquel poder, de
valor económico y político. Son aquellos intereses, los que terminan
modelando el nuevo gran espectro de principios y valores divergentes a
los que se va encaminando la humanidad. Son intereses, que dependen de
la interpretación de la verdad individual de unos pocos sobre una gran
mayoría. Adicionalmente, son principios y valores que están
desconectados del ejercicio de la razón en la fe y de la fe misma; por
ende, como se ha mencionado a través de John Henry Newman, un
conocimiento aceptado solo desde su reflejo funcional, "lo que funciona
bien para todos, está bien"; es un conocimiento mutilado en su
interpretación, ya que carece del sentido moral del estado correcto o
incorrecto del corazón. Es como aquel barco que avanza velozmente
impulsado por el viento del conocimiento en el saber único del poder
económico y productivo, pero navega sin rumbo fijo , puesto que el timón
ya no obedece al establecimiento de una dirección correcta, sino al
interés de adquirir cada vez más potencia, o en términos económicos, de
más progreso acorde a los grupos de interés que le manejan. Un interés
que tiene por momentos un rumbo definido y por momentos un rumbo
indefinido por la euforia de una circunstancia histórica desafiante, que
cambia inesperadamente, como lo puede hacer el viento frente al barco
sin timón. Este se ha convertido en el gran paradigma de la sabiduría
humana del mundo contemporáneo. Siendo así, la falta de definición de la
sabiduría humana en una dirección correcta , más aún, su reducido acceso
por el grueso de la comunidad mundial, se convierte de manera equívoca
en foco de rebeldía y violencia por quienes sienten aquella frustración
e impotencia en la falta de oportunidades; en muchos casos se convierte
en injusticia y en otros en manipulación y apropiación , de principios y
valores a favor de unos o de otros;ha derivado también en una
tergiversación de la columna vertebral de la sociedad humana, que no ha
sido capaz de ser conducida desde un "estado correcto del corazón" por
aquellos grupos de interés, que tienen el conocimiento científico y
técnico en su haber. Son estos líderes de la sociedad moderna, en todo
su amplio espectro, quienes tienen la riendas y el control del ideal del
progreso, bienestar y felicidad en sus manos; hoy en día estos grupos de
interés son de múltiples facetas y conformación, ya sea bien llamados
grupos políticos regionales o locales, instituciones de carácter global,
naciones y grupos de naciones bajo intereses comunes, grupos económicos
poderosos , entre muchos más. Existe entonces una limitación histórica
cuyas ataduras la humanidad no ha logrado desvanecer a través de la
sabiduría humana; como lo afirma H.G. Wells "Ningún hombre puede ir más
allá de sus propios conocimientos como ningún pensamiento puede exceder
los límites de su pensamiento contemporáneo".[^99] En el pensamiento
contemporáneo, la fe y el amor como guía y sustento del progreso y
desarrollo humanos, tienden a desaparecer, en detrimento del individuo y
por ende de la sociedad de la que hace parte.

Otro aspecto fundamental en la perspectiva de la sabiduría humana del
presente siglo que se deriva de los efectos del desarrollo
científico-tecnológico en la noción del estado deseado de bienestar y
felicidad es la tendencia hacia la creación de una cultura humana
propiamente individual donde se pretende minimizar la relación con "el
otro", aquel que no forma parte de "mi verdad". El individuo humano es
consciente de su sabiduría en términos de capacidad técnica e
intelectual, en un mundo donde las estructuras piramidales de los
antiguos esquemas imperiales tienden a desaparecer y a ser reemplazadas
por el poder y la libertad sin límites del individuo, es así como el
papel de los grupos de interés se alimentan desde aquel interés
individual; de tal manera que todo lo demás gravita sobre aquel supuesto
orden, que en realidad es una entropía divergente conformada desde una
verdad relativa que en el fondo es el absolutismo de alguna verdad
individual. En estos casos, la consistencia de los grupos de interés no
son en realidad, un interés colectivo o de comunidad, no prima el
interés de coherencia del grupo, sino una catarsis de intereses
individuales que alineados en un liderazgo común logra "dominar" a otros
grupos de interés en su carrera al progreso. En dicho sentido, aquella
célula de verdad e interés individual fortalecida y enaltecida en la
sabiduría humana universal y milenaria, tiende a transformarse, desde la
concepción del si mismo como parte de un grupo de interés bajo un
principio de unión coherente con el bien deseado por "mi" grupo de
interés, sobre el bien de toda la sociedad; un principio respetado y en
muchas ocasiones, de diversas formas, elevado a una nueva concepción de
una estirpe superior en el sentido del "super yo" alineado en una
comunidad donde prevalece el interés individual, capaz de todo con la
bandera de la razón, la ciencia y la tecnología, ante poniéndose como
escudo ante cualquier evento que afecte su noción de bienestar o su
interés individual. Es una evolución, un nuevo camino hacia un "super
yo" relativista, en un sentido similar al antiguo antropocentrismo[^100]
en el que todo giraba alrededor del ser humano. El anhelo es el de un
individuo con su propia sabiduría técnica embebida en su necesidad de
libertad ilimitada como fuente de bienestar y felicidad; un individuo
cuya máxima prioridad es el si mismo y bajo este condicional se perfila
un nuevo edificio de principios y valores en la sociedad de la razón,
que implica una tendencia hacia la construcción de islas de individuos
contradictoriamente felices; puesto que el ser humano depende de sus
relaciones con el "otro" para alcanzar su propio estado de
felicidad[^101]. La cultura del post modernismo tiene gruesos visos en
sus principios y valores que la fundamentan en un relativismo
práctico[^102] e individualista: El hombre puede llegar a dominarlo todo
, gracias a su inteligencia superior. En el centro estoy yo; todo gira a
mi alrededor. Yo impongo los principios y valores de acuerdo a mi propia
"verdad individual" o la de mi grupo de interés. Mi poder depende
directamente de mi capacidad material y racional; con mi poder
intelectual, tecnócrata y científico puedo lograrlo todo, incluso a
quienes no están de acuerdo conmigo; o a los débiles o a los ignorantes.
No existe una verdad objetiva, esta es mi imposición y si me descuido
caigo en una verdad ajena , inoportuna y traicionera. El amor por el
prójimo queda así sujeto al ego del si mismo en el esquema de la
sabiduría de nuestros días.

La desaparición de la humildad, en un ser humano desaforadamente
entusiasmado con la posibilidad de dominarlo todo sin límite alguno,
solo puede terminar dañando a la sociedad y al ambiente[^103]. Este
esquema de grupos de interés alineados en individuos modelos del super
yo , refleja un tejido social debilitado en el plano de "las relaciones"
con el otro individuo; aquel que difiere en sus intereses, tanto en el
nivel más rudimentario de las comunicaciones como en niveles
relacionales de mayor complejidad; en la relación de pareja o en la
relación familiar. Es un super yo impulsado con el viento de una
libertad que puede dominarlo todo; siempre y cuando se respeten los
principios funcionales del progreso y la razón. Jeremy Riffkin lo define
así: "En la edad moderna la libertad ha estado muy asociada a la
capacidad de controlar el propio trabajo y de proteger las propiedades
de uno, porque esa es la manera de optimizar el placer y ser feliz. La
libertad también ha estado muy vinculada con la representación política
y con la capacidad de la elección en el mercado. Los revolucionarios
franceses proclamaban que toda persona es soberana en la esfera pública.
Los economistas clásicos sostenían que cada individuo es libre de
procurar su propio interés en el mundo material. Las dos son maneras de
garantizar la autonomía personal. Desde el punto de vista racional, la
libertad es una libertad negativa: la libertad de excluir, de ser
independiente de los demás, de ser una isla. Ser libre es ser
autosuficiente, ser dueño de uno mismo".[^104] A pesar de que dicho
consuelo de libertad, con sombras antagónicas dada una potencial
descomposición del tejido social, es parte de una definición colectiva
de una verdad individual reflejada en un super yo; también es cierto que
el amor sigue cohabitando y creciendo, en lo más profundo del corazón de
aquellos seres humanos con tendencia a vivir en una esfera hiper
individualista. El individuo en busca de su identidad sigue escudriñando
en el legado milenario desde diversas filosofías y religiones,
tropezando y levantando, reflejando su sentir e impulsando en la
sociedad y comunidad a la que pertenece la misma búsqueda que le
inquieta; en el diario vivir la semilla del amor está siempre presente y
se manifiesta de muchas maneras, se marchita y reverdece cuando se
encuentra con el único Dios que ha sembrado su gracia en lo más profundo
del ser del si mismo.

## El cristal de la sabiduría desde el amor de Dios

En el misterio del amor divino, actúa la fe sumergida en la sabiduría de
Dios; está presente como complemento a la sabiduría humana desplegada
desde la razón y el conocimiento científico. "La luz de la fe , unida a
la verdad del amor, no es ajena al mundo material, porque el amor se
vive siempre en cuerpo y alma; la luz de la fe es una luz encarnada, que
procede de la vida luminosa de Jesús. Ilumina incluso la materia, confía
en su ordenamiento, sabe que en ella se abre un camino de armonía y de
comprensión cada vez mas amplio. La mirada de la ciencia se beneficia
así de la fe: esta invita al científico a estar abierto a la realidad,
en toda su riqueza inagotable. La fe despierta el sentido crítico, en
cuanto que no permite que la investigación se conforme con sus fórmulas
y la ayuda a darse cuenta de que la naturaleza no se reduce a ellas.
Invitando a maravillarse ante el misterio de la creación, la fe ensancha
los horizontes de la razón para iluminar mejor el mundo que se presenta
a los estudios de la ciencia[^105]". La sabiduría es irrigada desde el
Espíritu Santo y entre todas las criaturas de la tierra ha sido un
obsequio solo para el espíritu humano[^106]. Aquella gran
responsabilidad de la humanidad sobre si misma, sobre la naturaleza y
todo lo creado solo puede tener un sentido "correcto" desde la sabiduría
compartida por un Dios de amor. Aquel barco del progreso impulsado con
los motores del desarrollo económico solo puede tener dirección en
sentido correcto, si se acude a la sabiduría cimentada en el amor
divino. Respecto a esto dice así Santo Tomás de Aquino: "La sabiduría es
una cierta ciencia, en cuanto que cumple la función común a todas las
ciencias, que es deducir unas conclusiones a partir de unos principios.
Pero como tiene algo propio, superior a las demás ciencias, que es
juzgar de todas las cosas, y no sólo en cuanto a las conclusiones, sino
también en cuanto a los primeros principios, de ahí que tenga razón de
virtud más perfecta que la ciencia."[^107] La sabiduría humana por si
misma ha demostrado a través de su historia cuan fácil se enreda en las
mieles del poder de la idolatría; siglos antes reflejada en el poder
asignado a objetos y talismanes de todo tipo, evolucionando hacia los
tipos materiales que por su belleza y atracción adquieren gran valor a
la luz de los seres humanos y que luego se fueron transformando en el
poder de la riqueza material. La idolatría en la humanidad persiste en
el mundo del progreso; ha cambiado su forma y su manifestación, siempre
presentándose con ambigüedad y camuflada de amor, pero de un amor que
atrapa y no que libera, un supuesto amor que llena de vacío el alma
humana. La sabiduría de Dios, ha sido siempre aquel complemento de la
verdad científica y la razón sin la cual cualquier acción humana está en
peligro de caer en el vacío; en aquel Dios del vacío como manifestación
moderna de la idolatría que solo puede rasgar desesperadamente la
superficie de la verdad. [^108] Sin embargo, en el escenario de unión de
la fe y la razón, el amor es el timón en la acción; Dios se manifiesta
permanentemente a cada ser humano desde un estado que sobrepasa la
evidencia racional y científica, alimentando aquel vacío con verdadero
amor; es también el llamado de la caridad. Entonces, Dios actúa en cada
ser humano que lo busca desde el si mismo y por ende sobre la comunidad
que tiene la capacidad de construir su visión de progreso. [^109]. Actúa
indicando la "dirección correcta" a partir del amor divino en el corazón
de cada ser humano; la voluntad de todo ser humano es libre pero tiene
la facultad o el Don de decidir hacia donde caminar. La dirección del
progreso, de la ciencia, del bienestar y la felicidad puede edificarse
en los principios y valores definidos por el ser humano desde la
sabiduría del amor; este es otro sentido del mandato de Dios , el de
"amarse los unos a los otros como yo os he amado". Mandato que infiere
el amor al si mismo , acrecentado de manera infalible por el amor de
Dios. La sabiduría divina esconde un regalo, una gracia, el tesoro al
final del armonioso y colorido arco iris[^110]; la sabiduría de Dios es
un misterio que brilla desde un amor divino, un amor sin fin como una
tierna caricia en la mirada del alma, del corazón encontrando el
corazón, siempre indicando el camino "correcto". Pero a diferencia del
arco iris, el tesoro es una experiencia de la gracia , propia de la
verdad individual y encuentra su evidencia en el ejercicio de la razón
desde la fe. En todo ser humano que actúa en el sentido correcto que
dicta su propio espíritu, existe el entendimiento del gran lenguaje de
"gratitud" en su corazón, pero si además su esfuerzo es alimentado por
el Espíritu Santo , el premio de la paz y crecimiento del amor en el
alma del si mismo es una recompensa ilimitada, de imposible explicación.
Aquellas personas que hacen actos de misericordia con sus semejantes no
tienen su verdadera recompensa en especie, sino en el alimento ilimitado
del amor en su corazón. Por el contrario , quien en su voluntad se
decide por el acto incorrecto, podrá entender tarde o temprano el
lenguaje de la soberbia, la ira, la amargura, el rencor y la desidia en
su corazón. La expresión de la verdadera sabiduría no requiere de una
excepcional formación intelectual, esta activa y es permanente en la
humildad. En la sabiduría divina confluyen la misericordia, la justicia,
la paz, el sufrimiento, la armonía con la naturaleza y todas las
expresiones del amor de Dios. Sin ella, la justicia del ser humano,
cimentada en delicados bálsamos de aparentes promesas manipulables por
cada grupo de interés, ha demostrado ser tremendamente vulnerable en la
historia de la civilización. La historia ofrece incontables pasajes, a
través de los cuales diversos grupos de interés o individuos acobijados
por las sábanas del poder, han desarrollado una gran habilidad para
acomodar la justicia a su conveniencia. "hay una habilidad que solo
lleva a la injusticia: desfigurar las cosas pretendiendo imponer el
derecho".[^111] "Las cosas", en un escenario moderno, se refiere además,
a los ideales, los principios y valores de la comunidad, tal como fue
anotado en los pasillos de la conferencia de Solvay. La sabiduría divina
es aquel componente de la experiencia de cada individuo en el que todos
pueden estar de acuerdo, puesto que tiene la misma e inequívoca
dirección señalada por el Espíritu del amor. "En ella se encuentra un
Espíritu inteligente, santo, único múltiple, ágil, móvil, penetrante,
puro, límpido, no puede corromperse, orientado al bien y eficaz. Es un
Espíritu irresistible, bienhechor, amigo de los hombres, firme, seguro,
apacible, que lo puede todo y que vela por todo, impregna a todos los
otros espíritus por inteligentes, puros y sutiles que sean. La sabiduría
es mas movible que cualquier cosa, gracias a su fuerza atraviesa y lo
penetra todo. Se desprende como un vapor, del poder de Dios, es una
emanación muy pura de su Gloria; por eso nada de sucio se introduce en
ella. Es la irradiación de la luz eterna, el espejo sin tacha de la
actividad de Dios y la imagen de su perfección.[^112]" El misterio
omnipotente de la sabiduría divina lo ilumina todo; si el universo
entero fuese oscuro y no existiera en él una sola estrella , la
sabiduría tendría tanto poder como el brillo de una sola vela siempre
visible en la oscuridad infinita. Esta pequeña luz , actúa como la
chispa que alerta a la dirección e inteligencia humanas hacia el camino
"correcto". La humanidad en la edad de la razón y la ciencia, en el
camino del progreso debe asumir con toda responsabilidad los retos
éticos que se le presentan. La libertad de la voluntad en el ser humano
tiene este precio: la elección del camino incorrecto lleva a perdiciones
a veces incomprensibles por la misma razón. Las guerras y su historia de
barbarie son un ejemplo de aquello; quien la sufre a veces impone la
culpa en Dios, por el hecho de brindarle a cada ser humano el camino a
su sabiduría divina y haberle dejado el libre albedrío en manos de su
propia conciencia. [^113]Es entonces así como la libertad y la sabiduría
divina que Dios ha entregado al ser humano es un acto representativo de
ser creado a su imagen y semejanza. Pero como tal, la ignorancia del ser
humano en su estado espiritual intenta responder reemplazando a Dios en
el si mismo, en un super yo que desvanece la humildad ante la
exclusividad de la razón, la ciencia y la tecnología. "No es fácil
desarrollar esta sana humildad y una feliz sobriedad si nos volvemos
autónomos, si excluimos de nuestra vida a Dios y nuestro yo ocupa su
lugar, si creemos que es nuestra propia subjetividad la que determina lo
que esta bien o lo que esta mal"[^114]. El verdadero rostro de la
sabiduría humana pasa por la sabiduría en el amor de Dios y se enaltece
en la comunidad y en la sociedad, es en aquella única circunstancia
cuando puede ser permeada por una instancia de principios y valores que
marcan una dirección correcta y objetiva. El timón del barco del
progreso debería estar en los individuos verdaderamente sabios de cada
comunidad o grupo de interés, aunque en el progreso moderno cada vez se
les ignora más. [^115] La edificación de la sabiduría divina es además
la manera en que el bienestar como fruto de la razón y la ciencia pueden
adquirir un carácter apetecido por una sociedad brillante en
conocimiento, puesto que así está inmersa en la búsqueda una felicidad
embebida en el amor; no es un bienestar pasajero y sin rumbo, que solo
responde a la aspiración de una mejor calidad de vida estandarizada en
la verdad individual de una cultura pasajera, pero que en esencia no
perdura y en la que muchas veces no brota la felicidad. La religión
Cristiana, promueve la sabiduría bajo la luz del amor divino
construyendo así la felicidad de quienes la persiguen. [^116] .La
sabiduría divina es también un misterio, en esto se asemeja a la verdad
científica y deja así desconcertada a la razón. Tal cómo el
descubrimiento de la ley de la ciencia que camina de pregunta en
pregunta y el científico que vive en ciclos interminables de ignorancia
y conocimiento; así por diferentes caminos ambos van en busca de una
verdad absoluta; "Desde el principio el Señor me había creado[^117],
antes que existiera el tiempo, y no pasaré con el tiempo"(\...) "El
primero que la encontró no le verá el fin, el último que llegó no la
agotará".[^118] Esta afirmación es una mirada sobre la cual, la
sabiduría desde la Cristiandad se muestra como algo trascendente, la
inteligencia creadora de Dios se manifiesta de manera similar a la
inteligencia del ser humano en la verdad científica; la sabiduría divina
como la verdad científica son fuentes inagotables en la búsqueda de una
verdad absoluta, en la que que la ciencia y la razón tienen su
naturaleza única a partir de la capacidad incomprendida de la mente y el
cerebro humano, pero también de su espíritu, en el cual la sabiduría
divina se manifiesta por un Dios de amor quien por su voluntad ha
deseado compartirla con la humanidad. La sabiduría es el destello
inagotable en la fe como el motor del ejercicio de la razón en quienes
la viven bajo la oración en el silencio de su espíritu y su verdad
individual. Y esta fe adquiere todo su sentido abrazando la ciencia y la
razón envueltas en el misterio espacio temporal, que desde la sabiduría
divina guía al ser humano desorientado, en la oportunidad de dar sentido
a las acciones y decisiones de su vida como individuo, comunidad y
sociedad constituida por innumerables grupos de interés, dándole el
conocimiento en un tiempo preciso sobrepasado por la eternidad: "Todo lo
que Él hace llega a su tiempo; pero ha puesto la eternidad en sus
corazones, y el hombre no encuentra el sentido de la obra divina desde
el principio hasta el fin"[^119]. Aquella eternidad y su perfecto
entendimiento en el amor es la que permanece en la verdad absoluta,
esquiva en un entorno puramente racional y científico y hacia la cual
los seres humanos caminan en el misterio de la fe en Jesús, quien venció
la muerte para dar la vida eterna, quien se constituye en la llave del
camino hacia la sabiduría divina a través del Espíritu Santo a quienes
lo acojan. En abierta contraposición, el camino de la maldad y la
soberbia es contrario al mensaje de Jesucristo; y se puede caer en él
cuando se toma como única guía lo que enseña un mundo sin rumbo al
apartarse de la verdadera sabiduría. La consciencia del bien y del mal,
la virtud en contraposición de la corrupción y todas las demás
manifestaciones antagónicas del amor y consecuentes con el odio, están
presentes en el camino correcto o en el camino incorrecto según la
voluntad de cada ser humano. Encontrarse con la sabiduría en el contexto
del post modernismo no es fácil, como nunca lo ha sido, pues implica un
esfuerzo y una aparente pérdida de libertad cuando no se le busca en el
amor; pues implica el respeto sin miedo, el acompañamiento de de un Dios
cercano, que ama y enseña a amar, perdona y enseña a perdonar, pero que
exige algo a cambio: "Entonces dijo al hombre: Mira, el temor del señor
es la sabiduría; y huir del mal es la inteligencia".[^120] Quienes
aborrecen la Cristiandad aduciendo en ella un sistema coercitivo y
ventajoso de obediencia, no se percatan de que solo exige la única ley
del amor, mientras sus detractores son personas sumidas en un mar de
leyes humanas que muchas veces ni comprenden, ni desean.

## Corolario III

El cristal del amor de Dios, a través del cual se manifiesta en su
máximo esplendor la gracia del Espíritu Santo es una metáfora práctica
que permite revisar el reflejo del mensaje de Jesús frente a la vida de
cada persona y su comunidad; Jesucristo deja el legado del Evangelio,
pero, a pesar de que la cotidianidad de las vivencias del ser humano son
una muestra de la complejidad de la vida del ser humano en el mundo a
través de la misericordia, la justicia, la paz, la naturaleza, el
sufrimiento y la naturaleza, permiten estos temas entender que Jesús es
acción en la vida diaria, en mucho otros interminables aspectos que
suceden al ser humano y la civilización imposibles de abarcar en un
texto escrito; en este sentido el misterio de la encarnación como hombre
es una decisión de la voluntad de Dios en su amor infinito y siempre
fiel, que siendo incomprensible para la mente humana, se hace realidad
para mostrar con la propia vida y ejemplo de su hijo Jesús, con cada una
de sus acciones, el camino correcto frente al cual cada individuo en el
mundo y la misma sociedad puede cuestionarse. Más allá de las diferentes
interpretaciones y sus diferencias doctrinales, teológicas, religiosas;
o de los desacuerdos y críticas hacia y desde la misma Cristiandad,
Jesús con su vida es enseñanza pura, transparente y sencilla para el
alma de cualquier ser humano a través de signos, frases breves y
contundentes que se repiten a través de los siglos, con su presencia
real en quienes le abren su corazón a su amor infinito; amor que ha sido
sujeto de debate por siglos, pero que desde la Cristiandad tiene una
manifestación clara y objetiva; una manifestación de salvación y que
permite revelarse como un camino hacia la verdad a partir de la fe, un
camino hacia el amor, camino que la humanidad ha estado buscando y
todavía persiste en su búsqueda desde tiempos inmemoriales.

[^1]: *"Dios vio que todo cuanto había hecho era muy bueno y atardeció y
    amaneció: fue el día sexto. Así estuvieron terminados el cielo y la
    tierra y todo lo que hay en ellos."*Génesis 1, 31 .La Biblia --
    Latinoamérica, Edición revisada 2005. Texto íntegro traducido del
    hebreo y del griego.

[^2]: "*Dios no hizo la muerte, y no le gusta que se pierdan los
    vivos."*Sabiduría 1, 13. La Biblia -- Latinoamérica, Edición
    revisada 2005. Texto íntegro traducido del hebreo y del griego.

[^3]: [https://www.worldgivingreport.org](https://www.worldgivingreport.org/)

[^4]: The office of Jeremy Rifkin <https://www.foet.org/>

[^5]: Para el año 2019, el 0.9% - 47 millones de habitantes de la
    población mundial tenía el 43.9% de la riqueza global; y el 56.6% -
    2.883 millones de habitantes de la población mundial tenía el 1.8%
    de la riqueza mundial.En el 2009, los 326 mayores billonarios del
    mundo, tenían una riqueza igual al 50% más pobres; en el año 2018 ya
    se concentra en solo 26 billonarios.
    <https://inequality.org/facts/global-inequality/>

[^6]: La civilización empática, Jeremy Rifkin, páginas 432 - 438

[^7]: Absolute vs relative inequality: ¿ which measurement is better ?
    <https://difficultrun.nathanielgivens.com/2017/04/03/absolute-vs-relative-inequality-which-measurement-is-better/>

[^8]: Trends in global inequality -- a comprehensive approach -- united
    nations university
    [https://www.wider.unu.edu/publication/trends-global-inequality-%E2%80%93-comprehensive-approach](https://www.wider.unu.edu/publication/trends-global-inequality-–-comprehensive-approach)

[^9]: Birmania es uno de los países con índices de donaciones en caridad
    más altos del mundo, en parte debido a sus creencias en le budismo
    theravada.

[^10]: No se debe confundir el sentimiento de compasión con el de
    lástima. La compasión invita a actuar en un sentido concreto.

[^11]: La Biblia -- Latinoamérica, Edición revisada 2005. Texto íntegro
    traducido del hebreo y del griego.Génesis 2,15-17. "*Yavé tomó al
    hombre y lo puso en el jardín del Edén para que lo cultivara y lo
    cuidara. Y Yavé Dios le dio al hombre un mandamiento; le dijo:
    puedes comer todo lo que quieras de los árboles del jardín, pero no
    comerás del árbol de la ciencia del bien y del mal. El día que comas
    de él, ten la seguridad de que morirás*"

[^12]: Catecismo de la iglesia Católica No.404
    <http://www.vatican.va/archive/catechism_sp/p1s2c1p7_sp.html>

[^13]: El nombre de Dios es Misericordia, Francisco, Una conversación
    con Andrea Tornielli. Página 27

[^14]: El nombre de Dios es Misericordia, Francisco, Una conversación
    con Andrea Tornielli. Páginas 30 - 31

[^15]: El deseo de la carne contra el espíritu y del espíritu contra la
    carne. <https://ec.aciprensa.com/wiki/Concupiscencia>

[^16]: Catecismo de la iglesia Católica.
    <http://www.vatican.va/archive/catechism_sp/p1s2c1p7_sp.html>

[^17]: Biografía de Santa Teresa de Calcuta
    <https://www.es.catholic.net/op/articulos/31870/teresa-de-calcuta-beata.html>

[^18]: Las hermanas misioneras de la caridad
    <https://www.motherteresa.org/espanol/active-sisters.html>

[^19]: "Madre Teresa de Calcuta: Para mi es un deber luchar por por la
    santidad como lo es para todos los Cristianos.", Entrevista Lima,
    1989.
    [https://www.abc.es/sociedad/abci-madre-teresa-calcuta-para-deber-luchar-santidad-como-para-todos-Cristianos-201609020125_noticia.html](https://www.abc.es/sociedad/abci-madre-teresa-calcuta-para-deber-luchar-santidad-como-para-todos-cristianos-201609020125_noticia.html)

[^20]: Lc, 23,34, La Biblia -- Latinoamérica, Edición revisada 2005.
    Texto íntegro traducido del hebreo y del griego.

[^21]: Biografía de María Goretti
    <http://www.es.catholic.net/op/articulos/56417/santa-mara-goretti.html#modal>

[^22]: El perdón de maría me salvó. Alessandro Serenelli
    <https://mariagoretti.com/the-murderer/>

[^23]: Sexo y publicidad
    <https://es.wikipedia.org/wiki/Sexo_en_la_publicidad>

[^24]: Significado de injusticia social
    <https://www.significados.com/8-ejemplos-de-injusticia-social-en-el-mundo/>

[^25]: 25 millones de personas experimentan un estado de esclavitud,
    aproximadamente 3 por mil habitantes. La trata de seres humanos, la
    servidumbre por deudas y el trabajo doméstico forzoso son sólo
    algunos ejemplos de formas de esclavitud.
    [https://50forfreedom.org/es/esclavitud-moderna/#:\~:text=MITO%3A%20Son%20relativamente%20pocas%20las,1.000%20personas%20en%20el%20mundo.](https://50forfreedom.org/es/esclavitud-moderna/#:~:text=MITO%3A Son relativamente pocas las,1.000 personas en el mundo.)

[^26]: Cifras que superan los 200 millones de habitantes. Perspectivas
    sociales y del empleo en el mundo
    <https://www.ilo.org/global/research/global-reports/weso/trends2021/lang--es/index.htm>

[^27]: Pasa en 1991 del 62.4% al 57.4% en el 2019 .Radio de empleo vs
    población , Banco Mundial , 119 -- 2019
    <https://data.worldbank.org/indicator/SL.EMP.TOTL.SP.ZS?end=2019&start=1991&view=chart>

[^28]: Pasando de 150 millones de habitantes a casi 300 millones. Número
    de migrantes internacionales
    <https://www.migrationdataportal.org/es/international-data?i=stock_abs_&t=2020>

[^29]: Se estima que en el 2030 habrán 9,700 millones de habitantes y en
    el 2100 será 11,000 millones. Crecimiento de la población mundial.
    [https://www.un.org/es/global-issues/population#:\~:text=Se%20espera%20que%20la%20poblaci%C3%B3n,de%2011.000%20millones%20para%202100.](https://www.un.org/es/global-issues/population#:~:text=Se espera que la población,de 11.000 millones para 2100.)

[^30]: Discriminación religiosa, racial y sexual, persecución política,
    concentración de poder, terrorismo, desarrollo científico y técnico,
    acceso a educación, etc.

[^31]: Constitución pastoral, Gaudium et spes, sobre la iglesia en el
    mundo actual, No. 78
    <https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_const_19651207_gaudium-et-spes_sp.html>

[^32]: El 57% de incremento del costo en salud se presenta para vacunar
    al 70% de la población de países pobres vs el 0.8% para los países
    ricos. Panel global para la equidad en las vacunas delas Naciones
    Unidas:
    <https://www.wto.org/spanish/tratop_s/covid19_s/vaccine_trade_tracker_s.htm>

[^33]: Yuval Noah Harari (1976 - actualmente), Historiador y profesor
    Israelí. De animales a Dioses, página 434

[^34]: "El nombre de Dios es Misericordia", una conversación con Andrea
    Tornielli, Francisco, 2016, pág 37

[^35]: Su expresión bíblica más conocida es "Ojo por ojo, diente por
    diente"
    [https://es.wikipedia.org/wiki/Ley_del_tali%C3%B3n](https://es.wikipedia.org/wiki/Ley_del_talión)

[^36]: Romanos 2, 14-16 . La Biblia -- Latinoamérica, Edición revisada
    2005. Texto íntegro traducido del hebreo y del griego.

[^37]: "El nombre de Dios es Misericordia", una conversación con Andrea
    Tornielli, Francisco, 2016, pág 42

[^38]: Asociación Carlo Acutis
    <http://www.carloacutis.com/es/association>

[^39]: Carlo Acutis, frases que lo han hecho famoso
    <https://www.vaticannews.va/es/iglesia/news/2020-10/italia-carlo-acutis-frases-que-han-hecho-famoso.html>

[^40]: La justicia y misericordia de Dios no son opuestas. De hecho, el
    Creador perfecto equilibra las dos cualidades extraordinariamente.
    Si esto no fuera cierto, el salmista no hubiera podido
    proclamar,"Justicia y juicio son el cimiento de tu trono;
    misericordia y verdad van delante de tu rostro" (Salmos 89:14,
    énfasis añadido).
    <http://www.es.catholic.net/op/articulos/59080/www.messt.org#modal>

[^41]: ¿ Dios castiga o no castiga ?
    <https://www.aciprensa.com/noticias/dios-castiga-o-no-castiga-nuevo-e-book-aporta-en-debate-en-redes-sociales-44415>

[^42]: Laudato Si No.70 -
    <https://www.aciprensa.com/Docum/documento.php?id=552>

[^43]: "El nombre de Dios es Misericordia", una conversación con Andrea
    Tornielli, Francisco, 2016, pág 59

[^44]: Ver "las cien peores atrocidades de la humanidad en los últimos
    mil años", fuente: our world in data.
    <https://ourworldindata.org/uploads/2013/08/The-100-Worst-Atrocities-over-the-last-Millennia-New-York-Times-Data-from-Matthew-White0.png>

[^45]: La Guerra, Santo Tomás de Aquino
    <http://es.catholic.net/op/articulos/23707/la-guerra.html#modal>

[^46]: La teoría de la guerra justa: orígenes, evolución y contenidos
    <https://global-strategy.org/la-teoria-de-la-guerra-justa-origenes-evolucion-y-contenidos/>

[^47]: Biografía de Fray Francisco de Vitoria
    <https://www.dominicos.org/quienes-somos/grandes-figuras/personajes/francisco-de-vitoria-biografia/>

[^48]: Francisco de Vitoria, un humanista para un nuevo mundo
    <https://ethic.es/2023/07/francisco-de-vitoria-padre-del-derecho-humano/>

[^49]: Iniciativa del Jurista y diplomático Holandés Higo Grocio en el
    siglo XVI. <https://www.biografiasyvidas.com/biografia/g/grocio.htm>

[^50]: Biografía de Michael Walzer <https://www.ias.edu/scholars/walzer>

[^51]: War, Stanford Encyclopedia of Philosophy, May 3 2026.
    <https://plato.stanford.edu/entries/war/>

[^52]: Lucas 6, 29 .La Biblia -- Latinoamérica, Edición revisada 2005.
    Texto íntegro traducido del hebreo y del griego.

[^53]: Juan 14, 27 .La Biblia -- Latinoamérica, Edición revisada 2005.
    Texto íntegro traducido del hebreo y del griego.

[^54]: Biografía de Herbert George Wells
    <https://www.biografiasyvidas.com/biografia/w/wells.htm>

[^55]: "Breve Historia del Mundo", Herbert George Wells , Página 293.

[^56]: Biografía San Juan Pablo II:
    <https://es.catholic.net/op/articulos/52868/cat/169/biografia-de-juan-pablo-ii.html#modal>

[^57]: Biografía de Mahatma Gandhi
    <https://www.biografiasyvidas.com/monografia/gandhi/>

[^58]: En la única carta que se conoce de Ghandi sobre Jesús, afirma que
    es uno de los más grandes maestros de la humanidad; reconoce el amor
    como un hilo común entre las religiones.
    <https://www.mensaje.cl/sale-a-la-venta-la-unica-carta-que-mahatma-gandhi-escribio-sobre-jesus/>

[^59]: Biografía San Francisco de Asís:
    [https://www.Biografíasyvidas.com/Biografía/f/francisco_asis.htm](https://www.biografiasyvidas.com/biografia/f/francisco_asis.htm)

[^60]: Chennai se queda sin agua 2,019:
    <https://www.nytimes.com/es/2019/06/26/espanol/escasez-agua-india.html>

[^61]: La crisis del agua pronto afectará a un cuarto de la población
    mundial:
    <https://www.nytimes.com/es/interactive/2019/espanol/ciencia-y-tecnologia/crisis-del-agua.html>

[^62]: Renewable internal fresh water resources per capita 1962 -- 2014
    <https://data.worldbank.org/indicator/ER.H2O.INTR.PC>

[^63]: Estas comunidades constituyen solo el 5% de la población mundial,
    sin embargo los pueblos indígenas son los guardianes esenciales del
    medio ambiente <http://www.fao.org/zhc/detail-events/es/c/1028079/>

[^64]: "...entonces Yavé formó al hombre con polvo de la tierra; luego
    sopló en su nariz un aliento de vida..." Génesis 2,7.La Biblia --
    Latinoamérica, Edición revisada 2005. Texto íntegro traducido del
    hebreo y del griego.

[^65]: Desde la teoría de la evolución, se afirma el origen de la vida
    desde un proceso físico-químico que dió lugar a una primera célula
    llamada LUCA en el contexto científico, imposible de identificar o
    encontrar exactamente en el rango de tiempo y espacio que arroja la
    misma teoría.
    <https://es.wikipedia.org/wiki/Último_antepasado_común_universal>

[^66]: "Hagamos al hombre a nuestra imagen y semejanza. Que tenga
    autoridad sobre los peces del mar y sobre las aves del cielo, sobre
    los animales del campo , las fieras salvajes y los reptiles que se
    arrastran sobre el suelo". Génesis 1,26.La Biblia -- Latinoamérica,
    Edición revisada 2005. Texto íntegro traducido del hebreo y del
    griego.

[^67]: "El universo está inquieto, pues quiere ver lo que verdaderamente
    son los hijos e hijas de Dios. Pues si la creación está sometida a
    lo efímero, no es cosa suya, sino de aquel que le impuso este
    destino. Pero le queda la esperanza; porque el mundo creado también
    dejará de trabajar para el polvo, y compartirá la libertad y la
    gloria de los hijos de Dios. Romanos 8,19.La Biblia --
    Latinoamérica, Edición revisada 2005. Texto íntegro traducido del
    hebreo y del griego.

[^68]: ¿Los animales van al cielo ?
    [https://www.aciprensa.com/noticias/53589/los-animales-van-al-cielo-segun-el-Papa-francisco](https://www.aciprensa.com/noticias/53589/los-animales-van-al-cielo-segun-el-papa-francisco)

[^69]: "...El lobo habitará con el cordero, el puma se acostará junto al
    cabrito, el ternero comerá al lado del león y un niño chiquito los
    cuidará. Vaca y oso pastarán en compañía y sus crías reposarán
    juntas, pues el león también comerá pasto, igual que el buey. El
    niño de pecho jugará sobre el nido de la vívora, y en la cueva de la
    culebra el pequeñuelo meterá su mano. No cometerán el mal ni dañarán
    a su prójimo, en todo mi Cerro Santo, pues, como llenan las aguas el
    mar, se llenará la tierra del conocimiento de Yavé"

    > Isaías 11,6-9.La Biblia -- Latinoamérica, Edición revisada 2005.
    > Texto íntegro traducido del hebreo y del griego. Yave en el
    > antiguo testamento es Dios.Isaías 11,6-9.La Biblia --
    > Latinoamérica, Edición revisada 2005. Texto íntegro traducido del
    > hebreo y del griego. Yave en el antiguo testamento es Dios.

[^70]: Carta Encíclica, Laudato SI, del Santo Padre Francisco, sobre el
    cuidado de la casa común
    <https://www.aciprensa.com/Docum/documento.php?id=552>

[^71]: Encíclica Laudato Si No.59
    [https://www.aciprensa.com/Docum/documento.php?id=552]{.underline}

[^72]: No somos Dios. La tierra nos precede y nos ha sido dada. Esto
    permite responder a una acusación lanzada al pensamiento
    Judío-Cristiano: se ha dicho que, desde el relato del Génesis que
    invita a « dominar » la tierra (cf. Gn 1,28), se favorecería la
    explotación salvaje de la naturaleza presentando una imagen del ser
    humano como dominante y destructivo. Laudato Si No. 62
    <https://www.aciprensa.com/Docum/documento.php?id=552>

[^73]: Aquella visión antropomorfa asignada a la religión Cristiano
    Católica del hombre como centro de todo, es del todo incompatible
    con la interpretación desde la fe profesada por su iglesia.

[^74]: Laudato Si No. 92
    <https://www.aciprensa.com/Docum/documento.php?id=552>

[^75]: Cristiano Evangélico, En el 2001 recibió el premio Principe
    Asturias de Investigación Científica y Técnica , por su trabajo en
    el descubrimiento de la secuencia del genoma humano.
    <https://www.genome.gov/staff/Francis-S-Collins-MD-PhD>

[^76]: Aprendiendo el Lenguaje de Dios, una interesante experiencia de
    un científico frente a la muerte. Francis Collins, página 35
    <https://www.fliedner.es/media/modules/editor/cienciayfe/docs/La_FE_a_examen_muestra_capitulo_Francis_Collins.pdf>

[^77]: Esta experiencia se puede dar en muchas personas, pero no todas
    descubren a Dios. Sabiduría 13,1 "(..) se quedaron con las obras y
    no conocieron al artesano"

[^78]: De acuerdo a la Organización Mundial de la salud hay una
    tendencia creciente con 2,641 millones de personas afectadas por la
    depresión en el mundo; en su peor escenario, la depresión conduce al
    suicidio. Las tasas de suicidio en el mundo oscilan alrededor del
    1.4% de la población, en algunos países alcanzando niveles el 6%. En
    cifras, alrededor de 800,000 personas en el mundo se suicidan cada
    año, es decir una persona cada 40 segundos , el doble de muertes
    generadas por los homicidios. Open BMJ Journals , World wide impact
    of economic cycles on suicide trends over tree decades: differences
    acording to level of development. A mixed effect model study
    (1980-2007).
    <https://bmjopen.bmj.com/content/bmjopen/2/3/e000785.full.pdf>

[^79]: Our World in Data, Datos desde el año 2000; la tasa de suicidio
    por 100 mil habitantes varía entre menos de 10 a más de 15 personas
    en algunos países.
    <https://ourworldindata.org/suicide#suicide-is-a-leading-cause-of-death-especially-in-young-people>

[^80]: Mateo 26, 36 -- 38 Llegó Jesús con ellos aun lugar llamado
    Getsemaní, y dijo a sus discípulos: "Siéntense aquí , mientras yo
    voy más allá a orar". Tomo consigo a Pedro y a los dos hijos de
    Zebedeo y comenzó a sentir tristeza y angustia. Y les dijo: "Siento
    una tristeza de muerte. Quédense aquí conmigo y permanezcan
    despiertos"La Biblia -- Latinoamérica, Edición revisada 2005. Texto
    íntegro traducido del hebreo y del griego.

[^81]: Juan 16, 21 -- 23 .La Biblia -- Latinoamérica, Edición revisada
    2005. Texto íntegro traducido del hebreo y del griego.

[^82]: De acuerdo a San Agustín, "La posesión de Dios es la esencia de
    la felicidad", "Conocer a Dios es tener vida eterna". La verdadera
    felicidad está en el más allá. El bien perfecto que satisface
    completamente el deseo, podrá ser disfrutado inmediatamente sin
    retardos u obstáculos y ese goce no será un estado de quietud
    inactiva, sino la actividad intensa, aunque libre y pacífica del
    alma. <https://ec.aciprensa.com/wiki/Felicidad>

[^83]: Biografía de Marta Robin
    <https://www.es.catholic.net/op/vercapitulo/6790/presentacion.html>

[^84]: Reanimar en el mundo el amor que se apaga -
    <https://www.martherobin.com/es/>

[^85]: Misticismo: de acuerdo a su etimología, implica una relación con
    el misterio. En filosofía, misticismo es, o una tendencia religiosa
    y desde del alma humana hacia una unión íntima con la Divinidad, o
    un sistema que crece a partir de tal tendencia y deseo.
    <https://ec.aciprensa.com/wiki/Misticismo>

[^86]: Marthe Robin, una gran mística Francesa
    [https://www.martherobin.com/es/sa-vie/une-grande-mystique-francaise/#:\~:text=Marta%20Robin%20experimenta%20el%20poder,¡Es%20como%20una%20resurrección!%20»](https://www.martherobin.com/es/sa-vie/une-grande-mystique-francaise/#:~:text=Marta Robin experimenta el poder,¡Es como una resurrección! »)

[^87]: Châteauneuf-de-Galaure es la población donde nació y vivió Marta
    Robin en Francia. Vida de Marta Robin, Bernard Peyrous, primera
    edición 2015, páginas 50-51.

[^88]: Vida de Marta Robin, Bernard Peyrous, primera edición 2015,
    página 50.

[^89]: Se debe tener en cuenta que muchos de estos casos han sido
    identificados como fraudulentos, por la iglesia Católica. La
    Definición de los estigmas místicos:
    [https://ec.aciprensa.com/wiki/Estigmas_m%C3%ADsticos](https://ec.aciprensa.com/wiki/Estigmas_místicos)

[^90]: Vida de Marta Robin, Bernard Peyrous, primera edición 2015,
    páginas 68 - 73.

[^91]: USA national library of medicine
    <https://pubmed.ncbi.nlm.nih.gov/29624652/>

[^92]: Vida de Marta Robin, Bernard Peyrous, primera edición 2015,
    página 89.

[^93]: Vida de Marta Robin, Bernard Peyrous, primera edición 2015,
    páginas 90-93.

[^94]: Los Foyers de Charité
    <https://www.martherobin.com/es/son-heritage/les-foyers-de-charite/>

[^95]: La civilización empática , Jeremy Rifkin página 161.

[^96]: University of California, Los Angeles-EEUU.

[^97]: La civilización empática , Jeremy Rifkin páginas 137 - 138.

[^98]: La velocidad de acceso a los nuevos conocimientos de ciertos
    grupos de interés es mucho mayor que la velocidad de acceso de
    minorías superiores en miles de millones de habitantes; la brecha se
    incrementa con las consecuencias que eso trae en la concentración
    del poder. El ejemplo actual es el desarrollo de la inteligencia
    artificial y su control por unas exclusivas minorías. De tal manera,
    que en el momento en que esta tecnología esté al alcance en el
    conocimiento de las masas, aparecerá otra tecnología de mayor
    impacto en el acceso al poder, que contará inicialmente con un
    acceso limitado a ciertos grupos de interés.

[^99]: "Breve Historia del Mundo" , Herbert George Wells , Página270.

[^100]: Definición de Antropocentrismo:
    <https://es.wikipedia.org/wiki/Antropocentrismo>

[^101]: Las ciencias humanas han elaborado las suficientes tesis que
    confirman que el ser humano es un ser social, donde las relaciones
    con su familia y su comunidad le dan el sentido de ser individual.

[^102]: Laudato Si, S.S Francisco, No. 122-123 , páginas 105 - 106.

[^103]: Laudato Si, S.S Francisco, No. 224 , página 186.

[^104]: La civilización empática , Jeremy Rifkin páginas 154 - 155

[^105]: Encíclica Laudato SI, SS. Francisco, No.199, página 166.

[^106]: No se debe confundir esto como una posición filosófica
    Antropocentrica. Tampoco con una posición Teocéntrica, en la que
    Dios pretende dominarlo todo; Dios permite el libre albedrío en el
    ser humano; las actividades humanas son responsabilidad de la
    humanidad.

[^107]: Summa Teológica, Santo Tomás de Aquino, I -- IIae, C57
    <https://hjg.com.ar/sumat/b/c57.html#a2>

[^108]: "*La ignorancia de Dios siempre manifiesta en los hombres es una
    falla esencial. Todo lo que admiran por*

    *su valor no los llevó a conocer al Que Es.¿Se quedaron con las
    obras y no conocieron al Artesano".* Sabiduría 13, 1. La Biblia --
    Latinoamérica, Edición revisada 2005. Texto íntegro traducido del
    hebreo y del griego.

[^109]: ¿Pero cómo actúa la sabiduría de Dios ?. "*La sabiduría es luz y
    no se torna opaca; se muestra con gusto a los que la aman, se deja
    encontrar por los que la aman*"Sabiduría 6, 12 -13. La Biblia --
    Latinoamérica, Edición revisada 2005. Texto íntegro traducido del
    hebreo y del griego.

[^110]: "Pongo mi arco en las nubes para que sea una señal de mi alianza
    con toda la tierra" Génesis 13.La Biblia -- Latinoamérica, Edición
    revisada 2005. Texto íntegro traducido del hebreo y del griego.

[^111]: Sarácida 19, 25. La Biblia -- Latinoamérica, Edición revisada
    2005. Texto íntegro traducido del hebreo y del griego.

[^112]: Sabiduría 7, 22 -26. La Biblia -- Latinoamérica, Edición
    revisada 2005. Texto íntegro traducido del hebreo y del griego.

[^113]: "No aspires a algo superior a tus fuerzas , ni te lances a
    investigar lo que sobrepasa tus capacidades. Profundiza lo que se te
    ha mandado, no tienes necesidad alguna de conocer los misterios
    ocultos. No te canses resolviendo problemas inútiles, el saber que
    se te ha entregado desborda lo que una persona puede comprender.
    Piensa que muchos se han extraviado con sus teorías, su seguridad
    mal fundada les falseó el raciocinio".Sirácida 3, 21 -24. La Biblia
    -- Latinoamérica, Edición revisada 2005. Texto íntegro traducido del
    hebreo y del griego.

[^114]: Laudato Si, SS Francisco, No.224 página 186.

[^115]: "Si tu quieres hijo mio, llegarás a ser instruido; si te aplicas
    se abrirá tu espíritu. Si quieres escuchar, aprenderás; si pones
    atención, serás sabio. Frecuenta las asambleas de los ancianos; si
    ves ahí un hombre sabio, júntate con él."Sirácida 6, 32 -35. La
    Biblia -- Latinoamérica, Edición revisada 2005. Texto íntegro
    traducido del hebreo y del griego.

[^116]: "*Feliz el que se dedica a la sabiduría y puede responder al que
    lo interroga; que hace suyos los caminos de la sabiduría y
    profundiza sus secretos; que sale a cazarla y acecha su paso; que
    mira a través de sus ventanas y escucha a su puerta; que instala su
    tienda al lado de su casa y clava las estacas en sus muros. Pone su
    tienda en manos de la sabiduría y se queda en esa feliz morada. Deja
    a sus hijos bajo su protección y se tiende al abrigo de sus ramas,
    lo protege del calor y se instala en su gloria.*"Sirácida 14, 20
    -27. La Biblia -- Latinoamérica, Edición revisada 2005. Texto
    íntegro traducido del hebreo y del griego.

[^117]: Antes de la creación, ya la sabiduría divina existía.

[^118]: Sirácida 24, 9 / Sirácida 25,28. La Biblia -- Latinoamérica,
    Edición revisada 2005. Texto íntegro traducido del hebreo y del
    griego.

[^119]: Eclesiastés, 3,11 . La Biblia -- Latinoamérica, Edición revisada
    2005. Texto íntegro traducido del hebreo y del griego.

[^120]: Job, 28,28. La Biblia -- Latinoamérica, Edición revisada 2005.
    Texto íntegro traducido del hebreo y del griego.
